# Generated by Django 5.2 on 2026-06-15 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='代碼')),
                ('name', models.CharField(max_length=100, verbose_name='構念名稱')),
                ('group', models.CharField(blank=True, help_text='例如動機的四個子構面可填「學習動機」以利分組顯示', max_length=100, verbose_name='所屬量表')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='說明')),
                ('score_min', models.FloatField(default=1.0, verbose_name='分數下限')),
                ('score_max', models.FloatField(default=5.0, verbose_name='分數上限')),
                ('higher_is_better', models.BooleanField(default=True, help_text='焦慮這類「越低越好」請取消勾選', verbose_name='高分代表較好')),
                ('post_only', models.BooleanField(default=False, help_text='只在後測施測（如系統可行性量表）', verbose_name='僅後測')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '問卷構念',
                'verbose_name_plural': '問卷構念',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('pre', '前測'), ('post', '後測')], max_length=10, verbose_name='階段')),
                ('score', models.FloatField(verbose_name='分數')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('recorded_at', models.DateTimeField(auto_now=True, verbose_name='登錄時間')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='surveys.surveyscale', verbose_name='構念')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_scores', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '問卷成績',
                'verbose_name_plural': '問卷成績',
                'ordering': ['scale__order', 'phase', 'student__username'],
                'unique_together': {('student', 'scale', 'phase')},
            },
        ),
    ]
