# Generated by Django 5.2 on 2026-07-01 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyScoreRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('pre', '前測'), ('post', '後測')], max_length=10)),
                ('score', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(default='system', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='surveys.surveyscorerevision')),
                ('survey_score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='surveys.surveyscore')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
