# Generated by Django 5.2 on 2026-07-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyscorerevision'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='surveyscore',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='surveyscore',
            name='student',
        ),
        migrations.RemoveField(
            model_name='surveyscorerevision',
            name='survey_score',
        ),
        migrations.RemoveField(
            model_name='surveyscorerevision',
            name='supersedes',
        ),
        migrations.DeleteModel(
            name='SurveyScale',
        ),
        migrations.DeleteModel(
            name='SurveyScore',
        ),
        migrations.DeleteModel(
            name='SurveyScoreRevision',
        ),
    ]
