# Generated by Django 5.2 on 2026-07-01 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username_attempt', models.CharField(blank=True, max_length=150)),
                ('event_type', models.CharField(choices=[('login_success', '登入成功'), ('login_failed', '登入失敗'), ('logout', '登出')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('client_session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='users_login_user_id_9a8996_idx'), models.Index(fields=['event_type', 'occurred_at'], name='users_login_event_t_62a61f_idx')],
            },
        ),
    ]
