# Generated by Django 5.2 on 2026-07-01 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_loginevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cohort', models.CharField(blank=True, max_length=100)),
                ('is_included', models.BooleanField(default=True)),
                ('exclusion_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='research_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataChangeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100)),
                ('object_pk', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['model_label', 'object_pk', 'occurred_at'], name='users_datac_model_l_05136b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExperimentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_key', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
                ('algorithm_version', models.CharField(blank=True, max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='users.researchparticipant')),
            ],
            options={
                'unique_together': {('participant', 'experiment_key')},
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_version', models.CharField(max_length=50)),
                ('granted_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('data_scope', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='users.researchparticipant')),
            ],
            options={
                'unique_together': {('participant', 'consent_version')},
            },
        ),
    ]
