# Generated by Django 5.2 on 2026-07-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_researchparticipant_datachangeaudit_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experimentassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='experimentassignment',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='researchparticipant',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConsentRecord',
        ),
        migrations.DeleteModel(
            name='ExperimentAssignment',
        ),
        migrations.DeleteModel(
            name='ResearchParticipant',
        ),
    ]
