# Generated by Django 5.2 on 2026-07-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_experimentassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='import_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='匯入備註'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='必須修改密碼'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_programming_language',
            field=models.CharField(blank=True, max_length=100, verbose_name='預計使用的程式語言'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='學校'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='學校簡稱'),
        ),
    ]
