# Generated by Django 5.2 on 2026-07-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_import_note_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
