# Generated by Django 4.2.16 on 2026-04-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField(verbose_name='單元編號')),
                ('current_level', models.IntegerField(choices=[(1, 'Level 1 補救版'), (2, 'Level 2 標準版'), (3, 'Level 3 進階版')], default=2, verbose_name='當前等級')),
                ('last_score', models.FloatField(default=0.0, verbose_name='最近評量分數')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '適性學習路徑',
                'verbose_name_plural': '適性學習路徑',
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='推薦原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='是否忽略')),
            ],
            options={
                'verbose_name': '適性推薦',
                'verbose_name_plural': '適性推薦',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未開始'), ('in_progress', '學習中'), ('completed', '已完成')], default='not_started', max_length=20, verbose_name='狀態')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='花費時間(分鐘)')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '學習進度',
                'verbose_name_plural': '學習進度',
            },
        ),
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_score_avg', models.FloatField(default=0.0, verbose_name='平均評量分數')),
                ('proficiency', models.CharField(choices=[('low', '待加強'), ('medium', '普通'), ('high', '精熟')], default='medium', max_length=10, verbose_name='精熟度')),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='課程')),
            ],
            options={
                'verbose_name': '學習表現紀錄',
                'verbose_name_plural': '學習表現紀錄',
            },
        ),
    ]
