# Generated by Django 4.2.16 on 2026-04-13 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL, verbose_name='學生'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson', verbose_name='單元'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='學生'),
        ),
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='recommended_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='推薦單元'),
        ),
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='學生'),
        ),
        migrations.AddField(
            model_name='adaptivelearningpath',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_path', to=settings.AUTH_USER_MODEL, verbose_name='學生'),
        ),
        migrations.AlterUniqueTogether(
            name='performancerecord',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='learningprogress',
            unique_together={('student', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='adaptivelearningpath',
            unique_together={('student', 'unit_number')},
        ),
    ]
