# Generated by Django 5.2 on 2026-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancerecord',
            options={'ordering': ['course'], 'verbose_name': '學習表現紀錄', 'verbose_name_plural': '學習表現紀錄'},
        ),
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='點擊時間'),
        ),
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='is_clicked',
            field=models.BooleanField(default=False, verbose_name='是否點擊'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='瀏覽次數'),
        ),
    ]
