# Generated by Django 5.2 on 2026-05-29 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_teacher_alter_enrollment_course_and_more'),
        ('learning', '0003_alter_performancerecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptivelearningpath',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adaptive_path', to=settings.AUTH_USER_MODEL, verbose_name='學生'),
        ),
        migrations.AlterField(
            model_name='adaptiverecommendation',
            name='recommended_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.lesson', verbose_name='推薦單元'),
        ),
        migrations.AlterField(
            model_name='adaptiverecommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='學生'),
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='courses.lesson', verbose_name='單元'),
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='學生'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance', to=settings.AUTH_USER_MODEL, verbose_name='學生'),
        ),
    ]
