# Generated by Django 5.2 on 2026-06-15 20:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_adaptivelearningpath_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最後活動')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '使用時段',
                'verbose_name_plural': '使用時段',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'started_at'], name='learning_st_student_8b4a50_idx')],
            },
        ),
    ]
