# Generated by Django 5.2 on 2026-06-28 14:54

from django.conf import settings
from django.db import migrations, models


def prepare_existing_learning_data(apps, schema_editor):
    LearningProgress = apps.get_model('learning', 'LearningProgress')
    AdaptiveLearningPath = apps.get_model('learning', 'AdaptiveLearningPath')
    LearningProgress.objects.update(time_spent_seconds=models.F('time_spent') * 60)
    AdaptiveLearningPath.objects.filter(unit_number__lt=1).delete()
    AdaptiveLearningPath.objects.filter(unit_number__gt=8).delete()
    AdaptiveLearningPath.objects.filter(current_level__lt=1).update(current_level=1)
    AdaptiveLearningPath.objects.filter(current_level__gt=3).update(current_level=3)
    AdaptiveLearningPath.objects.filter(last_score__lt=0).update(last_score=0)
    AdaptiveLearningPath.objects.filter(last_score__gt=100).update(last_score=100)


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_studysession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogress',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='花費時間(秒)'),
        ),
        migrations.RunPython(prepare_existing_learning_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='adaptivelearningpath',
            constraint=models.CheckConstraint(condition=models.Q(('unit_number__gte', 1), ('unit_number__lte', 8)), name='adaptive_unit_between_1_and_8'),
        ),
        migrations.AddConstraint(
            model_name='adaptivelearningpath',
            constraint=models.CheckConstraint(condition=models.Q(('current_level__gte', 1), ('current_level__lte', 3)), name='adaptive_level_between_1_and_3'),
        ),
        migrations.AddConstraint(
            model_name='adaptivelearningpath',
            constraint=models.CheckConstraint(condition=models.Q(('last_score__gte', 0), ('last_score__lte', 100)), name='adaptive_score_between_0_and_100'),
        ),
    ]
