# Generated by Django 5.2 on 2026-07-01 20:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_quizattempt_abandoned_at_quizattempt_attempt_uuid_and_more'),
        ('courses', '0003_alter_course_teacher_alter_enrollment_course_and_more'),
        ('learning', '0006_learningprogress_time_spent_seconds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='algorithm_version',
            field=models.CharField(default='adaptive-v1', max_length=50),
        ),
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='點擊次數'),
        ),
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='first_impression_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='impression_count',
            field=models.PositiveIntegerField(default=0, verbose_name='曝光次數'),
        ),
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptiverecommendation',
            name='last_impression_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='client_session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='end_reason',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studysession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='StudentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('page_url', models.CharField(blank=True, max_length=1000)),
                ('referrer', models.CharField(blank=True, max_length=1000)),
                ('duration_ms', models.PositiveBigIntegerField(default=0)),
                ('sequence_number', models.PositiveIntegerField(blank=True, null=True)),
                ('client_timezone', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('content_version', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.lesson')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assessments.question')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assessments.quiz')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='learning.adaptiverecommendation')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='learning.studysession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['student', 'occurred_at'], name='learning_st_student_f02393_idx'), models.Index(fields=['student', 'event_type', 'occurred_at'], name='learning_st_student_1115a4_idx'), models.Index(fields=['lesson', 'occurred_at'], name='learning_st_lesson__d12795_idx')],
            },
        ),
    ]
