# Generated by Django 5.2 on 2026-07-03 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_adaptiverecommendation_algorithm_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptiverecommendation',
            name='clicked_at',
        ),
        migrations.RemoveField(
            model_name='adaptiverecommendation',
            name='is_clicked',
        ),
        migrations.RemoveField(
            model_name='learningprogress',
            name='time_spent',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='last_heartbeat_at',
        ),
        migrations.CreateModel(
            name='StudentUnitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField(verbose_name='單元編號')),
                ('current_level', models.IntegerField(default=2, verbose_name='目前等級')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='作答次數')),
                ('latest_score', models.FloatField(blank=True, null=True, verbose_name='最近分數')),
                ('best_score', models.FloatField(blank=True, null=True, verbose_name='最佳分數')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='教材停留(秒)')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='最後活動時間')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_summaries', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '學生單元彙總',
                'verbose_name_plural': '學生單元彙總',
                'ordering': ['student__username', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='UnitRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField(unique=True, verbose_name='單元編號')),
                ('is_open', models.BooleanField(default=False, verbose_name='是否開放')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='開放時間')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_units', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '單元開放',
                'verbose_name_plural': '單元開放',
                'ordering': ['unit_number'],
            },
        ),
        migrations.DeleteModel(
            name='PerformanceRecord',
        ),
        migrations.AddConstraint(
            model_name='studentunitsummary',
            constraint=models.CheckConstraint(condition=models.Q(('unit_number__gte', 1), ('unit_number__lte', 8)), name='summary_unit_between_1_and_8'),
        ),
        migrations.AlterUniqueTogether(
            name='studentunitsummary',
            unique_together={('student', 'unit_number')},
        ),
        migrations.AddConstraint(
            model_name='unitrelease',
            constraint=models.CheckConstraint(condition=models.Q(('unit_number__gte', 1), ('unit_number__lte', 8)), name='release_unit_between_1_and_8'),
        ),
    ]
