# Generated by Django 4.2.16 on 2026-04-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(verbose_name='學生作答')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正確')),
                ('points_earned', models.FloatField(default=0.0, verbose_name='獲得分數')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='選項內容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正確')),
            ],
            options={
                'verbose_name': '選項',
                'verbose_name_plural': '選項',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='題目內容')),
                ('question_type', models.CharField(choices=[('multiple_choice', '選擇題'), ('true_false', '是非題'), ('short_answer', '簡答題'), ('coding', '程式題')], max_length=20, verbose_name='題型')),
                ('points', models.FloatField(default=10.0, verbose_name='配分')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('explanation', models.TextField(blank=True, verbose_name='解析')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='評量名稱')),
                ('quiz_type', models.CharField(choices=[('formative', '形成性評量'), ('summative', '總結性評量')], default='formative', max_length=20, verbose_name='評量類型')),
                ('pass_score', models.FloatField(default=60.0, verbose_name='及格分數')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '評量',
                'verbose_name_plural': '評量',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='得分')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否通過')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.quiz', verbose_name='評量')),
            ],
            options={
                'verbose_name': '作答記錄',
                'verbose_name_plural': '作答記錄',
            },
        ),
    ]
