# Generated by Django 5.2 on 2026-04-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, verbose_name='正確答案（填空/程式題用）'),
        ),
    ]
