# Generated by Django 5.2 on 2026-06-28 15:00

from django.conf import settings
from django.db import migrations, models


def clamp_existing_scores(apps, schema_editor):
    QuizAttempt = apps.get_model('assessments', 'QuizAttempt')
    QuizAttempt.objects.filter(score__lt=0).update(score=0)
    QuizAttempt.objects.filter(score__gt=100).update(score=100)


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_answer_question_alter_quizattempt_quiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='多個可接受答案請以獨立一行 ---OR--- 分隔；程式題比對會忽略空白與大小寫。', verbose_name='正確答案（填空/程式題用）'),
        ),
        migrations.RunPython(clamp_existing_scores, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='attempt_score_between_0_and_100'),
        ),
    ]
