# Generated by Django 5.2 on 2026-07-01 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='content_version',
            field=models.CharField(default='v1', max_length=50),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='pass_score_snapshot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuestionInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('first_answered_at', models.DateTimeField(blank=True, null=True)),
                ('last_answered_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveBigIntegerField(default=0)),
                ('answer_revision_count', models.PositiveIntegerField(default=0)),
                ('final_answer', models.TextField(blank=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_interactions', to='assessments.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='assessments.question')),
            ],
            options={
                'ordering': ['attempt', 'question__order'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
