# Generated by Django 5.2 on 2026-07-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_quizattempt_abandoned_at_quizattempt_attempt_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_version',
            field=models.CharField(default='v1', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='content_version',
            field=models.CharField(default='v1', max_length=50),
        ),
    ]
