# Generated by Django 5.2 on 2026-07-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_question_content_version_quiz_content_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='selected_question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
