# Generated by Django 5.2 on 2026-07-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_quizattempt_selected_question_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='程式題：多個可接受答案以獨立一行 ---OR--- 分隔，比對忽略空白與大小寫。填空題：題目內文以 __1__、__2__ 標記空格，每行對應一格答案，同格多解以 ||| 分隔。', verbose_name='正確答案（填空/程式題用）'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', '選擇題'), ('true_false', '是非題'), ('short_answer', '簡答題'), ('coding', '程式題'), ('fill_blank', '程式填空題')], max_length=20, verbose_name='題型'),
        ),
    ]
