# Generated by Django 4.2.16 on 2026-04-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='課程名稱')),
                ('description', models.TextField(verbose_name='課程描述')),
                ('difficulty', models.CharField(choices=[('beginner', '初級'), ('intermediate', '中級'), ('advanced', '進階')], default='beginner', max_length=20, verbose_name='難度')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='封面圖')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否開放')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='單元名稱')),
                ('content', models.TextField(verbose_name='內容')),
                ('lesson_type', models.CharField(choices=[('video', '影片'), ('text', '閱讀'), ('exercise', '練習題')], default='text', max_length=20, verbose_name='單元類型')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='預估時間(分鐘)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='所屬課程')),
            ],
            options={
                'verbose_name': '單元',
                'verbose_name_plural': '單元',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.FloatField(default=0.0, verbose_name='進度(%)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='課程')),
            ],
            options={
                'verbose_name': '選課紀錄',
                'verbose_name_plural': '選課紀錄',
            },
        ),
    ]
