# Generated by Django 5.2 on 2026-07-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_teacher_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_version',
            field=models.CharField(default='v1', max_length=50),
        ),
    ]
