# Generated by Django 5.2 on 2026-07-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_content_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_type',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
