"""Unit 3（For／While 與基礎演算法）題庫 — 全選擇制。

L1 對標 ITS（迴圈概念、range 讀值、單步追蹤）、
L2 對標 TQC+ 觀念題（迴圈追蹤、break/continue、極值樣板；收錄競賽第 9、12 題）、
L3 對標競賽／TQC 實作（sentinel、reduce/filter/search、GCD；收錄競賽第 4、5、15、22、24 題）。
"""
from .question_helpers import mc, fb

# ── U3 Level 1：55 選擇 + 45 填空 ──
U3_L1 = [
    # 迴圈概念（12）
    mc('已經知道要重複幾次時，優先使用哪種迴圈？', 'for', 'while', 'if', 'def'),
    mc('重複次數不確定、要做到條件不成立為止，用哪種迴圈？', 'while', 'for', 'elif', 'range'),
    mc('while 迴圈最容易因為什麼問題停不下來？', '條件用到的變數忘記更新', '使用 print()',
       '條件寫成數字', '有縮排'),
    mc('range(1, 6) 「不會」產生下列哪個數字？', '6', '1', '3', '5',
       explanation='range 不包含結束值。'),
    mc('range(5) 產生的第一個數字是？', '0', '1', '5', '-1'),
    mc('range(2, 10, 2) 的第三個參數 2 代表什麼？', '間隔（每次加 2）', '起點', '終點', '重複次數'),
    mc('for ch in "abc" 這種寫法會發生什麼？', '依序取出字串的每個字元', '發生錯誤',
       '只取第一個字元', '把字串轉成數字'),
    mc('在迴圈中要「立刻結束整個迴圈」使用？', 'break', 'continue', 'return', 'stop'),
    mc('在迴圈中要「跳過這一圈、直接進下一圈」使用？', 'continue', 'break', 'pass', 'next'),
    mc('累加器變數 total 在迴圈開始前通常要設成？', '0', '1', '100', '不用設定'),
    mc('計數器變數 count 的作用是？', '記錄符合條件的資料出現幾次', '儲存最大值',
       '控制縮排', '轉換型態'),
    mc('for i in range(3) 中的 i 稱為什麼？', '迴圈變數', '常數', '函式', '條件式'),

    # range 讀值（12）
    mc('list(range(5)) 的結果是？', '[0, 1, 2, 3, 4]', '[1, 2, 3, 4, 5]', '[0, 1, 2, 3, 4, 5]', '[5]'),
    mc('range(1, 6) 產生的最後一個數字是？', '5', '6', '1', '0'),
    mc('range(2, 11, 2) 會產生幾個數字？', '5', '4', '6', '10',
       explanation='2、4、6、8、10 共 5 個。'),
    mc('range(3) 會讓 for 迴圈執行幾次？', '3 次', '2 次', '4 次', '無限次'),
    mc('range(10, 0, -2) 產生的最後一個數字是？', '2', '0', '10', '1',
       explanation='10、8、6、4、2，不包含 0。'),
    mc('range(1, 10, 3) 產生哪些數字？', '1、4、7', '1、3、9', '3、6、9', '1、4、7、10'),
    mc('要產生 5、6、7、8，range 應該寫？', 'range(5, 9)', 'range(5, 8)', 'range(4, 8)', 'range(5, 9, 2)'),
    mc('range(0) 會讓迴圈執行幾次？', '0 次', '1 次', '無限次', '發生錯誤'),
    mc('要從 10 倒數到 1，range 應該寫？', 'range(10, 0, -1)', 'range(10, 1, -1)',
       'range(1, 10, -1)', 'range(10, 0)',
       explanation='range(10, 1, -1) 只到 2；第三參數不寫預設 +1 產生不出倒數。'),
    mc('len(list(range(4, 9))) 的結果是？', '5', '4', '9', '6',
       explanation='4、5、6、7、8 共 5 個。'),
    mc('for i in range(1, 4): print(i) 共輸出幾行？', '3 行', '4 行', '1 行', '0 行'),
    mc('要印出 1 到 100（含），range 應該寫？', 'range(1, 101)', 'range(1, 100)',
       'range(0, 100)', 'range(100)'),

    # for 追蹤（12）
    mc('以下程式的輸出是？\n\n```python\nfor i in range(3):\n    print(i)\n```', '0 1 2（各一行）', '1 2 3（各一行）', '0 1 2 3', '3'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(1, 4):\n    total += i\nprint(total)\n```', '6', '3', '10', '4',
       explanation='1+2+3=6。'),
    mc('以下程式的輸出是？\n\n```python\nfor ch in "Hi":\n    print(ch)\n```', 'H 與 i（各一行）', 'Hi', 'H', '發生錯誤'),
    mc('以下程式共輸出幾行？\n\n```python\nfor i in range(2):\n    print("哈")\n```', '2 行', '1 行', '3 行', '0 行'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(2, 5):\n    print(i, end=" ")\n```', '2 3 4', '2 3 4 5', '0 1 2 3 4', '2 4'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nfor i in range(5):\n    count += 1\nprint(count)\n```', '5', '4', '10', '0'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in [2, 4, 6]:\n    total += i\nprint(total)\n```', '12', '6', '246', '3'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(3):\n    print("*" * (i + 1))\n```', '*、**、***（三行遞增）', '***、**、*（三行遞減)', '***', '* * *'),
    mc('以下程式的輸出是？\n\n```python\nresult = 1\nfor i in range(1, 4):\n    result *= i\nprint(result)\n```', '6', '3', '1', '24',
       explanation='1×1×2×3=6（連乘）。'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(1, 6):\n    if i % 2 == 0:\n        print(i, end=" ")\n```', '2 4', '1 3 5', '1 2 3 4 5', '2 4 6'),
    mc('以下程式最後輸出的 i 是？\n\n```python\nfor i in range(3):\n    pass\nprint(i)\n```', '2', '3', '0', '發生錯誤',
       explanation='迴圈結束後 i 保留最後一次的值 2。'),
    mc('以下程式的輸出是？\n\n```python\nname = "Amy"\ncount = 0\nfor ch in name:\n    count += 1\nprint(count)\n```', '3', 'Amy', '1', '0'),

    # while 追蹤（10）
    mc('以下程式的輸出是？\n\n```python\ncount = 1\nwhile count <= 3:\n    print(count)\n    count += 1\n```', '1 2 3（各一行）', '1 2 3 4', '0 1 2 3', '無限迴圈'),
    mc('以下程式會發生什麼？\n\n```python\ncount = 1\nwhile count <= 3:\n    print(count)\n```', '無限迴圈（count 永遠是 1）', '輸出 1 2 3', '輸出 1 後停止', 'SyntaxError',
       explanation='忘記 count += 1，條件永遠成立。'),
    mc('以下程式的輸出是？\n\n```python\nn = 5\nwhile n > 0:\n    print(n, end=" ")\n    n -= 1\n```', '5 4 3 2 1', '5 4 3 2 1 0', '1 2 3 4 5', '無限迴圈'),
    mc('while False: 底下的區塊會執行幾次？', '0 次', '1 次', '無限次', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nx = 1\nwhile x < 10:\n    x = x * 2\nprint(x)\n```', '16', '8', '10', '2',
       explanation='1→2→4→8→16，16 不小於 10 停止。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nn = 1\nwhile n <= 4:\n    total += n\n    n += 1\nprint(total)\n```', '10', '6', '4', '15',
       explanation='1+2+3+4=10。'),
    mc('while 迴圈每一圈開始前會先做什麼？', '檢查條件是否成立', '執行區塊一次',
       '把變數歸零', '輸出結果'),
    mc('以下程式的輸出是？\n\n```python\nn = 10\nwhile n >= 4:\n    n -= 3\nprint(n)\n```', '1', '4', '7', '-2',
       explanation='10→7→4→1，1 < 4 停止。'),
    mc('下列哪個 while 條件讓迴圈「永遠執行」（需搭配 break 離開）？', 'while True:',
       'while False:', 'while 0:', 'while x == x + 1:'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nwhile count < 3:\n    count += 1\nprint(count)\n```', '3', '2', '0', '4'),

    # break / continue（9）
    mc('以下程式的輸出是？\n\n```python\nfor i in range(1, 6):\n    if i == 3:\n        break\n    print(i, end=" ")\n```', '1 2', '1 2 3', '1 2 4 5', '3',
       explanation='i 等於 3 時直接跳出迴圈。'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(1, 6):\n    if i == 3:\n        continue\n    print(i, end=" ")\n```', '1 2 4 5', '1 2', '1 2 3', '4 5',
       explanation='continue 只跳過 3 這一圈。'),
    mc('break 和 continue 的差別是？', 'break 結束整個迴圈，continue 只跳過本圈',
       '兩者相同', 'break 跳過本圈，continue 結束迴圈', '都會結束程式'),
    mc('以下程式的輸出是？\n\n```python\nn = 0\nwhile True:\n    n += 1\n    if n == 4:\n        break\nprint(n)\n```', '4', '3', '5', '無限迴圈'),
    mc('以下程式共輸出幾個數字？\n\n```python\nfor i in range(10):\n    if i % 2 == 1:\n        continue\n    print(i)\n```', '5 個', '10 個', '4 個', '0 個',
       explanation='0、2、4、6、8。'),
    mc('搜尋到目標後不想再繼續找，應該用？', 'break', 'continue', 'pass', 'else'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(5):\n    if i > 2:\n        break\nprint(i)\n```', '3', '2', '4', '5',
       explanation='i=3 時觸發 break，迴圈變數保留 3。'),
    mc('continue 之後、同一圈剩下的程式會？', '不執行，直接進下一圈', '照常執行',
       '執行一半', '發生錯誤'),
    mc('break 只能跳出幾層迴圈？', '1 層（最靠近的那層）', '全部', '2 層', '看縮排決定'),

    # ── L1 填空（45）──
    fb('印出 1 到 5（各一行）。\n\n```python\nfor i in range(1, __1__):\n    print(i)\n```', '6'),
    fb('印出 0 到 4。\n\n```python\nfor i in range(__1__):\n    print(i)\n```', '5'),
    fb('計算 1 到 10 的總和。\n\n```python\ntotal = 0\nfor i in range(1, 11):\n    total __1__ i\nprint(total)   # 55\n```', '+='),
    fb('用 while 印出 1 到 5。\n\n```python\ni = 1\nwhile i __1__ 5:\n    print(i)\n    i += 1\n```', '<='),
    fb('while 迴圈每圈讓 i 加 1（避免無限迴圈）。\n\n```python\ni = 1\nwhile i <= 5:\n    print(i)\n    i __1__ 1\n```', '+='),
    fb('印出 2 到 10 的偶數（用 step）。\n\n```python\nfor i in range(2, 11, __1__):\n    print(i)\n```', '2'),
    fb('從 5 倒數到 1。\n\n```python\nfor i in range(5, 0, __1__):\n    print(i)\n```', '-1'),
    fb('計算連乘 1×2×3×4。\n\n```python\nresult = 1\nfor i in range(1, 5):\n    result __1__ i\nprint(result)   # 24\n```', '*='),
    fb('統計 1 到 20 中 3 的倍數個數。\n\n```python\ncount = 0\nfor i in range(1, 21):\n    if i % 3 == 0:\n        count += __1__\nprint(count)   # 6\n```', '1'),
    fb('走訪字串的每個字元。\n\n```python\nfor ch __1__ "Python":\n    print(ch)\n```', 'in'),
    fb('累加器歸零起步。\n\n```python\ntotal = __1__\nfor i in [5, 8, 2]:\n    total += i\nprint(total)   # 15\n```', '0'),
    fb('連乘的初始值。\n\n```python\nresult = __1__\nfor i in [2, 3, 4]:\n    result *= i\nprint(result)   # 24\n```', '1'),
    fb('遇到 5 就跳出迴圈。\n\n```python\nfor i in range(1, 10):\n    if i == 5:\n        __1__\n    print(i)\n```', 'break'),
    fb('略過 5、其餘照印。\n\n```python\nfor i in range(1, 8):\n    if i == 5:\n        __1__\n    print(i)\n```', 'continue'),
    fb('印出 1 到 10 中的奇數。\n\n```python\nfor i in range(1, 11):\n    if i % 2 == __1__:\n        print(i)\n```', '1'),
    fb('找出串列最大值（不用 max）。\n\n```python\nnums = [3, 9, 2, 7]\nbig = nums[0]\nfor n in nums:\n    if n __1__ big:\n        big = n\nprint(big)   # 9\n```', '>'),
    fb('找出串列最小值（不用 min）。\n\n```python\nnums = [8, 3, 12, 5]\nsmall = nums[0]\nfor n in nums:\n    if n __1__ small:\n        small = n\nprint(small)   # 3\n```', '<'),
    fb('輸入 0 就停止的 sentinel 迴圈。\n\n```python\nwhile True:\n    n = int(input())\n    if n == __1__:\n        break\n    print(n)\n```', '0'),
    fb('印出 3 的 1 到 5 倍。\n\n```python\nfor i in range(1, 6):\n    print(3 __1__ i)\n```', '*'),
    fb('用 while 從 10 倒數到 1。\n\n```python\nn = 10\nwhile n >= 1:\n    print(n)\n    n __1__ 1\n```', '-='),
    fb('計算 5 個數的平均：先加總再除以個數。\n\n```python\nnums = [4, 8, 6, 2, 10]\ntotal = 0\nfor n in nums:\n    total += n\nprint(total / __1__)   # 6.0\n```', '5'),
    fb('每圈輸出目前累計值（依序輸出 1、3、6）。\n\n```python\ntotal = 0\nfor i in [1, 2, 3]:\n    total += i\n    print(__1__)\n```', 'total',
       explanation='累計值依序為 1、3、6。'),
    fb('印出 1 到 6 每個數的平方。\n\n```python\nfor i in range(1, 7):\n    print(i __1__ 2)\n```', '**'),
    fb('while 條件：餘額夠就一直買（每次花 30）。\n\n```python\nmoney = 100\nwhile money __1__ 30:\n    money -= 30\nprint(money)   # 10\n```', '>='),
    fb('數字翻倍直到超過 100。\n\n```python\nn = 3\nwhile n <= 100:\n    n = n * __1__\nprint(n)   # 192\n```', '2'),
    fb('印出 20 到 10 的偶數（遞減）。\n\n```python\nfor i in range(20, 9, -__1__):\n    print(i)\n```', '2'),
    fb('統計字串中 "a" 出現次數。\n\n```python\ncount = 0\nfor ch in "banana":\n    if ch == __1__:\n        count += 1\nprint(count)   # 3\n```', ['"a"', "'a'"]),
    fb('累加 1 到 n（n 由輸入決定）。\n\n```python\nn = int(input())\ntotal = 0\nfor i in range(1, n __1__ 1):\n    total += i\nprint(total)\n```', '+'),
    fb('印出五五乘法：5×1 到 5×9 的結果。\n\n```python\nfor i in range(1, __1__):\n    print(5 * i)\n```', '10'),
    fb('只印出正數。\n\n```python\nfor n in [3, -1, 7, -5, 2]:\n    if n __1__ 0:\n        print(n)\n```', '>'),
    fb('印出 1 到 15 中「不是」4 的倍數的數（用 continue）。\n\n```python\nfor i in range(1, 16):\n    if i % 4 == 0:\n        __1__\n    print(i)\n```', 'continue'),
    fb('找到第一個大於 50 的數就停止。\n\n```python\nfor n in [12, 38, 57, 64]:\n    if n > 50:\n        print(n)\n        __1__\n```', 'break'),
    fb('每圈讀一次輸入，共讀 3 次並加總。\n\n```python\ntotal = 0\nfor i in range(__1__):\n    total += int(input())\nprint(total)\n```', '3'),
    fb('印出字串長度次數的星號（一行一個）。\n\n```python\ntext = "abcd"\nfor ch in text:\n    print(__1__)\n```', ['"*"', "'*'"]),
    fb('while 讀輸入直到輸入 "q"。\n\n```python\nwhile True:\n    cmd = input()\n    if cmd == __1__:\n        break\n    print("執行", cmd)\n```', ['"q"', "'q'"]),
    fb('計算 10 以內奇數和。\n\n```python\ntotal = 0\nfor i in range(1, 11, 2):\n    total += i\nprint(__1__)   # 25\n```', 'total'),
    fb('存錢到達 500 需要幾天（每天存 80）。\n\n```python\nmoney = 0\ndays = 0\nwhile money < 500:\n    money += 80\n    days += __1__\nprint(days)   # 7\n```', '1'),
    fb('印出 100、90、…、10。\n\n```python\nfor i in range(100, 0, __1__):\n    print(i)\n```', '-10'),
    fb('計數：串列中大於 60 的個數。\n\n```python\ncount = 0\nfor s in [55, 70, 88, 45, 92]:\n    if s > 60:\n        count += 1\nprint(__1__)   # 3\n```', 'count'),
    fb('把 1 到 5 印在同一行（空格分隔）。\n\n```python\nfor i in range(1, 6):\n    print(i, end=__1__)\n```', ['" "', "' '"]),
    fb('溫度連續下降模擬：每小時降 2 度，從 30 降到低於 20 需幾小時。\n\n```python\nt = 30\nhours = 0\nwhile t >= 20:\n    t -= 2\n    hours += 1\nprint(__1__)   # 6\n```', 'hours'),
    fb('印出 "Go!" 三次。\n\n```python\nfor i in range(__1__):\n    print("Go!")\n```', '3'),
    fb('計算 2 的 1 到 8 次方的最後一個值。\n\n```python\nfor i in range(1, 9):\n    v = 2 ** i\nprint(__1__)   # 256\n```', 'v'),
    fb('累加偶數：1 到 10 的偶數總和。\n\n```python\ntotal = 0\nfor i in range(1, 11):\n    if i % 2 == 0:\n        total += __1__\nprint(total)   # 30\n```', 'i'),
    fb('while 搭配輸入驗證：輸入負數就再問一次。\n\n```python\nn = int(input())\nwhile n __1__ 0:\n    n = int(input())\nprint("收到", n)\n```', '<'),
]


# ── U3 Level 2：60 選擇 + 40 填空（TQC+ 觀念題：迴圈追蹤＋演算法樣板）──
U3_L2 = [
    # 迴圈追蹤（30，含競賽原題 2 題）
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\nresult = 0\nfor i in range(1, 6):\n    if i % 2 == 0:\n        result += i\nprint(result % 4)\n```', '2', '0', '1', '3',
       explanation='2+4=6，6%4=2。（113 商業類技藝競賽學科第 9 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\nn = 0\nfor i in range(10):\n    if i % 3 == 0:\n        n += i\nprint(n % 4)\n```', '2', '0', '1', '3',
       explanation='0+3+6+9=18，18%4=2。（113 商業類技藝競賽學科第 12 題）'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(1, 101):\n    total += i\nprint(total)\n```', '5050', '5000', '4950', '10100'),
    mc('以下程式的輸出是？（TQC 偶數連加情境）\n\n```python\ntotal = 0\nfor i in range(1, 101):\n    if i % 2 == 0:\n        total += i\nprint(total)\n```', '2550', '2500', '5050', '2450',
       explanation='2+4+…+100 = 2550。'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(3):\n    print(i * 2, end=" ")\n```', '0 2 4', '2 4 6', '0 1 2', '0 2 4 6'),
    mc('以下程式的輸出是？\n\n```python\nx = 64\ncount = 0\nwhile x > 1:\n    x //= 2\n    count += 1\nprint(count)\n```', '6', '5', '7', '32',
       explanation='64→32→16→8→4→2→1，共 6 次。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\ni = 1\nwhile i <= 10:\n    total += i\n    i += 2\nprint(total)\n```', '25', '55', '30', '20',
       explanation='1+3+5+7+9=25。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [8, 3, 12, 5]\nm = nums[0]\nfor n in nums:\n    if n > m:\n        m = n\nprint(m)\n```', '12', '8', '5', '3'),
    mc('以下程式的輸出是？\n\n```python\nnums = [8, 3, 12, 5]\nm = nums[0]\nfor n in nums:\n    if n < m:\n        m = n\nprint(m)\n```', '3', '8', '12', '5'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nfor n in [3, -1, 7, -5, 2]:\n    if n > 0:\n        count += 1\nprint(count)\n```', '3', '2', '5', '12'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(1, 10):\n    if i * i > 20:\n        print(i)\n        break\n```', '5', '4', '21', '25',
       explanation='5×5=25 是第一個平方超過 20 的數。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(1, 6):\n    if i == 3:\n        continue\n    total += i\nprint(total)\n```', '12', '15', '3', '9',
       explanation='1+2+4+5=12（跳過 3）。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(0, 10, 3):\n    total += i\nprint(total)\n```', '18', '15', '12', '30',
       explanation='0+3+6+9=18。'),
    mc('range(1, 20, 4) 會產生幾個數字？', '5', '4', '6', '19',
       explanation='1、5、9、13、17。'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(5, 0, -1):\n    print(i, end="")\n```', '54321', '543210', '12345', '5 4 3 2 1'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(1, 4):\n    total += i * i\nprint(total)\n```', '14', '9', '36', '6',
       explanation='1+4+9=14。'),
    mc('以下程式的輸出是？\n\n```python\na, b = 0, 1\nfor i in range(3):\n    a, b = b, a + b\nprint(a)\n```', '2', '1', '3', '5',
       explanation='(0,1)→(1,1)→(1,2)→(2,3)，a=2。'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nfor ch in "hello":\n    if ch in "aeiou":\n        count += 1\nprint(count)\n```', '2', '3', '1', '5',
       explanation='母音 e、o 共 2 個。'),
    mc('以下程式依序輸入 3、5、0，輸出是？\n\n```python\ntotal = 0\nwhile True:\n    n = int(input())\n    if n == 0:\n        break\n    total += n\nprint(total)\n```', '8', '0', '3', '35'),
    mc('以下程式的輸出是？\n\n```python\nn = 345\ntotal = 0\nwhile n > 0:\n    total += n % 10\n    n //= 10\nprint(total)\n```', '12', '345', '15', '3',
       explanation='各位數和：5+4+3=12。'),
    mc('以下程式的輸出是？\n\n```python\ni = 0\nwhile i < 5:\n    i += 2\nprint(i)\n```', '6', '4', '5', '無限迴圈',
       explanation='0→2→4→6，6 不小於 5 停止。'),
    mc('以下程式的輸出是？\n\n```python\nn = 15\nfor i in range(2, 15):\n    if n % i == 0:\n        print(i)\n        break\n```', '3', '5', '15', '2',
       explanation='找最小因數：15 % 3 == 0 先成立。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(2, 8):\n    total += 1\nprint(total)\n```', '6', '7', '8', '5'),
    mc('以下程式的輸出是？\n\n```python\ns = 0\nk = 20\nwhile k > 0:\n    s += k\n    k -= 5\nprint(s)\n```', '50', '45', '40', '20',
       explanation='20+15+10+5=50。'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nfor i in range(1, 31):\n    if i % 4 == 0:\n        count += 1\nprint(count)\n```', '7', '8', '6', '30',
       explanation='4、8、…、28 共 7 個。'),
    mc('以下程式的輸出是？\n\n```python\nresult = 1\ni = 1\nwhile i <= 5:\n    result *= 2\n    i += 1\nprint(result)\n```', '32', '16', '10', '25',
       explanation='2 連乘 5 次 = 32。'),
    mc('以下程式的輸出是？\n\n```python\nbest = 0\nfor s in [72, 95, 88, 61]:\n    if s > best:\n        best = s\nprint(best)\n```', '95', '88', '72', '61'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(10, 0, -3):\n    total += i\nprint(total)\n```', '22', '18', '10', '30',
       explanation='10+7+4+1=22。'),
    mc('以下程式的輸出是？\n\n```python\nx = 100\nwhile x % 7 != 0:\n    x -= 1\nprint(x)\n```', '98', '94', '100', '7',
       explanation='從 100 往下找第一個 7 的倍數。'),
    mc('以下程式的輸出是？\n\n```python\nfound = False\nfor n in [4, 9, 16]:\n    if n % 2 == 1:\n        found = True\nprint(found)\n```', 'True', 'False', '9', '發生錯誤',
       explanation='9 是奇數，旗標被設為 True。'),

    # 觀念與常見錯誤（30）
    mc('「持續讀取輸入直到使用者輸入 -1」最適合用哪種寫法？', 'while 迴圈（次數未知）',
       'for i in range(10)', 'if 判斷', 'for ch in input()'),
    mc('「把串列每個元素都處理一次」最適合用？', 'for 迴圈', 'while True', 'if/elif', 'break'),
    mc('range(5, 1) 會讓迴圈執行幾次？', '0 次', '4 次', '5 次', '發生錯誤',
       explanation='起點大於終點且 step 為正，產生空範圍。'),
    mc('找最大值時，把初始值設成 0 而不是第一個元素，何時會出錯？', '所有資料都是負數時',
       '資料有 0 時', '資料超過 100 時', '永遠不會出錯',
       explanation='全負數時 0 比所有資料都大，答案會錯成 0。'),
    mc('下列哪個 while 迴圈「不是」無限迴圈？', 'n = 10 開始，每圈 n -= 1，條件 n > 0',
       'n = 10 開始，每圈 n += 1，條件 n > 0', '條件 while True: 且沒有 break',
       'n = 1 開始，每圈 n *= 1，條件 n < 100'),
    mc('計數器 count += 1 誤寫在 if 區塊外面，會造成？', '每一圈都加 1，統計結果偏大',
       '不影響結果', '語法錯誤', '迴圈提前結束'),
    mc('sum(range(1, 6)) 的結果是？', '15', '21', '10', '6'),
    mc('以下兩段程式的結果關係？\n\n```python\n# 甲\nfor i in range(3):\n    print("Hi")\n\n# 乙\ni = 0\nwhile i < 3:\n    print("Hi")\n    i += 1\n```', '輸出完全相同', '甲多一行', '乙多一行', '乙是無限迴圈',
       explanation='for 與 while 可以互相改寫。'),
    mc('pass 在迴圈（或分支）中的作用是？', '什麼都不做的占位符', '跳出迴圈',
       '跳過本圈', '暫停一秒'),
    mc('要「每圈都輸出在同一行」，print 應該加什麼？', 'end=""', 'sep=""', 'flush', 'inline=True'),
    mc('off-by-one 錯誤：想加總 1 到 n 卻寫 range(1, n)，結果會？', '少加了 n', '多加了 n',
       '完全正確', '發生錯誤'),
    mc('讀取「不定筆數」資料直到特殊值出現，這種模式稱為？', 'sentinel loop（哨兵值）',
       'for-else', '巢狀迴圈', '遞迴'),
    mc('while 迴圈的三要素不包含？', '大括號', '初始值', '條件式', '更新變數'),
    mc('下列哪段程式可以計算輸入的 5 個數的平均？',
       '累加 5 次後除以 5', '只讀最後一個數除以 5', '把 5 個數相乘', '排序後取中間',
       explanation='平均 = 總和 ÷ 個數。'),
    mc('for i in range(len("abc")) 中，i 依序是？', '0、1、2', '1、2、3', 'a、b、c', '0、1、2、3'),
    mc('以下程式想印 1~5 卻只印 1~4，哪裡錯？\n\n```python\nfor i in range(1, 5):\n    print(i)\n```', 'range 終點應為 6', 'range 起點應為 0', '缺少 step', 'print 縮排錯誤'),
    mc('continue 放在累加之前，會造成？', '被跳過的那圈不會累加', '每圈都累加',
       '迴圈結束', '語法錯誤'),
    mc('哪一種資料「不能」直接用 for 走訪？', '整數 12345', '字串 "abc"', '串列 [1, 2]', 'range(3)',
       explanation='整數不可迭代；要先轉字串。'),
    mc('while input() != "q": 這種寫法每圈會做什麼？', '讀一次輸入並判斷是否為 q',
       '只讀第一次輸入', '無限迴圈', '語法錯誤'),
    mc('印九九乘法表其中一列（5 的 1~9 倍）需要幾層迴圈？', '1 層', '2 層', '3 層', '0 層'),
    mc('累加浮點數 0.1 十次，結果可能是？', '0.9999999999999999（有浮點誤差）', '一定剛好 1.0',
       '發生錯誤', '10.0', explanation='二進位儲存造成微小誤差，比較時應用 round。'),
    mc('要統計及格與不及格「兩種」人數，需要幾個計數器？', '2 個', '1 個', '3 個', '0 個'),
    mc('以下程式的功能是？\n\n```python\nn = int(input())\nwhile n < 1 or n > 6:\n    n = int(input())\n```', '輸入驗證：直到輸入 1~6 才繼續', '計算總和',
       '找最大值', '無限迴圈'),
    mc('迴圈中若同時需要「元素值」與「這是第幾筆」，常用的寫法是？',
       '另外維護一個計數器變數', '用兩個 for', '用 if', '做不到'),
    mc('把 while True + break 改寫成一般 while 條件，好處是？', '停止條件一目了然',
       '執行速度加倍', '不需要縮排', '可以省略冒號'),
    mc('下列哪個任務「不需要」迴圈？', '判斷單一數字的正負', '加總 100 個數',
       '印 50 顆星星', '找 20 個數的最大值'),
    mc('for 迴圈結束後，迴圈變數 i 的值是？', '最後一次迭代的值', '0', 'None', '無法存取'),
    mc('兩個 print 之間想空一行，可以怎麼做？', '多呼叫一次 print()', '用 break',
       '用 continue', '把 end 設為 "x"'),
    mc('統計輸入的正、負、零三類個數，迴圈內需要什麼結構？', 'if/elif/else 三分支',
       '三個獨立迴圈', 'break', '巢狀 while'),
    mc('哪個寫法可以印出 1 到 9 的「奇數」？', 'range(1, 10, 2)', 'range(1, 10)',
       'range(2, 10, 2)', 'range(0, 9, 2)'),

    # ── L2 填空（40）──
    fb('TQC 情境：輸入 a、b（a<b），計算 a 到 b 之間偶數的總和。\n\n```python\na = int(input())\nb = int(input())\ntotal = 0\nfor i in range(a, b + 1):\n    if i % 2 __1__ 0:\n        total += i\nprint(total)\n```', '=='),
    fb('TQC 情境：不斷輸入數字直到 9999，輸出最小值。\n\n```python\nsmallest = None\nwhile True:\n    n = int(input())\n    if n == 9999:\n        __1__\n    if smallest is None or n < smallest:\n        smallest = n\nprint(smallest)\n```', 'break'),
    fb('密碼最多試 3 次，答對就跳出。\n\n```python\nok = False\nfor attempt in range(__1__):\n    pwd = input()\n    if pwd == "1234":\n        ok = True\n        break\nprint("登入成功" if ok else "鎖定")\n```', '3'),
    fb('統計正、負、零的個數。\n\n```python\npos = neg = zero = 0\nfor n in [3, -1, 0, 7, -5]:\n    if n > 0:\n        pos += 1\n    elif n < 0:\n        neg += 1\n    else:\n        zero __1__ 1\nprint(pos, neg, zero)   # 2 2 1\n```', '+='),
    fb('用 continue 跳過負數，只加總正數。\n\n```python\ntotal = 0\nfor n in [5, -2, 8, -1, 3]:\n    if n < 0:\n        __1__\n    total += n\nprint(total)   # 16\n```', 'continue'),
    fb('計算各位數字和。\n\n```python\nn = 2739\ntotal = 0\nwhile n > 0:\n    total += n % 10\n    n __1__ 10\nprint(total)   # 21\n```', '//='),
    fb('印出 7 的倍數（100 以內）。\n\n```python\nfor i in range(7, 101, __1__):\n    print(i)\n```', '7'),
    fb('計算平均（總和與筆數一起累計）。\n\n```python\nnums = [80, 95, 60, 75]\ntotal = 0\ncount = 0\nfor n in nums:\n    total += n\n    count += 1\nprint(total __1__ count)   # 77.5\n```', '/'),
    fb('找最大值同時記錄「第幾筆」。\n\n```python\nnums = [40, 90, 65]\nbest = nums[0]\npos = 0\nidx = 0\nfor n in nums:\n    if n > best:\n        best = n\n        pos = __1__\n    idx += 1\nprint(best, pos)   # 90 1\n```', 'idx'),
    fb('複利計算：本金翻到兩倍需要幾年（年利率 6%）。\n\n```python\nmoney = 100\nyears = 0\nwhile money < __1__:\n    money *= 1.06\n    years += 1\nprint(years)   # 12\n```', '200'),
    fb('用 while 印 1 到 n 的平方。\n\n```python\nn = 5\ni = 1\nwhile i <= n:\n    print(i ** 2)\n    i __1__ 1\n```', '+='),
    fb('倒數計時：從 10 到 1 再印出「發射」。\n\n```python\nfor i in range(10, __1__, -1):\n    print(i)\nprint("發射")\n```', '0'),
    fb('計算 1 到 50 中可被 3 或 5 整除的數量。\n\n```python\ncount = 0\nfor i in range(1, 51):\n    if i % 3 == 0 __1__ i % 5 == 0:\n        count += 1\nprint(count)   # 23\n```', 'or'),
    fb('累計消費直到超過預算就停止。\n\n```python\nbudget = 100\nspent = 0\nfor price in [30, 25, 40, 20]:\n    if spent + price > budget:\n        __1__\n    spent += price\nprint(spent)   # 95\n```', 'break'),
    fb('印乘法表的第 n 列（n×1 到 n×9，一行印完）。\n\n```python\nn = 7\nfor i in range(1, 10):\n    print(n * i, end=" ")\nprint(__1__)\n```', ['""', "''"],
       explanation='最後補一個換行；print() 空引數即可，這裡用空字串等效。'),
    fb('找出第一個能同時被 6 和 8 整除的正整數。\n\n```python\nn = 1\nwhile not (n % 6 == 0 and n % 8 == 0):\n    n += 1\nprint(__1__)   # 24\n```', 'n'),
    fb('模擬存錢筒：每天存的錢遞增 10 元（第一天 10）。存滿 5 天共多少？\n\n```python\ntotal = 0\nfor day in range(1, 6):\n    total += day * __1__\nprint(total)   # 150\n```', '10'),
    fb('旗標模式：檢查串列是否含有負數。\n\n```python\nhas_neg = False\nfor n in [3, 8, -2, 7]:\n    if n < 0:\n        has_neg = __1__\nprint(has_neg)   # True\n```', 'True'),
    fb('計算 n!（n 的階乘）。\n\n```python\nn = 6\nresult = 1\nfor i in range(1, n + 1):\n    result __1__ i\nprint(result)   # 720\n```', '*='),
    fb('把 while 改成由條件控制（不用 break）：加總到超過 100 為止。\n\n```python\ntotal = 0\nn = 1\nwhile total __1__ 100:\n    total += n\n    n += 1\nprint(total)   # 105\n```', '<='),
    fb('統計字串中的數字字元個數。\n\n```python\ncount = 0\nfor ch in "a1b22c333":\n    if "0" <= ch __1__ "9":\n        count += 1\nprint(count)   # 6\n```', '<='),
    fb('印出 1 到 30 中「既是 2 的倍數也是 3 的倍數」的數。\n\n```python\nfor i in range(1, 31):\n    if i % 2 == 0 __1__ i % 3 == 0:\n        print(i)\n```', 'and'),
    fb('分數登記：讀 4 筆成績，統計最高分。\n\n```python\nbest = 0\nfor i in range(4):\n    s = int(input())\n    if s __1__ best:\n        best = s\nprint(best)\n```', '>'),
    fb('雨量累計：超過 200 毫米發布警報並停止統計（輸出「警報」與 235）。\n\n```python\ntotal = 0\nfor rain in [80, 65, 90, 30]:\n    total += rain\n    if total > 200:\n        print("警報")\n        __1__\nprint(total)\n```', 'break',
       explanation='80+65+90=235 時觸發警報並跳出。'),
    fb('計算 2+4+6+…直到總和第一次超過 50，輸出最後加入的數。\n\n```python\ntotal = 0\nn = 0\nwhile total <= 50:\n    n += 2\n    total += n\nprint(__1__)   # 14\n```', 'n',
       explanation='2+4+…+14 = 56 > 50。'),
    fb('把秒數每圈減半，直到小於 1 秒，數共幾圈。\n\n```python\nt = 60\nrounds = 0\nwhile t >= 1:\n    t /= __1__\n    rounds += 1\nprint(rounds)   # 6\n```', '2',
       explanation='60→30→15→7.5→3.75→1.875→0.9375，共 6 次。'),
    fb('印出三角形：第 i 列印 i 顆星。\n\n```python\nfor i in range(1, 5):\n    print("*" __1__ i)\n```', '*'),
    fb('每圈輸入一個字，串接成句子，輸入 "。" 結束。\n\n```python\nsentence = ""\nwhile True:\n    w = input()\n    if w == "。":\n        break\n    sentence __1__ w\nprint(sentence)\n```', '+='),
    fb('找出 100 以內最大的 13 的倍數。\n\n```python\nn = 100\nwhile n % 13 != 0:\n    n -= __1__\nprint(n)   # 91\n```', '1'),
    fb('去掉極端值：加總時跳過最大值 100。\n\n```python\ntotal = 0\nfor s in [80, 100, 70, 90]:\n    if s == 100:\n        continue\n    total += s\nprint(__1__)   # 240\n```', 'total'),
    fb('雞兔同籠枚舉：頭 10、腳 28，找雞的數量。\n\n```python\nfor chicken in range(11):\n    rabbit = 10 - chicken\n    if chicken * 2 + rabbit * 4 == __1__:\n        print(chicken)   # 6\n```', '28'),
    fb('模擬骰子點數統計：出現 6 的次數。\n\n```python\nrolls = [3, 6, 2, 6, 6, 1]\ncount = 0\nfor r in rolls:\n    if r == __1__:\n        count += 1\nprint(count)   # 3\n```', '6'),
    fb('計算購物車總價，滿 500 折 50。\n\n```python\nprices = [120, 250, 180]\ntotal = 0\nfor p in prices:\n    total += p\nif total >= 500:\n    total -= __1__\nprint(total)   # 500\n```', '50'),
    fb('數列前 n 項：3、6、9…第 8 項的值。\n\n```python\nvalue = 0\nfor i in range(8):\n    value += __1__\nprint(value)   # 24\n```', '3'),
    fb('印出字串每個字元與其重複次數版本（a → aa）。\n\n```python\nfor ch in "abc":\n    print(ch * __1__)\n```', '2'),
    fb('while 讀入直到累計 3 個及格分數。\n\n```python\npassed = 0\nwhile passed < 3:\n    s = int(input())\n    if s >= 60:\n        passed += __1__\nprint("收齊")\n```', '1'),
    fb('計算等比數列 5、10、20、40 的總和（4 項）。\n\n```python\ntotal = 0\nterm = 5\nfor i in range(4):\n    total += term\n    term *= __1__\nprint(total)   # 75\n```', '2'),
    fb('轉出整數的位數（不轉字串）。\n\n```python\nn = 90210\ndigits = 0\nwhile n > 0:\n    n //= 10\n    digits += 1\nprint(__1__)   # 5\n```', 'digits'),
    fb('列出 36 的所有因數。\n\n```python\nfor i in range(1, 37):\n    if 36 __1__ i == 0:\n        print(i)\n```', '%'),
    fb('溫度取樣中找出高於平均的筆數（平均已知 25）。\n\n```python\ntemps = [22, 28, 31, 19, 27]\ncount = 0\nfor t in temps:\n    if t > 25:\n        count += 1\nprint(__1__)   # 3\n```', 'count'),
]



# ── U3 Level 3：35 選擇 + 65 填空（競賽／TQC 實作：演算法模式）──
U3_L3 = [
    # 進階追蹤（35，含競賽原題 5 題）
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\na = 7; b = 3\nwhile a > b:\n    a -= b\nprint(a % 4)\n```', '1', '0', '2', '3',
       explanation='7→4→1，1%4=1。（113 商業類技藝競賽學科第 4 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\na, b = 8, 4\nc = 0\nwhile b > 0:\n    c += a % b\n    b -= 1\nprint(c % 4)\n```', '2', '0', '1', '3',
       explanation='8%4=0、8%3=2、8%2=0、8%1=0，c=2。（113 商業類技藝競賽學科第 5 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\ntotal = 0\nfor i in range(1, 6, 2):\n    total += i ** 2\nprint(total % 4)\n```', '3', '0', '1', '2',
       explanation='1+9+25=35，35%4=3。（113 商業類技藝競賽學科第 15 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\ntotal = 0\nfor i in range(1, 5):\n    total += i * (5 - i)\nprint(total % 4)\n```', '0', '1', '2', '3',
       explanation='4+6+6+4=20，20%4=0。（113 商業類技藝競賽學科第 22 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\na = 1\nfor i in range(1, 4):\n    a = a + a * i\nprint(a % 4)\n```', '0', '1', '2', '3',
       explanation='1→2→6→24，24%4=0。（113 商業類技藝競賽學科第 24 題）'),
    mc('以下程式的輸出是？（輾轉相除法）\n\n```python\na, b = 48, 36\nwhile b:\n    a, b = b, a % b\nprint(a)\n```', '12', '6', '4', '48',
       explanation='(48,36)→(36,12)→(12,0)，最大公因數 12。'),
    mc('以下程式的輸出是？\n\n```python\nn = 6\ncount = 0\nwhile n != 1:\n    if n % 2 == 0:\n        n //= 2\n    else:\n        n = 3 * n + 1\n    count += 1\nprint(count)\n```', '8', '6', '7', '9',
       explanation='6→3→10→5→16→8→4→2→1，共 8 步。'),
    mc('以下程式的輸出是？（數字反轉）\n\n```python\nn = 123\nrev = 0\nwhile n > 0:\n    rev = rev * 10 + n % 10\n    n //= 10\nprint(rev)\n```', '321', '123', '6', '312'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\ni = 1\nwhile i * i <= 30:\n    count += 1\n    i += 1\nprint(count)\n```', '5', '6', '30', '4',
       explanation='1²~5² ≤ 30，6²=36 超過。'),
    mc('2 的幾次方會「第一次」達到 1000 以上？\n\n```python\nk = 0\nv = 1\nwhile v < 1000:\n    v *= 2\n    k += 1\nprint(k)\n```', '10', '9', '11', '1000',
       explanation='2^10 = 1024。'),
    mc('range(100, 0, -7) 會產生幾個數字？', '15', '14', '13', '100',
       explanation='100、93、…、2：(100-2)/7+1 = 15。'),
    mc('以下程式的輸出是？\n\n```python\nproduct = 1\nfor n in [2, -3, 4]:\n    if n > 0:\n        product *= n\nprint(product)\n```', '8', '-24', '6', '24',
       explanation='filter＋reduce：只乘正數 2×4。'),
    mc('以下程式的輸出是？\n\n```python\nscores = [72, 85, 91, 60]\ni = 0\nwhile scores[i] < 90:\n    i += 1\nprint(i)\n```', '2', '91', '3', '0',
       explanation='search 模式：找到第一個 >= 90 的位置。'),
    mc('以下程式依序輸入 10、20、30、-1，輸出是？\n\n```python\ntotal = 0\ncount = 0\nwhile True:\n    n = int(input())\n    if n == -1:\n        break\n    total += n\n    count += 1\nprint(total / count)\n```', '20.0', '15.0', '60', '19.75',
       explanation='sentinel 平均：60/3。'),
    mc('以下程式的輸出是？\n\n```python\nn = 48\ncount = 0\nwhile n % 2 == 0:\n    n //= 2\n    count += 1\nprint(count, n)\n```', '4 3', '3 6', '5 1', '4 6',
       explanation='48→24→12→6→3，除了 4 次後剩 3。'),
    mc('以下程式的輸出是？\n\n```python\ni = 1\ns = 0\nwhile s < 20:\n    s += i\n    i += 1\nprint(i)\n```', '7', '6', '21', '20',
       explanation='s 依序 1,3,6,10,15,21；停止時 i 已加到 7。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(1, 20):\n    if i % 3 == 0:\n        continue\n    total += i\nprint(total)\n```', '127', '190', '63', '187',
       explanation='1..19 總和 190 減去 3 的倍數和 63。'),
    mc('以下程式的輸出是？（各位數乘積）\n\n```python\nn = 234\np = 1\nwhile n > 0:\n    p *= n % 10\n    n //= 10\nprint(p)\n```', '24', '9', '234', '0'),
    mc('1 到 60 中，同時是 3 和 4 的倍數的數有幾個？\n\n```python\ncount = 0\nfor i in range(1, 61):\n    if i % 3 == 0 and i % 4 == 0:\n        count += 1\nprint(count)\n```', '5', '4', '20', '12',
       explanation='12 的倍數：12、24、36、48、60。'),
    mc('以下程式的輸出是？\n\n```python\nn = 1\nwhile n < 100:\n    n *= 3\nprint(n)\n```', '243', '81', '99', '100',
       explanation='1→3→9→27→81→243，81 仍小於 100 再乘一次。'),
    mc('以下程式的輸出是？（TQC 撲克牌總和情境）\n\n```python\ncards = ["5", "10", "K", "3", "A"]\ntotal = 0\nfor c in cards:\n    if c == "A":\n        total += 1\n    elif c == "J":\n        total += 11\n    elif c == "Q":\n        total += 12\n    elif c == "K":\n        total += 13\n    else:\n        total += int(c)\nprint(total)\n```', '32', '31', '19', '34',
       explanation='5+10+13+3+1=32。'),
    mc('28 的因數有幾個？\n\n```python\ncount = 0\nfor i in range(1, 29):\n    if 28 % i == 0:\n        count += 1\nprint(count)\n```', '6', '5', '4', '28',
       explanation='1、2、4、7、14、28。'),
    mc('以下程式判斷 28 是否為完全數（因數和等於自身，不含本身），輸出是？\n\n```python\nn = 28\ns = 0\nfor i in range(1, n):\n    if n % i == 0:\n        s += i\nprint(s == n)\n```', 'True', 'False', '28', '發生錯誤',
       explanation='1+2+4+7+14=28。'),
    mc('1 到 10 中奇數的平均是？\n\n```python\ntotal = 0\ncount = 0\nfor i in range(1, 11, 2):\n    total += i\n    count += 1\nprint(total / count)\n```', '5.0', '5', '25', '5.5'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(0, 10, 4):\n    total += i\nprint(total)\n```', '12', '4', '8', '20',
       explanation='0+4+8=12。'),
    mc('以下程式的輸出是？\n\n```python\nup = 0\ndown = 0\nprev = 5\nfor n in [8, 6, 9]:\n    if n > prev:\n        up += 1\n    else:\n        down += 1\n    prev = n\nprint(up, down)\n```', '2 1', '1 2', '3 0', '2 2',
       explanation='5→8 升、8→6 降、6→9 升。'),
    mc('以下程式共輸出幾行？\n\n```python\ni = 0\nwhile i < 10:\n    i += 3\n    print(i)\n```', '4 行', '3 行', '10 行', '無限',
       explanation='印 3、6、9、12。'),
    mc('以下程式的輸出是？\n\n```python\nx = 5\ny = 0\nwhile x > 0:\n    y += x % 2\n    x //= 2\nprint(y)\n```', '2', '5', '3', '1',
       explanation='5 的二進位 101 有 2 個 1（5%2=1、2%2=0、1%2=1）。'),
    mc('哪一段程式能找出串列中「最後一個」大於 50 的元素？',
       '走訪全部，每次符合就覆寫變數', '找到第一個就 break',
       '用 continue 跳過大於 50 的', '只檢查最後一個元素'),
    mc('while 迴圈執行次數與 for i in range(n) 相同的寫法是？',
       'i = 0 起始，條件 i < n，每圈 i += 1', 'i = 1 起始，條件 i <= n+1，每圈 i += 1',
       'i = 0 起始，條件 i <= n，每圈 i += 1', 'i = n 起始，條件 i > 0，每圈 i += 1'),
    mc('以下程式的輸出是？\n\n```python\ntext = "10 20 30"\ntotal = 0\nfor part in text.split():\n    total += int(part)\nprint(total)\n```', '60', '102030', '3', '發生錯誤',
       explanation='split 切出三個字串再轉整數累加（TQC 資料加總情境）。'),
    mc('計算 1×2 + 2×3 + 3×4 的程式，空格應是？\n\n```python\ntotal = 0\nfor i in range(1, 4):\n    total += i * (i + 1)\nprint(total)\n```\n\n輸出是？', '20', '14', '24', '11',
       explanation='2+6+12=20。'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nn = 1000\nwhile n >= 10:\n    n //= 10\n    count += 1\nprint(count)\n```', '3', '2', '4', '100',
       explanation='1000→100→10→1，共 3 次。'),
    mc('九九乘法表「只印對角線」（i×i），輸出的第三個數是？\n\n```python\nfor i in range(1, 10):\n    print(i * i)\n```', '9', '3', '6', '16'),
    mc('以下程式的輸出是？\n\n```python\nsteps = 0\npos = 0\nwhile pos < 30:\n    pos += 7\n    pos -= 2\n    steps += 1\nprint(steps)\n```', '6', '5', '7', '30',
       explanation='每圈淨走 5：5,10,15,20,25,30 → 6 圈。'),

    # ── L3 填空（65）──
    fb('輾轉相除法求最大公因數。\n\n```python\na, b = 60, 84\nwhile b:\n    a, b = b, a __1__ b\nprint(a)   # 12\n```', '%'),
    fb('用 GCD 求最小公倍數：LCM = a×b ÷ GCD。\n\n```python\na, b = 12, 18\nx, y = a, b\nwhile y:\n    x, y = y, x % y\nprint(a * b __1__ x)   # 36\n```', '//'),
    fb('數字反轉（123 → 321）。\n\n```python\nn = 456\nrev = 0\nwhile n > 0:\n    rev = rev * __1__ + n % 10\n    n //= 10\nprint(rev)   # 654\n```', '10'),
    fb('回文數判斷：反轉後與原數比較。\n\n```python\nn = 1221\noriginal = n\nrev = 0\nwhile n > 0:\n    rev = rev * 10 + n % 10\n    n //= 10\nprint(rev __1__ original)   # True\n```', '=='),
    fb('位數和：一直加到剩個位數（數字根）。\n\n```python\nn = 987\nwhile n >= 10:\n    s = 0\n    while n > 0:\n        s += n % 10\n        n //= 10\n    n = __1__\nprint(n)   # 6\n```', 's',
       explanation='9+8+7=24 → 2+4=6。'),
    fb('ATM 提款模擬：每次領 3000，餘額不足就停。\n\n```python\nbalance = 10000\ntimes = 0\nwhile balance >= 3000:\n    balance -= __1__\n    times += 1\nprint(times, balance)   # 3 1000\n```', '3000'),
    fb('細菌每小時翻倍，從 5 隻長到超過 1000 隻需幾小時。\n\n```python\nbacteria = 5\nhours = 0\nwhile bacteria <= 1000:\n    bacteria __1__ 2\n    hours += 1\nprint(hours)   # 8\n```', '*=',
       explanation='5×2^8 = 1280 > 1000。'),
    fb('存錢達標：每月存 4500，存到 50000 需幾個月。\n\n```python\nsaved = 0\nmonths = 0\nwhile saved __1__ 50000:\n    saved += 4500\n    months += 1\nprint(months)   # 12\n```', '<'),
    fb('階梯電價逐度累計：前 120 度每度 1.63、之後每度 2.38，共 150 度。\n\n```python\nbill = 0\nfor degree in range(1, 151):\n    if degree <= 120:\n        bill += 1.63\n    else:\n        bill += __1__\nprint(round(bill))   # 267\n```', '2.38'),
    fb('連勝計數：遇到輸就歸零，統計最長連勝。\n\n```python\nresults = ["W", "W", "L", "W", "W", "W"]\nstreak = 0\nbest = 0\nfor r in results:\n    if r == "W":\n        streak += 1\n        if streak > best:\n            best = streak\n    else:\n        streak = __1__\nprint(best)   # 3\n```', '0'),
    fb('手機電量：每小時剩下 88%，從 100% 掉到低於 50% 需幾小時。\n\n```python\nbattery = 100.0\nhours = 0\nwhile battery >= 50:\n    battery *= __1__\n    hours += 1\nprint(hours)   # 6\n```', '0.88',
       explanation='0.88^5 ≈ 52.8%、0.88^6 ≈ 46.4%。'),
    fb('找出 1000 以內最大的完全平方數。\n\n```python\ni = 1\nwhile (i + 1) ** 2 <= 1000:\n    i += 1\nprint(i __1__ 2)   # 961\n```', '**'),
    fb('過濾模式：只加總正偶數。\n\n```python\ntotal = 0\nfor n in [4, -2, 7, 8, -6, 10]:\n    if n > 0 and n % 2 == __1__:\n        total += n\nprint(total)   # 22\n```', '0'),
    fb('搜尋模式：找到第一個能被 7 整除的數立刻停止。\n\n```python\nfor n in [15, 22, 28, 35]:\n    if n % 7 == 0:\n        print(n)   # 28\n        __1__\n```', 'break'),
    fb('sentinel 模式：讀到 "end" 才停止並輸出筆數。\n\n```python\ncount = 0\nwhile True:\n    s = input()\n    if s == __1__:\n        break\n    count += 1\nprint(count)\n```', ['"end"', "'end'"]),
    fb('票根兌換：5 張票根換 1 支冰棒，吃完的冰棒棍也算票根。共 12 張票根可吃幾支？\n\n```python\nsticks = 12\neaten = 0\nwhile sticks >= 5:\n    sticks -= 5\n    eaten += 1\n    sticks += __1__\nprint(eaten)   # 2\n```', '1',
       explanation='12→換1支剩8→換1支剩4，共 2 支。'),
    fb('雙倍工資問題：第 1 天 1 元、每天翻倍，30 天總共領多少？\n\n```python\ntotal = 0\npay = 1\nfor day in range(30):\n    total += pay\n    pay *= __1__\nprint(total)   # 1073741823\n```', '2'),
    fb('慢跑計畫：第一天 2 公里，之後每天多 0.5 公里，累計到 30 公里需幾天。\n\n```python\nkm = 2.0\ntotal = 0.0\ndays = 0\nwhile total < 30:\n    total += km\n    km += __1__\n    days += 1\nprint(days)   # 8\n```', '0.5',
       explanation='2+2.5+…+5.5 = 30，第 8 天累計達 30。'),
    fb('分頁計算：每頁 25 筆，178 筆資料需要幾頁（無條件進位）。\n\n```python\nrecords = 178\npages = 0\nwhile records > 0:\n    records -= __1__\n    pages += 1\nprint(pages)   # 8\n```', '25'),
    fb('外幣換匯累計：每天用 1000 台幣換日元（匯率 0.22），5 天共換多少日元。\n\n```python\nyen = 0\nfor day in range(5):\n    yen += 1000 / __1__\nprint(round(yen))   # 22727\n```', '0.22'),
    fb('操場計圈：每圈 400 公尺，跑 10 圈以上才算達標，累計 4200 公尺跑了幾圈？\n\n```python\ndistance = 4200\nlaps = distance __1__ 400\nprint(laps, "達標" if laps >= 10 else "未達標")   # 10 達標\n```', '//'),
    fb('心跳偵測：連續兩筆都超過 100 就警示（找出現位置）。\n\n```python\nrates = [88, 102, 105, 95]\nfor i in range(1, 4):\n    if rates[i] > 100 __1__ rates[i - 1] > 100:\n        print(i)   # 2\n```', 'and'),
    fb('質數判斷：2 到 n-1 都除不盡才是質數。\n\n```python\nn = 17\nis_prime = True\nfor i in range(2, n):\n    if n % i __1__ 0:\n        is_prime = False\n        break\nprint(is_prime)   # True\n```', '=='),
    fb('計算調和數列 1/1 + 1/2 + 1/3 + 1/4（取 2 位小數）。\n\n```python\ntotal = 0\nfor i in range(1, 5):\n    total += 1 __1__ i\nprint(round(total, 2))   # 2.08\n```', '/'),
    fb('湊零錢：用最少的 50 元硬幣湊 380 元，剩下的用 10 元。\n\n```python\namount = 380\nc50 = amount // 50\nc10 = (amount % 50) // __1__\nprint(c50, c10)   # 7 3\n```', '10'),
    fb('遊戲經驗值：打一隻怪 +35 經驗，升級需 500，需打幾隻。\n\n```python\nexp = 0\nkills = 0\nwhile exp < 500:\n    exp += __1__\n    kills += 1\nprint(kills)   # 15\n```', '35'),
    fb('溫度資料找「最大溫差」（相鄰兩筆差的最大絕對值）。\n\n```python\ntemps = [22, 28, 19, 25]\nbig = 0\nfor i in range(1, 4):\n    diff = abs(temps[i] - temps[i - 1])\n    if diff > big:\n        big = __1__\nprint(big)   # 9\n```', 'diff'),
    fb('公車站牌：每 15 分鐘一班，錯過 8:03 的班次後下一班幾點幾分（8:00 起算）。\n\n```python\nminute = 3\nwhile minute % 15 != 0:\n    minute += __1__\nprint(f"8:{minute:02d}")   # 8:15\n```', '1'),
    fb('影印計費：前 10 張每張 3 元、11 張起每張 2 元，共印 25 張。\n\n```python\ncost = 0\nfor page in range(1, 26):\n    if page <= 10:\n        cost += 3\n    else:\n        cost += __1__\nprint(cost)   # 60\n```', '2'),
    fb('模擬水塔放水：每分鐘放 8%，從 1000 公升降到 500 以下需幾分鐘。\n\n```python\nwater = 1000\nminutes = 0\nwhile water >= 500:\n    water *= __1__\n    minutes += 1\nprint(minutes)   # 9\n```', '0.92',
       explanation='0.92^9 ≈ 0.472 < 0.5。'),
    fb('累計紅利點數：消費金額每滿 30 元 1 點，三筆消費 88、120、45。\n\n```python\npoints = 0\nfor amount in [88, 120, 45]:\n    points += amount __1__ 30\nprint(points)   # 7\n```', '//',
       explanation='2+4+1=7。'),
    fb('倒著印字串（用負向 range）。\n\n```python\ntext = "abcde"\nfor i in range(len(text) - 1, -1, __1__):\n    print(text[i], end="")\nprint()   # edcba\n```', '-1'),
    fb('骰子和為 8 的組合數（兩顆 1~6）。\n\n```python\ncount = 0\nfor a in range(1, 7):\n    for b in range(1, 7):\n        if a + b == __1__:\n            count += 1\nprint(count)   # 5\n```', '8'),
    fb('模擬走樓梯：每步上 3 階再滑下 1 階，爬到第 20 階需幾步。\n\n```python\nheight = 0\nsteps = 0\nwhile height < 20:\n    height += 3\n    if height >= 20:\n        break\n    height -= __1__\n    steps += 1\nprint(steps + 1)   # 10\n```', '1',
       explanation='每步淨升 2，第 10 步時 18+3=21 ≥ 20。'),
    fb('把整數的每一位平方後相加。\n\n```python\nn = 234\ntotal = 0\nwhile n > 0:\n    d = n % 10\n    total += d __1__ 2\n    n //= 10\nprint(total)   # 29\n```', '**',
       explanation='4+9+16=29。'),
    fb('連續整數乘積：找最小的 n 使 1×2×…×n 超過 1000。\n\n```python\nproduct = 1\nn = 0\nwhile product <= 1000:\n    n += 1\n    product __1__ n\nprint(n)   # 7\n```', '*=',
       explanation='6!=720、7!=5040。'),
    fb('電梯載重：依序上人，會超過 300 公斤就不再讓人上。\n\n```python\nweights = [65, 80, 72, 90, 55]\nload = 0\ncount = 0\nfor w in weights:\n    if load + w > 300:\n        __1__\n    load += w\n    count += 1\nprint(count, load)   # 3 217\n```', 'break',
       explanation='65+80+72=217，再加 90 會到 307 超過，停止。'),
    fb('倒數質數：從 20 往下找到第一個質數。\n\n```python\nn = 20\nwhile True:\n    is_p = n > 1\n    for i in range(2, n):\n        if n % i == 0:\n            is_p = False\n            break\n    if is_p:\n        break\n    n __1__ 1\nprint(n)   # 19\n```', '-='),
    fb('每圈折半猜數字：1~100 最多猜幾次（二分搜尋次數）。\n\n```python\nlow, high = 1, 100\ncount = 0\nwhile low < high:\n    mid = (low + high) // 2\n    high = mid\n    count += __1__\nprint(count)   # 7\n```', '1',
       explanation='100→50→25→13→7→4→2→1，7 次。'),
    fb('攤位營收目標：每天賣 2400，累計超過 15000 的那天是第幾天。\n\n```python\nrevenue = 0\nday = 0\nwhile revenue <= 15000:\n    day += 1\n    revenue += __1__\nprint(day)   # 7\n```', '2400'),
    fb('列出兩位數中十位與個位相同的數（11、22、…）共幾個。\n\n```python\ncount = 0\nfor n in range(10, 100):\n    if n // 10 == n __1__ 10:\n        count += 1\nprint(count)   # 9\n```', '%'),
    fb('模擬打點滴：每分鐘滴 2.5 毫升，500 毫升點滴需要幾分鐘滴完。\n\n```python\nvolume = 500\nminutes = 0\nwhile volume > 0:\n    volume -= __1__\n    minutes += 1\nprint(minutes)   # 200\n```', '2.5'),
    fb('累加到「剛好」超過目標時輸出差多少。\n\n```python\ntotal = 0\nn = 0\nwhile total <= 50:\n    n += 3\n    total += n\nprint(total __1__ 50)   # 13\n```', '-',
       explanation='3+9+18+30+45+63：total 到 63 時停止，63-50=13。'),
    fb('平方數數列 1、4、9、16…找出第一個超過 200 的平方數。\n\n```python\ni = 1\nwhile i * i __1__ 200:\n    i += 1\nprint(i * i)   # 225\n```', '<=',
       explanation='14²=196 仍 ≤ 200，15²=225 輸出。'),
    fb('紅綠燈週期：紅 30 秒、綠 25 秒、黃 5 秒，第 100 秒時是什麼燈（週期 60 秒）。\n\n```python\nt = 100 % 60\nif t < 30:\n    print("紅")\nelif t < __1__:\n    print("綠")   # 綠\nelse:\n    print("黃")\n```', '55',
       explanation='t=40，30≤40<55 是綠燈。'),
    fb('三角形數：1、3、6、10…第 10 個三角形數。\n\n```python\ntotal = 0\nfor i in range(1, __1__):\n    total += i\nprint(total)   # 55\n```', '11'),
    fb('模擬佇列消化：每分鐘服務 3 人又新來 1 人，隊伍 20 人清空需幾分鐘。\n\n```python\nqueue = 20\nminutes = 0\nwhile queue > 0:\n    queue -= 3\n    if queue > 0:\n        queue += __1__\n    minutes += 1\nprint(minutes)   # 10\n```', '1',
       explanation='每分鐘淨減 2；第 10 分鐘 2-3=-1 清空，共 10 分鐘。'),
    fb('找出三位數中「各位數字和為 20」的最小數。\n\n```python\nn = 100\nwhile (n // 100 + n // 10 % 10 + n % 10) != 20:\n    n += __1__\nprint(n)   # 299\n```', '1'),
    fb('印出鏡像三角形（右對齊星星）。\n\n```python\nfor i in range(1, 4):\n    print(" " * (3 - i) + "*" __1__ i)\n```', '*'),
    fb('黑白棋翻轉計數：連續翻轉直到顏色代碼回到 0（每次 +7 mod 10）。\n\n```python\ncolor = 7\nflips = 1\nwhile color != 0:\n    color = (color + 7) % __1__\n    flips += 1\nprint(flips)   # 10\n```', '10'),
    fb('模擬鬧鐘貪睡：每按一次延後 9 分鐘，7:30 按 4 次後是幾點。\n\n```python\nminute = 30\nfor i in range(4):\n    minute += __1__\nhour = 7 + minute // 60\nprint(f"{hour}:{minute % 60:02d}")   # 8:06\n```', '9'),
    fb('油箱警示：每公里耗油 0.08 公升，油量 5 公升，能跑幾「整」公里。\n\n```python\nfuel = 5.0\nkm = 0\nwhile fuel >= 0.08:\n    fuel -= __1__\n    km += 1\nprint(km)   # 62\n```', '0.08'),
    fb('比賽晉級：分數高於前一名才晉級，統計晉級次數。\n\n```python\nscores = [70, 75, 73, 80]\ncount = 0\nfor i in range(1, 4):\n    if scores[i] __1__ scores[i - 1]:\n        count += 1\nprint(count)   # 2\n```', '>'),
    fb('把 1~20 分成 5 人一組報數，輸出每人的組號。\n\n```python\nfor n in range(1, 21):\n    group = (n - 1) __1__ 5 + 1\n    print(n, "在第", group, "組")\n```', '//'),
    fb('模擬碼表：每圈 0.5 秒，跑 25 圈共花幾秒。\n\n```python\ntotal = 0.0\nfor lap in range(25):\n    total += __1__\nprint(total)   # 12.5\n```', '0.5'),
    fb('找到輸入中第一個重複出現的數（與前一筆相同）。\n\n```python\nnums = [3, 7, 7, 5]\nfor i in range(1, 4):\n    if nums[i] == nums[i __1__ 1]:\n        print(nums[i])   # 7\n        break\n```', '-'),
    fb('倍數報數遊戲：1~30 遇到 7 的倍數喊過，統計喊過次數。\n\n```python\ncount = 0\nfor n in range(1, 31):\n    if n % 7 == 0:\n        count += 1\nprint(__1__)   # 4\n```', 'count'),
    fb('薪水試算：底薪 28000，每滿一年年資加 800，年資 6 年的月薪。\n\n```python\nsalary = 28000\nfor year in range(6):\n    salary += __1__\nprint(salary)   # 32800\n```', '800'),
    fb('累計降雨：一週雨量取最大的三天總和（已排序資料）。\n\n```python\nrain = [50, 42, 38, 20, 15, 8, 0]\ntotal = 0\nfor i in range(__1__):\n    total += rain[i]\nprint(total)   # 130\n```', '3'),
    fb('模擬骰子期望：擲 6 次點數剛好 1~6 各一次，平均點數。\n\n```python\ntotal = 0\nfor d in range(1, 7):\n    total += d\nprint(total __1__ 6)   # 3.5\n```', '/'),
    fb('青蛙跳井：井深 10 公尺，每次跳 3 公尺滑 2 公尺，第幾次跳出？\n\n```python\nheight = 0\njumps = 0\nwhile True:\n    jumps += 1\n    height += 3\n    if height >= 10:\n        break\n    height -= __1__\nprint(jumps)   # 8\n```', '2'),
    fb('累進計費快遞：首公斤 80，續重每公斤 40，寄 4 公斤。\n\n```python\nweight = 4\ncost = 80\nfor i in range(weight - 1):\n    cost += __1__\nprint(cost)   # 200\n```', '40'),
    fb('模擬iPad定時鎖：連續錯 5 次鎖定 1 分鐘、10 次鎖定 5 分鐘。錯 7 次時鎖定幾分鐘？\n\n```python\nfails = 7\nif fails >= 10:\n    print(5)\nelif fails >= __1__:\n    print(1)   # 1\nelse:\n    print(0)\n```', '5'),
    fb('雙人輪流報數到 30，每人最多報 3 個數，先報到 30 的輸。安全數是 30-1=29、25、21…，第一個安全數？\n\n```python\nsafe = 29\nwhile safe - 4 >= 1:\n    safe -= __1__\nprint(safe)   # 1\n```', '4'),
    fb('停車場即時計數：進場 +1、出場 -1。\n\n```python\ncars = 0\nfor e in ["in", "in", "out", "in"]:\n    if e == __1__:\n        cars += 1\n    else:\n        cars -= 1\nprint(cars)   # 2\n```', ['"in"', "'in'"]),
]
