"""Unit 4（迴圈實作與基礎題庫）題庫 — 全選擇制。

L1 對標 ITS（圖形列印、巢狀概念、樣板複習）、
L2 對標 TQC+ 觀念題（巢狀追蹤、質數/階乘/費氏、sentinel 統計；收錄競賽第 13 題）、
L3 對標競賽／TQC 實作（二維資料、進位轉換、狀態追蹤；收錄競賽第 3、18、20 題）。
"""
from .question_helpers import mc, fb

# ── U4 Level 1：55 選擇 + 45 填空 ──
U4_L1 = [
    # 巢狀迴圈與解題觀念（15）
    mc('外層執行 3 次、內層每次執行 4 次，內層區塊總共執行幾次？', '12 次', '7 次', '3 次', '4 次'),
    mc('印出「列×欄」形式的表格（如乘法表）需要幾層迴圈？', '2 層', '1 層', '3 層', '0 層'),
    mc('巢狀迴圈中，內層的 break 會跳出哪裡？', '只跳出內層迴圈', '跳出所有迴圈',
       '跳出外層迴圈', '結束程式'),
    mc('印完一列後要換行，常在外層迴圈結尾寫？', 'print()', 'break', 'continue', 'end()'),
    mc('print("*", end="") 的效果是？', '印出星號後不換行', '印出星號後換行',
       '印出 end 三個字', '發生錯誤'),
    mc('巢狀迴圈中，每次外層進入新一圈時，內層的迴圈變數會？', '重新從頭開始跑一輪',
       '接續上次的值', '歸零後停止', '發生錯誤'),
    mc('要印出第 i 列有 i 顆星的三角形，每列應該印？', '"*" * i', '"*" + i', '"i" * i', '"*" * 5'),
    mc('解題四步驟中，第一步應該做什麼？', '寫出一組輸入與預期輸出', '直接開始寫程式',
       '先寫 print', '選擇變數名稱'),
    mc('演算法寫完後用「簡單資料＋邊界資料」測試的目的是？', '確認各種情況都能得到正確結果',
       '讓程式跑得更快', '減少程式行數', '美化輸出格式'),
    mc('把題目拆解成「初始化、重複處理、更新、輸出」是為了？', '把大問題變成可以逐步完成的小步驟',
       '增加程式長度', '避免使用迴圈', '讓程式自動除錯'),
    mc('以下程式內層的 print 總共執行幾次？\n\n```python\nfor row in range(2):\n    for col in range(5):\n        print("x", end="")\n```', '10 次', '7 次', '2 次', '5 次'),
    mc('印出 5×5 的星號正方形，總共會印出幾顆星？', '25 顆', '10 顆', '5 顆', '20 顆'),
    mc('哪一種圖形「不需要」巢狀迴圈就能印出？', '每列星數固定遞增的三角形（用字串乘法）',
       '有列有欄的乘法表', '西洋棋盤格', '二維座標表'),
    mc('猜數字遊戲中「提示太大或太小」應該用什麼結構？', 'if/elif 判斷放在迴圈內',
       '兩個獨立迴圈', '巢狀迴圈', '不需要判斷'),
    mc('while 迴圈實作猜數字，猜對時應該？', '用 break 結束迴圈', '用 continue',
       '把答案改掉', '重新開始'),

    # 圖形與樣板追蹤（40）
    mc('以下程式的輸出是？\n\n```python\nfor i in range(1, 4):\n    print("*" * i)\n```', '*、**、***（三列遞增）', '***、**、*（三列遞減）', '***', '* * *'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(3, 0, -1):\n    print("*" * i)\n```', '***、**、*（三列遞減）', '*、**、***', '***', '沒有任何輸出'),
    mc('以下程式輸出的「第三行」是？\n\n```python\nfor i in range(2):\n    for j in range(2):\n        print(i, j)\n```', '1 0', '0 1', '1 1', '0 0',
       explanation='輸出依序 0 0、0 1、1 0、1 1。'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(1, 3):\n    for j in range(1, 3):\n        print(i * j, end=" ")\n```', '1 2 2 4', '1 2 3 4', '2 4 6 8', '1 1 2 2'),
    mc('以下程式的輸出是？\n\n```python\nprint("#" * 4)\n```', '####', '# # # #', '#4', '4#'),
    mc('以下程式的輸出是？\n\n```python\nresult = 1\nfor i in range(1, 6):\n    result *= i\nprint(result)\n```', '120', '15', '25', '720',
       explanation='5! = 120。'),
    mc('以下程式的輸出是？\n\n```python\nresult = 1\nfor i in range(1, 5):\n    result *= i\nprint(result)\n```', '24', '120', '10', '12',
       explanation='4! = 24。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [3, 8, 2, 10, 5]\nbig = nums[0]\nfor n in nums:\n    if n > big:\n        big = n\nprint(big)\n```', '10', '8', '3', '5'),
    mc('以下程式的輸出是？\n\n```python\nnums = [5, 1, 9, 3]\nsmall = nums[0]\nfor n in nums:\n    if n < small:\n        small = n\nprint(small)\n```', '1', '5', '9', '3'),
    mc('猜數字：答案是 37，猜 50 時程式應提示？\n\n```python\nanswer = 37\nguess = 50\nif guess > answer:\n    print("太大")\nelif guess < answer:\n    print("太小")\nelse:\n    print("答對")\n```', '太大', '太小', '答對', '沒有任何輸出'),
    mc('以下程式共輸出幾行？\n\n```python\nfor ch in "ab":\n    for d in "12":\n        print(ch + d)\n```', '4 行', '2 行', '8 行', '1 行',
       explanation='a1、a2、b1、b2。'),
    mc('承上題，輸出的第二行是？\n\n```python\nfor ch in "ab":\n    for d in "12":\n        print(ch + d)\n```', 'a2', 'a1', 'b1', 'b2'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(3):\n    print(i, end="-")\n```', '0-1-2-', '0-1-2', '1-2-3-', '012'),
    mc('以下程式共印出幾行「AB」？\n\n```python\nfor row in range(2):\n    print("AB")\n```', '2 行', '1 行', '4 行', '0 行'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nfor i in range(2):\n    for j in range(5):\n        count += 1\nprint(count)\n```', '10', '7', '2', '25'),
    mc('print("*" * 0) 會輸出什麼？', '一個空行', '一顆星', '0', '發生錯誤',
       explanation='字串乘 0 是空字串，print 仍然換行。'),
    mc('第 i 列要印 6-i 顆星，i = 2 時印出？', '****', '**', '******', '*****'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(1, 3):\n    for j in range(1, 3):\n        total += i + j\nprint(total)\n```', '12', '6', '8', '10',
       explanation='(1+1)+(1+2)+(2+1)+(2+2)=12。'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(1, 4):\n    if i == 2:\n        continue\n    print(i)\n```', '1 與 3（兩行）', '1、2、3', '2', '1'),
    mc('九九乘法表的其中一格「3×7=21」，用 f-string 怎麼寫？',
       'f"{3}×{7}={3 * 7}"', '"3×7=3*7"', 'f"3×7=21" 只能寫死', 'print(3, 7, 21)'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(2, 11, 2):\n    print(i, end=" ")\n```', '2 4 6 8 10', '2 4 6 8', '0 2 4 6 8 10', '1 3 5 7 9'),
    mc('費波那契數列 0、1、1、2、3、5…下一個數是？', '8', '6', '7', '10',
       explanation='每一項是前兩項之和：3+5=8。'),
    mc('以下程式的輸出是？\n\n```python\na, b = 0, 1\nfor i in range(4):\n    a, b = b, a + b\nprint(a)\n```', '3', '2', '5', '1',
       explanation='a 依序 1、1、2、3。'),
    mc('印出西洋棋盤第一列「黑白黑白…」共 8 格，適合的寫法是？',
       '迴圈中用 if 判斷奇偶位置決定字元', '印 8 次黑色', '不用迴圈直接寫死也可以但不易改',
       '用 break 中斷',
       explanation='位置 % 2 判斷交替圖樣。'),
    mc('以下程式的輸出是？\n\n```python\nline = ""\nfor i in range(3):\n    line += "ab"\nprint(line)\n```', 'ababab', 'ab3', 'aaabbb', 'ab ab ab'),
    mc('印出如下圖形需要的迴圈設計是？\n\n```text\n*\n**\n***\n```', '外層跑 3 列，每列印 i 顆星',
       '一個 print 印完', '三層巢狀迴圈', 'while True'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in [1, 2]:\n    for j in [10, 20]:\n        total += i * j\nprint(total)\n```', '90', '60', '33', '120',
       explanation='10+20+20+40=90。'),
    mc('以下程式共輸出幾個數字？\n\n```python\nfor i in range(3):\n    for j in range(i):\n        print(j)\n```', '3 個', '6 個', '9 個', '0 個',
       explanation='i=0 印 0 個、i=1 印 1 個、i=2 印 2 個。'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(5, 0, -1):\n    if i == 3:\n        break\n    print(i)\n```', '5 與 4（兩行）', '5、4、3', '3', '5 4 3 2 1'),
    mc('計算 6! ÷ 4! 的值是？', '30', '2', '24', '720',
       explanation='720 ÷ 24 = 30（= 5×6）。'),
    mc('以下程式的輸出是？\n\n```python\nstars = 0\nfor i in range(1, 5):\n    stars += i\nprint(stars)\n```', '10', '4', '15', '5',
       explanation='三角形 1+2+3+4 = 10 顆星。'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(1, 4):\n    print(i * "A")\n```', 'A、AA、AAA（三列遞增）', 'AAA、AA、A', 'A A A', '3A'),
    mc('猜數字遊戲要「限制最多猜 5 次」，適合的寫法是？', 'for i in range(5) 搭配 break',
       'while True 不加 break', '5 個 if', '遞迴呼叫'),
    mc('以下程式的輸出是？\n\n```python\nn = 5\ntotal = 0\nwhile n > 0:\n    total += n\n    n -= 2\nprint(total)\n```', '9', '15', '6', '5',
       explanation='5+3+1=9。'),
    mc('把「印 3 列、每列 4 顆星」的程式改成「印 4 列、每列 3 顆星」，要改哪裡？',
       '外層與內層的次數對調', '只改 print', '加一層迴圈', '把 for 換成 while'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(1, 10):\n    if i * i > 50:\n        print(i)\n        break\n```', '8', '7', '49', '64',
       explanation='8²=64 是第一個超過 50 的平方。'),
    mc('印「每列印出列號重複列號次」（1、22、333），第 3 列是？', '333', '3', '33', '3333'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nfor i in range(1, 13):\n    if 12 % i == 0:\n        count += 1\nprint(count)\n```', '6', '5', '12', '4',
       explanation='12 的因數：1、2、3、4、6、12。'),
    mc('用迴圈印出 10、8、6、4、2，range 應寫？', 'range(10, 0, -2)', 'range(10, 2, -2)',
       'range(2, 11, 2)', 'range(10, 0, 2)'),
    mc('以下程式的輸出是？\n\n```python\ns = 0\nfor i in range(1, 5):\n    s = s * 10 + i\nprint(s)\n```', '1234', '10', '4321', '1111',
       explanation='數字累進：1→12→123→1234。'),

    # ── L1 填空（45）──
    fb('印出遞增星號三角形（1 到 5 顆）。\n\n```python\nfor i in range(1, 6):\n    print("*" __1__ i)\n```', '*'),
    fb('印出遞減星號三角形（5 到 1 顆）。\n\n```python\nfor i in range(5, 0, __1__):\n    print("*" * i)\n```', '-1'),
    fb('印出 3×4 的星號矩形（3 列、每列 4 顆）。\n\n```python\nfor row in range(__1__):\n    print("*" * 4)\n```', '3'),
    fb('巢狀迴圈：印出九九乘法表的一部分（1~3 的乘法）。\n\n```python\nfor i in range(1, 4):\n    for j in range(1, __1__):\n        print(i * j, end=" ")\n    print()\n```', '4'),
    fb('內層印完一列後換行。\n\n```python\nfor i in range(3):\n    for j in range(3):\n        print("*", end="")\n    __1__()\n```', 'print'),
    fb('讓星號印在同一列不換行。\n\n```python\nfor i in range(5):\n    print("*", end=__1__)\n```', ['""', "''"]),
    fb('計算 6 的階乘。\n\n```python\nresult = 1\nfor i in range(1, 7):\n    result __1__ i\nprint(result)   # 720\n```', '*='),
    fb('找最大值樣板。\n\n```python\nnums = [7, 12, 3, 9]\nbig = nums[0]\nfor n in nums:\n    if n __1__ big:\n        big = n\nprint(big)   # 12\n```', '>'),
    fb('印出 2、4、6、8、10。\n\n```python\nfor i in range(2, 11, __1__):\n    print(i)\n```', '2'),
    fb('每列印出「列號」重複列號次（1、22、333）。\n\n```python\nfor i in range(1, 4):\n    print(str(i) * __1__)\n```', 'i'),
    fb('印出 4 列、每列印出列號。\n\n```python\nfor row in range(1, 5):\n    print(__1__)\n```', 'row'),
    fb('巢狀計數：外層 3 圈、內層 4 圈，總執行次數。\n\n```python\ncount = 0\nfor i in range(3):\n    for j in range(4):\n        count += 1\nprint(__1__)   # 12\n```', 'count'),
    fb('猜數字提示：太大。\n\n```python\nanswer = 42\nguess = 60\nif guess __1__ answer:\n    print("太大")\nelif guess < answer:\n    print("太小")\n```', '>'),
    fb('印出座標組合 (0,0) 到 (1,1)。\n\n```python\nfor x in range(2):\n    for y in range(__1__):\n        print(x, y)\n```', '2'),
    fb('累加三角形星數：1+2+3+4+5。\n\n```python\ntotal = 0\nfor i in range(1, 6):\n    total += __1__\nprint(total)   # 15\n```', 'i'),
    fb('印出右對齊三角形（先空格後星號）。\n\n```python\nfor i in range(1, 4):\n    print(" " * (3 - i) + "*" * __1__)\n```', 'i'),
    fb('費波那契前 6 項（0 1 1 2 3 5）。\n\n```python\na, b = 0, 1\nfor i in range(6):\n    print(a, end=" ")\n    a, b = b, a __1__ b\n```', '+'),
    fb('計算 1 到 5 各數的平方和。\n\n```python\ntotal = 0\nfor i in range(1, 6):\n    total += i ** __1__\nprint(total)   # 55\n```', '2'),
    fb('把 5 列的「口」字元印成一直排。\n\n```python\nfor i in range(__1__):\n    print("口")\n```', '5'),
    fb('外層控制列數、內層印出等於列號的星數。\n\n```python\nfor i in range(1, 4):\n    line = ""\n    for j in range(__1__):\n        line += "*"\n    print(line)\n```', 'i'),
    fb('印出 1 到 20 的 5 的倍數。\n\n```python\nfor i in range(5, 21, __1__):\n    print(i)\n```', '5'),
    fb('數字金字塔：每列印出列號 x 列號的值。\n\n```python\nfor i in range(1, 5):\n    print(i __1__ i)\n```', '*'),
    fb('印出倒數 3、2、1 後印出「開始」。\n\n```python\nfor i in range(3, 0, -1):\n    print(i)\nprint(__1__)\n```', ['"開始"', "'開始'"]),
    fb('用 while 印出 1 到 4 的階乘值（4 行）。\n\n```python\nn = 1\nresult = 1\nwhile n <= 4:\n    result *= n\n    print(result)\n    n __1__ 1\n```', '+='),
    fb('找最小值樣板。\n\n```python\nnums = [6, 2, 8, 4]\nsmall = nums[0]\nfor n in nums:\n    if n __1__ small:\n        small = n\nprint(small)   # 2\n```', '<'),
    fb('印出 3 列「Hello」與列號。\n\n```python\nfor i in range(1, 4):\n    print("Hello", __1__)\n```', 'i'),
    fb('每圈把 i 加進字串尾端，印出 123。\n\n```python\ntext = ""\nfor i in range(1, 4):\n    text += __1__(i)\nprint(text)   # 123\n```', 'str'),
    fb('印出偶數列才印星號（2、4 列印，1、3 列印空行）。\n\n```python\nfor i in range(1, 5):\n    if i % 2 == __1__:\n        print("*" * i)\n    else:\n        print()\n```', '0'),
    fb('雙層迴圈印撲克牌組合（花色×點數，共 4 行）。\n\n```python\nfor suit in ["黑桃", "紅心"]:\n    for rank in ["A", "K"]:\n        print(suit __1__ rank)\n```', '+'),
    fb('計算 2×2 表格內所有 i*j 的總和。\n\n```python\ntotal = 0\nfor i in range(1, 3):\n    for j in range(1, 3):\n        total += i * j\nprint(total)   # 9\n```\n\n空格：內層變數名稱應是？（已填 j）此題輸出 9 的計算中 i=1,j=2 貢獻多少？（填數字）', '2',
       explanation='1×1+1×2+2×1+2×2=9；i=1、j=2 該格貢獻 2。'),
    fb('印出 5 的乘法表（5×1 到 5×9，每行一式）。\n\n```python\nfor i in range(1, 10):\n    print(f"5×{i}={5 __1__ i}")\n```', '*'),
    fb('印出正方形外框的第一列（5 顆星）。\n\n```python\nwidth = 5\nprint("*" * __1__)\n```', 'width'),
    fb('累計輸入 4 次成績的總和。\n\n```python\ntotal = 0\nfor i in range(4):\n    total += int(__1__())\nprint(total)\n```', 'input'),
    fb('印出字母金字塔：A、BB、CCC。\n\n```python\nletters = "ABC"\nfor i in range(1, 4):\n    print(letters[i - 1] * __1__)\n```', 'i'),
    fb('九九乘法表的直式其中一欄：印 1×3 到 9×3。\n\n```python\nfor i in range(1, 10):\n    print(i * __1__)\n```', '3'),
    fb('印 3 次「加油」且每次前面加編號（1. 加油）。\n\n```python\nfor i in range(1, 4):\n    print(f"{i}. __1__")\n```\n\n空格填輸出的文字。', '加油'),
    fb('把迴圈印出的星星連成一列（不換行），最後補一個換行。\n\n```python\nfor i in range(6):\n    print("*", end="")\nprint(__1__)\n```', ['""', "''"]),
    fb('計算 10 以內質數個數（2、3、5、7）。\n\n```python\ncount = 0\nfor n in range(2, 11):\n    is_p = True\n    for d in range(2, n):\n        if n % d == 0:\n            is_p = False\n    if is_p:\n        count += __1__\nprint(count)   # 4\n```', '1'),
    fb('印出 1~9 中每個數與其立方。\n\n```python\nfor i in range(1, 10):\n    print(i, i ** __1__)\n```', '3'),
    fb('猜數字答對就跳出。\n\n```python\nanswer = 7\nwhile True:\n    guess = int(input())\n    if guess == answer:\n        print("答對")\n        __1__\n```', 'break'),
    fb('印出遞減數字三角形：321、21、1。\n\n```python\nfor i in range(3, 0, -1):\n    line = ""\n    for j in range(i, 0, -1):\n        line += str(j)\n    print(__1__)\n```', 'line'),
    fb('計算 3 列 4 欄表格的元素個數。\n\n```python\nrows = 3\ncols = 4\nprint(rows __1__ cols)   # 12\n```', '*'),
    fb('印出上半三角形之後再印下半（菱形雛形的上半）。\n\n```python\nfor i in range(1, 4):\n    print("*" * i)\nfor i in range(2, 0, __1__):\n    print("*" * i)\n```', '-1'),
    fb('每列星數是列號的兩倍。\n\n```python\nfor i in range(1, 4):\n    print("*" * (i * __1__))\n```', '2'),
    fb('印出時鐘刻度 1 到 12。\n\n```python\nfor h in range(1, __1__):\n    print(h, "點")\n```', '13'),
]


# ── U4 Level 2：60 選擇 + 40 填空（TQC+ 觀念題：巢狀追蹤＋經典演算法）──
U4_L2 = [
    # 巢狀與經典追蹤（32，含競賽原題）
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\ntotal = 0\nfor i in range(1, 11):\n    if i % 3 == 0:\n        total += 1\nprint(total % 4)\n```', '3', '0', '1', '2',
       explanation='3、6、9 共 3 個，3%4=3。（113 商業類技藝競賽學科第 13 題）'),
    mc('以下程式的輸出是？\n\n```python\nn = 49\nis_prime = n >= 2\nfor d in range(2, int(n ** 0.5) + 1):\n    if n % d == 0:\n        is_prime = False\n        break\nprint(is_prime)\n```', 'False', 'True', '49', '7',
       explanation='檢查到 7 時整除（49=7×7）。'),
    mc('質數判斷只需檢查到 √n 的原因是？', '若有大於 √n 的因數，必有一個對應的小於 √n 的因數',
       '大於 √n 的數不可能是因數', '這樣寫比較短', '√n 一定是質數'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(3):\n    for j in range(3):\n        if j == 1:\n            break\n        print(i, j)\n```', '3 行（每列只印 j=0）', '9 行', '6 行', '1 行',
       explanation='內層 j=1 就 break，每個 i 只印一次。'),
    mc('以下程式的輸出是？\n\n```python\na, b = 0, 1\nfor i in range(7):\n    a, b = b, a + b\nprint(a)\n```', '13', '8', '21', '7',
       explanation='費氏：1,1,2,3,5,8,13。'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nfor i in range(1, 4):\n    for j in range(1, 4):\n        if i == j:\n            count += 1\nprint(count)\n```', '3', '9', '6', '1',
       explanation='對角線 (1,1)、(2,2)、(3,3)。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(1, 4):\n    for j in range(i):\n        total += 1\nprint(total)\n```', '6', '9', '3', '12',
       explanation='0+1+2… i=1 跑1次、i=2 跑2次、i=3 跑3次 → 6。'),
    mc('以下程式的輸出是？\n\n```python\nfor i in range(1, 3):\n    for j in range(1, 4):\n        print(f"{i}{j}", end=" ")\n    print()\n```\n\n第二列輸出是？', '21 22 23', '11 12 13', '21 22', '12 22 32'),
    mc('以下程式印出的第 5 行是？\n\n```python\nfor i in range(1, 10):\n    print(f"7×{i}={7 * i}")\n```', '7×5=35', '7×4=28', '7×6=42', '5×7=35'),
    mc('以下程式的輸出是？\n\n```python\nresult = 0\nfor i in range(1, 5):\n    if i % 2 == 0:\n        result += i * 10\n    else:\n        result += i\nprint(result)\n```', '64', '10', '46', '100',
       explanation='1+20+3+40=64。'),
    mc('以下程式依序輸入 80、90、70、-1，輸出是？\n\n```python\ntotal = 0\ncount = 0\nbest = 0\nwhile True:\n    s = int(input())\n    if s == -1:\n        break\n    total += s\n    count += 1\n    if s > best:\n        best = s\nprint(total // count, best)\n```', '80 90', '80 80', '240 90', '90 80',
       explanation='平均 240//3=80、最高 90。'),
    mc('以下程式的輸出是？\n\n```python\nn = 6\ntotal = 0\nfor i in range(1, n):\n    if n % i == 0:\n        total += i\nprint(total == n)\n```', 'True', 'False', '6', '發生錯誤',
       explanation='1+2+3=6，6 是完全數。'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nn = 100\nwhile n > 1:\n    n //= 3\n    count += 1\nprint(count)\n```', '4', '5', '3', '33',
       explanation='100→33→11→3→1，共除 4 次。'),
    mc('以下程式的輸出是？\n\n```python\ngrid = 0\nfor i in range(4):\n    for j in range(4):\n        if (i + j) % 2 == 0:\n            grid += 1\nprint(grid)\n```', '8', '16', '4', '12',
       explanation='4×4 棋盤中同色格（i+j 為偶數）有 8 格。'),
    mc('印出「倒直角三角形」（第一列 4 顆星遞減到 1），正確的 range 是？',
       'range(4, 0, -1)', 'range(1, 5)', 'range(4)', 'range(0, 4, -1)'),
    mc('以下程式的輸出是？\n\n```python\ns = ""\nfor i in range(1, 4):\n    s += str(i) * i\nprint(s)\n```', '122333', '123', '112233', '321',
       explanation='1 + 22 + 333。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\ni = 1\nwhile i <= 32:\n    total += i\n    i *= 2\nprint(total)\n```', '63', '32', '31', '64',
       explanation='1+2+4+8+16+32=63。'),
    mc('以下程式的輸出是？\n\n```python\nfound = 0\nfor n in range(10, 30):\n    if n % 7 == 0:\n        found = n\nprint(found)\n```', '28', '14', '21', '7',
       explanation='沒有 break，持續覆寫到最後一個 7 的倍數。'),
    mc('1A2B 遊戲：答案 1234、猜 1359，幾 A 幾 B？（A=位置數字都對、B=數字對位置錯）',
       '1A1B', '2A0B', '1A2B', '0A2B',
       explanation='1 位置正確（1A）；3 存在但位置錯（1B）。'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nfor i in range(1, 101):\n    if i % 10 == 7:\n        count += 1\nprint(count)\n```', '10', '9', '11', '7',
       explanation='7、17、27、…、97 共 10 個。'),
    mc('以下程式的輸出是？\n\n```python\nresult = 1\nfor i in range(2, 6, 2):\n    result *= i\nprint(result)\n```', '8', '48', '6', '16',
       explanation='2×4=8。'),
    mc('以下程式的輸出是？\n\n```python\nrows = 3\nfor i in range(1, rows + 1):\n    print(" " * (rows - i) + "*" * (2 * i - 1))\n```\n\n最後一列印出幾顆星？', '5', '3', '7', '6',
       explanation='金字塔第 3 列：2×3-1=5。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(5):\n    total += i\nfor j in range(5):\n    total += j\nprint(total)\n```', '20', '10', '25', '45',
       explanation='兩個「並列」迴圈各加 10，不是巢狀。'),
    mc('巢狀迴圈印 6×6 表格，內層 print 執行次數與並列兩個迴圈（各 6 次）差多少？',
       '巢狀 36 次、並列 12 次，差 24 次', '一樣多', '巢狀 12 次', '差 6 次'),
    mc('以下程式的輸出是？\n\n```python\nn = 24\nd = 2\nwhile n % d != 0:\n    d += 1\nprint(d)\n```', '2', '3', '4', '12',
       explanation='24 的最小因數（>1）是 2。'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nwhile count < 5:\n    count += 2\nprint(count)\n```', '6', '5', '4', '無限迴圈'),
    mc('猜數字（答案 65）依序猜 50、80、65，程式會依序輸出？',
       '太小、太大、答對', '太大、太小、答對', '太小、太小、答對', '答對',
       explanation='50<65 太小、80>65 太大。'),
    mc('以下程式的輸出是？\n\n```python\ntext = ""\nfor i in range(5, 0, -1):\n    text += str(i)\nprint(text)\n```', '54321', '12345', '5', '15'),
    mc('九九乘法表用 f"{row * column:2}" 中 :2 的作用是？', '欄寬至少 2、靠右對齊',
       '只印 2 位數', '乘以 2', '取 2 位小數'),
    mc('以下程式的輸出是？\n\n```python\nbest = ""\nfor w in ["cat", "elephant", "dog"]:\n    if len(w) > len(best):\n        best = w\nprint(best)\n```', 'elephant', 'cat', 'dog', '8',
       explanation='找最長字串的極值樣板。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(1, 4):\n    total += i\n    if total > 3:\n        break\nprint(i, total)\n```', '3 6', '2 3', '3 3', '4 6',
       explanation='i=3 時 total=6 > 3 觸發 break。'),
    mc('印質數表 2~20，輸出的最後一個質數是？', '19', '17', '20', '13'),

    # 觀念（28）
    mc('巢狀迴圈的時間成本大約是？', '外層次數 × 內層次數', '外層次數 + 內層次數',
       '固定 100 次', '與次數無關'),
    mc('印出金字塔需要哪兩部分組成每一列？', '前導空格＋星號', '只有星號',
       '只有空格', '換行符號×2'),
    mc('「讀入成績直到 -1，輸出平均」中，-1 的角色是？', '哨兵值（結束訊號），不列入計算',
       '最低分', '也要算進平均', '錯誤輸入'),
    mc('費波那契數列的定義是？', '每一項是前兩項之和', '每一項是前一項×2',
       '每一項是質數', '每一項遞增 1'),
    mc('計算階乘 n! 時，累積變數的初始值應是？', '1', '0', 'n', '-1',
       explanation='連乘起點是 1，設 0 會全部歸零。'),
    mc('驗證「質數判斷程式」最該測試的邊界資料是？', '1 和 2', '100 和 99', '50', '任何偶數',
       explanation='1 不是質數、2 是最小質數，最容易寫錯。'),
    mc('雙層迴圈中「內層的範圍跟著外層變數變動」（range(i)）常用來印？', '三角形圖案',
       '正方形圖案', '直線', '空心圖形'),
    mc('要統計 2~50 的質數個數，程式結構是？', '外層列舉候選數、內層檢查因數',
       '單層迴圈即可', '三層迴圈', '不需要迴圈'),
    mc('1A2B 遊戲中「B」代表？', '數字正確但位置錯誤', '位置與數字都正確',
       '數字不存在', '猜測次數'),
    mc('猜數字用「二分逼近」策略，1~100 內最多幾次一定能猜中？', '7 次', '50 次', '10 次', '100 次'),
    mc('印空心矩形（只有外框有星號），判斷「是否在邊框上」的條件是？',
       'i 或 j 是第一列/最後一列/第一欄/最後一欄', 'i == j', 'i + j 是偶數', 'i * j > 0'),
    mc('下列哪個任務「最適合」用巢狀迴圈？', '列出兩個骰子的所有點數組合',
       '計算單一串列總和', '判斷一個數的正負', '字串轉大寫'),
    mc('程式測試時「先用簡單資料再用邊界資料」的順序是為了？',
       '先確認基本邏輯再檢查極端情況', '節省時間', '避免當機', '美觀'),
    mc('把「印 n 列星號三角形」寫成可調整 n 的程式，好處是？', '改一個變數就能改圖形大小',
       '執行更快', '不需要迴圈', '自動置中'),
    mc('外層迴圈變數 i、內層也命名 i 會發生什麼？', '內層覆蓋外層的值，容易出錯',
       '語法錯誤', '自動改名', '兩者互不影響'),
    mc('累加器與計數器的差別是？', '累加器加「數值本身」、計數器每次加 1',
       '完全相同', '計數器只能用在 while', '累加器不能歸零'),
    mc('印九九乘法表時 print(..., end="  ") 的用意是？', '同一列的格子間隔兩個空格且不換行',
       '每格換行', '刪除空格', '對齊小數點'),
    mc('哪一種資料排列印出來是「西洋棋盤」樣式？', '(i + j) 為偶數的格子印黑、其餘印白',
       'i 為偶數的整列印黑', '對角線印黑', '全部印黑'),
    mc('十進位轉二進位（不用 bin()）的核心操作是？', '反覆除以 2 並收集餘數',
       '反覆乘以 2', '除以 10', '字串切割'),
    mc('要找 1~100 中「因數最多」的數，需要哪兩層結構？',
       '外層列舉數字、內層數因數，再用極值樣板記錄', '單層迴圈', '排序後取第一個', '遞迴'),
    mc('while 猜數字迴圈裡忘了重新 input()，會發生什麼？', '無限迴圈（guess 永遠相同）',
       '正常執行', '語法錯誤', '自動結束'),
    mc('印倒三角形時，第 i 列（從 1 數起、共 n 列）的星數是？', 'n - i + 1', 'i', 'n + i', 'n - i'),
    mc('計算「平均」時要避免哪種除法錯誤？', '筆數為 0 時除以 0', '除以負數',
       '除以浮點數', '整除'),
    mc('用巢狀迴圈列出三位數各位數字組合（百、十、個位各 0~9），內層 print 執行幾次？',
       '1000 次', '100 次', '30 次', '999 次'),
    mc('要在巢狀迴圈中「跳出全部迴圈」，常用的技巧是？', '設旗標變數並在外層檢查後 break',
       '寫兩個 break 在同一行', '用 continue', '把內層刪掉'),
    mc('印菱形 = 上金字塔 + 下倒金字塔，兩段迴圈的關係是？', '前後並列執行',
       '巢狀', '互斥', '遞迴'),
    mc('第 5 列印 5 顆星的三角形，全部列印完共幾顆星？', '15', '25', '10', '5',
       explanation='1+2+3+4+5。'),
    mc('九九乘法表共會印出幾個乘法算式？', '81', '99', '45', '100',
       explanation='9×9 = 81 格。'),

    # ── L2 填空（40）──
    fb('九九乘法表雙層迴圈。\n\n```python\nfor row in range(1, 10):\n    for col in range(1, 10):\n        print(f"{row}x{col}={row * col}", end=" ")\n    __1__()\n```', 'print'),
    fb('質數判斷：只檢查到平方根。\n\n```python\nn = 37\nis_prime = n >= 2\nfor d in range(2, int(n ** __1__) + 1):\n    if n % d == 0:\n        is_prime = False\n        break\nprint(is_prime)   # True\n```', '0.5'),
    fb('費波那契前 n 項：核心遞推。\n\n```python\na, b = 0, 1\nfor i in range(8):\n    print(a, end=" ")\n    a, b = b, a __1__ b\n```', '+'),
    fb('sentinel 成績統計：讀到 -1 停止，輸出最高分。\n\n```python\nbest = 0\nwhile True:\n    s = int(input())\n    if s == -1:\n        __1__\n    if s > best:\n        best = s\nprint(best)\n```', 'break'),
    fb('倒直角三角形（4 到 1 顆星）。\n\n```python\nfor i in range(4, 0, -1):\n    print("*" __1__ i)\n```', '*'),
    fb('金字塔：第 i 列印 2i-1 顆星、前面 rows-i 個空格。\n\n```python\nrows = 4\nfor i in range(1, rows + 1):\n    print(" " * (rows - i) + "*" * (2 * i - __1__))\n```', '1'),
    fb('計算 1! + 2! + 3! + 4!。\n\n```python\ntotal = 0\nfact = 1\nfor i in range(1, 5):\n    fact __1__ i\n    total += fact\nprint(total)   # 33\n```', '*=',
       explanation='1+2+6+24=33。'),
    fb('列出 30 的所有因數並統計個數。\n\n```python\ncount = 0\nfor i in range(1, 31):\n    if 30 % i == __1__:\n        count += 1\nprint(count)   # 8\n```', '0'),
    fb('雙層迴圈：印出兩骰子和為 7 的組合數。\n\n```python\ncount = 0\nfor a in range(1, 7):\n    for b in range(1, 7):\n        if a + b == 7:\n            count += __1__\nprint(count)   # 6\n```', '1'),
    fb('猜數字：太大/太小提示（answer=42，依序輸入 50、30、42）。\n\n```python\nanswer = 42\nwhile True:\n    g = int(input())\n    if g == answer:\n        print("答對")\n        break\n    elif g __1__ answer:\n        print("太大")\n    else:\n        print("太小")\n```', '>'),
    fb('二維表格總和：3 列 range 值相加。\n\n```python\ntotal = 0\nfor i in range(1, 4):\n    for j in range(1, 4):\n        total += i __1__ j\nprint(total)   # 36\n```', '*',
       explanation='(1+2+3)×(1+2+3)=36。'),
    fb('印出 1~50 的質數。\n\n```python\nfor n in range(2, 51):\n    ok = True\n    for d in range(2, n):\n        if n % d == 0:\n            ok = __1__\n            break\n    if ok:\n        print(n)\n```', 'False'),
    fb('空心三角形的斜邊判斷之一：只有第一顆、最後一顆或最後一列印星。\n\n```python\nrows = 4\nfor i in range(1, rows + 1):\n    line = ""\n    for j in range(1, i + 1):\n        if j == 1 or j == i or i == __1__:\n            line += "*"\n        else:\n            line += " "\n    print(line)\n```', 'rows'),
    fb('階乘表：印 1! 到 5!。\n\n```python\nfact = 1\nfor i in range(1, 6):\n    fact *= i\n    print(f"{i}! = {__1__}")\n```', 'fact'),
    fb('讀入 5 筆成績，統計及格數與不及格數。\n\n```python\npass_n = fail_n = 0\nfor i in range(5):\n    s = int(input())\n    if s >= 60:\n        pass_n += 1\n    else:\n        fail_n __1__ 1\nprint(pass_n, fail_n)\n```', '+='),
    fb('印出斜對角線星號（3×3，僅 i==j 印星）。\n\n```python\nfor i in range(3):\n    line = ""\n    for j in range(3):\n        if i __1__ j:\n            line += "*"\n        else:\n            line += "."\n    print(line)\n```', '=='),
    fb('數字直角三角形：每列印 1 到 i。\n\n```python\nfor i in range(1, 5):\n    for j in range(1, i + 1):\n        print(j, end="")\n    print()\n```\n\n第 4 列輸出是？（直接填）', '1234'),
    fb('用雙層迴圈找出 100 內「因數個數最多」的數的因數個數。\n\n```python\nbest = 0\nfor n in range(1, 101):\n    c = 0\n    for d in range(1, n + 1):\n        if n % d == 0:\n            c += 1\n    if c > best:\n        best = __1__\nprint(best)   # 12\n```', 'c',
       explanation='96 有 12 個因數。'),
    fb('印出乘法表中「乘積為偶數」的格子數（1~9 全表）。\n\n```python\ncount = 0\nfor i in range(1, 10):\n    for j in range(1, 10):\n        if (i * j) % 2 == 0:\n            count += 1\nprint(count)   # 56\n```\n\n空格：條件裡的運算子 __1__ 是？', '%',
       explanation='81 格中奇×奇=25 格是奇數，其餘 56 格為偶數。'),
    fb('骰子點數和分布：和為 10 的組合數。\n\n```python\ncount = 0\nfor a in range(1, 7):\n    for b in range(1, 7):\n        if a + b == __1__:\n            count += 1\nprint(count)   # 3\n```', '10'),
    fb('倒著印字母三角形：CCC、BB、A。\n\n```python\nletters = "ABC"\nfor i in range(3, 0, -1):\n    print(letters[i - 1] * __1__)\n```', 'i'),
    fb('累計購買直到預算不足，輸出可買件數（單價 45、預算 200）。\n\n```python\nmoney = 200\ncount = 0\nwhile money >= 45:\n    money -= __1__\n    count += 1\nprint(count)   # 4\n```', '45'),
    fb('印出 4×4 棋盤（黑=#、白=.）。\n\n```python\nfor i in range(4):\n    line = ""\n    for j in range(4):\n        if (i + j) % 2 == 0:\n            line += "#"\n        else:\n            line += __1__\n    print(line)\n```', ['"."', "'.'"]),
    fb('把兩層迴圈的座標印成 (i,j) 形式。\n\n```python\nfor i in range(2):\n    for j in range(2):\n        print(f"({i},{__1__})", end=" ")\n```', 'j'),
    fb('計算 2 的 0~10 次方總和。\n\n```python\ntotal = 0\nfor i in range(11):\n    total += 2 ** __1__\nprint(total)   # 2047\n```', 'i'),
    fb('連續整數段和：找出從 1 開始連加剛好等於 55 的最後一項。\n\n```python\ntotal = 0\nn = 0\nwhile total < 55:\n    n += 1\n    total += n\nprint(__1__)   # 10\n```', 'n'),
    fb('印出 12 個月的天數（非閏年，2 月 28）。\n\n```python\nfor m in range(1, 13):\n    if m == 2:\n        d = 28\n    elif m in [4, 6, 9, 11]:\n        d = 30\n    else:\n        d = __1__\n    print(m, "月", d, "天")\n```', '31'),
    fb('把整數逐位印出（由高位到低位，用字串）。\n\n```python\nn = 507\nfor ch in __1__(n):\n    print(ch)\n```', 'str'),
    fb('模擬時鐘報時：每 3 小時報一次（0~24）。\n\n```python\nfor h in range(0, 25, __1__):\n    print(h, "點報時")\n```', '3'),
    fb('雙迴圈找 1~30 中「同時是平方數與偶數」的數。\n\n```python\nfor n in range(1, 31):\n    for k in range(1, 7):\n        if k * k == n and n % 2 == __1__:\n            print(n)\n```\n\n（依序輸出 4 與 16）', '0'),
    fb('印身高排名：找第二高（先用迴圈找最高再排除）。\n\n```python\nheights = [172, 180, 168, 175]\nfirst = heights[0]\nfor h in heights:\n    if h > first:\n        first = h\nsecond = 0\nfor h in heights:\n    if h != first and h > second:\n        second = __1__\nprint(second)   # 175\n```', 'h'),
    fb('印出 5 列的號碼牌（No.1 到 No.5）。\n\n```python\nfor i in range(1, 6):\n    print(f"No.{__1__}")\n```', 'i'),
    fb('讀入 n 後印出 n 層數字塔（每列印列號 i 共 i 次）。\n\n```python\nn = int(input())\nfor i in range(1, n + 1):\n    print(str(i) * __1__)\n```', 'i'),
    fb('找 3 位數中的迴文數個數（百位=個位）。\n\n```python\ncount = 0\nfor n in range(100, 1000):\n    if n // 100 == n % __1__:\n        count += 1\nprint(count)   # 90\n```', '10'),
    fb('印九九乘法表「上三角」（j 從 i 開始）。\n\n```python\nfor i in range(1, 10):\n    for j in range(__1__, 10):\n        print(f"{i}x{j}", end=" ")\n    print()\n```', 'i'),
    fb('雞兔同籠：頭 35、腳 94。\n\n```python\nfor c in range(36):\n    r = 35 - c\n    if 2 * c + 4 * r == __1__:\n        print(c, r)   # 23 12\n```', '94'),
    fb('印出楊輝三角前 4 列的第一列與邊界（全 1 簡化版）。\n\n```python\nfor i in range(1, 5):\n    print("1 " * __1__)\n```', 'i'),
    fb('攤平巢狀計數：3 個班、每班 28 人，總人數。\n\n```python\ntotal = 0\nfor c in range(3):\n    for s in range(28):\n        total += 1\nprint(__1__)   # 84\n```', 'total'),
    fb('對戰表：4 隊兩兩對戰（不重複、不含自己）場次數。\n\n```python\ncount = 0\nfor i in range(4):\n    for j in range(i + 1, __1__):\n        count += 1\nprint(count)   # 6\n```', '4'),
    fb('讀入直到輸入負數，輸出所有正輸入的平均（至少一筆）。\n\n```python\ntotal = 0\ncount = 0\nwhile True:\n    n = int(input())\n    if n < 0:\n        break\n    total += n\n    count += 1\nprint(total __1__ count)\n```', '/'),
]


# ── U4 Level 3：35 選擇 + 65 填空（競賽／TQC 實作：二維資料、進位轉換、狀態追蹤）──
U4_L3 = [
    # 進階追蹤（35，含競賽原題 3 題）
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\ncount = 0\nfor i in range(3):\n    for j in range(i, 5):\n        count += 1\nprint(count % 4)\n```', '0', '1', '2', '3',
       explanation='5+4+3=12，12%4=0。（113 商業類技藝競賽學科第 3 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\nx = 0\nfor i in range(3):\n    for j in range(3):\n        x += i * j\nprint(x % 4)\n```', '1', '0', '2', '3',
       explanation='(0+1+2)×(0+1+2)=9，9%4=1。（113 商業類技藝競賽學科第 18 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\na = [[0] * 3 for _ in range(3)]\nfor i in range(3):\n    for j in range(3):\n        a[i][j] = i + j\nprint(a[2][2] % 4)\n```', '0', '1', '2', '3',
       explanation='a[2][2]=4，4%4=0。（113 商業類技藝競賽學科第 20 題）'),
    mc('以下程式的輸出是？（十進位轉二進位）\n\n```python\nn = 13\nbits = ""\nwhile n > 0:\n    bits = str(n % 2) + bits\n    n //= 2\nprint(bits)\n```', '1101', '1011', '13', '1110',
       explanation='13 = 8+4+1 = 1101₂。'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nfor n in range(2, 51):\n    ok = n >= 2\n    for d in range(2, n):\n        if n % d == 0:\n            ok = False\n            break\n    if ok:\n        count += 1\nprint(count)\n```', '15', '14', '16', '25',
       explanation='2~50 有 15 個質數。'),
    mc('以下程式的輸出是？（列總和）\n\n```python\ngrid = [[1, 2, 3], [4, 5, 6]]\nfor row in grid:\n    total = 0\n    for v in row:\n        total += v\n    print(total, end=" ")\n```', '6 15', '21', '5 7 9', '1 2 3',
       explanation='第一列 1+2+3、第二列 4+5+6。'),
    mc('以下程式的輸出是？（欄總和）\n\n```python\ngrid = [[1, 2, 3], [4, 5, 6]]\nfor c in range(3):\n    total = 0\n    for r in range(2):\n        total += grid[r][c]\n    print(total, end=" ")\n```', '5 7 9', '6 15', '21', '1 4',
       explanation='各欄：1+4、2+5、3+6。'),
    mc('以下程式的輸出是？（最長連續段）\n\n```python\nvalues = [1, 1, 2, 2, 2, 3]\nbest = cur = 1\nfor i in range(1, 6):\n    if values[i] == values[i - 1]:\n        cur += 1\n    else:\n        cur = 1\n    if cur > best:\n        best = cur\nprint(best)\n```', '3', '2', '1', '6',
       explanation='三個連續的 2。'),
    mc('以下程式的輸出是？\n\n```python\nn = 60\nfactors = []\nd = 2\nwhile n > 1:\n    while n % d == 0:\n        factors.append(d)\n        n //= d\n    d += 1\nprint(factors)\n```', '[2, 2, 3, 5]', '[2, 3, 5]', '[2, 2, 15]', '[60]',
       explanation='質因數分解：60 = 2×2×3×5。'),
    mc('空心矩形 5×4（5 欄 4 列）只印外框，共印幾顆星？', '14', '20', '18', '16',
       explanation='2×(5+4)−4 = 14。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(1, 5):\n    for j in range(1, 5):\n        if i < j:\n            total += 1\nprint(total)\n```', '6', '16', '10', '4',
       explanation='i<j 的組合：C(4,2)=6。'),
    mc('以下程式的輸出是？\n\n```python\nn = 9\nresult = ""\nwhile n > 0:\n    result += str(n % 2)\n    n //= 2\nprint(result)\n```', '1001', '1100', '9', '101',
       explanation='餘數依序 1,0,0,1，不反轉直接串接得 1001（9=1001₂ 恰為回文）。'),
    mc('以下程式的輸出是？\n\n```python\ngrid = [[2, 4], [6, 8]]\ntotal = 0\nfor i in range(2):\n    total += grid[i][i]\nprint(total)\n```', '10', '20', '12', '8',
       explanation='對角線 2+8。'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\ni = 1\nwhile i <= 100:\n    j = i\n    while j > 0:\n        j //= 10\n        count += 1\n    i *= 10\nprint(count)\n```', '6', '3', '111', '100',
       explanation='1（1位）+10（2位）+100（3位）→ 1+2+3=6 次。'),
    mc('外層 range(n)、內層 range(i)，內層總執行次數是？', 'n(n-1)/2', 'n²', 'n(n+1)/2', 'n',
       explanation='0+1+…+(n-1)。'),
    mc('以下程式的輸出是？\n\n```python\ns = 0\nfor i in range(1, 4):\n    for j in range(1, 4):\n        s += 10 * i + j\nprint(s)\n```', '198', '180', '99', '216',
       explanation='列和：(11+12+13)+(21+22+23)+(31+32+33)=36+66+96=198。'),
    mc('把 25 轉成二進位，最右邊（最低位）的位元是？', '1', '0', '2', '5',
       explanation='25 是奇數，25 % 2 = 1。'),
    mc('以下程式的輸出是？\n\n```python\nflag = False\nfor i in range(2):\n    for j in range(2):\n        if i + j == 3:\n            flag = True\nprint(flag)\n```', 'False', 'True', '3', '發生錯誤',
       explanation='i、j 最大各 1，和最大 2。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i in range(1, 21):\n    if i % 3 == 0 or i % 5 == 0:\n        total += i\nprint(total)\n```', '98', '63', '33', '78',
       explanation='3+5+6+9+10+12+15+18+20=98。'),
    mc('矩陣轉置後，原本 grid[1][2] 的值會出現在？', 'grid[2][1]', 'grid[1][2]', 'grid[0][0]', 'grid[2][2]'),
    mc('以下程式的輸出是？\n\n```python\nbest_len = 0\ncur = 0\nfor ch in "aabbbcc":\n    if ch == "b":\n        cur += 1\n        if cur > best_len:\n            best_len = cur\n    else:\n        cur = 0\nprint(best_len)\n```', '3', '2', '7', '1',
       explanation='連續 b 的最長長度。'),
    mc('九九乘法表中「乘積為 12」的格子有幾個？', '4', '2', '6', '3',
       explanation='2×6、3×4、4×3、6×2。'),
    mc('以下程式的輸出是？\n\n```python\nn = 100\ncount = 0\nwhile n != 1:\n    if n % 2 == 0:\n        n //= 2\n    else:\n        n = n * 3 + 1\n    count += 1\nprint(count)\n```', '25', '7', '100', '10',
       explanation='Collatz：100 需 25 步收斂到 1。'),
    mc('印 n=5 的菱形（上 5 列下 4 列），最寬列的星數是？', '9', '5', '7', '10',
       explanation='2n-1 = 9。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nk = 1\nfor i in range(1, 6):\n    total += k\n    k = -k * 2\nprint(total)\n```', '11', '31', '-11', '21',
       explanation='1-2+4-8+16=11。'),
    mc('二維串列 [[0]*3]*3 與 [[0]*3 for _ in range(3)] 的差別是？',
       '前者三列是同一個串列（改一列全變）、後者互相獨立', '完全相同',
       '前者比較快所以較好', '後者會發生錯誤',
       explanation='乘法複製的是參照，是經典陷阱。'),
    mc('以下程式的輸出是？\n\n```python\nrow_max = []\nfor row in [[3, 9], [7, 2]]:\n    m = row[0]\n    for v in row:\n        if v > m:\n            m = v\n    row_max.append(m)\nprint(row_max)\n```', '[9, 7]', '[3, 7]', '[9, 2]', '[7, 9]'),
    mc('用「埃氏篩法」思路找質數與逐一試除相比，主要差異是？',
       '先把倍數統統劃掉，避免重複檢查', '完全相同', '篩法只能找偶數', '篩法需要遞迴'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\nfor h in range(24):\n    for m in range(60):\n        if h % 10 == 3 and m % 10 == 3:\n            count += 1\nprint(count)\n```', '18', '12', '6', '36',
       explanation='小時個位為 3：3、13、23 共 3 個；分鐘個位為 3：6 個。3×6=18。'),
    mc('把 6 顆糖分給 2 人（每人至少 1 顆）的分法枚舉，內層條件是？',
       'a + b == 6 且 a、b 都 >= 1', 'a * b == 6', 'a - b == 6', 'a == b'),
    mc('以下程式的輸出是？\n\n```python\ngrid = [[1, 2], [3, 4]]\nfor i in range(2):\n    for j in range(2):\n        if i != j:\n            grid[i][j] *= 10\nprint(grid)\n```', '[[1, 20], [30, 4]]', '[[10, 2], [3, 40]]',
       '[[10, 20], [30, 40]]', '[[1, 2], [3, 4]]',
       explanation='非對角線元素乘 10。'),
    mc('模擬兩位數密碼鎖全部組合（00~99）需要試幾次？', '100', '99', '10', '20'),
    mc('以下程式的輸出是？\n\n```python\ns = "10110"\nvalue = 0\nfor ch in s:\n    value = value * 2 + int(ch)\nprint(value)\n```', '22', '10110', '11', '30',
       explanation='二進位字串轉十進位：10110₂ = 22。'),
    mc('印「乘法表但只印 i ≤ j 的格子」會印出幾格？', '45', '81', '36', '9',
       explanation='9+8+…+1 的上三角 = 45。'),
    mc('狀態追蹤「目前連續長度」歸零的時機是？', '當前值與前一個值不同時', '每一圈都歸零',
       '只在開頭歸零', '值大於 10 時'),

    # ── L3 填空（65）──
    fb('十進位轉二進位（不用 bin）。\n\n```python\nn = 19\nbits = ""\nwhile n > 0:\n    bits = str(n __1__ 2) + bits\n    n //= 2\nprint(bits)   # 10011\n```', '%'),
    fb('二進位字串轉十進位。\n\n```python\ns = "1101"\nvalue = 0\nfor ch in s:\n    value = value * __1__ + int(ch)\nprint(value)   # 13\n```', '2'),
    fb('質因數分解 84。\n\n```python\nn = 84\nd = 2\nresult = []\nwhile n > 1:\n    while n % d == 0:\n        result.append(d)\n        n __1__ d\n    d += 1\nprint(result)   # [2, 2, 3, 7]\n```', '//='),
    fb('完全數搜尋：找出 1~30 中的完全數。\n\n```python\nfor n in range(2, 31):\n    s = 0\n    for d in range(1, n):\n        if n % d == 0:\n            s += d\n    if s __1__ n:\n        print(n)\n```\n\n（依序輸出 6 與 28）', '=='),
    fb('列總和：輸出每列的和。\n\n```python\ngrid = [[5, 1], [2, 8], [4, 4]]\nfor row in grid:\n    total = 0\n    for v in row:\n        total __1__ v\n    print(total)\n```', '+='),
    fb('欄總和：輸出每欄的和。\n\n```python\ngrid = [[5, 1], [2, 8]]\nfor c in range(2):\n    total = 0\n    for r in range(2):\n        total += grid[r][__1__]\n    print(total)\n```\n\n（依序輸出 7 與 9）', 'c'),
    fb('對角線和：3×3 矩陣主對角線。\n\n```python\ngrid = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\ntotal = 0\nfor i in range(3):\n    total += grid[i][__1__]\nprint(total)   # 15\n```', 'i'),
    fb('空心矩形：只有邊框印星。\n\n```python\nh, w = 4, 6\nfor i in range(h):\n    line = ""\n    for j in range(w):\n        if i == 0 or i == h - 1 or j == 0 or j == w - __1__:\n            line += "*"\n        else:\n            line += " "\n    print(line)\n```', '1'),
    fb('菱形上半部：第 i 列 2i-1 顆星置中。\n\n```python\nn = 4\nfor i in range(1, n + 1):\n    print(" " * (n - i) + "*" * (2 * i - __1__))\n```', '1'),
    fb('最長連續相同值的長度。\n\n```python\nvalues = [3, 3, 3, 1, 2, 2]\nbest = cur = 1\nfor i in range(1, 6):\n    if values[i] == values[i - 1]:\n        cur += 1\n    else:\n        cur = __1__\n    if cur > best:\n        best = cur\nprint(best)   # 3\n```', '1'),
    fb('井字棋盤面印製（3×3 全部印 -）。\n\n```python\nfor i in range(3):\n    print("-" * __1__)\n```', '3'),
    fb('找出兩個骰子和最常出現的值（枚舉統計 7 的次數）。\n\n```python\ncount = 0\nfor a in range(1, 7):\n    for b in range(1, 7):\n        if a + b == 7:\n            count += 1\nprint(__1__)   # 6\n```', 'count'),
    fb('楊輝三角邊界簡化：印 n 列、每列 i 個 1。\n\n```python\nn = 4\nfor i in range(1, n + 1):\n    print(("1 " * i).strip())\n```\n\n第 3 列輸出（直接填）？', '1 1 1'),
    fb('模擬密碼鎖窮舉：找出兩位數密碼（已知數字和為 9、差為 3、十位大）。\n\n```python\nfor t in range(10):\n    for o in range(10):\n        if t + o == 9 and t - o == __1__:\n            print(t, o)   # 6 3\n```', '3'),
    fb('埃氏篩法簡化：把 2 的倍數標記為非質數。\n\n```python\nis_prime = [True] * 20\nfor i in range(4, 20, __1__):\n    is_prime[i] = False\nprint(is_prime[6], is_prime[7])   # False True\n```', '2'),
    fb('棋盤格子統計：8×8 中黑格數（i+j 偶數）。\n\n```python\ncount = 0\nfor i in range(8):\n    for j in range(8):\n        if (i + j) % 2 == __1__:\n            count += 1\nprint(count)   # 32\n```', '0'),
    fb('迴圈次數分析：三角形巢狀的總次數。\n\n```python\nn = 6\ncount = 0\nfor i in range(n):\n    for j in range(i):\n        count += 1\nprint(count)   # 15\n```\n\n公式為 n(n-1)/2，n=6 時為？（填數字）', '15'),
    fb('數字塔：第 i 列印 i 重複的 i。\n\n```python\nfor i in range(1, 6):\n    print(__1__(i) * i)\n```', 'str'),
    fb('沙漏圖形上半：5、3、1 顆星置中。\n\n```python\nfor i in range(5, 0, -2):\n    print(" " * ((5 - i) // 2) + "*" * __1__)\n```', 'i'),
    fb('視力表 E 方向枚舉：4 方向 × 5 大小共幾種。\n\n```python\ncount = 0\nfor d in range(4):\n    for s in range(5):\n        count += 1\nprint(count)   # 20\n```\n\n輸出？（填數字）', '20'),
    fb('存款封頂：每月存 6000，存到 5 萬就停，最後一個月只存差額。\n\n```python\nsaved = 0\nmonths = 0\nwhile saved < 50000:\n    deposit = min(6000, 50000 - saved)\n    saved += deposit\n    months += __1__\nprint(months, saved)   # 9 50000\n```', '1'),
    fb('數獨列檢查：確認一列是否包含 1~4 各一次。\n\n```python\nrow = [2, 4, 1, 3]\nok = True\nfor v in range(1, 5):\n    if v not in row:\n        ok = __1__\nprint(ok)   # True\n```', 'False'),
    fb('乘法表找「乘積個位數為 6」的格數。\n\n```python\ncount = 0\nfor i in range(1, 10):\n    for j in range(1, 10):\n        if (i * j) % 10 == __1__:\n            count += 1\nprint(count)   # 12\n```', '6',
       explanation='(1,6)(2,3)(2,8)(3,2)(4,4)(4,9)(6,1)(6,6)(7,8)(8,2)(8,7)(9,4) 共 12 格。'),
    fb('比賽勝場統計：連勝中斷就結算，輸出最長連勝。\n\n```python\nresults = "WWLWWWL"\nbest = cur = 0\nfor r in results:\n    if r == "W":\n        cur += 1\n        best = max(best, cur)\n    else:\n        cur = __1__\nprint(best)   # 3\n```', '0'),
    fb('溫度矩陣找全域最大值。\n\n```python\ngrid = [[22, 31], [28, 25]]\nbig = grid[0][0]\nfor row in grid:\n    for v in row:\n        if v __1__ big:\n            big = v\nprint(big)   # 31\n```', '>'),
    fb('印出 1~n 每個數的因數個數（n=6）。\n\n```python\nfor num in range(1, 7):\n    c = 0\n    for d in range(1, num + 1):\n        if num % d == 0:\n            c += 1\n    print(num, "有", c, "個因數")\n```\n\n6 有幾個因數？（填數字）', '4'),
    fb('雙迴圈積分格：計算 4×4 網格內 i*j 的最大值（i、j 為 1~4）。\n\n```python\nbest = 0\nfor i in range(1, 5):\n    for j in range(1, 5):\n        if i * j > best:\n            best = i __1__ j\nprint(best)   # 16\n```', '*'),
    fb('把 10 進位數逐位加總直到剩一位（數字根，用巢狀 while）。\n\n```python\nn = 9875\nwhile n >= 10:\n    s = 0\n    while n > 0:\n        s += n % 10\n        n //= 10\n    n = s\nprint(n)   # 2\n```\n\n9+8+7+5=29 → 2+9=11 → 1+1=？（填數字）', '2'),
    fb('轉置 2×2 矩陣。\n\n```python\ng = [[1, 2], [3, 4]]\nt = [[0, 0], [0, 0]]\nfor i in range(2):\n    for j in range(2):\n        t[j][__1__] = g[i][j]\nprint(t)   # [[1, 3], [2, 4]]\n```', 'i'),
    fb('印出所有兩位數迴文（11、22、…、99）共幾個。\n\n```python\ncount = 0\nfor n in range(10, 100):\n    if n // 10 == n % 10:\n        count += 1\nprint(count)   # __1__\n```\n\n（填輸出的數字）', '9'),
    fb('紙牌花色×點數共 52 張的枚舉。\n\n```python\ncount = 0\nfor suit in range(4):\n    for rank in range(1, 14):\n        count += 1\nprint(count)   # 52\n```\n\n內層 range 的終點是？（已填 14）輸出？（填數字）', '52'),
    fb('螺旋計數簡化：外圈元素個數（5×5 矩陣最外圈）。\n\n```python\nn = 5\nprint(4 * (n - 1))   # 16\n```\n\n公式 4(n-1)，n=5 輸出？（填數字）', '16'),
    fb('模擬電梯樓層停靠：從 1 樓開始依按鈕順序移動，累計移動樓層數。\n\n```python\nfloors = [5, 2, 8]\ncur = 1\nmoved = 0\nfor f in floors:\n    moved += abs(f - cur)\n    cur = __1__\nprint(moved)   # 13\n```', 'f',
       explanation='|5-1|+|2-5|+|8-2| = 4+3+6 = 13。'),
    fb('雙人猜拳計分：R>S、S>P、P>R，統計 A 的勝場。\n\n```python\na_moves = "RSP"\nb_moves = "SSR"\nwins = 0\nfor i in range(3):\n    a, b = a_moves[i], b_moves[i]\n    if (a == "R" and b == "S") or (a == "S" and b == "P") or (a == "P" and b == __1__):\n        wins += 1\nprint(wins)   # 2\n```', ['"R"', "'R'"],
       explanation='R vs S 勝、S vs S 平、P vs R 勝。'),
    fb('累計獎金：連續達標獎金翻倍（達標 3 天，起始 100）。\n\n```python\nbonus = 100\ntotal = 0\nfor day in range(3):\n    total += bonus\n    bonus *= __1__\nprint(total)   # 700\n```', '2'),
    fb('計算 50 以內所有質數的總和。\n\n```python\ntotal = 0\nfor n in range(2, 51):\n    ok = True\n    for d in range(2, n):\n        if n % d == 0:\n            ok = False\n            break\n    if ok:\n        total += __1__\nprint(total)   # 328\n```', 'n',
       explanation='2+3+5+…+47 = 328。'),
    fb('回力鏢數列：1,2,3,2,1 的總和。\n\n```python\ntotal = 0\nfor v in [1, 2, 3, 2, 1]:\n    total += v\nprint(total)   # __1__\n```\n\n（填輸出）', '9'),
    fb('印星號箭頭（上 1、2、3，下 2、1）。\n\n```python\nfor i in [1, 2, 3, 2, 1]:\n    print("*" __1__ i)\n```', '*'),
    fb('計算矩陣所有元素平均。\n\n```python\ngrid = [[2, 4], [6, 8]]\ntotal = 0\nn = 0\nfor row in grid:\n    for v in row:\n        total += v\n        n += 1\nprint(total __1__ n)   # 5.0\n```', '/'),
    fb('把 1~20 的數字依 5 個一列排版。\n\n```python\nfor i in range(1, 21):\n    print(i, end=" ")\n    if i % 5 == 0:\n        __1__()\n```', 'print'),
    fb('模擬骰子丟 3 顆全枚舉，統計總和為 10 的組合數。\n\n```python\ncount = 0\nfor a in range(1, 7):\n    for b in range(1, 7):\n        for c in range(1, 7):\n            if a + b + c == __1__:\n                count += 1\nprint(count)   # 27\n```', '10'),
    fb('溫度轉換表：攝氏 0~100 每 25 度印華氏。\n\n```python\nfor c in range(0, 101, __1__):\n    print(c, c * 9 / 5 + 32)\n```', '25'),
    fb('印乘法表其中的平方項（1x1、2x2、…、9x9）。\n\n```python\nfor i in range(1, 10):\n    print(f"{i}x{i}={i __1__ i}")\n```', '*'),
    fb('停車場計費全枚舉檢查：找出費用剛好 100 的停車時數（每小時 20、上限 8 小時）。\n\n```python\nfor h in range(1, 9):\n    if h * 20 == __1__:\n        print(h)   # 5\n```', '100'),
    fb('數字直方圖：分數對應星號數（每 10 分一顆星）。\n\n```python\nfor s in [35, 72, 90]:\n    print("*" * (s // __1__))\n```', '10'),
    fb('螞蟻搬家：每天搬 15 顆，倉庫 100 顆搬完需幾天（最後一天不足 15 也算一天）。\n\n```python\nstock = 100\ndays = 0\nwhile stock > 0:\n    stock -= __1__\n    days += 1\nprint(days)   # 7\n```', '15'),
    fb('找出加總後最接近 50 的前綴（不超過 50）。\n\n```python\nnums = [20, 15, 10, 9]\ntotal = 0\nfor n in nums:\n    if total + n > 50:\n        break\n    total += n\nprint(total)   # __1__\n```\n\n（填輸出）', '45'),
    fb('印出時刻表：6 點到 22 點每 4 小時一班。\n\n```python\nfor h in range(6, 23, __1__):\n    print(f"{h}:00 發車")\n```', '4'),
    fb('雙迴圈製作座位表（3 排 × 4 位）：印出排號-位號。\n\n```python\nfor r in range(1, 4):\n    for s in range(1, __1__):\n        print(f"{r}-{s}", end=" ")\n    print()\n```', '5'),
    fb('找零錢組合枚舉：用 10 元与 5 元湊 35 元的組合數。\n\n```python\ncount = 0\nfor a in range(4):\n    for b in range(8):\n        if a * 10 + b * 5 == 35:\n            count += __1__\nprint(count)   # 4\n```', '1',
       explanation='(a,b) = (0,7)、(1,5)、(2,3)、(3,1)。'),
    fb('溫室資料：連續兩天升溫的次數。\n\n```python\ntemps = [20, 22, 21, 25, 27]\ncount = 0\nfor i in range(1, 5):\n    if temps[i] > temps[i - __1__]:\n        count += 1\nprint(count)   # 3\n```', '1'),
    fb('數列變號：正變負、負變正後加總。\n\n```python\ntotal = 0\nfor n in [3, -5, 2]:\n    total += -n\nprint(total)   # __1__\n```\n\n（填輸出）', '0'),
    fb('模擬影印店計價表：印 1~5 張各需多少（每張 3 元，第 3 張起每張 2 元）。\n\n```python\nfor pages in range(1, 6):\n    if pages <= 2:\n        cost = pages * 3\n    else:\n        cost = 6 + (pages - 2) * __1__\n    print(pages, cost)\n```', '2'),
    fb('骰子點數出現表：統計列表中各點數出現次數（印 1~6）。\n\n```python\nrolls = [1, 3, 3, 6, 1, 3]\nfor face in range(1, 7):\n    c = 0\n    for r in rolls:\n        if r == face:\n            c += 1\n    print(face, __1__)\n```', 'c'),
    fb('迴圈驗證乘法交換律：檢查 i*j == j*i 是否全部成立。\n\n```python\nok = True\nfor i in range(1, 5):\n    for j in range(1, 5):\n        if i * j != j * i:\n            ok = __1__\nprint(ok)   # True\n```', 'False'),
    fb('金字塔總星數：n=4 的金字塔（1+3+5+7）。\n\n```python\ntotal = 0\nfor i in range(1, 5):\n    total += 2 * i - 1\nprint(total)   # __1__\n```\n\n（填輸出）', '16'),
    fb('紙張對折超過 101 公尺需幾次（初始 0.0001 公尺，每折厚度加倍）。\n\n```python\nthick = 0.0001\ncount = 0\nwhile thick <= 101:\n    thick *= 2\n    count += __1__\nprint(count)   # 20\n```', '1',
       explanation='0.0001×2²⁰ ≈ 104.9 公尺，第 20 次對折後超過 101。'),
    fb('全字母組合：兩位密碼（A~C）共幾組。\n\n```python\ncount = 0\nfor a in "ABC":\n    for b in "ABC":\n        count += 1\nprint(count)   # __1__\n```\n\n（填輸出）', '9'),
    fb('第 n 個三角形數的公式驗證：迴圈與公式相等。\n\n```python\nn = 7\ntotal = 0\nfor i in range(1, n + 1):\n    total += i\nprint(total == n * (n + 1) // __1__)   # True\n```', '2'),
    fb('尋找矩陣中的目標值位置。\n\n```python\ngrid = [[4, 7], [9, 2]]\nfor i in range(2):\n    for j in range(2):\n        if grid[i][j] == 9:\n            print(i, __1__)   # 1 0\n```', 'j'),
    fb('印出斜線圖案（3×3，i+j==2 印星）。\n\n```python\nfor i in range(3):\n    line = ""\n    for j in range(3):\n        line += "*" if i + j == __1__ else "."\n    print(line)\n```', '2'),
    fb('列印購物明細與總計。\n\n```python\nprices = [30, 45, 25]\ntotal = 0\nfor p in prices:\n    print("品項", p, "元")\n    total += p\nprint("總計", __1__, "元")\n```', 'total'),
    fb('驗證 1+3+5+…+(2n-1) = n²（n=5）。\n\n```python\nn = 5\ntotal = 0\nfor i in range(1, 2 * n, 2):\n    total += i\nprint(total == n ** __1__)   # True\n```', '2'),
    fb('印出乾電池串聯電壓表：1~4 顆電池（每顆 1.5V）。\n\n```python\nfor n in range(1, 5):\n    print(n, "顆 =", n * __1__, "V")\n```', '1.5'),
    fb('雙層迴圈印年曆月份標頭：第 1~2 季各三個月。\n\n```python\nfor q in range(1, 3):\n    for m in range(1, 4):\n        month = (q - 1) * 3 + m\n        print(month, "月", end=" ")\n    __1__()\n```', 'print'),
]
