"""Unit 6（串列與字串實戰題庫）題庫 — 全選擇制。

L1 對標 ITS（資料流程、過濾統計樣板）、
L2 對標 TQC+ 觀念題（綜合管線追蹤、母音/回文/去重）、
L3 對標競賽／TQC 實作（收錄競賽第 2、7、16、17、19 題）。
"""
from .question_helpers import mc, fb

# ── U6 Level 1：55 選擇 + 45 填空 ──
U6_L1 = [
    # 資料流程觀念（12）
    mc('「原始文字 → 清理切割 → 串列 → 統計 → 輸出」描述的是？', '資料處理流程',
       '遞迴呼叫', '排序演算法', '網路連線'),
    mc('把 "80 65 92" 變成數字串列的第一步是？', '用 split() 切割', '直接 int()',
       '用 join() 合併', '排序'),
    mc('「過濾」資料（挑出及格分數）的基本樣板是？', '迴圈＋if＋append 到新串列',
       '直接 print', '排序後取一半', '用 pop 刪除'),
    mc('統計及格人數，應該對「過濾後的串列」做什麼？', '取 len()', '取 sum()',
       '取 max()', '再排序'),
    mc('sum([10, 20, 30]) 的結果是？', '60', '30', '3', '[60]'),
    mc('max([3, 9, 5]) 的結果是？', '9', '3', '5', '17'),
    mc('min([3, 9, 5]) 的結果是？', '3', '9', '5', '1'),
    mc('計算平均分數的公式是？', 'sum(scores) / len(scores)', 'max(scores) / 2',
       'len(scores) / sum(scores)', 'sum(scores) * len(scores)'),
    mc('判斷回文（正反讀相同）最簡潔的比較是？', 'text == text[::-1]', 'text == text.upper()',
       'len(text) % 2 == 0', 'text.find(text)'),
    mc('回文判斷前先 replace(" ", "") 的目的是？', '忽略空格的影響', '刪除所有字母',
       '轉成大寫', '增加長度'),
    mc('找出「兩個串列共同元素」的基本做法是？', '走訪其中一個，用 in 檢查另一個',
       '直接相加', '排序後相減', '用 join 合併'),
    mc('把清理後的資料存進新串列而不是覆蓋原串列，好處是？', '保留原始資料可供對照',
       '執行較快', '省記憶體', '不需要迴圈'),

    # 過濾統計追蹤（30）
    mc('以下程式的輸出是？\n\n```python\nscores = [80, 65, 92, 58, 77]\npassed = []\nfor s in scores:\n    if s >= 60:\n        passed.append(s)\nprint(len(passed))\n```', '4', '5', '3', '1',
       explanation='58 以外都及格。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, 2, 3, 4, 5, 6]\nevens = []\nfor n in nums:\n    if n % 2 == 0:\n        evens.append(n)\nprint(evens)\n```', '[2, 4, 6]', '[1, 3, 5]', '[2, 4]', '6'),
    mc('以下程式的輸出是？\n\n```python\ntext = "level"\nprint(text == text[::-1])\n```', 'True', 'False', 'level', 'lev'),
    mc('以下程式的輸出是？\n\n```python\ntext = "Python"\nprint(text == text[::-1])\n```', 'False', 'True', 'nohtyP', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nscores = [70, 80, 90]\nprint(sum(scores) / len(scores))\n```', '80.0', '80', '240', '3'),
    mc('以下程式的輸出是？\n\n```python\nwords = ["cat", "dog", "cat"]\ncount = 0\nfor w in words:\n    if w == "cat":\n        count += 1\nprint(count)\n```', '2', '1', '3', 'cat'),
    mc('以下程式的輸出是？\n\n```python\na = [1, 2, 3]\nb = [2, 3, 4]\ncommon = []\nfor x in a:\n    if x in b:\n        common.append(x)\nprint(common)\n```', '[2, 3]', '[1, 4]', '[1, 2, 3, 4]', '[2]'),
    mc('以下程式的輸出是？\n\n```python\ntext = "  hello  "\ncleaned = text.strip()\nprint(len(cleaned))\n```', '5', '9', '7', '0'),
    mc('以下程式的輸出是？\n\n```python\nraw = "5 10 15"\nnums = raw.split()\nprint(len(nums))\n```', '3', '7', '5', '30'),
    mc('以下程式的輸出是？\n\n```python\nnums = [int(x) for x in "5 10 15".split()]\nprint(sum(nums))\n```', '30', '51015', '3', '15'),
    mc('以下程式的輸出是？\n\n```python\ntext = "banana"\ncount = 0\nfor ch in text:\n    if ch == "a":\n        count += 1\nprint(count)\n```', '3', '2', '6', '1'),
    mc('以下程式的輸出是？\n\n```python\nscores = [55, 88, 62, 40]\nfailed = [s for s in scores if s < 60]\nprint(failed)\n```', '[55, 40]', '[88, 62]', '[40]', '2'),
    mc('以下程式的輸出是？\n\n```python\ntext = "A B A"\nparts = text.split()\nprint(parts.count("A"))\n```', '2', '1', '3', 'A'),
    mc('以下程式的輸出是？\n\n```python\nnames = [" amy ", " bob "]\ncleaned = [n.strip() for n in names]\nprint(cleaned[0])\n```', 'amy', ' amy ', 'bob', 'Amy'),
    mc('以下程式的輸出是？\n\n```python\nnums = [8, 2, 9, 4]\nprint(max(nums) + min(nums))\n```', '11', '17', '23', '13'),
    mc('以下程式的輸出是？\n\n```python\ntext = "abc"\nreversed_text = text[::-1]\nprint(reversed_text)\n```', 'cba', 'abc', 'bca', 'c'),
    mc('以下程式的輸出是？\n\n```python\ndata = "3,1,2"\nnums = [int(x) for x in data.split(",")]\nnums.sort()\nprint(nums)\n```', '[1, 2, 3]', '[3, 1, 2]', "['1', '2', '3']", '6'),
    mc('以下程式的輸出是？\n\n```python\nvotes = ["同意", "反對", "同意"]\nprint(votes.count("同意") > votes.count("反對"))\n```', 'True', 'False', '2', '1'),
    mc('以下程式的輸出是？\n\n```python\nnums = [5, 3, 8]\ntotal = 0\nfor n in nums:\n    total += n\nprint(total == sum(nums))\n```', 'True', 'False', '16', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nsentence = "i am happy"\nwords = sentence.split()\nlongest = words[0]\nfor w in words:\n    if len(w) > len(longest):\n        longest = w\nprint(longest)\n```', 'happy', 'i', 'am', '5'),
    mc('以下程式的輸出是？\n\n```python\ntext = "Hello World"\nprint(text.lower().count("o"))\n```', '2', '1', '0', '3'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, 2, 2, 3]\nunique = []\nfor n in nums:\n    if n not in unique:\n        unique.append(n)\nprint(unique)\n```', '[1, 2, 3]', '[1, 2, 2, 3]', '[2]', '[1, 3]'),
    mc('以下程式的輸出是？\n\n```python\nscores = [90, 45, 70]\nresult = []\nfor s in scores:\n    if s >= 60:\n        result.append("過")\n    else:\n        result.append("不過")\nprint(result)\n```', "['過', '不過', '過']", "['過', '過', '過']", "['不過']", '2'),
    mc('以下程式的輸出是？\n\n```python\ntext = "2024-07-06"\nparts = text.split("-")\nprint(parts[1] + parts[2])\n```', '0706', '13', '202407', '07-06'),
    mc('以下程式的輸出是？\n\n```python\nprices = [120, 80, 200]\ncheap = [p for p in prices if p < 100]\nprint(len(cheap), sum(cheap))\n```', '1 80', '2 200', '1 120', '3 400'),
    mc('以下程式的輸出是？\n\n```python\nletters = ["b", "a", "c"]\nprint(sorted(letters)[0])\n```', 'a', 'b', 'c', '[a, b, c]'),
    mc('以下程式的輸出是？\n\n```python\ntext = "aabb"\nhalf = len(text) // 2\nprint(text[:half] == text[half:])\n```', 'False', 'True', 'aa', 'bb',
       explanation='"aa" 與 "bb" 不同。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [10, 20, 30]\ndoubled = [n * 2 for n in nums]\nprint(sum(doubled))\n```', '120', '60', '[20, 40, 60]', '6'),
    mc('以下程式的輸出是？\n\n```python\nmoney = "NT$1200"\namount = int(money[3:])\nprint(amount * 2)\n```', '2400', '1200', 'NT$2400', '發生錯誤',
       explanation='切掉前三個字元 NT$。'),
    mc('以下程式的輸出是？\n\n```python\nitems = ["蛋:30", "奶:55"]\ntotal = 0\nfor item in items:\n    total += int(item.split(":")[1])\nprint(total)\n```', '85', '30', '55', '3055'),

    # 觀念（13）
    mc('replace(" ", "") 與 strip() 的差別是？', 'replace 移除「所有」空格、strip 只移除兩端',
       '完全相同', 'strip 移除所有空格', 'replace 只移除兩端'),
    mc('統計字串中的英文字母，判斷條件可用？', '"a" <= ch.lower() <= "z"', 'ch > 0',
       'ch == "abc"', 'len(ch) > 1'),
    mc('把名單「去除空白、統一小寫、排序」的正確順序是？',
       '逐一清理 → 全部收集 → 排序', '先排序再清理', '排序兩次', '順序不重要但要用遞迴'),
    mc('兩串列共同元素「不可重複」，收集時要加什麼檢查？',
       '同時檢查 in b 與 not in 結果串列', '只檢查 in b', '不需檢查', '檢查長度'),
    mc('二維成績 [[80, 90], [70, 60]] 中，每個內層串列代表？', '一位學生的多科成績',
       '一科的名稱', '總分', '座號'),
    mc('哪個內建函式「不能」直接用在數字串列上？', 'split()', 'sum()', 'max()', 'len()',
       explanation='split 是字串方法。'),
    mc('過濾後的串列可能是空的，計算平均前應該？', '先檢查 len() 是否為 0',
       '直接除', '補一個 0', '改用 max'),
    mc('「搜尋第一筆符合資料後停止」要搭配？', 'break', 'continue', 'sort', 'join'),
    mc('列表生成式 [s for s in scores if s >= 60] 等價於？',
       '迴圈＋if＋append 的過濾樣板', '排序', '刪除原串列', '加總'),
    mc('資料分組（及格一組、不及格一組）需要幾個收集串列？', '2 個', '1 個', '3 個', '0 個'),
    mc('要輸出「平均：85.5」保留一位小數，f-string 寫法是？', 'f"平均：{avg:.1f}"',
       'f"平均：{avg:1}"', 'f"平均：avg"', 'f"平均：{avg:d}"'),
    mc('先 strip() 再 split(",") 與先 split(",") 再對每段 strip()，處理 " a , b " 時結果？',
       '後者才能把每段的空白清乾淨', '前者比較乾淨', '兩者完全相同', '都會報錯'),
    mc('反轉字串用切片 [::-1] 的原理是？', '步長 -1 由尾到頭取字元', '刪除第一個字元',
       '排序', '轉大寫'),

    # ── L1 填空（45）──
    fb('過濾出及格成績。\n\n```python\nscores = [80, 55, 92]\npassed = []\nfor s in scores:\n    if s >= 60:\n        passed.__1__(s)\nprint(passed)   # [80, 92]\n```', 'append'),
    fb('統計及格人數。\n\n```python\npassed = [80, 92, 75]\nprint(__1__(passed))   # 3\n```', 'len'),
    fb('計算總分。\n\n```python\nscores = [70, 80, 90]\nprint(__1__(scores))   # 240\n```', 'sum'),
    fb('找出最高分。\n\n```python\nscores = [70, 95, 80]\nprint(__1__(scores))   # 95\n```', 'max'),
    fb('找出最低分。\n\n```python\nscores = [70, 95, 80]\nprint(__1__(scores))   # 70\n```', 'min'),
    fb('回文判斷。\n\n```python\ntext = "noon"\nprint(text == text[::__1__])   # True\n```', '-1'),
    fb('去掉空格再判斷回文。\n\n```python\ntext = "a b a"\ncleaned = text.__1__(" ", "")\nprint(cleaned == cleaned[::-1])   # True\n```', 'replace'),
    fb('把空格分隔的成績轉成整數串列。\n\n```python\nraw = "80 65 92"\nscores = [__1__(v) for v in raw.split()]\nprint(scores)   # [80, 65, 92]\n```', 'int'),
    fb('找出所有偶數。\n\n```python\nnums = [1, 2, 3, 4]\nevens = [n for n in nums if n % 2 == __1__]\nprint(evens)   # [2, 4]\n```', '0'),
    fb('計算平均。\n\n```python\nscores = [80, 90]\navg = sum(scores) / __1__(scores)\nprint(avg)   # 85.0\n```', 'len'),
    fb('統計 "e" 出現次數。\n\n```python\ntext = "excellent"\nprint(text.__1__("e"))   # 3\n```', 'count'),
    fb('找兩串列共同元素。\n\n```python\na = [1, 2, 3]\nb = [2, 3, 4]\ncommon = [x for x in a if x __1__ b]\nprint(common)   # [2, 3]\n```', 'in'),
    fb('把名字清單去空白。\n\n```python\nnames = [" amy ", " bob "]\ncleaned = [n.__1__() for n in names]\nprint(cleaned)   # [\'amy\', \'bob\']\n```', 'strip'),
    fb('排序名單。\n\n```python\nnames = ["bob", "amy"]\nnames.__1__()\nprint(names)   # [\'amy\', \'bob\']\n```', 'sort'),
    fb('平均輸出保留一位小數。\n\n```python\navg = 85.678\nprint(f"平均：{avg:.__1__f}")   # 平均：85.7\n```', '1'),
    fb('統計不及格人數。\n\n```python\nscores = [55, 88, 40]\nfailed = [s for s in scores if s __1__ 60]\nprint(len(failed))   # 2\n```', '<'),
    fb('把大小寫統一再比較。\n\n```python\nans = "YES"\nprint(ans.__1__() == "yes")   # True\n```', 'lower'),
    fb('把逗號分隔名字排序輸出。\n\n```python\nraw = "bob,amy,cid"\nnames = raw.split(",")\nnames.sort()\nprint(names[__1__])   # amy\n```', '0'),
    fb('去除重複元素（保持順序）。\n\n```python\nnums = [1, 2, 2, 3]\nunique = []\nfor n in nums:\n    if n __1__ unique:\n        unique.append(n)\nprint(unique)   # [1, 2, 3]\n```', 'not in'),
    fb('把每個字轉大寫收集。\n\n```python\nwords = ["hi", "yo"]\nupper_words = [w.__1__() for w in words]\nprint(upper_words)   # [\'HI\', \'YO\']\n```', 'upper'),
    fb('統計字母 a~z 出現的總數（英文字母數）。\n\n```python\ntext = "ab1c!"\ncount = 0\nfor ch in text:\n    if "a" <= ch <= __1__:\n        count += 1\nprint(count)   # 3\n```', ['"z"', "'z'"]),
    fb('把分數轉及格標記。\n\n```python\nscores = [80, 50]\nmarks = ["O" if s >= 60 else "X" for s in scores]\nprint(marks)   # [\'O\', __1__]\n```\n\n（填印出的第二個標記，含引號）', ["'X'", '"X"']),
    fb('二維成績：取第一位學生的平均。\n\n```python\ngrades = [[80, 90], [70, 60]]\nfirst = grades[__1__]\nprint(sum(first) / len(first))   # 85.0\n```', '0'),
    fb('反轉名單。\n\n```python\nnames = ["A", "B", "C"]\nnames.__1__()\nprint(names)   # [\'C\', \'B\', \'A\']\n```', 'reverse'),
    fb('把句子每個單字長度列出。\n\n```python\nsentence = "I love py"\nlengths = [__1__(w) for w in sentence.split()]\nprint(lengths)   # [1, 4, 2]\n```', 'len'),
    fb('選出價格低於 100 的商品數。\n\n```python\nprices = [50, 120, 80]\ncheap = [p for p in prices if p < __1__]\nprint(len(cheap))   # 2\n```', '100'),
    fb('把姓名接成通知名單。\n\n```python\nnames = ["Amy", "Bob"]\nprint("、".__1__(names) + " 請到辦公室")   # Amy、Bob 請到辦公室\n```', 'join'),
    fb('數出句子有幾個字（以空格分）。\n\n```python\nsentence = "today is a good day"\nprint(len(sentence.__1__()))   # 5\n```', 'split'),
    fb('找出第一個不及格分數就停止。\n\n```python\nscores = [80, 55, 90]\nfor s in scores:\n    if s < 60:\n        print(s)   # 55\n        __1__\n```', 'break'),
    fb('把電話清單掉頭尾空白後找人。\n\n```python\nphones = [" 0912 ", " 0987 "]\ncleaned = [p.strip() for p in phones]\nprint("0987" __1__ cleaned)   # True\n```', 'in'),
    fb('及格與不及格分兩組。\n\n```python\nscores = [80, 50, 90]\ngood = []\nbad = []\nfor s in scores:\n    if s >= 60:\n        good.append(s)\n    else:\n        bad.__1__(s)\nprint(good, bad)   # [80, 90] [50]\n```', 'append'),
    fb('計算全班總分（二維攤平加總）。\n\n```python\ngrades = [[80, 90], [70, 60]]\ntotal = 0\nfor row in grades:\n    total += __1__(row)\nprint(total)   # 300\n```', 'sum'),
    fb('把混入的空字串過濾掉。\n\n```python\ndata = ["a", "", "b"]\nvalid = [d for d in data if d != __1__]\nprint(valid)   # [\'a\', \'b\']\n```', ['""', "''"]),
    fb('統計母音個數。\n\n```python\ntext = "apple"\ncount = 0\nfor ch in text:\n    if ch in "aeiou":\n        count += __1__\nprint(count)   # 2\n```', '1'),
    fb('取出最高分與最低分的差距。\n\n```python\nscores = [60, 95, 72]\nprint(max(scores) __1__ min(scores))   # 35\n```', '-'),
    fb('把逗號資料轉數字後找最大。\n\n```python\nraw = "35,78,52"\nnums = [int(x) for x in raw.split(",")]\nprint(__1__(nums))   # 78\n```', 'max'),
    fb('把每筆金額打八折。\n\n```python\nprices = [100, 250]\nsale = [p * __1__ for p in prices]\nprint(sale)   # [80.0, 200.0]\n```', '0.8'),
    fb('確認清單中沒有負數。\n\n```python\nnums = [3, 7, 2]\nok = True\nfor n in nums:\n    if n < 0:\n        ok = __1__\nprint(ok)   # True\n```', 'False'),
    fb('把單字第一次出現位置印出。\n\n```python\nsentence = "we love python"\nprint(sentence.__1__("love"))   # 3\n```', 'find'),
    fb('計算購物車數量與總價。\n\n```python\ncart = [60, 40, 100]\nprint(len(cart), __1__(cart))   # 3 200\n```', 'sum'),
    fb('把二維名單攤平。\n\n```python\ngroups = [["A"], ["B", "C"]]\nflat = []\nfor g in groups:\n    for name in g:\n        flat.append(__1__)\nprint(flat)   # [\'A\', \'B\', \'C\']\n```', 'name'),
    fb('留下長度大於 2 的單字。\n\n```python\nwords = ["hi", "cat", "a"]\nlong_words = [w for w in words if len(w) __1__ 2]\nprint(long_words)   # [\'cat\']\n```', '>'),
    fb('把成績由高到低排序取前兩名。\n\n```python\nscores = [70, 95, 80]\nscores.sort(reverse=__1__)\nprint(scores[:2])   # [95, 80]\n```', 'True'),
    fb('轉換溫度清單（攝氏轉華氏）。\n\n```python\ncelsius = [0, 100]\nfahrenheit = [c * 9 / 5 + __1__ for c in celsius]\nprint(fahrenheit)   # [32.0, 212.0]\n```', '32'),
    fb('把答案卷比對正解算得分。\n\n```python\nanswers = ["A", "B", "C"]\nkeys = ["A", "C", "C"]\nscore = 0\nfor i in range(3):\n    if answers[i] __1__ keys[i]:\n        score += 1\nprint(score)   # 2\n```', '=='),
]


# ── U6 Level 2：60 選擇 + 40 填空（TQC+ 觀念題：綜合管線追蹤）──
U6_L2 = [
    # 管線追蹤（32）
    mc('以下程式輸入 "80 65 92" 時的輸出是？\n\n```python\nraw = input()\nscores = [int(v) for v in raw.split()]\npassed = [s for s in scores if s >= 60]\nprint(len(passed), max(scores))\n```', '2 92', '3 92', '2 80', '3 65'),
    mc('以下程式的輸出是？\n\n```python\ntext = "Aba"\ncleaned = text.lower()\nprint(cleaned == cleaned[::-1])\n```', 'True', 'False', 'aba', '發生錯誤',
       explanation='轉小寫後 aba 是回文。'),
    mc('以下程式的輸出是？\n\n```python\nsentence = "good morning"\nvowels = 0\nfor ch in sentence:\n    if ch in "aeiou":\n        vowels += 1\nprint(vowels)\n```', '4', '5', '3', '2',
       explanation='o、o、o、i 共 4 個母音。'),
    mc('以下程式的輸出是？\n\n```python\na = [1, 2, 2, 3]\nb = [2, 3, 5]\ncommon = []\nfor x in a:\n    if x in b and x not in common:\n        common.append(x)\nprint(common)\n```', '[2, 3]', '[2, 2, 3]', '[1, 5]', '[2]',
       explanation='共同元素且去重。'),
    mc('以下程式的輸出是？\n\n```python\ngrades = [[80, 90], [60, 70]]\nfor row in grades:\n    print(sum(row) / len(row), end=" ")\n```', '85.0 65.0', '75.0 75.0', '170 130', '85 65'),
    mc('以下程式的輸出是？\n\n```python\nnums = [5, 3, 8, 1]\nfor i in range(3):\n    if nums[i] > nums[i + 1]:\n        nums[i], nums[i + 1] = nums[i + 1], nums[i]\nprint(nums)\n```', '[3, 5, 1, 8]', '[1, 3, 5, 8]', '[5, 3, 8, 1]', '[8, 5, 3, 1]',
       explanation='氣泡排序單輪：最大值 8 沉到最後。'),
    mc('氣泡排序一輪結束後可以保證什麼？', '最大值移到最後面', '完全排序完成',
       '最小值在最前面', '沒有任何改變'),
    mc('以下程式的輸出是？\n\n```python\nraw = " Amy, bob ,CID "\nnames = [n.strip().lower() for n in raw.split(",")]\nprint(names)\n```', "['amy', 'bob', 'cid']", "['Amy', 'bob', 'CID']", "['amy', 'bob']", '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndata = "77,45,92,60"\nnums = [int(x) for x in data.split(",")]\nprint(sum(nums) // len(nums))\n```', '68', '68.5', '274', '60',
       explanation='274 // 4 = 68。'),
    mc('以下程式的輸出是？\n\n```python\nwords = "to be or not to be".split()\nunique = []\nfor w in words:\n    if w not in unique:\n        unique.append(w)\nprint(len(unique))\n```', '4', '6', '5', '2',
       explanation='to、be、or、not。'),
    mc('以下程式的輸出是？\n\n```python\nscores = [88, 92, 79, 65]\nabove = 0\navg = sum(scores) / len(scores)\nfor s in scores:\n    if s > avg:\n        above += 1\nprint(above)\n```', '2', '3', '1', '4',
       explanation='平均 81，高於平均的是 88、92。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "abcabcabc"\nprint(text.count("abc"), len(text) // 3)\n```', '3 3', '3 9', '9 3', '1 3'),
    mc('以下程式的輸出是？\n\n```python\nnums = [4, 1, 7, 3]\nsmallest = nums[0]\npos = 0\nfor i in range(len(nums)):\n    if nums[i] < smallest:\n        smallest = nums[i]\n        pos = i\nprint(pos, smallest)\n```', '1 1', '0 4', '2 7', '3 3'),
    mc('以下程式的輸出是？\n\n```python\nline = "A:90 B:85"\ntotal = 0\nfor pair in line.split():\n    total += int(pair.split(":")[1])\nprint(total)\n```', '175', '90', '85', '9085'),
    mc('以下程式的輸出是？\n\n```python\ntext = "Madam"\ncleaned = text.lower()\nresult = "是" if cleaned == cleaned[::-1] else "否"\nprint(result)\n```', '是', '否', 'madam', 'True'),
    mc('以下程式的輸出是？\n\n```python\nnums = [2, 4, 6, 8]\nodd_pos = [nums[i] for i in range(len(nums)) if i % 2 == 1]\nprint(odd_pos)\n```', '[4, 8]', '[2, 6]', '[4, 6]', '[2, 4, 6, 8]',
       explanation='取「奇數索引」的元素。'),
    mc('以下程式的輸出是？\n\n```python\nsentence = "the cat sat"\nresult = ""\nfor w in sentence.split():\n    result += w[0]\nprint(result)\n```', 'tcs', 'the', 'tca', 'cat'),
    mc('以下程式的輸出是？\n\n```python\nscores = [50, 80, 30, 95]\nranked = sorted(scores, reverse=True)\nprint(ranked.index(80))\n```', '1', '2', '0', '3',
       explanation='排序後 [95, 80, 50, 30]，80 在索引 1。'),
    mc('以下程式的輸出是？\n\n```python\ndata = ["7", "x", "3"]\ntotal = 0\nfor d in data:\n    if d.isdigit():\n        total += int(d)\nprint(total)\n```', '10', '7', '3', '發生錯誤',
       explanation='isdigit 過濾非數字。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [3, 6, 9]\nresult = [n // 3 for n in nums]\nprint(result)\n```', '[1, 2, 3]', '[3, 6, 9]', '[9, 18, 27]', '[0, 0, 0]'),
    mc('以下程式的輸出是？\n\n```python\nvotes = "AABAB"\nprint(votes.count("A") - votes.count("B"))\n```', '1', '2', '3', '0'),
    mc('以下程式的輸出是？\n\n```python\nheights = [158, 172, 165]\ntallest = heights.index(max(heights))\nprint(tallest)\n```', '1', '172', '0', '2',
       explanation='index 回傳最大值的位置。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "a1b2c3"\nletters = ""\ndigits = ""\nfor ch in text:\n    if ch.isdigit():\n        digits += ch\n    else:\n        letters += ch\nprint(letters, digits)\n```', 'abc 123', '123 abc', 'a1b2c3', 'abc'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, 2, 3, 4, 5]\nprint(sum(nums[1:4]))\n```', '9', '15', '6', '12',
       explanation='2+3+4。'),
    mc('以下程式的輸出是？\n\n```python\nrecords = ["Amy,80", "Bob,95", "Cid,70"]\nbest = ""\nbest_s = 0\nfor r in records:\n    name, s = r.split(",")\n    if int(s) > best_s:\n        best_s = int(s)\n        best = name\nprint(best)\n```', 'Bob', 'Amy', 'Cid', '95'),
    mc('以下程式的輸出是？\n\n```python\nnums = [10, 25, 8, 31]\ncount = 0\nfor n in nums:\n    if n % 2 == 1:\n        count += 1\nprint(f"{count}/{len(nums)}")\n```', '2/4', '4/2', '2/2', '1/4'),
    mc('以下程式的輸出是？\n\n```python\ntext = "banana"\npositions = [i for i in range(len(text)) if text[i] == "a"]\nprint(positions)\n```', '[1, 3, 5]', '[0, 2, 4]', '[1, 3]', '3'),
    mc('以下程式的輸出是？\n\n```python\nlst = ["b", "a"] * 2\nlst.sort()\nprint("".join(lst))\n```', 'aabb', 'baba', 'abab', 'bbaa'),
    mc('以下程式的輸出是？\n\n```python\nscores = [72, 88, 95]\nlabels = []\nfor s in scores:\n    labels.append("高" if s >= 85 else "普")\nprint("".join(labels))\n```', '普高高', '高高普', '普普高', '高普普'),
    mc('以下程式的輸出是？\n\n```python\nphone = "0912-345-678"\ndigits = phone.replace("-", "")\nprint(len(digits))\n```', '10', '12', '9', '11'),
    mc('以下程式的輸出是？\n\n```python\nwords = ["apple", "fig", "banana"]\nshortest = words[0]\nfor w in words:\n    if len(w) < len(shortest):\n        shortest = w\nprint(shortest)\n```', 'fig', 'apple', 'banana', '3'),
    mc('以下程式的輸出是？\n\n```python\nnums = [6, 2, 9]\ntotal = 0\nfor i, v in enumerate(nums):\n    total += i * v\nprint(total)\n```', '20', '17', '18', '11',
       explanation='0×6+1×2+2×9=20。'),

    # 觀念（28）
    mc('資料處理管線「驗證 → 解析 → 轉換 → 輸出」中，int(x) 屬於哪一步？',
       '解析（轉成結構化資料）', '驗證', '輸出', '排序'),
    mc('過濾與轉換同時做，生成式寫法是？', '[f(x) for x in data if 條件]',
       '[if 條件 for x]', 'filter+map 必須分開', 'sort(key=...)'),
    mc('統計各母音出現次數（5 個母音），簡單做法是？', '對每個母音各用一次 count()',
       '排序後數', '只能用字典', 'len() 除以 5'),
    mc('忽略大小寫的回文判斷，正確的前處理是？', '先 lower() 再比較反轉',
       '先反轉再 lower()（結果不同）', '不需處理', 'upper 後長度會變'),
    mc('兩個串列的共同元素「不可重複」，重複可能來自哪裡？', '第一個串列本身有重複元素',
       'in 運算子', 'append', '排序'),
    mc('把「二維成績轉每人平均」的輸出型態應該是？', '一維串列（每人一個平均值）',
       '二維串列', '單一數字', '字串'),
    mc('氣泡排序完整排好 n 筆資料，大約需要幾輪？', 'n-1 輪', '1 輪', 'n² 輪', 'log n 輪'),
    mc('isdigit() 的作用是？', '判斷字串是否全為數字字元', '轉成數字',
       '刪除數字', '計算位數'),
    mc('資料驗證「拒絕超出 0–100 的成績」應該在哪一步做？', '解析後、統計前',
       '輸出後', '不需要', '排序中'),
    mc('index() 與 find() 的差別是？', 'index 找不到會報錯、find 回傳 -1（且 find 僅字串可用）',
       '完全相同', 'index 回傳 -1', 'find 會排序'),
    mc('要找「出現次數最多的字元」，基本結構是？', '對候選字元逐一 count 並記錄最大',
       '排序即可', '取第一個字元', 'len 除以 2'),
    mc('清理使用者輸入時，最先處理的通常是？', '去除頭尾空白（strip）', '排序',
       '轉浮點數', '加密'),
    mc('生成式中可以同時對兩個串列配對處理，搭配什麼函式？', 'zip()', 'sort()',
       'count()', 'strip()'),
    mc('為何統計前常把文字全部轉小寫？', '讓 "Apple" 與 "apple" 視為同一字',
       '節省記憶體', '執行較快', '避免報錯'),
    mc('「找出兩份名單只出現在其中一份的人」的邏輯是？',
       'in 其中一份且 not in 另一份', '兩份都 in', '兩份都 not in', '排序後相加'),
    mc('計算「加權平均」（各科學分不同）需要哪些資料？', '分數串列與對應權重串列',
       '只要分數', '只要權重', '排序後的分數'),
    mc('資料含 "N/A" 這種無效值，加總前應該？', '先過濾或跳過無效值', '直接 int()',
       '把它當 0 不用管來源', '排序'),
    mc('對已排序串列找中位數（奇數筆）的位置是？', 'len(nums) // 2', '0', 'len(nums)',
       'len(nums) - 1'),
    mc('把長字串每 n 個字元切一段，使用哪種迴圈設計？', 'range(0, len(s), n) 搭配切片',
       'for ch in s', 'while True', 'split(n)'),
    mc('「先分組再各自統計」的輸出範例是？', '及格 3 人平均 80、不及格 2 人平均 50',
       '全班平均 70', '最高分 95', '排序後的名單'),
    mc('比較兩字串「內容相同但順序不同」（如變位詞 anagram），可行做法是？',
       '各自排序字元後比較', '直接 ==', '比較長度即可', 'find 檢查'),
    mc('資料筆數很多時，用生成式代替迴圈 append 的主要好處是？', '程式碼更精簡易讀',
       '結果不同', '不用記憶體', '自動去重'),
    mc('統計「各分數區間人數」（0-59、60-79、80-100）需要？', '多個計數器或條件分支',
       '一個計數器', '排序兩次', 'join'),
    mc('把統計結果輸出成「項目：數量」格式，適合用？', 'f-string 逐行輸出', 'sort',
       'split', 'pop'),
    mc('何時適合把處理步驟拆成多個中間串列？', '步驟多且需要檢查中間結果時',
       '永遠不要', '資料少於 3 筆', '只有輸出時'),
    mc('大量重複的 in 檢查（名單比對）效率較好的改法是？（概念）',
       '先把被查名單轉成不重複集合再查', '多排序幾次', '改用字串相加', '用 print 檢查'),
    mc('「兩人成績單合併後找最高分」需要的步驟是？', '串列相加後取 max',
       '各取 max 相加', '只看第一份', 'join 後排序'),
    mc('程式輸出與預期不符時，管線除錯的好方法是？', '逐步印出每個中間串列',
       '重寫全部', '刪掉 if', '改用 while'),

    # ── L2 填空（40）──
    fb('綜合成績分析：切割→轉型→過濾。\n\n```python\nraw = "80 45 92 60"\nscores = [int(v) for v in raw.__1__()]\npassed = [s for s in scores if s >= 60]\nprint(len(passed))   # 3\n```', 'split'),
    fb('平均保留一位小數輸出。\n\n```python\nscores = [82, 91, 76]\navg = sum(scores) / len(scores)\nprint(f"{avg:.1__1__}")   # 83.0\n```', 'f'),
    fb('母音統計。\n\n```python\ntext = "education"\ncount = 0\nfor ch in text:\n    if ch __1__ "aeiou":\n        count += 1\nprint(count)   # 5\n```', 'in'),
    fb('忽略空白與大小寫的回文判斷。\n\n```python\ntext = "Was saw"\ncleaned = text.replace(" ", "").__1__()\nprint(cleaned == cleaned[::-1])   # True\n```', 'lower'),
    fb('名單正規化：去空白＋小寫＋排序。\n\n```python\nraw = " Bob , amy "\nnames = [n.strip().lower() for n in raw.split(",")]\nnames.__1__()\nprint(names)   # [\'amy\', \'bob\']\n```', 'sort'),
    fb('共同元素去重。\n\n```python\na = [1, 2, 2, 3]\nb = [2, 3]\ncommon = []\nfor x in a:\n    if x in b and x __1__ common:\n        common.append(x)\nprint(common)   # [2, 3]\n```', 'not in'),
    fb('二維成績轉每人平均。\n\n```python\ngrades = [[80, 90], [60, 70]]\naverages = [sum(row) / __1__(row) for row in grades]\nprint(averages)   # [85.0, 65.0]\n```', 'len'),
    fb('氣泡排序的交換。\n\n```python\nnums = [5, 2, 8, 1]\nfor r in range(3):\n    for i in range(3 - r):\n        if nums[i] > nums[i + 1]:\n            nums[i], nums[i + 1] = nums[i + 1], nums[__1__]\nprint(nums)   # [1, 2, 5, 8]\n```', 'i'),
    fb('各區間人數統計。\n\n```python\nscores = [45, 82, 65, 95]\nlow = mid = high = 0\nfor s in scores:\n    if s < 60:\n        low += 1\n    elif s < 80:\n        mid += 1\n    else:\n        high __1__ 1\nprint(low, mid, high)   # 1 1 2\n```', '+='),
    fb('加權平均：分數乘權重。\n\n```python\nscores = [80, 90]\nweights = [0.6, 0.4]\ntotal = 0\nfor s, w in zip(scores, weights):\n    total += s __1__ w\nprint(total)   # 84.0\n```', '*'),
    fb('變位詞判斷：排序字元後比較。\n\n```python\na = "listen"\nb = "silent"\nprint(__1__(a) == sorted(b))   # True\n```', 'sorted'),
    fb('過濾無效值再加總。\n\n```python\ndata = ["80", "N/A", "70"]\ntotal = 0\nfor d in data:\n    if d.__1__():\n        total += int(d)\nprint(total)   # 150\n```', 'isdigit'),
    fb('中位數（已排序、奇數筆）。\n\n```python\nnums = [3, 8, 12, 15, 20]\nprint(nums[len(nums) // __1__])   # 12\n```', '2'),
    fb('出現最多的字元。\n\n```python\ntext = "aabbbc"\nbest = ""\nfor ch in "abc":\n    if text.count(ch) > text.__1__(best):\n        best = ch\nprint(best)   # b\n```', 'count'),
    fb('只在 A 名單不在 B 名單的人。\n\n```python\na = ["Amy", "Bob", "Cid"]\nb = ["Bob"]\nonly_a = [x for x in a if x __1__ b]\nprint(only_a)   # [\'Amy\', \'Cid\']\n```', 'not in'),
    fb('統計字串中英文字母與數字的個數。\n\n```python\ntext = "ab12c"\nletters = sum(1 for ch in text if ch.isalpha())\ndigits = sum(1 for ch in text if ch.__1__())\nprint(letters, digits)   # 3 2\n```', 'isdigit'),
    fb('每三字元切段。\n\n```python\ncode = "abcdefgh"\nchunks = [code[i:i + 3] for i in range(0, len(code), __1__)]\nprint(chunks)   # [\'abc\', \'def\', \'gh\']\n```', '3'),
    fb('分數轉排名表（由高到低取名次）。\n\n```python\nscores = [70, 95, 88]\nordered = sorted(scores, reverse=True)\nrank = ordered.__1__(88) + 1\nprint(rank)   # 2\n```', 'index'),
    fb('刪除連續重複（壓縮）。\n\n```python\ndata = [1, 1, 2, 2, 2, 3]\nresult = [data[0]]\nfor v in data[1:]:\n    if v != result[__1__]:\n        result.append(v)\nprint(result)   # [1, 2, 3]\n```', '-1'),
    fb('把姓名成績配對輸出。\n\n```python\nnames = ["Amy", "Bob"]\nscores = [90, 80]\nfor n, s in __1__(names, scores):\n    print(f"{n}:{s}")\n```', 'zip'),
    fb('大於平均的名單。\n\n```python\nscores = [60, 90, 75]\navg = sum(scores) / 3\nabove = [s for s in scores if s __1__ avg]\nprint(above)   # [90]\n```', '>'),
    fb('把整行輸入變成兩個整數。\n\n```python\nraw = "13 27"\na, b = [int(x) for x in raw.split()]\nprint(a __1__ b)   # 40\n```', '+'),
    fb('留下唯一的學號（去重後排序）。\n\n```python\nids = [103, 101, 103, 102]\nunique = []\nfor i in ids:\n    if i not in unique:\n        unique.append(i)\nunique.__1__()\nprint(unique)   # [101, 102, 103]\n```', 'sort'),
    fb('把消費紀錄「品名:金額」解析後找最貴。\n\n```python\nitems = ["筆:35", "尺:20", "包:250"]\nbest = 0\nfor it in items:\n    price = int(it.split(":")[__1__])\n    if price > best:\n        best = price\nprint(best)   # 250\n```', '1'),
    fb('回傳訊息長度限制：超過 10 字截斷加省略號。\n\n```python\nmsg = "今天天氣真的非常好呢朋友"\nif len(msg) > 10:\n    msg = msg[:__1__] + "…"\nprint(msg)   # 今天天氣真的非常好呢…\n```', '10'),
    fb('票數過半判斷。\n\n```python\nvotes = ["Y", "N", "Y", "Y"]\nyes = votes.count("Y")\nprint(yes __1__ len(votes) / 2)   # True\n```', '>'),
    fb('計算字串的「數字和」。\n\n```python\ntext = "a3b5c1"\ntotal = 0\nfor ch in text:\n    if ch.isdigit():\n        total += __1__(ch)\nprint(total)   # 9\n```', 'int'),
    fb('清理再驗證：空輸入顯示錯誤。\n\n```python\nraw = "   "\ncleaned = raw.strip()\nif len(cleaned) == __1__:\n    print("輸入不可為空")   # 輸入不可為空\n```', '0'),
    fb('把段落的每行開頭加編號。\n\n```python\nlines = ["蘋果", "香蕉"]\nfor i, line in enumerate(lines, start=1):\n    print(f"{i}. {__1__}")\n```', 'line'),
    fb('模擬簽到表：找出未簽到的人。\n\n```python\nall_students = ["A", "B", "C"]\nsigned = ["A", "C"]\nmissing = [s for s in all_students if s not in __1__]\nprint(missing)   # [\'B\']\n```', 'signed'),
    fb('把價格字串轉數字（去除 $ 與逗號）。\n\n```python\nprice = "$1,250"\nvalue = int(price.replace("$", "").__1__(",", ""))\nprint(value)   # 1250\n```', 'replace'),
    fb('統計單字出現次數（不用字典）。\n\n```python\nwords = "a b a c a".split()\nprint(words.__1__("a"))   # 3\n```', 'count'),
    fb('依長度排序單字。\n\n```python\nwords = ["banana", "fig", "apple"]\nordered = sorted(words, key=__1__)\nprint(ordered[0])   # fig\n```', 'len'),
    fb('計算兩班平均差。\n\n```python\nclass_a = [80, 90]\nclass_b = [70, 75]\ndiff = sum(class_a) / 2 - sum(class_b) / __1__\nprint(diff)   # 12.5\n```', '2'),
    fb('把手機末四碼遮罩。\n\n```python\nphone = "0912345678"\nmasked = phone[:-4] + "*" * __1__\nprint(masked)   # 091234****\n```', '4'),
    fb('雙重過濾：及格且為偶數的分數。\n\n```python\nscores = [55, 72, 88, 61]\npicked = [s for s in scores if s >= 60 __1__ s % 2 == 0]\nprint(picked)   # [72, 88]\n```', 'and'),
    fb('把逐行資料組合成報表標題與筆數。\n\n```python\nrows = ["r1", "r2", "r3"]\nprint(f"共 {__1__(rows)} 筆資料")   # 共 3 筆資料\n```', 'len'),
    fb('找出成績進步最多的科目索引。\n\n```python\nmid = [70, 80, 60]\nfinal = [85, 82, 90]\nbest = 0\nfor i in range(3):\n    if final[i] - mid[i] > final[best] - mid[__1__]:\n        best = i\nprint(best)   # 2\n```', 'best'),
    fb('把布林結果串列轉通過率。\n\n```python\nresults = [True, False, True, True]\nrate = results.count(__1__) / len(results) * 100\nprint(rate)   # 75.0\n```', 'True'),
    fb('清單輪流分兩組（奇偶索引）。\n\n```python\nnames = ["A", "B", "C", "D"]\ngroup1 = names[::2]\ngroup2 = names[1::__1__]\nprint(group1, group2)   # [\'A\', \'C\'] [\'B\', \'D\']\n```', '2'),
]


# ── U6 Level 3：35 選擇 + 65 填空（競賽／TQC 實作）──
U6_L3 = [
    # 進階追蹤（35，含競賽原題 5 題）
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\na = [1, 2, 3, 4]\nb = [2, 3, 4, 5]\ntotal = 0\nfor i in range(4):\n    total += a[i] * b[i]\nprint(total % 4)\n```', '0', '1', '2', '3',
       explanation='2+6+12+20=40，40%4=0。（113 商業類技藝競賽學科第 2 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\nvalues = [i * 2 for i in range(1, 6)]\nprint(sum(values) % 4)\n```', '2', '0', '1', '3',
       explanation='[2,4,6,8,10] 總和 30，30%4=2。（113 商業類技藝競賽學科第 7 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\norders = [100, 150, 200, 80, 120]\navg_orders = sum(orders) / len(orders)\nbelow_avg = [o for o in orders if o < avg_orders]\nprint(len(below_avg) % 4)\n```', '3', '0', '1', '2',
       explanation='平均 130，低於平均：100、80、120 共 3 筆。（113 商業類技藝競賽學科第 16 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\na = [1, 2, 3, 4, 5]\nb = [x * 2 for x in a if x % 2 == 0]\nprint(sum(b) % 4)\n```', '0', '1', '2', '3',
       explanation='偶數 2、4 → [4, 8]，和 12，12%4=0。（113 商業類技藝競賽學科第 17 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\ndp = [0 for _ in range(10)]\ndp[0], dp[1], dp[2] = 1, 2, 2\nfor i in range(3, 8):\n    dp[i] = dp[i - 2] + dp[i - 3]\nprint(dp[5] % 4)\n```', '1', '0', '2', '3',
       explanation='dp[3]=3、dp[4]=4、dp[5]=dp[3]+dp[2]=5，5%4=1。（113 商業類技藝競賽學科第 19 題）'),
    mc('normalize 流程「保留英數字元並轉小寫」處理 "Hi, 2024!" 的結果是？',
       'hi2024', 'Hi2024', 'hi 2024', 'hi,2024!',
       explanation='isalnum 過濾掉逗號、空白與驚嘆號後轉小寫。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "A man, a plan"\ncleaned = "".join(ch.lower() for ch in text if ch.isalnum())\nprint(cleaned)\n```', 'amanaplan', 'a man a plan', 'AmanAplan', 'amanplan'),
    mc('以下程式的輸出是？\n\n```python\nnums = [3, 1, 4, 1, 5, 9, 2, 6]\ntop = sorted(nums, reverse=True)[:3]\nprint(sum(top))\n```', '20', '15', '18', '31',
       explanation='9+6+5=20。'),
    mc('以下程式的輸出是？\n\n```python\nwords = "the quick the lazy the".split()\nbest = ""\nfor w in words:\n    if words.count(w) > words.count(best):\n        best = w\nprint(best, words.count(best))\n```', 'the 3', 'quick 1', 'the 2', 'lazy 1'),
    mc('以下程式的輸出是？\n\n```python\ndata = [("Amy", 88), ("Bob", 95), ("Cid", 70)]\ndata.sort(key=lambda x: x[1])\nprint([d[0] for d in data])\n```', "['Cid', 'Amy', 'Bob']", "['Amy', 'Bob', 'Cid']", "['Bob', 'Amy', 'Cid']", "[70, 88, 95]",
       explanation='依分數升冪排序。'),
    mc('以下程式的輸出是？\n\n```python\nmatrix = [[1, 2], [3, 4]]\ntransposed = [[matrix[j][i] for j in range(2)] for i in range(2)]\nprint(transposed)\n```', '[[1, 3], [2, 4]]', '[[1, 2], [3, 4]]', '[[4, 3], [2, 1]]', '[[2, 1], [4, 3]]'),
    mc('以下程式的輸出是？\n\n```python\nscores = [88, 45, 92, 60, 55]\npassed_rate = len([s for s in scores if s >= 60]) / len(scores)\nprint(f"{passed_rate:.0%}")\n```', '60%', '0.6', '3', '40%',
       explanation='3/5 = 60%，:.0% 轉百分比格式。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "abca"\nseen = ""\nfor ch in text:\n    if ch in seen:\n        print(ch)\n        break\n    seen += ch\n```', 'a', 'b', 'c', '沒有任何輸出',
       explanation='找出第一個重複出現的字元。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, -3, 5, -7]\nresult = sorted(nums, key=abs)\nprint(result)\n```', '[1, -3, 5, -7]', '[-7, -3, 1, 5]', '[1, 5, -3, -7]', '[-3, -7, 1, 5]',
       explanation='依絕對值排序：1、3、5、7。'),
    mc('以下程式的輸出是？\n\n```python\nlines = ["Amy,88", "Bad", "Bob,95"]\nvalid = [l for l in lines if "," in l]\nprint(len(valid))\n```', '2', '3', '1', '0',
       explanation='資料驗證：拒絕缺欄位的列。'),
    mc('以下程式的輸出是？\n\n```python\nsales = [120, 200, 90, 310]\ngrowth = [sales[i] > sales[i - 1] for i in range(1, 4)]\nprint(growth)\n```', '[True, False, True]', '[False, True, False]', '[True, True, True]', '[200, 90, 310]'),
    mc('以下程式的輸出是？\n\n```python\ntext = "aabbbcccc"\nresult = ""\nfor ch in "abc":\n    result += ch + str(text.count(ch))\nprint(result)\n```', 'a2b3c4', 'abc234', 'a2b3c3', '9',
       explanation='字元頻率編碼。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [5, 8, 12, 3]\npairs = [(n, n % 2 == 0) for n in nums]\neven_count = sum(1 for n, is_even in pairs if is_even)\nprint(even_count)\n```', '2', '3', '1', '4',
       explanation='8 與 12 是偶數。'),
    mc('以下程式的輸出是？\n\n```python\ngrid = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\ncorners = grid[0][0] + grid[0][-1] + grid[-1][0] + grid[-1][-1]\nprint(corners)\n```', '20', '15', '45', '10',
       explanation='四個角：1+3+7+9。'),
    mc('以下程式的輸出是？\n\n```python\nraw = "10,20;30,40"\ntotal = 0\nfor part in raw.split(";"):\n    for v in part.split(","):\n        total += int(v)\nprint(total)\n```', '100', '70', '30', '1020304',
       explanation='雙層切割：10+20+30+40。'),
    mc('以下程式的輸出是？\n\n```python\nvotes = ["A", "B", "A", "C", "B", "A"]\ncandidates = ["A", "B", "C"]\nresult = [votes.count(c) for c in candidates]\nprint(result)\n```', '[3, 2, 1]', '[1, 2, 3]', '[3, 3, 3]', '6'),
    mc('以下程式的輸出是？\n\n```python\nwords = ["cat", "window", "silent"]\nresult = [w for w in words if len(w) == 6 and w[0] < "t"]\nprint(result)\n```', "['silent']", "['window', 'silent']", "['window']", '[]',
       explanation='六個字母且字首在 t 之前：silent（w > t 排除 window）。'),
    mc('以下程式的輸出是？\n\n```python\ns = "21:35"\nh, m = s.split(":")\nmins = int(h) * 60 + int(m)\nprint(mins % 100)\n```', '95', '1295', '12', '35',
       explanation='1295 分鐘，取 %100 = 95。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [2, 3, 4]\nresult = 1\nfor n in nums:\n    result *= n\nprint(result // sum(nums))\n```', '2', '24', '9', '3',
       explanation='24 // 9 = 2。'),
    mc('以下程式的輸出是？\n\n```python\ndata = ["5", "12", "7"]\nordered = sorted(data)\nprint(ordered)\n```', "['12', '5', '7']", "['5', '7', '12']", "['5', '12', '7']", '[5, 7, 12]',
       explanation='字串排序依字典序，"12" 排最前 — 常見陷阱。'),
    mc('以下程式的輸出是？\n\n```python\ndata = ["5", "12", "7"]\nordered = sorted(data, key=int)\nprint(ordered)\n```', "['5', '7', '12']", "['12', '5', '7']", '[5, 7, 12]', '發生錯誤',
       explanation='key=int 讓排序依數值比較。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\nfor i, v in enumerate([10, 20, 30], start=1):\n    total += v / i\nprint(total)\n```', '30.0', '60.0', '20.0', '10.0',
       explanation='10/1+20/2+30/3 = 10+10+10。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "hello"\nshifted = ""\nfor ch in text:\n    shifted += chr(ord(ch) + 1)\nprint(shifted)\n```', 'ifmmp', 'hello', 'gdkkn', 'ifmmo',
       explanation='每個字元位移 +1（ord/chr 對應競賽 ASCII 題型）。'),
    mc('以下程式的輸出是？（TQC 字元對應情境）\n\n```python\ntext = "AB"\ntotal = 0\nfor ch in text:\n    total += ord(ch)\nprint(total)\n```', '131', '65', '66', '196',
       explanation='ord("A")=65、ord("B")=66。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [4, 4, 4, 4]\nprint(len(set(nums)))\n```', '1', '4', '0', '16',
       explanation='set 去重後只剩一個元素。'),
    mc('二維串列尋找「每欄最大值」，外層應走訪？', '欄索引，內層走訪每列', '每列',
       '對角線', '長度'),
    mc('以下程式的輸出是？\n\n```python\nlogs = ["OK", "ERR", "OK", "ERR", "ERR"]\nstreak = 0\nbest = 0\nfor s in logs:\n    streak = streak + 1 if s == "ERR" else 0\n    best = max(best, streak)\nprint(best)\n```', '2', '3', '1', '5',
       explanation='最長連續 ERR 是 2。'),
    mc('把成績依「同分不同名次」排名（88, 92, 88），92 的名次是？',
       '1', '2', '3', '並列 1',
       explanation='降冪排序後 92 在第一位。'),
    mc('以下程式的輸出是？\n\n```python\nsentence = "aa bb aa cc aa"\nwords = sentence.split()\nprint(round(words.count("aa") / len(words), 1))\n```', '0.6', '0.5', '3', '0.4',
       explanation='3/5 = 0.6。'),
    mc('用 zip 同時走訪三個串列的寫法是？', 'for a, b, c in zip(x, y, z):',
       'for a in x, y, z:', 'zip 只能兩個', 'for a, b, c in x + y + z:'),

    # ── L3 填空（65）──
    fb('normalize：保留英數並轉小寫。\n\n```python\ntext = "Hi, 2024!"\ncleaned = "".join(ch.lower() for ch in text if ch.__1__())\nprint(cleaned)   # hi2024\n```', 'isalnum'),
    fb('嚴格回文（忽略符號）判斷。\n\n```python\ntext = "No.on"\ncleaned = "".join(ch.lower() for ch in text if ch.isalnum())\nprint(cleaned == cleaned[::__1__])   # True\n```', '-1'),
    fb('內積計算（競賽風格）。\n\n```python\na = [2, 4]\nb = [3, 5]\ntotal = 0\nfor i in range(2):\n    total += a[i] __1__ b[i]\nprint(total)   # 26\n```', '*'),
    fb('dp 遞推：走樓梯方法數（每次 1 或 2 階，共 5 階）。\n\n```python\ndp = [0] * 6\ndp[0] = dp[1] = 1\nfor i in range(2, 6):\n    dp[i] = dp[i - 1] + dp[i - __1__]\nprint(dp[5])   # 8\n```', '2'),
    fb('取前三名總和。\n\n```python\nnums = [3, 9, 6, 5, 1]\ntop = sorted(nums, reverse=__1__)[:3]\nprint(sum(top))   # 20\n```', 'True'),
    fb('詞頻最高的單字。\n\n```python\nwords = "a b a c a b".split()\nbest = ""\nfor w in words:\n    if words.count(w) > words.count(best):\n        best = __1__\nprint(best)   # a\n```', 'w'),
    fb('依第二欄排序（lambda）。\n\n```python\ndata = [("Amy", 88), ("Bob", 72)]\ndata.sort(key=__1__ x: x[1])\nprint(data[0][0])   # Bob\n```', 'lambda'),
    fb('ASCII 總和（TQC 字元對應情境）。\n\n```python\ntext = "Kd"\ntotal = 0\nfor ch in text:\n    total += __1__(ch)\nprint(total)   # 175\n```', 'ord',
       explanation='75 + 100 = 175。'),
    fb('字元位移加密（凱薩 +2 的核心）。\n\n```python\nch = "a"\nshifted = chr(__1__(ch) + 2)\nprint(shifted)   # c\n```', 'ord'),
    fb('每欄最大值。\n\n```python\ngrid = [[3, 9], [7, 2]]\ncol_max = []\nfor c in range(2):\n    m = grid[0][c]\n    for r in range(2):\n        if grid[r][c] > m:\n            m = grid[r][__1__]\n    col_max.append(m)\nprint(col_max)   # [7, 9]\n```', 'c'),
    fb('資料驗證：只接受兩欄且分數 0–100。\n\n```python\nlines = ["Amy,88", "Bob,150", "Cid"]\nvalid = []\nfor l in lines:\n    parts = l.split(",")\n    if len(parts) == 2 and 0 <= int(parts[1]) <= 100:\n        valid.append(l)\nprint(len(valid))   # __1__\n```\n\n（填輸出）', '1',
       explanation='Bob 分數超標、Cid 缺欄位。'),
    fb('連續遞增最長段。\n\n```python\nnums = [1, 2, 3, 2, 3, 4, 5]\nbest = cur = 1\nfor i in range(1, 7):\n    if nums[i] > nums[i - 1]:\n        cur += 1\n    else:\n        cur = __1__\n    best = max(best, cur)\nprint(best)   # 4\n```', '1'),
    fb('把清單依正負分組後輸出兩組長度。\n\n```python\nnums = [3, -1, 4, -5, 9]\npos = [n for n in nums if n > 0]\nneg = [n for n in nums if n __1__ 0]\nprint(len(pos), len(neg))   # 3 2\n```', '<'),
    fb('雙層切割解析購物資料。\n\n```python\nraw = "筆:35;尺:20"\ntotal = 0\nfor item in raw.split(";"):\n    total += int(item.split(":")[__1__])\nprint(total)   # 55\n```', '1'),
    fb('去頭去尾平均（體操評分）。\n\n```python\nscores = [9.0, 8.5, 9.5, 8.0, 9.2]\nscores.sort()\ntrimmed = scores[1:-1]\nprint(round(sum(trimmed) / len(trimmed), 2))   # __1__\n```\n\n（填輸出）', '8.9',
       explanation='去掉 8.0 與 9.5，(8.5+9.0+9.2)/3 = 8.9。'),
    fb('模擬座號抽籤後排序找中位。\n\n```python\npicked = [17, 3, 25, 9, 11]\npicked.sort()\nprint(picked[len(picked) // __1__])   # 11\n```', '2'),
    fb('比對兩字串的相同位置字元數。\n\n```python\na = "apple"\nb = "ample"\nsame = 0\nfor i in range(5):\n    if a[i] == b[__1__]:\n        same += 1\nprint(same)   # 4\n```', 'i'),
    fb('把逐日營收轉「累計營收」。\n\n```python\ndaily = [100, 50, 80]\nrunning = []\ntotal = 0\nfor d in daily:\n    total += d\n    running.append(__1__)\nprint(running)   # [100, 150, 230]\n```', 'total'),
    fb('票選過濾廢票（不在候選名單）。\n\n```python\nvotes = ["A", "X", "B", "A"]\ncandidates = ["A", "B"]\nvalid = [v for v in votes if v __1__ candidates]\nprint(len(valid))   # 3\n```', 'in'),
    fb('把英文句子轉「首字母縮寫」大寫。\n\n```python\nname = "central processing unit"\nabbr = "".join(w[0] for w in name.split()).__1__()\nprint(abbr)   # CPU\n```', 'upper'),
    fb('找出唯一沒重複的數（出現一次）。\n\n```python\nnums = [7, 3, 7, 9, 3]\nfor n in nums:\n    if nums.count(n) == __1__:\n        print(n)   # 9\n        break\n```', '1'),
    fb('計算對角線與反對角線和。\n\n```python\ng = [[1, 2], [3, 4]]\nmain = g[0][0] + g[1][1]\nanti = g[0][1] + g[1][__1__]\nprint(main, anti)   # 5 5\n```', '0'),
    fb('字串每字元出現位置表（僅 a）。\n\n```python\ntext = "banana"\npos = [i for i, ch in enumerate(text) if ch == __1__]\nprint(pos)   # [1, 3, 5]\n```', ['"a"', "'a'"]),
    fb('模擬快篩結果統計陽性率。\n\n```python\nresults = ["P", "N", "P", "N", "N"]\nrate = results.count("P") / len(results) * __1__\nprint(rate)   # 40.0\n```', '100'),
    fb('把成績跟名次 zip 成表。\n\n```python\nnames = ["Amy", "Bob"]\nranks = [2, 1]\ntable = list(zip(ranks, __1__))\ntable.sort()\nprint(table[0][1])   # Bob\n```', 'names'),
    fb('隔位加總（偶數索引）。\n\n```python\nnums = [5, 1, 6, 2, 7]\nprint(sum(nums[::__1__]))   # 18\n```', '2'),
    fb('文字倒序但保留單字。\n\n```python\ns = "we love py"\nprint(" ".join(s.split()[::-1]))   # py love we\n```\n\n切片 [::-1] 反轉的對象是？（填 words 或 chars）', 'words',
       explanation='反轉單字順序而非字元。'),
    fb('把混合大小寫名單統一並去重計數。\n\n```python\nnames = ["Amy", "AMY", "bob"]\nnormalized = [n.__1__() for n in names]\nunique = []\nfor n in normalized:\n    if n not in unique:\n        unique.append(n)\nprint(len(unique))   # 2\n```', 'lower'),
    fb('連續三天營收都成長的判斷。\n\n```python\nsales = [100, 120, 150, 200]\nok = True\nfor i in range(1, 4):\n    if sales[i] <= sales[i - 1]:\n        ok = __1__\nprint(ok)   # True\n```', 'False'),
    fb('身分證檢查碼加權和（前兩碼示意）。\n\n```python\ndigits = [1, 2]\nweights = [8, 7]\ntotal = 0\nfor d, w in zip(digits, weights):\n    total += d * w\nprint(total)   # __1__\n```\n\n（填輸出）', '22'),
    fb('把清單切成大小為 2 的批次。\n\n```python\ndata = [1, 2, 3, 4, 5]\nbatches = [data[i:i + 2] for i in range(0, len(data), __1__)]\nprint(len(batches))   # 3\n```', '2'),
    fb('大樂透對獎：對中幾個號碼。\n\n```python\nmy = [7, 12, 33, 41]\nwin = [12, 41, 8, 25]\nhits = [n for n in my if n __1__ win]\nprint(len(hits))   # 2\n```', 'in'),
    fb('把整數清單轉字串串接。\n\n```python\nnums = [2, 0, 2, 4]\ntext = "".join(__1__(n) for n in nums)\nprint(text)   # 2024\n```', 'str'),
    fb('尋找峰值（比左右都大）。\n\n```python\nnums = [1, 5, 2, 8, 3]\nfor i in range(1, 4):\n    if nums[i] > nums[i - 1] and nums[i] > nums[i + __1__]:\n        print(nums[i], end=" ")   # 5 8\n```', '1'),
    fb('模擬文字跑馬燈：每次左移一格（做 2 次）。\n\n```python\ntext = "abcde"\nfor _ in range(2):\n    text = text[1:] + text[__1__]\nprint(text)   # cdeab\n```', '0'),
    fb('把每人成績表算全班單科平均（第 1 科）。\n\n```python\ntable = [[80, 90], [60, 70], [100, 50]]\nsubject = [row[__1__] for row in table]\nprint(sum(subject) / 3)   # 80.0\n```', '0'),
    fb('過濾與映射合併：及格分數開根號。\n\n```python\nscores = [49, 81, 36, 100]\nresult = [s ** 0.5 for s in scores if s >= __1__]\nprint(result)   # [9.0, 10.0]\n```', '60',
       explanation='81 與 100 及格。'),
    fb('氣泡排序統計交換次數。\n\n```python\nnums = [3, 2, 1]\nswaps = 0\nfor r in range(2):\n    for i in range(2 - r):\n        if nums[i] > nums[i + 1]:\n            nums[i], nums[i + 1] = nums[i + 1], nums[i]\n            swaps += __1__\nprint(swaps)   # 3\n```', '1'),
    fb('查表翻譯：用平行串列把代碼轉名稱。\n\n```python\ncodes = ["tw", "jp"]\nnames = ["台灣", "日本"]\ncode = "jp"\nprint(names[codes.__1__(code)])   # 日本\n```', 'index'),
    fb('模擬購物滿額門檻提示。\n\n```python\ncart = [250, 380]\ntotal = sum(cart)\nremain = 1000 - total\nif remain > 0:\n    print(f"再買 {__1__} 元免運")   # 再買 370 元免運\n```', 'remain'),
    fb('把日期清單找最早的一天（字串比較）。\n\n```python\ndates = ["2024-07-06", "2024-03-15", "2024-11-01"]\nprint(__1__(dates))   # 2024-03-15\n```', 'min',
       explanation='ISO 格式日期可直接依字串比較。'),
    fb('剔除離群值（超過平均兩倍）。\n\n```python\nnums = [10, 12, 11, 50]\navg = sum(nums) / len(nums)\nnormal = [n for n in nums if n <= avg * __1__]\nprint(normal)   # [10, 12, 11]\n```', '2'),
    fb('把逗號字串反轉重組。\n\n```python\npath = "a,b,c"\nparts = path.split(",")\nprint(",".join(parts[::__1__]))   # c,b,a\n```', '-1'),
    fb('雙欄資料找第二欄最大值那筆的第一欄。\n\n```python\nrows = [["筆", 35], ["包", 250], ["尺", 20]]\nbest = rows[0]\nfor r in rows:\n    if r[1] > best[1]:\n        best = __1__\nprint(best[0])   # 包\n```', 'r'),
    fb('每人分數距平均的差。\n\n```python\nscores = [70, 80, 90]\navg = sum(scores) / 3\ndiffs = [round(s - avg, 1) for s in __1__]\nprint(diffs)   # [-10.0, 0.0, 10.0]\n```', 'scores'),
    fb('用生成式建立乘法表其中一列。\n\n```python\nrow = [3 * j for j in range(1, __1__)]\nprint(row)   # [3, 6, 9, 12, 15, 18, 21, 24, 27]\n```', '10'),
    fb('把清單元素兩兩相加（相鄰）。\n\n```python\nnums = [1, 2, 3, 4]\npair_sums = [nums[i] + nums[i + 1] for i in range(len(nums) - __1__)]\nprint(pair_sums)   # [3, 5, 7]\n```', '1'),
    fb('計算購物車折扣：第二件半價（排序後便宜的那件半價）。\n\n```python\nitems = [200, 100]\nitems.sort()\ntotal = items[1] + items[0] * __1__\nprint(total)   # 250.0\n```', '0.5'),
    fb('過濾出手機號碼（09 開頭且 10 碼）。\n\n```python\nnums = ["0912345678", "021234", "0987654321"]\nphones = [n for n in nums if n.startswith("09") and len(n) == __1__]\nprint(len(phones))   # 2\n```', '10'),
    fb('把答對題號轉成得分（每題 5 分）。\n\n```python\ncorrect = [1, 3, 7, 9]\nprint(len(correct) * __1__)   # 20\n```', '5'),
    fb('列出缺席名單（全班減出席）。\n\n```python\nall_ids = [1, 2, 3, 4, 5]\npresent = [1, 3, 5]\nabsent = [i for i in all_ids if i not in __1__]\nprint(absent)   # [2, 4]\n```', 'present'),
    fb('把姓名依姓氏（第一個字）分組計數。\n\n```python\nnames = ["王小明", "李大仁", "王美麗"]\nwang = [n for n in names if n[0] == __1__]\nprint(len(wang))   # 2\n```', ['"王"', "'王'"]),
    fb('檢查密碼是否含至少一個數字。\n\n```python\npwd = "abc123"\nhas_digit = False\nfor ch in pwd:\n    if ch.isdigit():\n        has_digit = __1__\nprint(has_digit)   # True\n```', 'True'),
    fb('計算字串的字元種類數。\n\n```python\ntext = "aabbc"\nkinds = []\nfor ch in text:\n    if ch not in kinds:\n        kinds.append(ch)\nprint(__1__(kinds))   # 3\n```', 'len'),
    fb('營收前 30% 的門檻（排序後取位置）。\n\n```python\nsales = [50, 90, 20, 70, 100, 40, 60, 30, 80, 10]\nsales.sort(reverse=True)\ncutoff = sales[__1__]\nprint(cutoff)   # 80\n```', '2',
       explanation='前 30% 是前 3 名，第 3 名（索引 2）為門檻。'),
    fb('把段落每句話的長度統計。\n\n```python\npara = "早安。你好嗎。再見。"\nsentences = [s for s in para.split("。") if s]\nlengths = [len(s) for s in __1__]\nprint(lengths)   # [2, 3, 2]\n```', 'sentences'),
    fb('用 zip 找兩串列同位置相同的個數。\n\n```python\na = [1, 2, 3, 4]\nb = [1, 5, 3, 6]\nsame = sum(1 for x, y in zip(a, b) if x __1__ y)\nprint(same)   # 2\n```', '=='),
    fb('把清單旋轉到指定元素開頭。\n\n```python\nnames = ["A", "B", "C", "D"]\nk = names.index("C")\nrotated = names[k:] + names[:__1__]\nprint(rotated)   # [\'C\', \'D\', \'A\', \'B\']\n```', 'k'),
    fb('多數決：出現超過一半的元素。\n\n```python\nvotes = [1, 2, 1, 1]\nfor v in [1, 2]:\n    if votes.count(v) > len(votes) // __1__:\n        print(v)   # 1\n```', '2'),
    fb('把成對括號資料拆開加總。\n\n```python\ndata = "(3,4)(5,6)"\ntotal = 0\nfor pair in data.replace(")(", ";").strip("()").split(";"):\n    a, b = pair.split(",")\n    total += int(a) + int(__1__)\nprint(total)   # 18\n```', 'b'),
    fb('計算與前一筆的差距絕對值總和（波動度）。\n\n```python\nprices = [100, 105, 98]\nswing = 0\nfor i in range(1, 3):\n    swing += __1__(prices[i] - prices[i - 1])\nprint(swing)   # 12\n```', 'abs'),
    fb('過濾出以母音開頭的單字。\n\n```python\nwords = ["apple", "banana", "orange"]\nresult = [w for w in words if w[0] __1__ "aeiou"]\nprint(result)   # [\'apple\', \'orange\']\n```', 'in'),
    fb('把二維清單每列反轉。\n\n```python\ngrid = [[1, 2], [3, 4]]\nflipped = [row[::-1] for row in __1__]\nprint(flipped)   # [[2, 1], [4, 3]]\n```', 'grid'),
    fb('把訂單金額分成大小單（門檻 500）並輸出大單數。\n\n```python\norders = [320, 780, 150, 900]\nbig = [o for o in orders if o >= __1__]\nprint(len(big))   # 2\n```', '500'),
    fb('把姓名首字母當代號檢查唯一性。\n\n```python\nnames = ["Amy", "Alan", "Bob"]\ninitials = [n[0] for n in names]\nprint(len(initials) == len(set(initials)))   # __1__\n```\n\n（填輸出 True 或 False）', 'False',
       explanation='A 重複出現兩次。'),
]
