"""Unit 5（List 與 String 進階操作）題庫 — 全選擇制。

L1 對標 ITS（索引/方法概念、單步讀值）、
L2 對標 TQC+ 觀念題（切片與方法追蹤、複製陷阱、unpacking）、
L3 對標競賽／TQC 實作（aliasing、enumerate/zip、清理管線；收錄競賽第 8 題）。
"""
from .question_helpers import mc, fb

# ── U5 Level 1：55 選擇 + 45 填空 ──
U5_L1 = [
    # 索引與切片（14）
    mc('串列的第一個元素索引是？', '0', '1', '-1', '看長度決定'),
    mc('nums = [10, 20, 30] 時，nums[1] 是？', '20', '10', '30', '1'),
    mc('nums = [10, 20, 30] 時，nums[-1] 是？', '30', '10', '20', '發生錯誤',
       explanation='-1 代表最後一個元素。'),
    mc('nums = [10, 20, 30] 時，nums[3] 會發生什麼？', '引發 IndexError', '得到 30',
       '得到 None', '自動新增元素'),
    mc('len([5, 8, 2, 9]) 的結果是？', '4', '3', '9', '24'),
    mc('"Python"[0] 的結果是？', 'P', 'y', 'n', 'Python'),
    mc('"Python"[-1] 的結果是？', 'n', 'P', 'o', '發生錯誤'),
    mc('"Python"[1:4] 的結果是？', 'yth', 'yt', 'ytho', 'Pyt',
       explanation='切片含起點、不含終點。'),
    mc('nums = [1, 2, 3, 4, 5] 時，nums[:3] 是？', '[1, 2, 3]', '[1, 2]', '[3, 4, 5]', '[4, 5]'),
    mc('nums = [1, 2, 3, 4, 5] 時，nums[2:] 是？', '[3, 4, 5]', '[1, 2]', '[2, 3, 4, 5]', '[3, 4]'),
    mc('切片 text[2:5] 總共取出幾個字元？', '3 個', '4 個', '2 個', '5 個'),
    mc('串列與字串都支援下列哪個操作？', '切片', 'append()', '修改單一元素', 'sort()',
       explanation='字串不可變，不能 append 或改單一字元。'),
    mc('nums = [7, 8, 9] 時，nums[0] + nums[2] 是？', '16', '15', '17', '79'),
    mc('判斷元素是否在串列中使用哪個關鍵字？', 'in', 'has', 'find', 'exist'),

    # list 方法（14）
    mc('在串列「末端」加入元素的方法是？', 'append()', 'insert()', 'add()', 'push()'),
    mc('在串列「指定位置」插入元素的方法是？', 'insert()', 'append()', 'put()', 'sort()'),
    mc('移除並「回傳」串列最後一個元素的方法是？', 'pop()', 'remove()', 'delete()', 'cut()'),
    mc('依「內容」刪除第一個符合元素的方法是？', 'remove()', 'pop()', 'discard()', 'del()'),
    mc('把串列由小到大「就地」排序的方法是？', 'sort()', 'sorted()', 'order()', 'arrange()'),
    mc('nums = [3, 1, 2]; nums.sort() 之後 nums 是？', '[1, 2, 3]', '[3, 1, 2]', '[3, 2, 1]', 'None'),
    mc('nums = [1, 2]; nums.append(3) 之後 nums 是？', '[1, 2, 3]', '[3, 1, 2]', '[1, 2]', '[[1, 2], 3]'),
    mc('nums = [1, 3]; nums.insert(1, 2) 之後 nums 是？', '[1, 2, 3]', '[1, 3, 2]', '[2, 1, 3]', '[1, 2]',
       explanation='insert(位置, 值)。'),
    mc('nums = [5, 6, 7]; nums.pop() 之後 nums 是？', '[5, 6]', '[6, 7]', '[5, 7]', '[]'),
    mc('nums = [4, 5, 4]; nums.remove(4) 之後 nums 是？', '[5, 4]', '[5]', '[4, 5]', '[4, 4]',
       explanation='remove 只刪第一個符合的。'),
    mc('sort() 與 sorted() 的差別是？', 'sort() 改變原串列、sorted() 回傳新串列',
       '完全相同', 'sorted() 改變原串列', 'sort() 只能排數字'),
    mc('nums.sort(reverse=True) 的效果是？', '由大到小排序', '由小到大排序',
       '把串列反轉（不排序）', '刪除重複'),
    mc('串列建立後可以修改內容嗎？', '可以，串列是可變的', '不可以',
       '只能改第一個', '只能增加不能刪'),
    mc('tuple（元組）與串列最大的差別是？', '元組建立後不能修改', '元組比較短',
       '元組只能放數字', '元組不能用索引'),

    # 字串方法（14）
    mc('把 "A,B,C" 依逗號拆成串列的方法是？', 'split(",")', 'join(",")', 'strip(",")', 'cut(",")'),
    mc('把 ["A", "B"] 用 "-" 接成 "A-B" 的寫法是？', '"-".join(["A", "B"])',
       '["A", "B"].join("-")', 'join("A", "B", "-")', '"A" - "B"'),
    mc('移除字串「兩端」空白的方法是？', 'strip()', 'split()', 'trim()', 'cut()'),
    mc('尋找子字串位置的方法是？', 'find()', 'search()', 'look()', 'get()'),
    mc('"hello".upper() 的結果是？', 'HELLO', 'Hello', 'hello', 'hELLO'),
    mc('"HELLO".lower() 的結果是？', 'hello', 'HELLO', 'Hello', 'hEllo'),
    mc('"a b c".split() 的結果是？', "['a', 'b', 'c']", "['a b c']", "'abc'", "['a', ' ', 'b']",
       explanation='不給參數時以空白切割。'),
    mc('"apple".find("p") 的結果是？', '1', '2', '0', 'p',
       explanation='回傳第一次出現的索引。'),
    mc('"apple".find("z") 的結果是？', '-1', '0', '發生錯誤', 'None',
       explanation='找不到回傳 -1。'),
    mc('"  hi  ".strip() 的結果是？', '"hi"', '"  hi"', '"hi  "', '"h i"'),
    mc('"banana".count("a") 的結果是？', '3', '2', '1', '6'),
    mc('len("Hello World") 的結果是？', '11', '10', '12', '2',
       explanation='空格也算一個字元。'),
    mc('"Amy,88".split(",") 的結果是？', "['Amy', '88']", "['Amy,88']", "'Amy88'", "['A', 'm', 'y']"),
    mc('字串可以用 text[0] = "x" 修改第一個字元嗎？', '不可以，字串不可變（TypeError）',
       '可以', '只有英文可以', '只能改最後一個'),

    # 讀碼追蹤（13）
    mc('以下程式的輸出是？\n\n```python\nfruits = ["蘋果", "香蕉", "西瓜"]\nfruits.append("芒果")\nprint(len(fruits))\n```', '4', '3', '5', '芒果'),
    mc('以下程式的輸出是？\n\n```python\nfruits = ["蘋果", "香蕉"]\nfruits[1] = "草莓"\nprint(fruits)\n```', "['蘋果', '草莓']", "['蘋果', '香蕉']", "['草莓', '香蕉']", '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nnums = [10, 20, 30]\nprint(nums[0] + nums[-1])\n```', '40', '30', '50', '1030'),
    mc('以下程式的輸出是？\n\n```python\ntext = "Hello Python"\nprint(text[6:])\n```', 'Python', 'Hello', 'Hello ', 'P'),
    mc('以下程式的輸出是？\n\n```python\nparts = "1,2,3".split(",")\nprint(len(parts))\n```', '3', '5', '1', '6'),
    mc('以下程式的輸出是？\n\n```python\nwords = ["我", "愛", "Python"]\nprint("".join(words))\n```', '我愛Python', '我 愛 Python', "['我','愛','Python']", '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nnums = [5, 2, 8]\nnums.sort()\nprint(nums[0])\n```', '2', '5', '8', '[2, 5, 8]'),
    mc('以下程式的輸出是？\n\n```python\ntext = " Python "\nprint(len(text.strip()))\n```', '6', '8', '7', '9'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, 2, 3]\nlast = nums.pop()\nprint(last, nums)\n```', '3 [1, 2]', '[1, 2] 3', '1 [2, 3]', '3 [1, 2, 3]'),
    mc('以下程式的輸出是？\n\n```python\nprint("2024-07-06".split("-")[0])\n```', '2024', '07', '06', '2024-07'),
    mc('以下程式的輸出是？\n\n```python\nletters = ["c", "a", "b"]\nletters.sort()\nprint(letters)\n```', "['a', 'b', 'c']", "['c', 'a', 'b']", "['c', 'b', 'a']", 'abc'),
    mc('以下程式的輸出是？\n\n```python\nprint("banana".upper()[0])\n```', 'B', 'b', 'BANANA', 'A'),
    mc('以下程式的輸出是？\n\n```python\npoint = (3, 4)\nprint(point[0] * point[1])\n```', '12', '7', '34', '發生錯誤',
       explanation='元組一樣可以用索引讀取。'),

    # ── L1 填空（45）──
    fb('取出串列第一個元素。\n\n```python\nfruits = ["蘋果", "香蕉", "西瓜"]\nprint(fruits[__1__])   # 蘋果\n```', '0'),
    fb('取出串列最後一個元素（負索引）。\n\n```python\nnums = [10, 20, 30]\nprint(nums[__1__])   # 30\n```', '-1'),
    fb('在串列末端加入 40。\n\n```python\nnums = [10, 20, 30]\nnums.__1__(40)\nprint(nums)   # [10, 20, 30, 40]\n```', 'append'),
    fb('把串列由小到大排序。\n\n```python\nnums = [9, 2, 7]\nnums.__1__()\nprint(nums)   # [2, 7, 9]\n```', 'sort'),
    fb('移除並取出最後一個元素。\n\n```python\nnums = [1, 2, 3]\nlast = nums.__1__()\nprint(last)   # 3\n```', 'pop'),
    fb('依內容刪除元素 5。\n\n```python\nnums = [4, 5, 6]\nnums.__1__(5)\nprint(nums)   # [4, 6]\n```', 'remove'),
    fb('在索引 1 的位置插入 15。\n\n```python\nnums = [10, 20]\nnums.__1__(1, 15)\nprint(nums)   # [10, 15, 20]\n```', 'insert'),
    fb('取出字串前 5 個字元。\n\n```python\ntext = "Hello Python"\nprint(text[:__1__])   # Hello\n```', '5'),
    fb('把 "A,B,C" 依逗號拆開。\n\n```python\ntext = "A,B,C"\nprint(text.__1__(","))   # [\'A\', \'B\', \'C\']\n```', 'split'),
    fb('把串列用「/」接成一個字串。\n\n```python\nitems = ["a", "b", "c"]\nprint("/".__1__(items))   # a/b/c\n```', 'join'),
    fb('去除兩端空白。\n\n```python\ntext = "  Python  "\nprint(text.__1__())   # Python\n```', 'strip'),
    fb('找出 "n" 第一次出現的位置。\n\n```python\ntext = "banana"\nprint(text.__1__("n"))   # 2\n```', 'find'),
    fb('取得串列長度。\n\n```python\nnums = [3, 1, 4, 1, 5]\nprint(__1__(nums))   # 5\n```', 'len'),
    fb('把字串轉成大寫。\n\n```python\ntext = "python"\nprint(text.__1__())   # PYTHON\n```', 'upper'),
    fb('把字串轉成小寫。\n\n```python\ntext = "HELLO"\nprint(text.__1__())   # hello\n```', 'lower'),
    fb('修改串列索引 1 的元素為 99。\n\n```python\nnums = [1, 2, 3]\nnums[__1__] = 99\nprint(nums)   # [1, 99, 3]\n```', '1'),
    fb('判斷 "b" 是否在串列中。\n\n```python\nletters = ["a", "b", "c"]\nprint("b" __1__ letters)   # True\n```', 'in'),
    fb('統計字串中 "o" 的個數。\n\n```python\ntext = "good morning"\nprint(text.__1__("o"))   # 3\n```', 'count'),
    fb('取出中間三個元素（索引 1 到 3）。\n\n```python\nnums = [1, 2, 3, 4, 5]\nprint(nums[1:__1__])   # [2, 3, 4]\n```', '4'),
    fb('由大到小排序。\n\n```python\nnums = [3, 8, 1]\nnums.sort(reverse=__1__)\nprint(nums)   # [8, 3, 1]\n```', 'True'),
    fb('把兩個串列接在一起。\n\n```python\na = [1, 2]\nb = [3, 4]\nprint(a __1__ b)   # [1, 2, 3, 4]\n```', '+'),
    fb('建立空串列，準備收集資料。\n\n```python\nresult = __1__\nresult.append(10)\nprint(result)   # [10]\n```', '[]'),
    fb('取出最後兩個元素。\n\n```python\nnums = [1, 2, 3, 4, 5]\nprint(nums[__1__:])   # [4, 5]\n```', '-2'),
    fb('取出偶數索引的字元（間隔 2）。\n\n```python\ntext = "abcdef"\nprint(text[::__1__])   # ace\n```', '2'),
    fb('把姓名串列的第一位改成新同學。\n\n```python\nnames = ["小明", "小華"]\nnames[0] = __1__\nprint(names)   # [\'小美\', \'小華\']\n```', ['"小美"', "'小美'"]),
    fb('用切片複製整個串列。\n\n```python\nnums = [1, 2, 3]\ncopied = nums[__1__]\ncopied.append(4)\nprint(nums)   # [1, 2, 3]\n```', ':'),
    fb('把座號與姓名組成元組。\n\n```python\nstudent = (5, "Amy")\nprint(student[__1__])   # Amy\n```', '1'),
    fb('取字串最後 3 個字元。\n\n```python\nfilename = "report.txt"\nprint(filename[-__1__:])   # txt\n```', '3'),
    fb('串列尾端同時是最大索引：長度減 1。\n\n```python\nnums = [7, 8, 9, 10]\nprint(nums[len(nums) - __1__])   # 10\n```', '1'),
    fb('把電話號碼中的「-」拆掉。\n\n```python\nphone = "0912-345-678"\nparts = phone.split(__1__)\nprint(parts)   # [\'0912\', \'345\', \'678\']\n```', ['"-"', "'-'"]),
    fb('把單字串列接成句子（空格分隔）。\n\n```python\nwords = ["I", "love", "Python"]\nprint(__1__.join(words))   # I love Python\n```', ['" "', "' '"]),
    fb('清除輸入資料的兩端空白再輸出長度。\n\n```python\nraw = "  abc  "\nprint(len(raw.__1__()))   # 3\n```', 'strip'),
    fb('把 "hello world" 首字母位置的字元取出。\n\n```python\ntext = "hello world"\nprint(text[__1__])   # h\n```', '0'),
    fb('刪除串列索引 0 的元素（用 pop）。\n\n```python\nnums = [9, 8, 7]\nnums.pop(__1__)\nprint(nums)   # [8, 7]\n```', '0'),
    fb('把成績串列的最高分找出來（先排序再取最後）。\n\n```python\nscores = [72, 95, 88]\nscores.sort()\nprint(scores[__1__])   # 95\n```', '-1'),
    fb('組合購物清單字串。\n\n```python\nitems = ["蛋", "奶", "麵包"]\nprint("、".__1__(items))   # 蛋、奶、麵包\n```', 'join'),
    fb('檢查關鍵字是否在句子裡。\n\n```python\nsentence = "今天天氣很好"\nprint("天氣" __1__ sentence)   # True\n```', 'in'),
    fb('把字串反轉（負步長切片）。\n\n```python\ntext = "abc"\nprint(text[::__1__])   # cba\n```', '-1'),
    fb('數字串列翻倍輸出第一個元素。\n\n```python\nnums = [3, 5]\nnums[0] = nums[0] * __1__\nprint(nums)   # [6, 5]\n```', '2'),
    fb('把身分字串的第 1 個字元當性別碼。\n\n```python\ncode = "A123456789"\ngender = code[__1__]\nprint(gender)   # 1\n```', '1'),
    fb('串列中有幾個 7？\n\n```python\nnums = [7, 1, 7, 3]\nprint(nums.__1__(7))   # 2\n```', 'count'),
    fb('把逗號分隔的成績轉成整數加總。\n\n```python\ndata = "80,90,70"\ntotal = 0\nfor s in data.split(","):\n    total += __1__(s)\nprint(total)   # 240\n```', 'int'),
    fb('元組不可修改：改用重新指定整個元組。\n\n```python\npoint = (1, 2)\npoint = (1, __1__)\nprint(point)   # (1, 3)\n```', '3'),
    fb('把字串的第 2~4 個字元取出（索引 1 到 3）。\n\n```python\ntext = "ABCDEF"\nprint(text[1:__1__])   # BCD\n```', '4'),
    fb('清空購物車（重新指定空串列）。\n\n```python\ncart = ["筆", "尺"]\ncart = __1__\nprint(len(cart))   # 0\n```', '[]'),
]


# ── U5 Level 2：60 選擇 + 40 填空（TQC+ 觀念題：方法追蹤＋複製陷阱）──
U5_L2 = [
    # 追蹤（32）
    mc('以下程式的輸出是？\n\n```python\nscores = [88, 72, 95, 61]\nscores.append(84)\nscores.sort(reverse=True)\nprint(scores[:3])\n```', '[95, 88, 84]', '[61, 72, 84]', '[95, 88, 72]', '[84, 88, 95]',
       explanation='加入 84 後由大到小排序，取前三。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, 2, 3]\nfirst = nums.pop(0)\nprint(first, nums)\n```', '1 [2, 3]', '3 [1, 2]', '[2, 3] 1', '0 [1, 2, 3]',
       explanation='pop(0) 移除並回傳第一個元素。'),
    mc('以下程式的輸出是？\n\n```python\noriginal = [1, 2, 3]\nsame = original\nsame.append(4)\nprint(original)\n```', '[1, 2, 3, 4]', '[1, 2, 3]', '[4]', '發生錯誤',
       explanation='same 與 original 指向同一個串列（aliasing）。'),
    mc('以下程式的輸出是？\n\n```python\noriginal = [1, 2, 3]\ncopied = original.copy()\ncopied.append(4)\nprint(original)\n```', '[1, 2, 3]', '[1, 2, 3, 4]', '[4]', '發生錯誤',
       explanation='copy() 產生獨立副本。'),
    mc('以下程式的輸出是？\n\n```python\npoint = (25, 121)\nlat, lng = point\nprint(lng)\n```', '121', '25', '(25, 121)', '發生錯誤',
       explanation='tuple unpacking 依序拆值。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "apple,banana"\nfruits = text.split(",")\nprint(fruits[1])\n```', 'banana', 'apple', ',', "['banana']"),
    mc('以下程式的輸出是？\n\n```python\nraw = " Amy , Bob "\nnames = [n.strip() for n in raw.split(",")]\nprint(names)\n```', "['Amy', 'Bob']", "[' Amy ', ' Bob ']", "'Amy Bob'", '發生錯誤',
       explanation='comprehension 中逐一去除空白。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [2, 4, 6]\ndoubled = [n * 2 for n in nums]\nprint(doubled)\n```', '[4, 8, 12]', '[2, 4, 6]', '[2, 4, 6, 2, 4, 6]', '24',
       explanation='串列生成式對每個元素做運算。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, 2, 3, 4, 5, 6]\nevens = [n for n in nums if n % 2 == 0]\nprint(len(evens))\n```', '3', '2', '6', '[2, 4, 6]'),
    mc('以下程式的輸出是？\n\n```python\ntext = "hello"\nprint(text.find("l"), text.count("l"))\n```', '2 2', '3 2', '2 3', '3 3',
       explanation='find 回傳第一次出現位置 2、count 數出 2 個。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [5, 3, 8, 1]\nprint(sorted(nums), nums)\n```', '[1, 3, 5, 8] [5, 3, 8, 1]', '[1, 3, 5, 8] [1, 3, 5, 8]',
       '[5, 3, 8, 1] [1, 3, 5, 8]', '[8, 5, 3, 1] [5, 3, 8, 1]',
       explanation='sorted 回傳新串列，原串列不變。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "2024/07/06"\ny, m, d = text.split("/")\nprint(m)\n```', '07', '2024', '06', '7'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, 2] * 3\nprint(len(nums))\n```', '6', '3', '2', '8',
       explanation='串列乘法重複內容：[1,2,1,2,1,2]。'),
    mc('以下程式的輸出是？\n\n```python\nwords = "the quick brown fox".split()\nprint(words[-2])\n```', 'brown', 'fox', 'quick', 'the'),
    mc('以下程式的輸出是？\n\n```python\nnums = [10, 20, 30, 40, 50]\nprint(nums[1:4:2])\n```', '[20, 40]', '[20, 30, 40]', '[10, 30, 50]', '[20]',
       explanation='從索引 1 到 3、間隔 2：20、40。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "abcdef"\nprint(text[::-1])\n```', 'fedcba', 'abcdef', 'f', 'a'),
    mc('以下程式的輸出是？\n\n```python\nchars = list("abc")\nprint(chars)\n```', "['a', 'b', 'c']", "['abc']", 'abc', "['a b c']",
       explanation='list() 把字串逐字元轉成串列。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [3, 1, 2]\nresult = nums.sort()\nprint(result)\n```', 'None', '[1, 2, 3]', '[3, 1, 2]', '發生錯誤',
       explanation='sort() 就地排序、回傳 None — 常見陷阱。'),
    mc('以下程式的輸出是？\n\n```python\nscores = [70, 85, 90]\ntotal = 0\nfor s in scores:\n    total += s\nprint(total // len(scores))\n```', '81', '245', '82', '80',
       explanation='245 // 3 = 81。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "Python"\nprint(text[2:4] + text[0])\n```', 'thP', 'Pth', 'yhP', 'tho'),
    mc('以下程式的輸出是？\n\n```python\ndata = "a-b-c"\nprint(data.split("-")[1] * 3)\n```', 'bbb', 'b3', 'abc', 'b-b-b'),
    mc('以下程式的輸出是？\n\n```python\nnames = ["Bob", "Amy", "Cindy"]\nnames.sort()\nprint(names[0])\n```', 'Amy', 'Bob', 'Cindy', '發生錯誤',
       explanation='字串排序依字典序。'),
    mc('以下程式的輸出是？\n\n```python\nnums = []\nfor i in range(3):\n    nums.append(i * i)\nprint(nums)\n```', '[0, 1, 4]', '[1, 4, 9]', '[0, 1, 2]', '[9]'),
    mc('以下程式的輸出是？\n\n```python\ntext = "aabbcc"\nprint(text.count("a") + text.find("b"))\n```', '4', '2', '6', '5',
       explanation='count("a")=2、find("b")=2。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, 2, 3]\nnums.insert(0, 0)\nnums.pop()\nprint(nums)\n```', '[0, 1, 2]', '[1, 2, 3]', '[0, 1, 2, 3]', '[0, 2, 3]'),
    mc('以下程式的輸出是？\n\n```python\nline = "60 70 80"\nscores = line.split()\nprint(int(scores[0]) + int(scores[-1]))\n```', '140', '130', '150', '6080'),
    mc('以下程式的輸出是？\n\n```python\nwords = ["hi"] * 2 + ["yo"]\nprint(len(words), words[-1])\n```', '3 yo', '2 hi', '3 hi', '2 yo'),
    mc('以下程式的輸出是？\n\n```python\ntext = "banana"\nnew = text.replace("a", "o")\nprint(new)\n```', 'bonono', 'banana', 'bonana', 'bnn',
       explanation='replace 產生新字串，全部取代。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [4, 8, 15]\nnums[1] = nums[1] + nums[0]\nprint(nums)\n```', '[4, 12, 15]', '[4, 8, 15]', '[8, 12, 15]', '[4, 12, 19]'),
    mc('以下程式的輸出是？\n\n```python\ns = "Amy,88,92"\nparts = s.split(",")\nprint(parts[0], int(parts[1]) + int(parts[2]))\n```', 'Amy 180', 'Amy 8892', '88 92', 'Amy180'),
    mc('以下程式的輸出是？\n\n```python\nstack = []\nstack.append("a")\nstack.append("b")\nprint(stack.pop())\n```', 'b', 'a', "['a', 'b']", '發生錯誤',
       explanation='pop 取出最後放入的（堆疊行為）。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "  Python  "\nprint("[" + text.strip() + "]")\n```', '[Python]', '[  Python  ]', 'Python', '[ Python ]'),

    # 觀念（28）
    mc('a = b 與 a = b.copy() 的差別是？', '前者兩名稱指向同一串列、後者產生獨立副本',
       '完全相同', '前者比較安全', '後者會清空 b'),
    mc('切片 nums[:] 的效果等同於？', 'nums.copy()', 'nums.sort()', 'nums.pop()', 'del nums'),
    mc('串列生成式 [n * 2 for n in nums] 的作用是？', '產生每個元素乘 2 的新串列',
       '把 nums 就地乘 2', '刪除偶數', '排序'),
    mc('修改「用 = 指定的第二個名稱」會影響原串列，這個現象稱為？', 'aliasing（同一物件的別名）',
       'copying', 'sorting', 'casting'),
    mc('remove(x) 在串列中找不到 x 時會？', '引發 ValueError', '回傳 -1', '默默跳過', '回傳 None'),
    mc('pop() 在空串列上執行會？', '引發 IndexError', '回傳 None', '回傳 0', '自動新增元素'),
    mc('元組適合用來存放什麼資料？', '不應被修改的固定資料（如座標）', '需要频繁增刪的資料',
       '只有數字', '需要排序的資料'),
    mc('字串的 upper()、strip() 等方法會？', '回傳新字串，原字串不變', '就地修改原字串',
       '刪除原字串', '只改第一個字元'),
    mc('要把 "80,90,70" 變成整數串列 [80, 90, 70]，正確流程是？',
       '先 split(",") 再對每個元素 int()', '直接 int()', '先 int() 再 split()', 'join 後 int()'),
    mc('串列切片 nums[1:3] 取出的是？', '索引 1 和 2 的元素', '索引 1、2、3 的元素',
       '第 1 到第 3 個元素', '索引 3 以後的元素'),
    mc('負索引 -2 代表？', '倒數第二個元素', '第二個元素', '刪除兩個', '發生錯誤'),
    mc('join 的呼叫者（點號前面的字串）是什麼角色？', '接合時使用的分隔字串', '要被拆開的字串',
       '第一個元素', '結尾符號'),
    mc('split 與 join 的關係是？', '互為相反操作（拆開／接合）', '完全相同',
       '都會排序', '都改變原字串'),
    mc('哪一個操作「不會」改變原串列？', 'sorted(nums)', 'nums.sort()', 'nums.append(1)', 'nums.pop()'),
    mc('in 運算子用在字串時的行為是？', '判斷子字串是否出現', '只判斷單一字元',
       '回傳位置', '計算次數'),
    mc('要同時保留原始串列並得到排序結果，應該用？', 'sorted()', 'sort()', 'reverse()', 'copy() 後不排序'),
    mc('切片超出範圍（如 "abc"[1:10]）會發生什麼？', '回傳能取到的部分 "bc"，不會報錯',
       '引發 IndexError', '回傳空字串', '補上空白'),
    mc('find() 與 in 的差別是？', 'find 回傳位置（找不到 -1）、in 回傳 True/False',
       '完全相同', 'in 回傳位置', 'find 只能找字母'),
    mc('nums = [1, [2, 3]] 的長度 len(nums) 是？', '2', '3', '1', '發生錯誤',
       explanation='內層串列整個算一個元素。'),
    mc('把使用者輸入的一行多個數字讀進串列，常見寫法是？', 'input().split()',
       'input().join()', 'list(input) 不加括號', 'input.split'),
    mc('字串與串列的共同點是？', '都有長度、可索引、可切片', '都可以就地修改',
       '都能 append', '都會自動排序'),
    mc('哪個方法可以「一次移除所有」符合條件的元素？', '沒有現成方法，需用迴圈或生成式過濾',
       'remove()', 'pop()', 'delete_all()'),
    mc('tuple 用什麼符號建立？', '小括號 ( )', '中括號 [ ]', '大括號 { }', '角括號 < >'),
    mc('對元組執行 point[0] = 5 會發生什麼？', '引發 TypeError（元組不可修改）',
       '正常修改', '自動轉成串列', '刪除元素'),
    mc('清理使用者輸入「先去空白再判斷」的正確順序是？', 'input().strip() 之後再比較',
       '先比較再 strip', '不需要 strip', 'strip 會刪掉所有空格'),
    mc('串列中放不同型態（如 [1, "a", True]）是否允許？', '允許，串列可混放各種型態',
       '不允許', '只能兩種', '會自動轉成字串'),
    mc('sort() 排序中文字串串列的依據是？', '字元編碼順序', '筆畫', '注音', '隨機'),
    mc('要取出字串的「副檔名」（最後一個點之後），適合的工具是？',
       'split(".") 取最後一段', 'strip(".")', 'find 後不切', 'upper()'),

    # ── L2 填空（40）──
    fb('成績加入新分數後由大到小排序，取前三名。\n\n```python\nscores = [88, 72, 95, 61]\nscores.append(84)\nscores.sort(reverse=True)\nprint(scores[:__1__])   # [95, 88, 84]\n```', '3'),
    fb('清理逗號分隔資料的空白。\n\n```python\nraw = " Amy , Bob "\nnames = [n.__1__() for n in raw.split(",")]\nprint(names)   # [\'Amy\', \'Bob\']\n```', 'strip'),
    fb('複製串列，避免改到原本的。\n\n```python\noriginal = [1, 2, 3]\ncopied = original.__1__()\ncopied.append(4)\nprint(original)   # [1, 2, 3]\n```', 'copy'),
    fb('tuple unpacking：把座標拆成兩個變數。\n\n```python\npoint = (25.04, 121.56)\nlat, __1__ = point\nprint(lng)   # 121.56\n```', 'lng'),
    fb('串列生成式：取出所有及格分數。\n\n```python\nscores = [55, 80, 90, 45]\npassed = [s for s in scores __1__ s >= 60]\nprint(passed)   # [80, 90]\n```', 'if'),
    fb('串列生成式：全部打九折。\n\n```python\nprices = [100, 200]\nsale = [p * 0.9 for p __1__ prices]\nprint(sale)   # [90.0, 180.0]\n```', 'in'),
    fb('把一行輸入的數字轉成整數串列。\n\n```python\nnums = [int(x) for x in "3 8 5".__1__()]\nprint(nums)   # [3, 8, 5]\n```', 'split'),
    fb('保留原串列的排序：用 sorted。\n\n```python\nnums = [5, 2, 9]\nordered = __1__(nums)\nprint(ordered, nums)   # [2, 5, 9] [5, 2, 9]\n```', 'sorted'),
    fb('取出前三高分（先排序）。\n\n```python\nscores = [70, 95, 88, 60, 82]\nscores.sort(reverse=True)\ntop3 = scores[:3]\nprint(sum(top3))   # __1__\n```\n\n（填輸出）', '265',
       explanation='95+88+82=265。'),
    fb('把檔名與副檔名分開。\n\n```python\nfilename = "report.final.txt"\nparts = filename.split(".")\nprint(parts[__1__])   # txt\n```', '-1'),
    fb('把字串反轉判斷回文。\n\n```python\ntext = "level"\nprint(text == text[::__1__])   # True\n```', '-1'),
    fb('移除第一個 0 分（無效成績）。\n\n```python\nscores = [80, 0, 90]\nscores.__1__(0)\nprint(scores)   # [80, 90]\n```', 'remove'),
    fb('堆疊操作：後進先出。\n\n```python\nstack = []\nstack.append("A")\nstack.append("B")\nprint(stack.__1__())   # B\n```', 'pop'),
    fb('把三個欄位的資料拆開取分數。\n\n```python\nrecord = "Amy,88,92"\nparts = record.split(",")\ntotal = int(parts[1]) + int(parts[__1__])\nprint(total)   # 180\n```', '2'),
    fb('把單字反過來接成句子。\n\n```python\nwords = ["好", "很", "天氣"]\nwords.reverse()\nprint("".__1__(words))   # 天氣很好\n```', 'join'),
    fb('計算平均分數。\n\n```python\nscores = [80, 90, 70]\nprint(sum(scores) / __1__(scores))   # 80.0\n```', 'len'),
    fb('把大小寫混雜的輸入統一成小寫後比對。\n\n```python\nans = "YeS"\nif ans.__1__() == "yes":\n    print("確認")   # 確認\n```', 'lower'),
    fb('用切片取出西元年。\n\n```python\ndate = "20240706"\nyear = date[:__1__]\nprint(year)   # 2024\n```', '4'),
    fb('在清單開頭插入緊急事項。\n\n```python\ntodo = ["寫作業", "運動"]\ntodo.insert(__1__, "繳費")\nprint(todo[0])   # 繳費\n```', '0'),
    fb('找出關鍵字位置，-1 表示不存在。\n\n```python\ntext = "python is fun"\npos = text.__1__("is")\nprint(pos)   # 7\n```', 'find'),
    fb('串列相加合併兩班名單並計算總人數。\n\n```python\na = ["小明", "小華"]\nb = ["小美"]\nall_students = a __1__ b\nprint(len(all_students))   # 3\n```', '+'),
    fb('把重複名單保留唯一（迴圈判斷 not in）。\n\n```python\nnames = ["A", "B", "A"]\nunique = []\nfor n in names:\n    if n __1__ unique:\n        unique.append(n)\nprint(unique)   # [\'A\', \'B\']\n```', 'not in'),
    fb('每個字元加密位移（取字元後接續）。\n\n```python\ntext = "abc"\nresult = ""\nfor ch in text:\n    result = ch + result\nprint(result)   # __1__\n```\n\n（填輸出）', 'cba'),
    fb('把過長的暱稱截斷為 5 字。\n\n```python\nnickname = "PythonMaster"\nshort = nickname[:__1__]\nprint(short)   # Pytho\n```', '5'),
    fb('比較兩份名單是否相同（排序後比較）。\n\n```python\na = [3, 1, 2]\nb = [1, 2, 3]\nprint(sorted(a) __1__ sorted(b))   # True\n```', '=='),
    fb('把成績每科加 5 分（就地逐一修改）。\n\n```python\nscores = [70, 80]\nfor i in range(len(scores)):\n    scores[i] += __1__\nprint(scores)   # [75, 85]\n```', '5'),
    fb('用 in 檢查違禁字。\n\n```python\nmessage = "這是廣告訊息"\nif "廣告" __1__ message:\n    print("封鎖")   # 封鎖\n```', 'in'),
    fb('把電子郵件的帳號與網域分開。\n\n```python\nemail = "amy@example.com"\nuser = email.split("@")[__1__]\nprint(user)   # amy\n```', '0'),
    fb('數列去頭去尾後求和。\n\n```python\nnums = [99, 3, 5, 7, 99]\nmiddle = nums[1:__1__]\nprint(sum(middle))   # 15\n```', '-1'),
    fb('把姓名正規化：去空白＋首字大寫。\n\n```python\nraw = "  amy  "\nname = raw.strip()\nprint(name[0].__1__() + name[1:])   # Amy\n```', 'upper'),
    fb('隊伍輪替：把第一位移到最後。\n\n```python\nqueue = ["A", "B", "C"]\nfirst = queue.pop(__1__)\nqueue.append(first)\nprint(queue)   # [\'B\', \'C\', \'A\']\n```', '0'),
    fb('把數字字串每個字元轉成整數串列。\n\n```python\ndigits = [int(ch) for ch in "504"]\nprint(sum(digits))   # __1__\n```\n\n（填輸出）', '9'),
    fb('檢查括號是否成對（計數法）。\n\n```python\ntext = "(a(b)c)"\nprint(text.count("(") __1__ text.count(")"))   # True\n```', '=='),
    fb('把最低分換成 60（找到位置再修改）。\n\n```python\nscores = [75, 42, 88]\nlow = scores[0]\npos = 0\nfor i in range(len(scores)):\n    if scores[i] < low:\n        low = scores[i]\n        pos = i\nscores[__1__] = 60\nprint(scores)   # [75, 60, 88]\n```', 'pos'),
    fb('把兩個字串合併後排序字元。\n\n```python\nchars = list("ba" + "dc")\nchars.__1__()\nprint("".join(chars))   # abcd\n```', 'sort'),
    fb('確認車牌末碼（最後一個字元）是否為數字。\n\n```python\nplate = "ABC-1234"\nlast = plate[__1__]\nprint("0" <= last <= "9")   # True\n```', '-1'),
    fb('把課表字串整理成清單並數堂數。\n\n```python\nplan = "國文;英文;數學"\nsubjects = plan.split(__1__)\nprint(len(subjects))   # 3\n```', ['";"', "';'"]),
    fb('刪除購物車最後一項並顯示剩餘。\n\n```python\ncart = ["筆", "尺", "橡皮擦"]\ncart.__1__()\nprint(cart)   # [\'筆\', \'尺\']\n```', 'pop'),
    fb('把座位表第一排整排換成 "X"。\n\n```python\nrow = ["A", "B", "C"]\nfor i in range(len(row)):\n    row[i] = __1__\nprint(row)   # [\'X\', \'X\', \'X\']\n```', ['"X"', "'X'"]),
    fb('把整數串列接成一個字串數字。\n\n```python\nnums = [1, 2, 3]\ntext = "".join(str(n) __1__ n in nums)\nprint(text)   # 123\n```', 'for'),
]


# ── U5 Level 3：35 選擇 + 65 填空（競賽／TQC 實作：aliasing、zip、清理管線）──
U5_L3 = [
    # 進階追蹤（35，含競賽原題）
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\nprint(\'NO\' if str(101) != str(101)[::-1] else \'YES\', end=" ")\nprint(\'NO\' if str(11) != str(11)[::-1] else \'YES\')\n```', 'YES YES', 'NO NO', 'YES NO', 'NO YES',
       explanation='101 與 11 反轉後都與原字串相同（回文）。（113 商業類技藝競賽學科第 8 題）'),
    mc('以下程式的輸出是？\n\n```python\na = [1, 2]\nb = a\nc = a[:]\nb.append(3)\nc.append(4)\nprint(a)\n```', '[1, 2, 3]', '[1, 2, 3, 4]', '[1, 2]', '[1, 2, 4]',
       explanation='b 是別名（影響 a）、c 是切片副本（不影響）。'),
    mc('以下程式的輸出是？\n\n```python\nfor i, name in enumerate(["Amy", "Bob"], start=1):\n    print(i, name)\n```\n\n第二行輸出是？', '2 Bob', '1 Bob', '0 Bob', 'Bob 2',
       explanation='enumerate 同時取得編號與元素。'),
    mc('以下程式的輸出是？\n\n```python\nnames = ["Amy", "Bob"]\nscores = [90, 80]\nfor n, s in zip(names, scores):\n    print(n, s)\n```\n\n第一行輸出是？', 'Amy 90', 'Bob 80', 'Amy Bob', '90 80',
       explanation='zip 把兩串列成對配對。'),
    mc('以下程式的輸出是？\n\n```python\nrecords = ["Amy,88", "Bob,72"]\nparsed = []\nfor r in records:\n    name, score = r.split(",")\n    parsed.append((name, int(score)))\nprint(parsed[1][1])\n```', '72', '88', 'Bob', "('Bob', 72)"),
    mc('以下程式的輸出是？\n\n```python\npairs = [("A", 3), ("B", 1), ("C", 2)]\nordered = sorted(pairs, key=lambda p: p[1])\nprint(ordered[0][0])\n```', 'B', 'A', 'C', '1',
       explanation='依第二欄排序後最小的是 ("B", 1)。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "abc"\ntext[0] = "x"\nprint(text)\n```', '引發 TypeError（字串不可變）', 'xbc', 'abc', 'x'),
    mc('以下程式的輸出是？\n\n```python\nnums = [3, 1, 4, 1, 5]\nprint(max(nums) - min(nums))\n```', '4', '5', '1', '2'),
    mc('以下程式的輸出是？\n\n```python\ndata = "  5, 8 , 2 "\nnums = [int(x.strip()) for x in data.split(",")]\nprint(sum(nums))\n```', '15', '582', '發生錯誤', '10',
       explanation='清理管線：split → strip → int。'),
    mc('以下程式的輸出是？\n\n```python\ngrid = [[1, 2], [3, 4], [5, 6]]\nprint(grid[1][0] + grid[2][1])\n```', '9', '7', '8', '11',
       explanation='3 + 6。'),
    mc('以下程式的輸出是？\n\n```python\nwords = ["cat", "elephant", "ox"]\nlengths = [len(w) for w in words]\nprint(lengths)\n```', '[3, 8, 2]', '[3, 8]', '13', "['cat', 'elephant', 'ox']"),
    mc('以下程式的輸出是？\n\n```python\ntext = "hello world hello"\nprint(text.count("hello"))\n```', '2', '1', '3', '10'),
    mc('以下程式的輸出是？\n\n```python\nnums = [5, 2, 8, 1]\nnums.sort()\nmid = nums[len(nums) // 2]\nprint(mid)\n```', '5', '2', '8', '4',
       explanation='排序後 [1,2,5,8]，索引 2 是 5。'),
    mc('以下程式的輸出是？\n\n```python\na, b, *rest = [1, 2, 3, 4, 5]\nprint(rest)\n```', '[3, 4, 5]', '[1, 2]', '3', '[5]',
       explanation='星號收集剩餘元素。'),
    mc('以下程式的輸出是？\n\n```python\nmatrix = [[1, 2, 3], [4, 5, 6]]\ntotal = 0\nfor row in matrix:\n    total += row[1]\nprint(total)\n```', '7', '5', '9', '21',
       explanation='第二欄：2+5。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "aAbBcC"\nresult = ""\nfor ch in text:\n    if ch.isupper():\n        result += ch\nprint(result)\n```', 'ABC', 'abc', 'aAbBcC', 'A',
       explanation='isupper() 判斷大寫字元。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, 2, 3, 4]\nprint(nums[::-1][0])\n```', '4', '1', '[4, 3, 2, 1]', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nscores = {"90", "80"}\nprint(type(scores).__name__)\n```', 'set', 'list', 'dict', 'tuple',
       explanation='大括號無鍵值對是集合（U8 詳教，此處辨識即可）。'),
    mc('以下程式的輸出是？\n\n```python\ndata = ["b", "a", "c"]\ndata.sort()\ndata.reverse()\nprint(data)\n```', "['c', 'b', 'a']", "['a', 'b', 'c']", "['b', 'a', 'c']", "['c', 'a', 'b']"),
    mc('以下程式的輸出是？\n\n```python\nsentence = "i love python"\nwords = sentence.split()\ncap = [w[0].upper() + w[1:] for w in words]\nprint(" ".join(cap))\n```', 'I Love Python', 'i love python', 'I LOVE PYTHON', 'ILovePython'),
    mc('以下程式的輸出是？\n\n```python\nnums = [2, 7, 4, 9]\nbig = [n for n in nums if n > 5]\nsmall = [n for n in nums if n <= 5]\nprint(len(big), len(small))\n```', '2 2', '1 3', '3 1', '4 0'),
    mc('以下程式的輸出是？\n\n```python\npair = ("x", "y")\na, b = pair\na, b = b, a\nprint(a, b)\n```', 'y x', 'x y', '(y, x)', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ntext = "10:30:45"\nh, m, s = text.split(":")\nprint(int(h) * 3600 + int(m) * 60 + int(s))\n```', '37845', '103045', '3600', '1845',
       explanation='10×3600+30×60+45。'),
    mc('以下程式的輸出是？\n\n```python\nnames = ["Ann", "Bob", "Cat"]\nresult = [n for n in names if "a" in n.lower()]\nprint(result)\n```', "['Ann', 'Cat']", "['Cat']", "['Ann']", "['Ann', 'Bob', 'Cat']",
       explanation='轉小寫後 Ann（ann 含 a）與 Cat 都符合。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, 2, 3]\ndoubled = nums * 2\nnums.append(9)\nprint(doubled)\n```', '[1, 2, 3, 1, 2, 3]', '[1, 2, 3, 9, 1, 2, 3, 9]', '[2, 4, 6]', '[1, 2, 3, 9]',
       explanation='doubled 在 append 前就建立，是獨立新串列。'),
    mc('以下程式的輸出是？\n\n```python\nlog = "ERROR: disk full"\nlevel = log[:log.find(":")]\nprint(level)\n```', 'ERROR', 'disk full', ':', 'ERROR:',
       explanation='取出冒號前的部分。'),
    mc('二維串列 grid = [[0] * 3 for _ in range(2)]，grid[0].append(9) 之後 grid[1] 的長度是？',
       '3', '4', '0', '發生錯誤',
       explanation='生成式建立的每列互相獨立。'),
    mc('以下程式的輸出是？\n\n```python\nvotes = ["A", "B", "A", "A"]\nprint(votes.count("A") > len(votes) / 2)\n```', 'True', 'False', '3', '2',
       explanation='3 票超過半數 2 票。'),
    mc('以下程式的輸出是？\n\n```python\nnums = [10, 20, 30]\nfor i, v in enumerate(nums):\n    nums[i] = v // 10\nprint(nums)\n```', '[1, 2, 3]', '[10, 20, 30]', '[0, 0, 0]', '[1, 2]',
       explanation='用索引就地修改每個元素。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "banana"\npos = []\nfor i in range(len(text)):\n    if text[i] == "a":\n        pos.append(i)\nprint(pos)\n```', '[1, 3, 5]', '[0, 2, 4]', '[1, 3]', '3'),
    mc('哪個寫法可以把二維串列「攤平」成一維？',
       '雙層迴圈逐一 append', 'flatten()', 'sum() 直接用', 'sort()',
       explanation='走訪每列再走訪每個元素。'),
    mc('以下程式的輸出是？\n\n```python\na = (1, 2, 3)\nb = a + (4,)\nprint(len(a), len(b))\n```', '3 4', '4 4', '3 3', '發生錯誤',
       explanation='元組不可變，相加產生新元組。'),
    mc('以下程式的輸出是？\n\n```python\nraw = "A;B,C;D"\nparts = raw.replace(",", ";").split(";")\nprint(len(parts))\n```', '4', '3', '2', '5',
       explanation='先統一分隔符再切割。'),
    mc('以下程式的輸出是？\n\n```python\nscores = [88, 92, 79]\nlabels = ["國", "英", "數"]\nbest = 0\nfor i in range(3):\n    if scores[i] > scores[best]:\n        best = i\nprint(labels[best])\n```', '英', '國', '數', '92',
       explanation='平行串列：用索引對應科目與分數。'),
    mc('切片 nums[len(nums):] 的結果是？', '空串列 []', '整個串列', '最後一個元素', 'IndexError',
       explanation='起點等於長度時取不到任何元素。'),

    # ── L3 填空（65）──
    fb('競賽風格：判斷數字回文。\n\n```python\nn = 12321\ns = str(n)\nprint("YES" if s == s[::__1__] else "NO")   # YES\n```', '-1'),
    fb('成績單解析：取出各科分數並求平均。\n\n```python\nrecord = "Amy,88,92,75"\nparts = record.split(",")\nscores = [int(x) for x in parts[__1__:]]\nprint(sum(scores) / len(scores))   # 85.0\n```', '1'),
    fb('aliasing 測驗：讓 b 的修改「不」影響 a。\n\n```python\na = [1, 2, 3]\nb = a.__1__()\nb.append(4)\nprint(a)   # [1, 2, 3]\n```', 'copy'),
    fb('enumerate 從 1 開始編號印排行榜。\n\n```python\nfor rank, name in enumerate(["Amy", "Bob"], start=__1__):\n    print(rank, name)\n```', '1'),
    fb('zip 配對名字與分數。\n\n```python\nnames = ["Amy", "Bob"]\nscores = [90, 80]\nfor n, s in __1__(names, scores):\n    print(n, s)\n```', 'zip'),
    fb('依成績排序（tuple 第二欄）。\n\n```python\npairs = [("Amy", 88), ("Bob", 95)]\nordered = sorted(pairs, key=lambda p: p[__1__], reverse=True)\nprint(ordered[0][0])   # Bob\n```', '1'),
    fb('二維串列：取出第 2 列第 1 欄。\n\n```python\ngrid = [[1, 2], [3, 4]]\nprint(grid[1][__1__])   # 3\n```', '0'),
    fb('攤平二維串列。\n\n```python\ngrid = [[1, 2], [3, 4]]\nflat = []\nfor row in grid:\n    for v in row:\n        flat.__1__(v)\nprint(flat)   # [1, 2, 3, 4]\n```', 'append'),
    fb('清理管線：split → strip → int。\n\n```python\ndata = " 5 , 8 , 2 "\nnums = [int(x.__1__()) for x in data.split(",")]\nprint(nums)   # [5, 8, 2]\n```', 'strip'),
    fb('把時間字串轉成總秒數。\n\n```python\nt = "01:30:00"\nh, m, s = t.split(":")\nprint(int(h) * 3600 + int(m) * __1__ + int(s))   # 5400\n```', '60'),
    fb('字數統計：計算句子的單字數。\n\n```python\nsentence = "the quick brown fox"\nprint(len(sentence.__1__()))   # 4\n```', 'split'),
    fb('馬拉松成績：找最快（最小值）選手的索引。\n\n```python\ntimes = [245, 198, 220]\nbest = 0\nfor i in range(len(times)):\n    if times[i] < times[__1__]:\n        best = i\nprint(best)   # 1\n```', 'best'),
    fb('把每個名字的首字母接成縮寫。\n\n```python\nnames = ["Guido", "van", "Rossum"]\nabbr = ""\nfor n in names:\n    abbr += n[__1__]\nprint(abbr)   # GvR\n```', '0'),
    fb('過濾負數並平方（生成式雙操作）。\n\n```python\nnums = [3, -1, 4, -2]\nresult = [n ** 2 for n in nums if n __1__ 0]\nprint(result)   # [9, 16]\n```', '>'),
    fb('倒轉句子的單字順序。\n\n```python\nsentence = "a b c"\nwords = sentence.split()\nprint(" ".join(words[::__1__]))   # c b a\n```', '-1'),
    fb('取出前 5 名之外的名單。\n\n```python\nranking = ["A", "B", "C", "D", "E", "F", "G"]\nothers = ranking[__1__:]\nprint(others)   # [\'F\', \'G\']\n```', '5'),
    fb('把巢狀成績表算每人總分。\n\n```python\ntable = [["Amy", 80, 90], ["Bob", 70, 60]]\nfor row in table:\n    print(row[0], row[1] __1__ row[2])\n```', '+'),
    fb('大小寫不敏感的關鍵字搜尋。\n\n```python\ntext = "Python Is Fun"\nprint("is" in text.__1__())   # True\n```', 'lower'),
    fb('把購物明細字串轉總價。\n\n```python\ncart = "120;250;80"\ntotal = 0\nfor p in cart.split(";"):\n    total += int(p)\nprint(__1__)   # 450\n```', 'total'),
    fb('用 zip 計算兩串列對應元素乘積和（內積）。\n\n```python\na = [1, 2, 3]\nb = [4, 5, 6]\ntotal = 0\nfor x, y in zip(a, b):\n    total += x __1__ y\nprint(total)   # 32\n```', '*'),
    fb('走訪同時要索引與值。\n\n```python\nfor i, v in __1__(["x", "y"]):\n    print(i, v)\n```', 'enumerate'),
    fb('列出字串中所有數字字元。\n\n```python\ntext = "a1b22c3"\ndigits = [ch for ch in text if ch.__1__()]\nprint(digits)   # [\'1\', \'2\', \'2\', \'3\']\n```', 'isdigit'),
    fb('把矩陣每列求和成一維串列。\n\n```python\nmatrix = [[1, 2], [3, 4], [5, 6]]\nsums = [row[0] + row[1] for row in __1__]\nprint(sums)   # [3, 7, 11]\n```', 'matrix'),
    fb('隊列操作：先進先出。\n\n```python\nqueue = ["A", "B", "C"]\nfirst = queue.pop(__1__)\nprint(first, queue)   # A [\'B\', \'C\']\n```', '0'),
    fb('把逗號千分位字串轉整數。\n\n```python\nmoney = "1,234,567"\nvalue = int(money.__1__(",", ""))\nprint(value + 1)   # 1234568\n```', 'replace'),
    fb('統計及格與不及格（平行累計）。\n\n```python\nscores = [55, 88, 62, 40]\nresult = ["及格" if s >= 60 else "不及格" for s in scores]\nprint(result.count(__1__))   # 2\n```', ['"及格"', "'及格'"]),
    fb('去除字串所有空格（不只兩端）。\n\n```python\ntext = "a b  c"\nprint(text.replace(" ", __1__))   # abc\n```', ['""', "''"]),
    fb('每三個字元切一段。\n\n```python\ncode = "abcdefghi"\nfor i in range(0, len(code), __1__):\n    print(code[i:i + 3])\n```', '3'),
    fb('把身高串列配上名字找最高者。\n\n```python\nnames = ["Amy", "Bob", "Cid"]\nheights = [160, 175, 168]\ntall = 0\nfor i in range(3):\n    if heights[i] > heights[tall]:\n        tall = i\nprint(names[__1__])   # Bob\n```', 'tall'),
    fb('把段落切成句子（以句號）並數句數。\n\n```python\npara = "今天晴。明天雨。後天陰。"\nsentences = [s for s in para.split("。") if s]\nprint(__1__(sentences))   # 3\n```', 'len'),
    fb('用切片每兩個字元取一個做抽樣。\n\n```python\ndata = "0123456789"\nsampled = data[::__1__]\nprint(sampled)   # 02468\n```', '2'),
    fb('把撲克牌字串拆成花色與點數。\n\n```python\ncard = "黑桃-A"\nsuit, rank = card.split(__1__)\nprint(rank)   # A\n```', ['"-"', "'-'"]),
    fb('計算購物車折扣後總價（生成式＋sum）。\n\n```python\nprices = [100, 200, 300]\nprint(__1__(p * 0.9 for p in prices))   # 540.0\n```', 'sum'),
    fb('保留字串前 3 與後 3 字元、中間打碼。\n\n```python\nphone = "0912345678"\nmasked = phone[:3] + "****" + phone[__1__:]\nprint(masked)   # 091****5678\n```', '-4',
       explanation='後 4 碼是 5678。'),
    fb('兩兩交換相鄰元素。\n\n```python\nnums = [1, 2, 3, 4]\nfor i in range(0, 4, 2):\n    nums[i], nums[i + 1] = nums[i + 1], nums[__1__]\nprint(nums)   # [2, 1, 4, 3]\n```', 'i'),
    fb('把成績轉等第（巢狀三元＋生成式）。\n\n```python\nscores = [95, 72, 55]\ngrades = ["A" if s >= 90 else ("B" if s >= 60 else "C") for s in scores]\nprint(grades)   # [\'A\', \'B\', \'C\']\n```\n\n72 分對應的等第是？（填答案）', 'B'),
    fb('接龍檢查：前一個字尾是否等於下一個字首。\n\n```python\nwords = ["大海", "海洋", "洋蔥"]\nok = True\nfor i in range(1, 3):\n    if words[i - 1][-1] != words[i][__1__]:\n        ok = False\nprint(ok)   # True\n```', '0'),
    fb('票數統計找最高票。\n\n```python\nvotes = ["A", "B", "A", "C", "A"]\nbest = ""\nbest_n = 0\nfor c in ["A", "B", "C"]:\n    n = votes.__1__(c)\n    if n > best_n:\n        best_n = n\n        best = c\nprint(best, best_n)   # A 3\n```', 'count'),
    fb('把清單每項編號輸出成選單。\n\n```python\nitems = ["紅茶", "綠茶"]\nfor i, item in enumerate(items, start=1):\n    print(f"{i}. {__1__}")\n```', 'item'),
    fb('檢查學號格式：必須以 "S" 開頭且長度 6。\n\n```python\nsid = "S12345"\nok = sid[0] == "S" and len(sid) == __1__\nprint(ok)   # True\n```', '6'),
    fb('把兩科成績表相加成總分表。\n\n```python\nmid = [80, 70]\nfinal = [90, 85]\ntotal = [mid[i] + final[i] for i in range(__1__)]\nprint(total)   # [170, 155]\n```', '2'),
    fb('倒著取出每列最後一欄。\n\n```python\ngrid = [[1, 9], [2, 8], [3, 7]]\nlast_col = [row[-1] for row in grid]\nprint(last_col[::-1])   # [7, 8, 9]\n```\n\n空格：row[__1__] 取每列最後一欄。', '-1'),
    fb('模擬洗牌後發前兩張（用切片）。\n\n```python\ndeck = ["A", "K", "Q", "J"]\nhand = deck[:__1__]\nprint(hand)   # [\'A\', \'K\']\n```', '2'),
    fb('把課程時間字串轉分鐘數。\n\n```python\nduration = "2h30m"\nh = int(duration[:duration.find("h")])\nm = int(duration[duration.find("h") + 1:duration.find(__1__)])\nprint(h * 60 + m)   # 150\n```', ['"m"', "'m'"]),
    fb('列出所有相鄰差值。\n\n```python\nnums = [3, 7, 12]\ndiffs = [nums[i + 1] - nums[i] for i in range(len(nums) - __1__)]\nprint(diffs)   # [4, 5]\n```', '1'),
    fb('大樂透號碼排序後找最大間距。\n\n```python\nballs = [7, 33, 12, 41]\nballs.sort()\ngap = 0\nfor i in range(1, 4):\n    d = balls[i] - balls[i - 1]\n    if d > gap:\n        gap = __1__\nprint(gap)   # 21\n```', 'd',
       explanation='排序後 7,12,33,41，最大間距 33-12=21。'),
    fb('把名單旋轉 k 位（切片重組）。\n\n```python\nnames = ["A", "B", "C", "D"]\nk = 1\nrotated = names[k:] + names[:__1__]\nprint(rotated)   # [\'B\', \'C\', \'D\', \'A\']\n```', 'k'),
    fb('過濾空字串（split 後可能有空段）。\n\n```python\nraw = "a,,b,"\nparts = [p for p in raw.split(",") if p != __1__]\nprint(parts)   # [\'a\', \'b\']\n```', ['""', "''"]),
    fb('字元頻率最高者（用 count 逐字檢查）。\n\n```python\ntext = "aabbbcc"\nbest = ""\nfor ch in "abc":\n    if text.count(ch) > text.count(best):\n        best = __1__\nprint(best)   # b\n```', 'ch'),
    fb('把矩陣主對角線取出。\n\n```python\nm = [[5, 1, 2], [3, 6, 4], [7, 8, 9]]\ndiag = [m[i][__1__] for i in range(3)]\nprint(diag)   # [5, 6, 9]\n```', 'i'),
    fb('IP 位址取出第三段。\n\n```python\nip = "192.168.1.100"\nprint(ip.split(".")[__1__])   # 1\n```', '2'),
    fb('把清單內容左右互換（前半與後半）。\n\n```python\nnums = [1, 2, 3, 4]\nhalf = len(nums) // 2\nswapped = nums[half:] + nums[:__1__]\nprint(swapped)   # [3, 4, 1, 2]\n```', 'half'),
    fb('找出兩份名單的共同成員。\n\n```python\na = ["Amy", "Bob", "Cid"]\nb = ["Bob", "Dan"]\ncommon = [x for x in a if x __1__ b]\nprint(common)   # [\'Bob\']\n```', 'in'),
    fb('把秒數轉「分:秒」格式（補零）。\n\n```python\nsec = 125\nprint(f"{sec // 60}:{sec % 60:02__1__}")   # 2:05\n```', 'd'),
    fb('去掉最高與最低分後平均（先排序）。\n\n```python\nscores = [10, 8, 9, 6, 7]\nscores.sort()\ntrimmed = scores[1:__1__]\nprint(sum(trimmed) / len(trimmed))   # 8.0\n```', '-1',
       explanation='去掉 6 與 10，剩 7,8,9。'),
    fb('檢查是否已排序（相鄰比較）。\n\n```python\nnums = [1, 3, 5]\nok = True\nfor i in range(1, len(nums)):\n    if nums[i] __1__ nums[i - 1]:\n        ok = False\nprint(ok)   # True\n```', '<'),
    fb('把字串每個字元與位置印成表。\n\n```python\nfor i in range(len("abc")):\n    print(i, "abc"[__1__])\n```', 'i'),
    fb('模擬報數淘汰：每次移除第一個（共移除 2 次）。\n\n```python\npeople = ["A", "B", "C", "D"]\nfor _ in range(2):\n    people.pop(__1__)\nprint(people)   # [\'C\', \'D\']\n```', '0'),
    fb('計算字串中母音個數。\n\n```python\ntext = "education"\ncount = 0\nfor ch in text:\n    if ch __1__ "aeiou":\n        count += 1\nprint(count)   # 5\n```', 'in'),
    fb('把消費紀錄依金額排序取最大兩筆的總和。\n\n```python\nspend = [320, 150, 480, 90]\nspend.sort(reverse=True)\nprint(sum(spend[:__1__]))   # 800\n```', '2'),
    fb('把字串切成前後兩半。\n\n```python\ntext = "abcdef"\nhalf = len(text) // 2\nprint(text[:half], text[half:__1__])   # abc def\n```\n\n空格處讓後半取到字串結尾（可留空的位置應填什麼長度值）？提示：len(text)。', 'len(text)',
       explanation='text[half:len(text)] 等同 text[half:]。'),
    fb('用 join 把座標元組轉字串。\n\n```python\npoint = (25, 121)\nprint(",".join(str(v) __1__ v in point))   # 25,121\n```', 'for'),
    fb('刪除黑名單中的人。\n\n```python\nmembers = ["A", "B", "C"]\nbanned = "B"\nif banned in members:\n    members.__1__(banned)\nprint(members)   # [\'A\', \'C\']\n```', 'remove'),
    fb('拼接多行地址成單行（去換行）。\n\n```python\nlines = ["台北市", "中正區", "重慶南路"]\nprint("".__1__(lines))   # 台北市中正區重慶南路\n```', 'join'),
    fb("把姓名與成績兩串列包成配對串列。\n\n```python\nnames = ['Amy', 'Bob']\nscores = [90, 80]\npairs = list(__1__(names, scores))\nprint(len(pairs))   # 2\n```", 'zip'),
]
