"""Unit 8（遞迴與 Dictionary 應用）題庫 — 全選擇制。

L1 對標 ITS（字典基本操作、遞迴概念、set 辨識）、
L2 對標 TQC+ 觀念題（遞迴追蹤、字典遍歷、詞頻、集合運算）、
L3 對標競賽／TQC 實作（遞迴組合、字典建模；收錄競賽第 6、10、21、23 題）。
"""
from .question_helpers import mc, fb

# ── U8 Level 1：55 選擇 + 45 填空 ──
U8_L1 = [
    # 字典基本（16）
    mc('字典用什麼方式保存資料？', '鍵（key）與值（value）配對', '只有索引',
       '固定順序的數字', '只有字串'),
    mc('建立字典使用哪種括號？', '大括號 { }', '中括號 [ ]', '小括號 ( )', '角括號 < >'),
    mc('student = {"name": "Amy"} 時，student["name"] 的結果是？', 'Amy', 'name', 'None', '發生錯誤'),
    mc('要新增一組鍵值 student["age"] = 16，這個動作是？', '新增（若鍵不存在）或修改（若存在）',
       '刪除', '排序', '查詢'),
    mc('字典用什麼當「索引」來取值？', '鍵（key）', '位置編號', '長度', '型態'),
    mc('存取字典中「不存在的鍵」會發生什麼？', '引發 KeyError', '回傳 None',
       '回傳 0', '自動新增'),
    mc('取得字典所有「鍵」的方法是？', 'keys()', 'values()', 'items()', 'getkeys()'),
    mc('取得字典所有「值」的方法是？', 'values()', 'keys()', 'items()', 'getvals()'),
    mc('同時取得鍵與值來遍歷的方法是？', 'items()', 'keys()', 'values()', 'pairs()'),
    mc('scores = {"A": 90}; scores["A"] = 95 之後，scores["A"] 是？', '95', '90', '185', '發生錯誤'),
    mc('len({"a": 1, "b": 2}) 的結果是？', '2', '4', '1', '3',
       explanation='字典長度是鍵值對的數量。'),
    mc('判斷鍵 "name" 是否在字典 d 中，寫法是？', '"name" in d', 'd.has("name")',
       'name in d.values()', 'd["name"] == True'),
    mc('get("x", 0) 方法的作用是？', '取得鍵 x 的值，不存在時回傳預設值 0',
       '一定回傳 0', '刪除 x', '新增 x'),
    mc('字典的鍵可以重複嗎？', '不可以，鍵是唯一的', '可以重複', '最多兩個相同', '只有數字鍵可重複'),
    mc('d = {"a": 1}; d["b"] = 2 之後 d 是？', "{'a': 1, 'b': 2}", "{'a': 1}", "{'b': 2}", "{'a': 2}"),
    mc('刪除字典中某個鍵可以用？', 'del d["key"]', 'd.remove("key")', 'd.pop()', 'd - "key"'),

    # 遞迴概念（14）
    mc('遞迴函式指的是？', '函式呼叫自己', '有兩個參數的函式', '很長的函式', '沒有回傳值的函式'),
    mc('遞迴函式不可缺少的是？', '終止條件', 'while 迴圈', '全域變數', '字典'),
    mc('沒有終止條件的遞迴會？', '無限遞迴（最後導致錯誤）', '正常結束', '回傳 0', '自動停止'),
    mc('遞迴的每次呼叫應該讓問題規模如何變化？', '縮小（逐步靠近終止條件）', '放大',
       '不變', '隨機'),
    mc('countdown(3) 呼叫 countdown(2) 呼叫 countdown(1)…這是遞迴的哪個部分？',
       '遞迴步驟（問題縮小）', '終止條件', '回傳值', '參數宣告'),
    mc('遞迴與迴圈的關係是？', '很多遞迴可以改寫成迴圈，反之亦然', '完全不同無法互換',
       '遞迴一定比較快', '迴圈不能重複'),
    mc('階乘 factorial(n) 的終止條件通常是？', 'n <= 1 時回傳 1', 'n == 100',
       'n 是偶數', '沒有終止條件'),
    mc('讀懂遞迴的第一步是？', '先找出「何時停止」（終止條件）', '先數行數',
       '先看回傳值', '先改成迴圈'),
    mc('遞迴呼叫時，每一層都會？', '在記憶體中保留自己的區域變數', '共用同一組變數',
       '刪除上一層', '不佔記憶體'),
    mc('factorial(0) 若終止條件是 n <= 1 回傳 1，結果是？', '1', '0', '發生錯誤', 'None'),
    mc('遞迴函式 f 呼叫 f 時，若忘記縮小問題會？', '無限遞迴', '正常結束', '回傳最大值', '跳過'),
    mc('「先學字典再學遞迴」的建議中，看到遞迴要先圈出？', '何時停止與問題如何縮小',
       '變數名稱', '縮排格數', '回傳型態'),
    mc('遞迴計算 1 到 n 的總和，n=1 時應該回傳？', '1', '0', 'n', 'None'),
    mc('遞迴每呼叫一次，離終止條件應該？', '更近一步', '更遠', '不變', '看情況'),

    # set 與遍歷追蹤（12）
    mc('set(["A", "B", "A"]) 的結果元素個數是？', '2', '3', '1', '0',
       explanation='集合自動去除重複。'),
    mc('集合（set）的特性是？', '元素不重複', '有固定順序', '可用索引取值', '鍵值成對'),
    mc('建立集合可以用哪種括號？', '大括號 { }（有元素時）或 set()', '中括號 [ ]',
       '小括號 ( )', '角括號'),
    mc('以下程式的輸出是？\n\n```python\nd = {"a": 1, "b": 2}\nfor k in d:\n    print(k, end=" ")\n```', 'a b', '1 2', 'a 1 b 2', "('a', 'b')",
       explanation='直接遍歷字典會取得「鍵」。'),
    mc('以下程式的輸出是？\n\n```python\nd = {"x": 10, "y": 20}\ntotal = 0\nfor v in d.values():\n    total += v\nprint(total)\n```', '30', '10', 'xy', '2'),
    mc('以下程式的輸出是？\n\n```python\nd = {"a": 1}\nd["b"] = 2\nd["a"] = 5\nprint(d["a"] + d["b"])\n```', '7', '3', '8', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nscores = {"Amy": 88}\nprint(scores.get("Bob", 0))\n```', '0', 'None', '88', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nnames = {"Amy", "Bob", "Amy", "Cid"}\nprint(len(names))\n```', '3', '4', '2', '1'),
    mc('以下程式的輸出是？\n\n```python\nd = {"a": 1, "b": 2, "c": 3}\nprint(len(d.keys()))\n```', '3', '6', '1', '2'),
    mc('以下程式的輸出是？\n\n```python\ndef countdown(n):\n    if n == 0:\n        return\n    print(n, end=" ")\n    countdown(n - 1)\n\ncountdown(3)\n```', '3 2 1', '1 2 3', '0 1 2 3', '3'),
    mc('以下程式的輸出是？\n\n```python\ndef fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(4))\n```', '24', '10', '12', '4'),
    mc('以下程式的輸出是？\n\n```python\nphone = {"Amy": "0912", "Bob": "0987"}\nif "Amy" in phone:\n    print(phone["Amy"])\n```', '0912', 'Amy', 'True', '0987'),

    # 綜合追蹤（13）
    mc('以下程式的輸出是？\n\n```python\nstudent = {"name": "Amy", "score": 88}\nstudent["score"] += 2\nprint(student["score"])\n```', '90', '88', '2', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nd = {}\nd["count"] = d.get("count", 0) + 1\nd["count"] = d.get("count", 0) + 1\nprint(d["count"])\n```', '2', '1', '0', '發生錯誤',
       explanation='詞頻計數的典型模式。'),
    mc('以下程式的輸出是？\n\n```python\nfruits = {"apple": 3, "banana": 5}\nfor k, v in fruits.items():\n    print(k, v)\n```\n\n第一行輸出是？', 'apple 3', 'banana 5', 'apple banana', '3 5'),
    mc('以下程式的輸出是？\n\n```python\ndef sum_to(n):\n    if n == 0:\n        return 0\n    return n + sum_to(n - 1)\n\nprint(sum_to(3))\n```', '6', '3', '0', '9',
       explanation='3+2+1+0。'),
    mc('以下程式的輸出是？\n\n```python\na = {"x", "y"}\nb = {"y", "z"}\nprint(a & b)\n```', "{'y'}", "{'x', 'z'}", "{'x', 'y', 'z'}", 'set()',
       explanation='& 是交集。'),
    mc('以下程式的輸出是？\n\n```python\na = {1, 2}\nb = {2, 3}\nprint(a | b)\n```', '{1, 2, 3}', '{2}', '{1, 3}', '{1, 2, 2, 3}',
       explanation='| 是聯集。'),
    mc('以下程式的輸出是？\n\n```python\nscores = {"A": 90, "B": 80, "C": 70}\nprint(max(scores.values()))\n```', '90', 'A', '70', 'C'),
    mc('以下程式的輸出是？\n\n```python\nd = {"a": 1, "b": 2}\nif "c" not in d:\n    d["c"] = 3\nprint(len(d))\n```', '3', '2', '4', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndef power(base, n):\n    if n == 0:\n        return 1\n    return base * power(base, n - 1)\n\nprint(power(2, 3))\n```', '8', '6', '9', '5',
       explanation='2 的 3 次方。'),
    mc('以下程式的輸出是？\n\n```python\nvotes = ["A", "B", "A"]\ncount = {}\nfor v in votes:\n    count[v] = count.get(v, 0) + 1\nprint(count["A"])\n```', '2', '1', '3', 'A'),
    mc('以下程式的輸出是？\n\n```python\nnums = [1, 2, 2, 3, 3, 3]\nprint(len(set(nums)))\n```', '3', '6', '2', '1'),
    mc('以下程式的輸出是？\n\n```python\nd = {"name": "Amy", "age": 16}\nprint("age" in d, "Amy" in d)\n```', 'True False', 'True True', 'False True', 'False False',
       explanation='in 檢查的是「鍵」，Amy 是值不是鍵。'),
    mc('以下程式的輸出是？\n\n```python\ndef f(n):\n    if n <= 0:\n        return 0\n    return 1 + f(n - 1)\n\nprint(f(5))\n```', '5', '0', '15', '6',
       explanation='每層加 1，共 5 層。'),

    # ── L1 填空（45）──
    fb('取出字典中 name 的值。\n\n```python\nstudent = {"name": "Amy", "score": 88}\nprint(student[__1__])   # Amy\n```', ['"name"', "'name'"]),
    fb('新增一組鍵值。\n\n```python\nstudent = {"name": "Amy"}\nstudent["age"] = __1__\nprint(student["age"])   # 16\n```', '16'),
    fb('修改分數。\n\n```python\nscores = {"Amy": 88}\nscores["Amy"] = __1__\nprint(scores["Amy"])   # 92\n```', '92'),
    fb('遍歷字典的鍵與值。\n\n```python\nd = {"a": 1, "b": 2}\nfor k, v in d.__1__():\n    print(k, v)\n```', 'items'),
    fb('取得所有值並加總。\n\n```python\nd = {"x": 10, "y": 20}\nprint(sum(d.__1__()))   # 30\n```', 'values'),
    fb('用 get 提供預設值。\n\n```python\nscores = {"Amy": 88}\nprint(scores.__1__("Bob", 0))   # 0\n```', 'get'),
    fb('判斷鍵是否存在。\n\n```python\nphone = {"Amy": "0912"}\nprint("Amy" __1__ phone)   # True\n```', 'in'),
    fb('遞迴階乘的終止條件。\n\n```python\ndef fact(n):\n    if n <= 1:\n        return __1__\n    return n * fact(n - 1)\n\nprint(fact(5))   # 120\n```', '1'),
    fb('遞迴階乘的遞迴步驟。\n\n```python\ndef fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n __1__ 1)\n\nprint(fact(4))   # 24\n```', '-'),
    fb('遞迴倒數的終止判斷。\n\n```python\ndef countdown(n):\n    if n == __1__:\n        return\n    print(n)\n    countdown(n - 1)\n\ncountdown(3)\n```', '0'),
    fb('去除重複元素（用集合）。\n\n```python\nnames = ["Amy", "Bob", "Amy"]\nunique = __1__(names)\nprint(len(unique))   # 2\n```', 'set'),
    fb('詞頻計數。\n\n```python\nwords = ["a", "b", "a"]\ncount = {}\nfor w in words:\n    count[w] = count.get(w, 0) + __1__\nprint(count["a"])   # 2\n```', '1'),
    fb('集合交集。\n\n```python\na = {1, 2, 3}\nb = {2, 3, 4}\nprint(a __1__ b)   # {2, 3}\n```', '&'),
    fb('集合聯集。\n\n```python\na = {1, 2}\nb = {2, 3}\nprint(a __1__ b)   # {1, 2, 3}\n```', '|'),
    fb('取得所有鍵。\n\n```python\nd = {"a": 1, "b": 2}\nprint(list(d.__1__()))   # [\'a\', \'b\']\n```', 'keys'),
    fb('遞迴求 1 到 n 總和。\n\n```python\ndef total(n):\n    if n == 0:\n        return 0\n    return n + total(n - __1__)\n\nprint(total(4))   # 10\n```', '1'),
    fb('字典計算全班平均。\n\n```python\nscores = {"A": 80, "B": 90, "C": 70}\nprint(sum(scores.values()) / __1__(scores))   # 80.0\n```', 'len'),
    fb('新增學生到成績簿。\n\n```python\nbook = {"Amy": 88}\nbook["Bob"] = __1__\nprint(len(book))   # 2\n```', '72'),
    fb('遞迴次方。\n\n```python\ndef power(b, n):\n    if n == 0:\n        return 1\n    return b * power(b, n __1__ 1)\n\nprint(power(3, 2))   # 9\n```', '-'),
    fb('用 in 找學生。\n\n```python\nphone = {"Amy": "0912", "Bob": "0987"}\nif "Bob" __1__ phone:\n    print(phone["Bob"])   # 0987\n```', 'in'),
    fb('遍歷字典印出鍵。\n\n```python\nd = {"x": 1, "y": 2}\nfor k in d.__1__():\n    print(k)\n```', 'keys'),
    fb('找出字典最高分。\n\n```python\nscores = {"A": 90, "B": 85}\nprint(__1__(scores.values()))   # 90\n```', 'max'),
    fb('集合差集。\n\n```python\na = {1, 2, 3}\nb = {2}\nprint(a __1__ b)   # {1, 3}\n```', '-'),
    fb('刪除字典的鍵。\n\n```python\nd = {"a": 1, "b": 2}\n__1__ d["a"]\nprint(d)   # {\'b\': 2}\n```', 'del'),
    fb('遞迴的終止條件（費氏基底）。\n\n```python\ndef fib(n):\n    if n <= 1:\n        return __1__\n    return fib(n - 1) + fib(n - 2)\n\nprint(fib(6))   # 8\n```', 'n'),
    fb('把兩個字典合併（後者覆蓋）。\n\n```python\na = {"x": 1}\nb = {"y": 2}\na.__1__(b)\nprint(len(a))   # 2\n```', 'update'),
    fb('累加字典中某鍵的值。\n\n```python\ninventory = {"apple": 5}\ninventory["apple"] += __1__\nprint(inventory["apple"])   # 8\n```', '3'),
    fb('建立空字典開始收集。\n\n```python\nresult = __1__\nresult["a"] = 1\nprint(result)   # {\'a\': 1}\n```', '{}'),
    fb('遞迴計算列表長度。\n\n```python\ndef my_len(items):\n    if not items:\n        return 0\n    return 1 + my_len(items[__1__:])\n\nprint(my_len([1, 2, 3]))   # 3\n```', '1'),
    fb('用集合判斷是否有重複。\n\n```python\nnums = [1, 2, 2]\nprint(len(nums) != len(set(nums)))   # __1__\n```\n\n（填 True 或 False）', 'True'),
    fb('字典依鍵取值後運算。\n\n```python\nprices = {"筆": 30, "尺": 20}\nprint(prices["筆"] + prices[__1__])   # 50\n```', ['"尺"', "'尺'"]),
    fb('遞迴印出 1 到 n。\n\n```python\ndef up(n):\n    if n == 0:\n        return\n    up(n - 1)\n    print(n, end=" ")\n\nup(3)   # 1 2 3\n```\n\n空格：終止條件 n == __1__。', '0'),
    fb('統計字母出現次數存進字典。\n\n```python\ntext = "aba"\nfreq = {}\nfor ch in text:\n    freq[ch] = freq.get(ch, 0) + 1\nprint(freq["a"])   # __1__\n```\n\n（填輸出）', '2'),
    fb('用集合找兩班共同學生。\n\n```python\nclass_a = {"Amy", "Bob"}\nclass_b = {"Bob", "Cid"}\ncommon = class_a __1__ class_b\nprint(common)   # {\'Bob\'}\n```', '&'),
    fb('遞迴求最大公因數。\n\n```python\ndef gcd(a, b):\n    if b == 0:\n        return a\n    return gcd(b, a __1__ b)\n\nprint(gcd(12, 8))   # 4\n```', '%'),
    fb('字典查詢電話。\n\n```python\ncontacts = {"Amy": "0912", "Bob": "0987"}\nname = "Amy"\nprint(contacts.get(name, "查無此人"))   # __1__\n```\n\n（填輸出）', '0912'),
    fb('把清單轉集合去重再算數量。\n\n```python\ntags = ["py", "ai", "py", "web"]\nprint(len(__1__(tags)))   # 3\n```', 'set'),
    fb('遞迴累乘。\n\n```python\ndef product(nums):\n    if not nums:\n        return 1\n    return nums[0] * product(nums[1:])\n\nprint(product([2, 3, 4]))   # __1__\n```\n\n（填輸出）', '24'),
    fb('字典記錄庫存並補貨。\n\n```python\nstock = {"蛋": 10}\nstock["蛋"] = stock["蛋"] __1__ 5\nprint(stock["蛋"])   # 15\n```', '+'),
    fb('遍歷字典找特定值的鍵。\n\n```python\nages = {"Amy": 16, "Bob": 17}\nfor name, age in ages.items():\n    if age == 17:\n        print(__1__)   # Bob\n```', 'name'),
    fb('遞迴反轉字串。\n\n```python\ndef rev(s):\n    if len(s) <= 1:\n        return s\n    return rev(s[1:]) + s[__1__]\n\nprint(rev("abc"))   # cba\n```', '0'),
    fb('集合聯集算總人數。\n\n```python\na = {"A", "B"}\nb = {"B", "C"}\nprint(len(a __1__ b))   # 3\n```', '|'),
    fb('字典預設值累加建立計數。\n\n```python\nletters = "aabc"\nfreq = {}\nfor ch in letters:\n    freq[ch] = freq.__1__(ch, 0) + 1\nprint(freq)   # {\'a\': 2, \'b\': 1, \'c\': 1}\n```', 'get'),
    fb('遞迴計算數字各位數和。\n\n```python\ndef digit_sum(n):\n    if n == 0:\n        return 0\n    return n % 10 + digit_sum(n __1__ 10)\n\nprint(digit_sum(123))   # 6\n```', '//'),
    fb('把成績字典依值找最低分的科目。\n\n```python\nscores = {"國": 90, "英": 75, "數": 88}\nlow = min(scores, key=scores.__1__)\nprint(low)   # 英\n```', 'get'),
]


# ── U8 Level 2：60 選擇 + 40 填空（TQC+ 觀念題：遞迴追蹤＋字典遍歷）──
U8_L2 = [
    # 遞迴追蹤（20，含競賽原題）
    mc('以下程式的輸出是？（TQC 資料加總情境）\n\n```python\ndef calculate(n):\n    if n == 0:\n        return 0\n    return n + calculate(n - 1)\nprint(calculate(4) % 4)\n```', '2', '0', '1', '3',
       explanation='4+3+2+1=10，10%4=2。（113 商業類技藝競賽學科第 6 題）'),
    mc('以下程式的輸出是？\n\n```python\ndef factorial(n):\n    if n == 0:\n        return 1\n    return n * factorial(n - 1)\nprint(factorial(3) % 4)\n```', '2', '0', '1', '3',
       explanation='3!=6，6%4=2。（113 商業類技藝競賽學科第 10 題）'),
    mc('以下程式的輸出是？\n\n```python\ndef calc(x):\n    if x == 0:\n        return 4\n    return calc(x - 1) + 4\nprint(calc(3) % 4)\n```', '0', '1', '2', '3',
       explanation='4×4=16，16%4=0。（113 商業類技藝競賽學科第 21 題）'),
    mc('以下程式的輸出是？\n\n```python\ndef calc(x):\n    if x < 2:\n        return x\n    return calc(x - 1) + calc(x - 2)\nprint(calc(5) % 4)\n```', '1', '0', '2', '3',
       explanation='費氏 calc(5)=5，5%4=1。（113 商業類技藝競賽學科第 23 題）'),
    mc('以下程式的輸出是？\n\n```python\ndef fib(n):\n    if n <= 1:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\nprint(fib(7))\n```', '13', '8', '21', '11'),
    mc('以下程式的輸出是？\n\n```python\ndef mystery(n):\n    if n == 1:\n        return 1\n    return n + mystery(n - 1)\n\nprint(mystery(5))\n```', '15', '5', '10', '120',
       explanation='5+4+3+2+1。'),
    mc('以下程式的輸出是？\n\n```python\ndef f(n):\n    if n == 0:\n        return 0\n    return 2 + f(n - 1)\n\nprint(f(4))\n```', '8', '4', '16', '2',
       explanation='每層加 2，共 4 層。'),
    mc('以下程式的輸出是？\n\n```python\ndef count_down(n):\n    if n < 0:\n        return\n    print(n, end="")\n    count_down(n - 2)\n\ncount_down(6)\n```', '6420', '6543210', '0246', '6420-2'),
    mc('以下程式的輸出是？\n\n```python\ndef sum_digits(n):\n    if n < 10:\n        return n\n    return n % 10 + sum_digits(n // 10)\n\nprint(sum_digits(456))\n```', '15', '456', '6', '5'),
    mc('以下程式的輸出是？\n\n```python\ndef power(b, e):\n    if e == 0:\n        return 1\n    return b * power(b, e - 1)\n\nprint(power(3, 4))\n```', '81', '12', '64', '27'),
    mc('遞迴階乘 factorial(5) 總共呼叫了函式幾次（含第一次）？', '6 次', '5 次', '4 次', '120 次',
       explanation='factorial(5) 到 factorial(0)。'),
    mc('以下程式的輸出是？\n\n```python\ndef rev(s):\n    if s == "":\n        return ""\n    return rev(s[1:]) + s[0]\n\nprint(rev("abcd"))\n```', 'dcba', 'abcd', 'a', 'dabc'),
    mc('以下遞迴為何會出錯（無限遞迴）？\n\n```python\ndef f(n):\n    return f(n - 1)\n```', '缺少終止條件', '參數太多',
       '沒有 return', '缺少迴圈'),
    mc('以下程式的輸出是？\n\n```python\ndef gcd(a, b):\n    if b == 0:\n        return a\n    return gcd(b, a % b)\n\nprint(gcd(48, 18))\n```', '6', '3', '12', '18',
       explanation='輾轉相除的遞迴版。'),
    mc('以下程式的輸出是？\n\n```python\ndef count_list(items):\n    if not items:\n        return 0\n    return 1 + count_list(items[1:])\n\nprint(count_list([5, 6, 7, 8]))\n```', '4', '3', '26', '5'),
    mc('以下程式的輸出是？\n\n```python\ndef ascending(n):\n    if n == 0:\n        return\n    ascending(n - 1)\n    print(n, end="")\n\nascending(4)\n```', '1234', '4321', '0123', '4'),
    mc('遞迴的每一層在什麼時候真正「回傳」結果？', '碰到終止條件後逐層往回計算',
       '第一次呼叫時', '最外層直接算出', '不需要回傳'),
    mc('以下程式的輸出是？\n\n```python\ndef double_sum(n):\n    if n == 0:\n        return 0\n    return n * 2 + double_sum(n - 1)\n\nprint(double_sum(3))\n```', '12', '6', '18', '3',
       explanation='6+4+2。'),
    mc('把「階乘」改寫成迴圈版與遞迴版，兩者結果？', '相同', '遞迴版比較大',
       '迴圈版比較大', '無法比較'),
    mc('以下程式的輸出是？\n\n```python\ndef f(n):\n    if n == 1:\n        return 1\n    if n % 2 == 0:\n        return f(n // 2)\n    return f(3 * n + 1)\n\nprint(f(8))\n```', '1', '8', '0', '無限遞迴',
       explanation='8→4→2→1。'),

    # 字典追蹤（20）
    mc('以下程式的輸出是？\n\n```python\nscores = {"Amy": 88, "Bob": 72}\nscores["Cid"] = 95\nprint(len(scores))\n```', '3', '2', '4', '95'),
    mc('以下程式的輸出是？\n\n```python\nwords = ["a", "b", "a", "c", "a"]\nfreq = {}\nfor w in words:\n    freq[w] = freq.get(w, 0) + 1\nprint(freq["a"])\n```', '3', '1', '5', '2',
       explanation='詞頻統計。'),
    mc('以下程式的輸出是？\n\n```python\nd = {"x": 1, "y": 2, "z": 3}\ntotal = 0\nfor v in d.values():\n    total += v\nprint(total)\n```', '6', '3', 'xyz', '9'),
    mc('以下程式的輸出是？\n\n```python\nscores = {"A": 90, "B": 80, "C": 85}\nbest = max(scores, key=scores.get)\nprint(best)\n```', 'A', 'C', '90', 'B',
       explanation='max 搭配 key=scores.get 找最高值對應的鍵。'),
    mc('以下程式的輸出是？\n\n```python\nd = {"a": 1}\nprint(d.get("b", "無"))\n```', '無', 'None', '1', 'KeyError'),
    mc('以下程式的輸出是？\n\n```python\nd = {"a": 1, "b": 2}\nfor k, v in d.items():\n    print(f"{k}={v}", end=" ")\n```', 'a=1 b=2', '1=a 2=b', 'a b', '1 2'),
    mc('以下程式的輸出是？\n\n```python\ninventory = {"筆": 3, "尺": 5}\ninventory["筆"] += 2\nprint(inventory["筆"])\n```', '5', '3', '2', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ntext = "hello"\nfreq = {}\nfor ch in text:\n    freq[ch] = freq.get(ch, 0) + 1\nprint(freq["l"])\n```', '2', '1', '3', 'l'),
    mc('以下程式的輸出是？\n\n```python\nd = {"a": 1, "b": 2, "c": 3}\nprint(sorted(d.keys()))\n```', "['a', 'b', 'c']", '[1, 2, 3]', "['c', 'b', 'a']", 'abc'),
    mc('以下程式的輸出是？\n\n```python\nd = {"one": 1, "two": 2}\nif "three" not in d:\n    d["three"] = 3\nprint(sum(d.values()))\n```', '6', '3', '2', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nscores = {"Amy": 88, "Bob": 95, "Cid": 72}\nfor name in sorted(scores):\n    print(name, end=" ")\n```', 'Amy Bob Cid', 'Bob Amy Cid', 'Cid Bob Amy', '88 95 72',
       explanation='sorted(字典) 依鍵排序。'),
    mc('以下程式的輸出是？\n\n```python\nd = {}\nfor i in range(3):\n    d[i] = i * i\nprint(d)\n```', '{0: 0, 1: 1, 2: 4}', '{0: 0, 1: 2, 2: 4}', '{1: 1, 2: 4, 3: 9}', '[0, 1, 4]'),
    mc('以下程式的輸出是？\n\n```python\nmenu = {"茶": 30, "咖啡": 50}\ntotal = 0\nfor price in menu.values():\n    total += price\nprint(total)\n```', '80', '30', '50', '2'),
    mc('以下程式的輸出是？\n\n```python\nstudents = {"Amy": [80, 90], "Bob": [70, 60]}\nprint(sum(students["Amy"]))\n```', '170', '150', '80', '2',
       explanation='字典的值可以是串列。'),
    mc('以下程式的輸出是？\n\n```python\nd = {"a": 1, "b": 2}\nd.pop("a")\nprint(d)\n```', "{'b': 2}", "{'a': 1}", "{}", '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ncount = {"red": 2, "blue": 3}\ncount["red"] = count["red"] + count["blue"]\nprint(count["red"])\n```', '5', '2', '3', '6'),
    mc('以下程式的輸出是？\n\n```python\nscores = {"A": 60, "B": 90}\npassed = [k for k, v in scores.items() if v >= 60]\nprint(passed)\n```', "['A', 'B']", "['B']", "['A']", '[60, 90]'),
    mc('以下程式的輸出是？\n\n```python\ninventory = {"apple": 0, "banana": 5}\nempty = [k for k, v in inventory.items() if v == 0]\nprint(empty)\n```', "['apple']", "['banana']", '[]', "['apple', 'banana']"),
    mc('以下程式的輸出是？\n\n```python\nd = {"x": 10}\nvalue = d.get("y", 0) + d.get("x", 0)\nprint(value)\n```', '10', '0', '20', 'None'),
    mc('以下程式的輸出是？\n\n```python\ngrades = {"Amy": "A", "Bob": "B", "Cid": "A"}\ncount_a = list(grades.values()).count("A")\nprint(count_a)\n```', '2', '1', '3', 'A'),

    # 觀念（20）
    mc('遞迴三要素是？', '終止條件、問題縮小、組合子問題結果', '迴圈、變數、輸出',
       '參數、回傳、縮排', '字典、集合、串列'),
    mc('字典的「值」可以是哪些型態？', '任何型態（數字、字串、串列、甚至字典）', '只能是數字',
       '只能是字串', '只能是串列'),
    mc('字典的「鍵」通常必須是？', '不可變型態（字串、數字、元組）', '只能是字串',
       '可以是串列', '任何型態都行'),
    mc('d.get("x", 0) 相較於 d["x"] 的好處是？', '鍵不存在時不會報錯（回傳預設值）',
       '執行較快', '會自動排序', '可以刪除'),
    mc('詞頻統計用 freq[w] = freq.get(w, 0) + 1 的原理是？',
       '第一次出現時用預設 0，之後累加', '每次都設成 1', '刪除重複', '排序'),
    mc('集合（set）與字典（dict）的共同點是？', '都用大括號、元素/鍵不重複',
       '都有順序', '都用鍵取值', '都可以用索引'),
    mc('遞迴太深（如 factorial(10000)）可能發生什麼？', 'RecursionError（超過遞迴深度限制）',
       '執行變快', '自動改成迴圈', '沒有影響'),
    mc('集合運算 a & b 代表？', '交集（同時在兩者中）', '聯集', '差集', '對稱差'),
    mc('集合運算 a - b 代表？', '差集（在 a 但不在 b）', '交集', '聯集', '相減數值'),
    mc('要「統計每個元素出現次數」，最適合的資料結構是？', '字典（元素當鍵、次數當值）',
       '集合', '單一變數', '元組'),
    mc('sorted(d.items()) 會依什麼排序？', '預設依鍵（key）排序', '依值排序',
       '不排序', '隨機'),
    mc('要依「值」排序字典，需要？', '指定 key=lambda item: item[1]', '直接 sorted(d)',
       '用 d.sort()', '無法排序'),
    mc('遞迴函式與呼叫自己的無窮迴圈差別在？', '遞迴有終止條件會停止',
       '沒有差別', '遞迴比較慢所以會停', '遞迴不佔記憶體'),
    mc('把清單去重「且保留唯一」，用集合的缺點是？', '會失去原本的順序',
       '無法去重', '會報錯', '速度太慢'),
    mc('字典適合用來建模「學生資料」的原因是？', '用有意義的鍵（name、scores）取值，可讀性高',
       '比串列快十倍', '不佔記憶體', '自動排序'),
    mc('遞迴「組合子問題結果」的例子是？', 'factorial：return n * factorial(n-1)',
       'return 0', 'print(n)', 'n += 1'),
    mc('in 運算子用在字典 d 時，檢查的是？', '鍵是否存在', '值是否存在',
       '長度', '型態'),
    mc('把兩個字典合併，後者覆蓋前者相同鍵，用？', 'd1.update(d2)', 'd1 + d2',
       'd1 & d2', 'd1.append(d2)'),
    mc('遞迴 binary_search 相比線性搜尋的優勢是？', '每次排除一半、較快（需已排序）',
       '不需要排序', '一定比較慢', '不用終止條件'),
    mc('巢狀字典 students["S001"]["name"] 代表？', '先用 S001 取內層字典、再取 name',
       '取兩個值相加', '發生錯誤', '取第一個字元'),

    # ── L2 填空（40）──
    fb('遞迴階乘。\n\n```python\ndef factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - __1__)\n\nprint(factorial(5))   # 120\n```', '1'),
    fb('遞迴費氏數列。\n\n```python\ndef fib(n):\n    if n <= 1:\n        return n\n    return fib(n - 1) + fib(n - __1__)\n\nprint(fib(7))   # 13\n```', '2'),
    fb('遞迴求和的終止條件。\n\n```python\ndef total(n):\n    if n == __1__:\n        return 0\n    return n + total(n - 1)\n\nprint(total(5))   # 15\n```', '0'),
    fb('詞頻計數（get 預設值）。\n\n```python\nwords = "a b a c a".split()\nfreq = {}\nfor w in words:\n    freq[w] = freq.__1__(w, 0) + 1\nprint(freq["a"])   # 3\n```', 'get'),
    fb('遍歷字典的鍵值對。\n\n```python\nscores = {"Amy": 88, "Bob": 72}\nfor name, score in scores.__1__():\n    print(name, score)\n```', 'items'),
    fb('找出字典最高分對應的鍵。\n\n```python\nscores = {"A": 80, "B": 95, "C": 70}\nbest = max(scores, key=scores.__1__)\nprint(best)   # B\n```', 'get'),
    fb('集合交集找共同選課。\n\n```python\npy = {"Amy", "Bob"}\nai = {"Bob", "Cid"}\nprint(py __1__ ai)   # {\'Bob\'}\n```', '&'),
    fb('遞迴次方。\n\n```python\ndef power(b, e):\n    if e == 0:\n        return 1\n    return b * power(b, e - __1__)\n\nprint(power(2, 5))   # 32\n```', '1'),
    fb('遞迴各位數和。\n\n```python\ndef digit_sum(n):\n    if n < 10:\n        return n\n    return n % 10 + digit_sum(n __1__ 10)\n\nprint(digit_sum(789))   # 24\n```', '//'),
    fb('字典加總所有值。\n\n```python\nmenu = {"茶": 30, "咖啡": 50}\nprint(sum(menu.__1__()))   # 80\n```', 'values'),
    fb('遞迴輾轉相除法。\n\n```python\ndef gcd(a, b):\n    if b == 0:\n        return a\n    return gcd(b, a __1__ b)\n\nprint(gcd(48, 18))   # 6\n```', '%'),
    fb('依鍵排序後遍歷。\n\n```python\nd = {"c": 3, "a": 1, "b": 2}\nfor k in __1__(d):\n    print(k, end="")\n# abc\n```', 'sorted'),
    fb('集合聯集算總人數。\n\n```python\na = {"A", "B"}\nb = {"B", "C", "D"}\nprint(len(a __1__ b))   # 4\n```', '|'),
    fb('字典計數後找出現最多的。\n\n```python\nvotes = ["A", "B", "A", "A"]\ncount = {}\nfor v in votes:\n    count[v] = count.get(v, 0) + 1\nwinner = max(count, key=count.__1__)\nprint(winner)   # A\n```', 'get'),
    fb('遞迴計算列表總和。\n\n```python\ndef list_sum(nums):\n    if not nums:\n        return 0\n    return nums[0] + list_sum(nums[__1__:])\n\nprint(list_sum([1, 2, 3, 4]))   # 10\n```', '1'),
    fb('把新學生加入成績字典。\n\n```python\nscores = {"Amy": 88}\nscores["Bob"] = __1__\nprint(len(scores))   # 2\n```', '72'),
    fb('遞迴倒印數字。\n\n```python\ndef show(n):\n    if n == 0:\n        return\n    print(n, end="")\n    show(n - 1)\n\nshow(3)   # 321\n```\n\n空格：終止條件 n == __1__。', '0'),
    fb('用集合去重後計數。\n\n```python\ntags = ["py", "ai", "py"]\nprint(len(__1__(tags)))   # 2\n```', 'set'),
    fb('篩出及格的學生名單。\n\n```python\nscores = {"A": 55, "B": 88, "C": 70}\npassed = [k for k, v in scores.items() if v >= __1__]\nprint(passed)   # [\'B\', \'C\']\n```', '60'),
    fb('遞迴印出 1 到 n（順序）。\n\n```python\ndef up(n):\n    if n == 0:\n        return\n    up(n - 1)\n    print(n, end="")\n\nup(3)   # 123\n```\n\n空格：先遞迴呼叫 up(n - __1__) 再印出。', '1'),
    fb('合併兩個字典。\n\n```python\na = {"x": 1}\nb = {"y": 2, "z": 3}\na.__1__(b)\nprint(len(a))   # 3\n```', 'update'),
    fb('集合差集找退選學生。\n\n```python\nbefore = {"A", "B", "C"}\nafter = {"A", "C"}\nprint(before __1__ after)   # {\'B\'}\n```', '-'),
    fb('遞迴反轉字串。\n\n```python\ndef rev(s):\n    if len(s) <= 1:\n        return s\n    return rev(s[1:]) + s[__1__]\n\nprint(rev("hello"))   # olleh\n```', '0'),
    fb('字典建模：巢狀取值。\n\n```python\nstudents = {"S1": {"name": "Amy", "age": 16}}\nprint(students["S1"][__1__])   # Amy\n```', ['"name"', "'name'"]),
    fb('統計字母頻率並印出特定字母。\n\n```python\ntext = "banana"\nfreq = {}\nfor ch in text:\n    freq[ch] = freq.get(ch, 0) + 1\nprint(freq[__1__])   # 3\n```', ['"a"', "'a'"]),
    fb('遞迴計算 2 的 n 次方。\n\n```python\ndef pow2(n):\n    if n == 0:\n        return 1\n    return 2 * pow2(n - 1)\n\nprint(pow2(10))   # __1__\n```\n\n（填輸出）', '1024'),
    fb('依值由大到小排序字典。\n\n```python\nscores = {"A": 70, "B": 95, "C": 85}\nordered = sorted(scores.items(), key=lambda x: x[__1__], reverse=True)\nprint(ordered[0][0])   # B\n```', '1'),
    fb('用字典累計各類別金額。\n\n```python\nrecords = [("食", 100), ("衣", 200), ("食", 50)]\ntotal = {}\nfor cat, amount in records:\n    total[cat] = total.get(cat, 0) + amount\nprint(total["食"])   # __1__\n```\n\n（填輸出）', '150'),
    fb('遞迴計算列表最大值。\n\n```python\ndef my_max(nums):\n    if len(nums) == 1:\n        return nums[0]\n    rest = my_max(nums[1:])\n    return nums[0] if nums[0] > rest else __1__\n\nprint(my_max([3, 9, 2]))   # 9\n```', 'rest'),
    fb('刪除字典中的鍵。\n\n```python\nd = {"a": 1, "b": 2, "c": 3}\ndel d[__1__]\nprint(len(d))   # 2\n```', ['"a"', "'a'"]),
    fb('用集合判斷子集合關係。\n\n```python\nsmall = {1, 2}\nbig = {1, 2, 3}\nprint(small.issubset(big))   # __1__\n```\n\n（填 True 或 False）', 'True'),
    fb('遞迴計算階乘並取模。\n\n```python\ndef fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(4) __1__ 4)   # 0\n```', '%'),
    fb('把清單元素當鍵、出現次數當值。\n\n```python\nitems = ["a", "b", "a"]\nfreq = {}\nfor x in items:\n    freq[x] = freq.get(x, 0) + 1\nprint(len(freq))   # __1__\n```\n\n（填輸出）', '2'),
    fb('遞迴 countdown 到 0 印完成。\n\n```python\ndef cd(n):\n    if n < 0:\n        print("完成")\n        return\n    print(n, end=" ")\n    cd(n - 1)\n\ncd(2)   # 2 1 0 完成\n```\n\n空格：終止條件 n __1__ 0。', '<'),
    fb('字典的值是串列，計算平均。\n\n```python\nstu = {"Amy": [80, 90, 100]}\nscores = stu["Amy"]\nprint(sum(scores) / __1__(scores))   # 90.0\n```', 'len'),
    fb('用 in 檢查字典是否已有該鍵。\n\n```python\ncache = {"a": 1}\nkey = "b"\nif key not __1__ cache:\n    cache[key] = 99\nprint(cache["b"])   # 99\n```', 'in'),
    fb('遞迴計算列表長度。\n\n```python\ndef length(items):\n    if items == []:\n        return 0\n    return 1 + length(items[1:])\n\nprint(length([5, 6, 7]))   # __1__\n```\n\n（填輸出）', '3'),
    fb('把成績字典的所有值轉成串列。\n\n```python\nscores = {"A": 90, "B": 80}\nvalues = list(scores.__1__())\nprint(sum(values))   # 170\n```', 'values'),
    fb('集合對稱差（只在其中一邊）。\n\n```python\na = {1, 2, 3}\nb = {3, 4}\nprint(a __1__ b)   # {1, 2, 4}\n```', '^'),
    fb('遞迴印出字串每個字元。\n\n```python\ndef spell(s):\n    if s == "":\n        return\n    print(s[0], end="")\n    spell(s[__1__:])\n\nspell("abc")   # abc\n```', '1'),
]


# ── U8 Level 3：35 選擇 + 65 填空（競賽／TQC 實作：遞迴組合、字典建模）──
U8_L3 = [
    # 進階追蹤（35，含競賽原題再現）
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\ndef calculate(n):\n    if n == 0:\n        return 0\n    return n + calculate(n - 1)\nprint(calculate(4) % 4)\n```', '2', '0', '1', '3',
       explanation='10 % 4 = 2。（113 商業類技藝競賽學科第 6 題）'),
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\ndef calc(x):\n    if x < 2:\n        return x\n    return calc(x - 1) + calc(x - 2)\nprint(calc(5) % 4)\n```', '1', '0', '2', '3',
       explanation='費氏 calc(5)=5，5%4=1。（113 商業類技藝競賽學科第 23 題）'),
    mc('以下程式的輸出是？（二分搜尋遞迴）\n\n```python\ndef bsearch(arr, target, lo, hi):\n    if lo > hi:\n        return -1\n    mid = (lo + hi) // 2\n    if arr[mid] == target:\n        return mid\n    if target < arr[mid]:\n        return bsearch(arr, target, lo, mid - 1)\n    return bsearch(arr, target, mid + 1, hi)\n\nprint(bsearch([1, 3, 5, 7, 9], 7, 0, 4))\n```', '3', '7', '2', '-1',
       explanation='7 在索引 3。'),
    mc('以下程式的輸出是？\n\n```python\ndef ackermann_like(m, n):\n    if m == 0:\n        return n + 1\n    if n == 0:\n        return ackermann_like(m - 1, 1)\n    return ackermann_like(m - 1, ackermann_like(m, n - 1))\n\nprint(ackermann_like(1, 1))\n```', '3', '2', '1', '4',
       explanation='A(1,1)=A(0,A(1,0))=A(0,A(0,1))=A(0,2)=3。'),
    mc('以下程式的輸出是？\n\n```python\ndef hanoi(n):\n    if n == 1:\n        return 1\n    return 2 * hanoi(n - 1) + 1\n\nprint(hanoi(4))\n```', '15', '7', '8', '16',
       explanation='河內塔步數 2ⁿ-1。'),
    mc('以下程式的輸出是？\n\n```python\nstudents = {\n    "S1": {"name": "Amy", "scores": [80, 90]},\n    "S2": {"name": "Bob", "scores": [70, 60]},\n}\ntotal = 0\nfor sid in students:\n    total += sum(students[sid]["scores"])\nprint(total)\n```', '300', '170', '130', '2',
       explanation='巢狀字典：170+130。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "the cat the dog the"\nfreq = {}\nfor w in text.split():\n    freq[w] = freq.get(w, 0) + 1\ntop = max(freq, key=freq.get)\nprint(top, freq[top])\n```', 'the 3', 'cat 1', 'the 2', 'dog 1'),
    mc('以下程式的輸出是？\n\n```python\ndef flatten_sum(data):\n    total = 0\n    for v in data.values():\n        if isinstance(v, dict):\n            total += flatten_sum(v)\n        else:\n            total += v\n    return total\n\nprint(flatten_sum({"a": 1, "b": {"c": 2, "d": 3}}))\n```', '6', '3', '1', '5',
       explanation='遞迴走訪巢狀字典：1+2+3。'),
    mc('以下程式的輸出是？\n\n```python\ndef fib_memo(n, memo={}):\n    if n <= 1:\n        return n\n    if n in memo:\n        return memo[n]\n    memo[n] = fib_memo(n - 1) + fib_memo(n - 2)\n    return memo[n]\n\nprint(fib_memo(10))\n```', '55', '89', '34', '10',
       explanation='記憶化費氏數列。'),
    mc('以下程式的輸出是？\n\n```python\nscores = {"Amy": 88, "Bob": 95, "Cid": 72}\nranking = sorted(scores.items(), key=lambda x: x[1], reverse=True)\nprint(ranking[0][0])\n```', 'Bob', 'Amy', 'Cid', '95'),
    mc('以下程式的輸出是？\n\n```python\ndef sum_digits(n):\n    if n == 0:\n        return 0\n    return n % 10 + sum_digits(n // 10)\n\nprint(sum_digits(9999))\n```', '36', '9999', '9', '4'),
    mc('以下程式的輸出是？\n\n```python\ninventory = {"A": 5, "B": 0, "C": 3, "D": 0}\nout_of_stock = [k for k, v in inventory.items() if v == 0]\nprint(len(out_of_stock))\n```', '2', '1', '4', '0'),
    mc('以下程式的輸出是？\n\n```python\ndef combinations(n, r):\n    if r == 0 or r == n:\n        return 1\n    return combinations(n - 1, r - 1) + combinations(n - 1, r)\n\nprint(combinations(4, 2))\n```', '6', '4', '8', '12',
       explanation='C(4,2)=6（帕斯卡遞迴）。'),
    mc('以下程式的輸出是？\n\n```python\ngroups = {}\nfor name in ["王明", "李華", "王美"]:\n    key = name[0]\n    groups[key] = groups.get(key, [])\n    groups[key].append(name)\nprint(len(groups["王"]))\n```', '2', '1', '3', '王'),
    mc('以下程式的輸出是？\n\n```python\ndef count_down(n):\n    if n < 0:\n        return 0\n    return n + count_down(n - 3)\n\nprint(count_down(10))\n```', '22', '10', '18', '25',
       explanation='10+7+4+1。'),
    mc('以下程式的輸出是？\n\n```python\nd1 = {"a": 1, "b": 2}\nd2 = {"b": 3, "c": 4}\nmerged = {**d1, **d2}\nprint(merged["b"])\n```', '3', '2', '5', '發生錯誤',
       explanation='字典解包合併，後者覆蓋前者。'),
    mc('以下程式的輸出是？\n\n```python\ndef digits_reverse(n):\n    if n < 10:\n        return str(n)\n    return str(n % 10) + digits_reverse(n // 10)\n\nprint(digits_reverse(123))\n```', '321', '123', '6', '3'),
    mc('以下程式的輸出是？\n\n```python\nsales = {"Jan": 100, "Feb": 200, "Mar": 150}\navg = sum(sales.values()) / len(sales)\nabove = [m for m, v in sales.items() if v > avg]\nprint(above)\n```', "['Feb']", "['Feb', 'Mar']", "['Jan']", '[]',
       explanation='平均 150，只有 Feb(200) 超過。'),
    mc('以下程式的輸出是？\n\n```python\ndef tribonacci(n):\n    if n < 3:\n        return n if n > 0 else 0\n    return tribonacci(n-1) + tribonacci(n-2) + tribonacci(n-3)\n\nprint(tribonacci(5))\n```', '7', '5', '9', '4',
       explanation='0,1,1,2,4,7。'),
    mc('以下程式的輸出是？\n\n```python\nword_len = {}\nfor w in ["cat", "dog", "bird", "cow"]:\n    L = len(w)\n    word_len[L] = word_len.get(L, 0) + 1\nprint(word_len[3])\n```', '3', '4', '2', '1',
       explanation='長度 3 的字：cat、dog、cow。'),
    mc('以下程式的輸出是？\n\n```python\ndef power_set_size(n):\n    if n == 0:\n        return 1\n    return 2 * power_set_size(n - 1)\n\nprint(power_set_size(4))\n```', '16', '8', '4', '32'),
    mc('以下程式的輸出是？\n\n```python\ncart = {"apple": 3, "banana": 2}\nprices = {"apple": 20, "banana": 15}\ntotal = 0\nfor item, qty in cart.items():\n    total += qty * prices[item]\nprint(total)\n```', '90', '60', '30', '5',
       explanation='3×20+2×15=90。'),
    mc('以下程式的輸出是？\n\n```python\ndef deep_count(data):\n    count = 0\n    for v in data.values():\n        if isinstance(v, dict):\n            count += deep_count(v)\n        else:\n            count += 1\n    return count\n\nprint(deep_count({"a": 1, "b": {"c": 2, "d": {"e": 3}}}))\n```', '3', '2', '4', '5',
       explanation='遞迴數葉節點：a、c、e。'),
    mc('以下程式的輸出是？\n\n```python\ntext = "aabbbcc"\nfreq = {}\nfor ch in text:\n    freq[ch] = freq.get(ch, 0) + 1\nmost = max(freq.values())\nprint(most)\n```', '3', '2', '7', 'b'),
    mc('以下程式的輸出是？\n\n```python\ndef gcd(a, b):\n    return a if b == 0 else gcd(b, a % b)\n\ndef lcm(a, b):\n    return a * b // gcd(a, b)\n\nprint(lcm(4, 6))\n```', '12', '24', '2', '10'),
    mc('以下程式的輸出是？\n\n```python\nregistrations = {"Amy", "Bob", "Cid"}\npaid = {"Bob", "Dan"}\nunpaid = registrations - paid\nprint(sorted(unpaid))\n```', "['Amy', 'Cid']", "['Bob']", "['Dan']", "['Amy', 'Bob', 'Cid']"),
    mc('以下程式的輸出是？\n\n```python\ndef collatz(n):\n    if n == 1:\n        return 0\n    if n % 2 == 0:\n        return 1 + collatz(n // 2)\n    return 1 + collatz(3 * n + 1)\n\nprint(collatz(6))\n```', '8', '6', '7', '9',
       explanation='6→3→10→5→16→8→4→2→1 共 8 步。'),
    mc('以下程式的輸出是？\n\n```python\nvotes = ["A", "B", "A", "C", "A", "B"]\ntally = {}\nfor v in votes:\n    tally[v] = tally.get(v, 0) + 1\nresult = sorted(tally.items(), key=lambda x: (-x[1], x[0]))\nprint(result[0])\n```', "('A', 3)", "('B', 2)", "('C', 1)", "('A', 1)",
       explanation='依票數降冪、同票依名稱升冪。'),
    mc('以下程式的輸出是？\n\n```python\ndef sum_list(nums):\n    if len(nums) == 0:\n        return 0\n    return nums[0] + sum_list(nums[1:])\n\nprint(sum_list([10, 20, 30]))\n```', '60', '10', '30', '0'),
    mc('以下程式的輸出是？\n\n```python\nmatrix = {"r1": {"c1": 5, "c2": 3}, "r2": {"c1": 2, "c2": 8}}\ncol1 = matrix["r1"]["c1"] + matrix["r2"]["c1"]\nprint(col1)\n```', '7', '13', '8', '5',
       explanation='巢狀字典模擬矩陣：5+2。'),
    mc('遞迴走訪巢狀資料時，判斷「是否還要往下」通常用？', 'isinstance() 檢查型態',
       'len()', 'sort()', 'in 運算子'),
    mc('以下程式的輸出是？\n\n```python\nphonebook = {"Amy": "0912", "Bob": "0987"}\nreverse = {v: k for k, v in phonebook.items()}\nprint(reverse["0987"])\n```', 'Bob', 'Amy', '0987', '發生錯誤',
       explanation='字典生成式做鍵值反轉。'),
    mc('以下程式的輸出是？\n\n```python\ndef nested_max(data):\n    best = 0\n    for v in data.values():\n        if isinstance(v, dict):\n            best = max(best, nested_max(v))\n        else:\n            best = max(best, v)\n    return best\n\nprint(nested_max({"a": 3, "b": {"c": 9, "d": 5}}))\n```', '9', '5', '3', '17'),
    mc('把「迴圈版階乘」與「遞迴版階乘」比較，何者較省記憶體？', '迴圈版（不需堆疊呼叫）',
       '遞迴版', '兩者相同', '無法比較'),
    mc('以下程式的輸出是？\n\n```python\nseen = set()\nresult = []\nfor x in [1, 2, 2, 3, 1]:\n    if x not in seen:\n        seen.add(x)\n        result.append(x)\nprint(result)\n```', '[1, 2, 3]', '[1, 2, 2, 3, 1]', '[1, 1, 2, 2, 3]', '[3, 2, 1]',
       explanation='用集合輔助去重且保留順序。'),

    # ── L3 填空（65）──
    fb('遞迴計算組合數 C(n, r)。\n\n```python\ndef comb(n, r):\n    if r == 0 or r == n:\n        return 1\n    return comb(n - 1, r - 1) + comb(n - 1, __1__)\n\nprint(comb(5, 2))   # 10\n```', 'r'),
    fb('二分搜尋遞迴的中點。\n\n```python\ndef bsearch(arr, t, lo, hi):\n    if lo > hi:\n        return -1\n    mid = (lo + hi) __1__ 2\n    if arr[mid] == t:\n        return mid\n    if t < arr[mid]:\n        return bsearch(arr, t, lo, mid - 1)\n    return bsearch(arr, t, mid + 1, hi)\n\nprint(bsearch([1, 4, 6, 9], 9, 0, 3))   # 3\n```', '//'),
    fb('遞迴走訪巢狀字典加總。\n\n```python\ndef deep_sum(d):\n    total = 0\n    for v in d.values():\n        if isinstance(v, dict):\n            total += deep_sum(v)\n        else:\n            total += v\n    return __1__\n\nprint(deep_sum({"a": 1, "b": {"c": 2}}))   # 3\n```', 'total'),
    fb('河內塔步數遞迴。\n\n```python\ndef hanoi(n):\n    if n == 1:\n        return 1\n    return 2 * hanoi(n - 1) + __1__\n\nprint(hanoi(3))   # 7\n```', '1'),
    fb('記憶化費氏：查表避免重算。\n\n```python\ndef fib(n, memo={}):\n    if n <= 1:\n        return n\n    if n __1__ memo:\n        return memo[n]\n    memo[n] = fib(n - 1) + fib(n - 2)\n    return memo[n]\n\nprint(fib(10))   # 55\n```', 'in'),
    fb('字典排名：依平均分排序。\n\n```python\nstudents = {"Amy": [88, 92], "Bob": [70, 60]}\nranking = sorted(students.items(), key=lambda x: sum(x[1]) / len(x[1]), reverse=__1__)\nprint(ranking[0][0])   # Amy\n```', 'True'),
    fb('字典生成式做鍵值反轉。\n\n```python\nd = {"a": 1, "b": 2}\nrev = {v: k for k, v in d.__1__()}\nprint(rev[2])   # b\n```', 'items'),
    fb('遞迴計算列表最大值。\n\n```python\ndef rmax(nums):\n    if len(nums) == 1:\n        return nums[0]\n    return max(nums[0], rmax(nums[__1__:]))\n\nprint(rmax([3, 9, 2, 7]))   # 9\n```', '1'),
    fb('詞頻分析找最高頻詞。\n\n```python\ntext = "a b a c a b"\nfreq = {}\nfor w in text.split():\n    freq[w] = freq.get(w, 0) + 1\ntop = max(freq, key=freq.__1__)\nprint(top)   # a\n```', 'get'),
    fb('遞迴 Collatz 步數。\n\n```python\ndef collatz(n):\n    if n == 1:\n        return 0\n    if n % 2 == 0:\n        return 1 + collatz(n __1__ 2)\n    return 1 + collatz(3 * n + 1)\n\nprint(collatz(8))   # 3\n```', '//'),
    fb('用集合輔助去重保留順序。\n\n```python\nseen = set()\nresult = []\nfor x in [1, 2, 2, 3]:\n    if x not in seen:\n        seen.__1__(x)\n        result.append(x)\nprint(result)   # [1, 2, 3]\n```', 'add'),
    fb('字典購物車計算總價。\n\n```python\ncart = {"apple": 3, "milk": 2}\nprices = {"apple": 20, "milk": 30}\ntotal = 0\nfor item, qty in cart.items():\n    total += qty * prices[__1__]\nprint(total)   # 120\n```', 'item'),
    fb('巢狀字典取值。\n\n```python\ndata = {"S1": {"name": "Amy", "gpa": 3.8}}\nprint(data["S1"][__1__])   # 3.8\n```', ['"gpa"', "'gpa'"]),
    fb('遞迴求冪次。\n\n```python\ndef power(b, e):\n    if e == 0:\n        return 1\n    return b * power(b, e __1__ 1)\n\nprint(power(2, 8))   # 256\n```', '-'),
    fb('用字典分組（同首字歸一組）。\n\n```python\ngroups = {}\nfor name in ["Amy", "Alan", "Bob"]:\n    key = name[0]\n    groups.__1__(key, [])\n    # 使用 setdefault 建立空清單\n```\n\n空格：以 __1__(key, []) 確保鍵存在。', 'setdefault'),
    fb('字典解包合併。\n\n```python\na = {"x": 1}\nb = {"y": 2}\nmerged = {**a, __1__ b}\nprint(len(merged))   # 2\n```', '**'),
    fb('遞迴反轉數字。\n\n```python\ndef rev(n, acc=0):\n    if n == 0:\n        return acc\n    return rev(n // 10, acc * 10 + n __1__ 10)\n\nprint(rev(123))   # 321\n```', '%'),
    fb('集合找未繳費名單。\n\n```python\nall_students = {"A", "B", "C", "D"}\npaid = {"A", "C"}\nunpaid = all_students __1__ paid\nprint(len(unpaid))   # 2\n```', '-'),
    fb('遞迴階乘取模（競賽風格）。\n\n```python\ndef fact(n):\n    if n == 0:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(5) __1__ 4)   # 0\n```', '%',
       explanation='120 % 4 = 0。'),
    fb('字典統計各科平均。\n\n```python\nsubjects = {"國": [80, 90], "英": [70, 60]}\nfor subj, scores in subjects.items():\n    avg = sum(scores) / __1__(scores)\n    print(subj, avg)\n```', 'len'),
    fb('遞迴計算列表元素個數。\n\n```python\ndef count(items):\n    if not items:\n        return 0\n    return 1 + count(items[1:])\n\nprint(count([5, 6, 7, 8, 9]))   # __1__\n```\n\n（填輸出）', '5'),
    fb('找出字典中值最大的鍵。\n\n```python\nsales = {"Jan": 100, "Feb": 300, "Mar": 200}\nbest = max(sales, __1__=sales.get)\nprint(best)   # Feb\n```', 'key'),
    fb('用集合運算找共同好友。\n\n```python\namy = {"Bob", "Cid", "Dan"}\nbob = {"Cid", "Eve"}\ncommon = amy __1__ bob\nprint(common)   # {\'Cid\'}\n```', '&'),
    fb('遞迴印出巢狀清單所有元素個數。\n\n```python\ndef flatten_count(data):\n    total = 0\n    for x in data:\n        if isinstance(x, list):\n            total += flatten_count(x)\n        else:\n            total += 1\n    return total\n\nprint(flatten_count([1, [2, 3], [4, [5]]]))   # __1__\n```\n\n（填輸出）', '5'),
    fb('字典依鍵排序後輸出詞頻報表。\n\n```python\nfreq = {"c": 1, "a": 3, "b": 2}\nfor k, v in sorted(freq.__1__()):\n    print(k, v)\n# a 3 / b 2 / c 1\n```', 'items'),
    fb('遞迴計算等比級數和（首項 1、比 2、n 項）。\n\n```python\ndef geo_sum(n):\n    if n == 0:\n        return 0\n    return 2 ** (n - 1) + geo_sum(n __1__ 1)\n\nprint(geo_sum(5))   # 31\n```', '-'),
    fb('用字典建模學生並更新成績。\n\n```python\nstudent = {"name": "Amy", "score": 80}\nstudent["score"] __1__ 10\nprint(student["score"])   # 90\n```', '+='),
    fb('集合聯集統計不重複標籤數。\n\n```python\npost1 = {"py", "ai"}\npost2 = {"ai", "web", "py"}\nprint(len(post1 __1__ post2))   # 3\n```', '|'),
    fb('遞迴 GCD 求最小公倍數。\n\n```python\ndef gcd(a, b):\n    return a if b == 0 else gcd(b, a % b)\n\ndef lcm(a, b):\n    return a * b __1__ gcd(a, b)\n\nprint(lcm(6, 8))   # 24\n```', '//'),
    fb('字典計數並找唯一出現一次的元素。\n\n```python\nnums = [1, 2, 2, 3, 3]\nfreq = {}\nfor n in nums:\n    freq[n] = freq.get(n, 0) + 1\nfor k, v in freq.items():\n    if v == __1__:\n        print(k)   # 1\n```', '1'),
    fb('遞迴計算最大公因數。\n\n```python\ndef gcd(a, b):\n    if b == 0:\n        return a\n    return gcd(b, a __1__ b)\n\nprint(gcd(100, 60))   # 20\n```', '%'),
    fb('字典 get 巢狀預設值累計。\n\n```python\nscore_by_class = {}\ndata = [("A", 80), ("B", 90), ("A", 70)]\nfor cls, s in data:\n    score_by_class[cls] = score_by_class.get(cls, 0) + s\nprint(score_by_class["A"])   # __1__\n```\n\n（填輸出）', '150'),
    fb('遞迴輸出 1 到 n（正序）。\n\n```python\ndef up(n):\n    if n == 0:\n        return\n    up(n __1__ 1)\n    print(n, end=" ")\n\nup(3)   # 1 2 3\n```', '-'),
    fb('用集合檢查兩清單是否有交集。\n\n```python\na = [1, 2, 3]\nb = [4, 5, 3]\nprint(bool(set(a) __1__ set(b)))   # True\n```', '&'),
    fb('字典模擬庫存進貨。\n\n```python\nstock = {"筆": 10}\nstock["尺"] = stock.get("尺", 0) + 5\nprint(len(stock))   # __1__\n```\n\n（填輸出）', '2'),
    fb('遞迴累乘列表。\n\n```python\ndef prod(nums):\n    if not nums:\n        return 1\n    return nums[0] * prod(nums[1:])\n\nprint(prod([1, 2, 3, 4]))   # __1__\n```\n\n（填輸出）', '24'),
    fb('把字典值排序取前三高。\n\n```python\nscores = {"A": 70, "B": 95, "C": 88, "D": 60}\ntop3 = sorted(scores.values(), reverse=True)[:__1__]\nprint(top3)   # [95, 88, 70]\n```', '3'),
    fb('遞迴計算字串長度。\n\n```python\ndef strlen(s):\n    if s == "":\n        return 0\n    return 1 + strlen(s[__1__:])\n\nprint(strlen("hello"))   # 5\n```', '1'),
    fb('字典找出所有及格科目。\n\n```python\ngrades = {"國": 55, "英": 88, "數": 72}\npassed = [k for k, v in grades.items() if v >= __1__]\nprint(sorted(passed))   # [\'數\', \'英\']\n```', '60'),
    fb('遞迴數字反轉成整數。\n\n```python\ndef digit_sum(n):\n    if n < 10:\n        return n\n    return n % 10 + digit_sum(n // __1__)\n\nprint(digit_sum(12345))   # 15\n```', '10'),
    fb('用字典建通訊錄並反查。\n\n```python\nbook = {"Amy": "0912", "Bob": "0987"}\nreverse = {v: k for k, v in book.items()}\nprint(reverse[__1__])   # Amy\n```', ['"0912"', "'0912'"]),
    fb('遞迴合併排序的合併步驟計數（概念）。\n\n```python\ndef merge_count(a, b):\n    if not a:\n        return len(b)\n    if not b:\n        return len(a)\n    return 1 + merge_count(a[1:], b) if a[0] < b[0] else 1 + merge_count(a, b[__1__:])\n\nprint(merge_count([1, 3], [2]))   # 3\n```', '1'),
    fb('集合差集找退課學生。\n\n```python\nweek1 = {"A", "B", "C"}\nweek2 = {"A", "C"}\ndropped = week1 __1__ week2\nprint(dropped)   # {\'B\'}\n```', '-'),
    fb('字典累計出現次數後排序。\n\n```python\nletters = "mississippi"\nfreq = {}\nfor ch in letters:\n    freq[ch] = freq.get(ch, 0) + 1\nprint(freq[__1__])   # 4\n```\n\n空格：填出現 4 次的字母。', ['"s"', "'s'", '"i"', "'i'"]),
    fb('遞迴計算斐波那契第 n 項（迭代較快但此處遞迴）。\n\n```python\ndef fib(n):\n    if n <= 1:\n        return n\n    return fib(n - 1) + fib(n __1__ 2)\n\nprint(fib(8))   # 21\n```', '-'),
    fb('用字典統計並找眾數。\n\n```python\nvotes = [3, 1, 3, 3, 2]\ncount = {}\nfor v in votes:\n    count[v] = count.get(v, 0) + 1\nmode = max(count, key=count.get)\nprint(mode)   # __1__\n```\n\n（填輸出）', '3'),
    fb('遞迴組合子問題：路徑數（往右或往下）。\n\n```python\ndef paths(m, n):\n    if m == 0 or n == 0:\n        return 1\n    return paths(m - 1, n) + paths(m, n __1__ 1)\n\nprint(paths(2, 2))   # 6\n```', '-'),
    fb('集合對稱差找只在一邊的人。\n\n```python\na = {1, 2, 3}\nb = {3, 4, 5}\nprint(a __1__ b)   # {1, 2, 4, 5}\n```', '^'),
    fb('字典建模：更新巢狀分數。\n\n```python\nstu = {"Amy": {"math": 80}}\nstu["Amy"]["math"] += __1__\nprint(stu["Amy"]["math"])   # 90\n```', '10'),
    fb('遞迴印出等腰數字三角形總層數。\n\n```python\ndef rows(n):\n    if n == 0:\n        return 0\n    return 1 + rows(n - 1)\n\nprint(rows(5))   # __1__\n```\n\n（填輸出）', '5'),
    fb('用字典查表轉換等第。\n\n```python\ngrade_map = {"A": 4.0, "B": 3.0, "C": 2.0}\ngrades = ["A", "B", "A"]\ntotal = sum(grade_map[g] for g in grades)\nprint(total / __1__(grades))   # 3.6666666666666665\n```', 'len'),
    fb('遞迴計算冪塔（2^2^n 簡化為連乘）。\n\n```python\ndef tower(n):\n    if n == 0:\n        return 1\n    return 2 * tower(n - 1)\n\nprint(tower(6))   # __1__\n```\n\n（填輸出）', '64'),
    fb('字典依值篩選並計數。\n\n```python\nstatus = {"A": "ok", "B": "fail", "C": "ok"}\nok_count = sum(1 for v in status.values() if v == __1__)\nprint(ok_count)   # 2\n```', ['"ok"', "'ok'"]),
    fb('集合去重後排序輸出。\n\n```python\nnums = [3, 1, 2, 3, 1]\nprint(sorted(__1__(nums)))   # [1, 2, 3]\n```', 'set'),
    fb('遞迴計算數列 a(n)=a(n-1)*2+1。\n\n```python\ndef seq(n):\n    if n == 0:\n        return 0\n    return seq(n - 1) * 2 + __1__\n\nprint(seq(4))   # 15\n```', '1',
       explanation='0→1→3→7→15。'),
    fb('字典模擬快取：命中就回傳。\n\n```python\ncache = {2: 4, 3: 9}\ndef square(n):\n    if n in cache:\n        return cache[n]\n    cache[n] = n * n\n    return cache[__1__]\n\nprint(square(3))   # 9\n```', 'n'),
    fb('遞迴走訪巢狀字典最大深度。\n\n```python\ndef depth(d):\n    if not isinstance(d, dict) or not d:\n        return 0\n    return 1 + max(depth(v) for v in d.values())\n\nprint(depth({"a": {"b": {"c": 1}}}))   # __1__\n```\n\n（填輸出）', '3'),
    fb('字典累加多筆訂單金額。\n\n```python\norders = [("Amy", 100), ("Bob", 50), ("Amy", 200)]\ntotal = {}\nfor name, amount in orders:\n    total[name] = total.get(name, 0) + amount\nprint(total["Amy"])   # __1__\n```\n\n（填輸出）', '300'),
    fb('遞迴計算最大公因數的迴圈等價寫法比較（此處遞迴）。\n\n```python\ndef gcd(a, b):\n    if b == 0:\n        return __1__\n    return gcd(b, a % b)\n\nprint(gcd(24, 36))   # 12\n```', 'a'),
    fb('用集合快速判斷是否所有元素唯一。\n\n```python\ndata = [1, 2, 3, 2]\nprint(len(data) == len(set(data)))   # __1__\n```\n\n（填 True 或 False）', 'False'),
    fb('字典生成式建立平方表。\n\n```python\nsquares = {n: n * n for n in range(1, 4)}\nprint(squares[__1__])   # 9\n```', '3'),
    fb('遞迴計算清單中偶數個數。\n\n```python\ndef count_even(nums):\n    if not nums:\n        return 0\n    add = 1 if nums[0] % 2 == 0 else 0\n    return add + count_even(nums[__1__:])\n\nprint(count_even([1, 2, 3, 4, 6]))   # 3\n```', '1'),
    fb('字典找出並列最高分的所有人。\n\n```python\nscores = {"A": 90, "B": 90, "C": 80}\nbest = max(scores.values())\ntop = [k for k, v in scores.items() if v == __1__]\nprint(sorted(top))   # [\'A\', \'B\']\n```', 'best'),
    fb('用字典把成績轉排名（相同分同名次概念，此處直接查）。\n\n```python\nranks = {95: 1, 88: 2, 70: 3}\nmy_score = 88\nprint(ranks[__1__])   # 2\n```', 'my_score'),
    fb('集合聯集去重合併兩份名單。\n\n```python\nlist_a = ["Amy", "Bob"]\nlist_b = ["Bob", "Cid"]\nall_people = set(list_a) __1__ set(list_b)\nprint(len(all_people))   # 3\n```', '|'),
]

