"""Unit 7（函式與模組化）題庫 — 全選擇制。

L1 對標 ITS（def/參數/return 概念、簡單呼叫追蹤）、
L2 對標 TQC+ 觀念題（預設/關鍵字參數、區域變數、多值回傳）、
L3 對標競賽／TQC 實作（函式組合、介面設計；收錄競賽第 14 題）。
"""
from .question_helpers import mc, fb

# ── U7 Level 1：55 選擇 + 45 填空 ──
U7_L1 = [
    # def / return 概念（15）
    mc('定義函式使用哪個關鍵字？', 'def', 'func', 'function', 'define'),
    mc('函式把結果交回呼叫端使用？', 'return', 'print', 'give', 'output'),
    mc('def greet(name): 中的 name 稱為？', '參數', '引數值', '回傳值', '函式名'),
    mc('呼叫 greet("Amy") 時，"Amy" 稱為？', '引數（傳入的值）', '參數名稱', '回傳值', '變數宣告'),
    mc('函式定義行的結尾要加？', '冒號 :', '分號 ;', '句點 .', '等號 ='),
    mc('函式的內容（主體）要如何標示？', '縮排', '大括號', '引號', '括號'),
    mc('沒有寫 return 的函式，呼叫後得到什麼？', 'None', '0', '空字串', '發生錯誤'),
    mc('函式要「先定義還是先呼叫」？', '先定義才能呼叫', '先呼叫', '順序無關', '同時'),
    mc('def add(a, b): return a + b 有幾個參數？', '2 個', '1 個', '3 個', '0 個'),
    mc('使用函式的主要好處是？', '重複邏輯只寫一次、可重複呼叫', '程式一定變快',
       '不需要變數', '自動除錯'),
    mc('「函式像一台小機器」的比喻中，參數相當於？', '投入的材料', '成品',
       '機器名稱', '說明書'),
    mc('return 之後、同函式內剩下的程式會？', '不執行（函式立即結束）', '照常執行',
       '下次呼叫才執行', '發生錯誤'),
    mc('函式名稱的命名慣例是？', '小寫加底線（如 calc_area）', '全大寫',
       '首字大寫駝峰必須', '任意符號'),
    mc('一個函式可以被呼叫幾次？', '不限次數', '一次', '最多十次', '兩次'),
    mc('docstring 是什麼？', '函式開頭說明用途的字串', '錯誤訊息',
       '回傳值', '參數型態'),

    # 呼叫追蹤（27）
    mc('以下程式的輸出是？\n\n```python\ndef greet(name):\n    return f"你好，{name}！"\n\nprint(greet("Amy"))\n```', '你好，Amy！', 'greet("Amy")', 'name', 'None'),
    mc('以下程式的輸出是？\n\n```python\ndef add(a, b):\n    return a + b\n\nprint(add(2, 3))\n```', '5', '23', 'a + b', 'None'),
    mc('以下程式的輸出是？\n\n```python\ndef rectangle_area(width, height):\n    return width * height\n\nprint(rectangle_area(8, 5))\n```', '40', '13', '85', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndef is_even(n):\n    return n % 2 == 0\n\nprint(is_even(7))\n```', 'False', 'True', '1', '7'),
    mc('以下程式的輸出是？\n\n```python\ndef square(x):\n    return x * x\n\nprint(square(4) + square(3))\n```', '25', '49', '12', '7',
       explanation='16 + 9。'),
    mc('以下程式的輸出是？\n\n```python\ndef hello():\n    print("哈囉")\n\nhello()\nhello()\n```', '哈囉（兩行）', '哈囉（一行）', '沒有輸出', 'hello hello'),
    mc('以下程式的輸出是？\n\n```python\ndef double(n):\n    return n * 2\n\nx = double(5)\nprint(x + 1)\n```', '11', '10', '51', '6'),
    mc('以下程式的輸出是？\n\n```python\ndef f(x):\n    return x + 1\n\nprint(f(f(3)))\n```', '5', '4', '3', '7',
       explanation='內層 f(3)=4，外層 f(4)=5。'),
    mc('以下程式的輸出是？\n\n```python\ndef nothing():\n    pass\n\nprint(nothing())\n```', 'None', '0', 'pass', '沒有輸出'),
    mc('以下程式的輸出是？\n\n```python\ndef grade(score):\n    if score >= 60:\n        return "及格"\n    return "不及格"\n\nprint(grade(59))\n```', '不及格', '及格', '59', 'None'),
    mc('以下程式的輸出是？\n\n```python\ndef bigger(a, b):\n    if a > b:\n        return a\n    return b\n\nprint(bigger(4, 9))\n```', '9', '4', '13', 'a'),
    mc('以下程式的輸出是？\n\n```python\ndef count_vowel(text):\n    n = 0\n    for ch in text:\n        if ch in "aeiou":\n            n += 1\n    return n\n\nprint(count_vowel("hello"))\n```', '2', '3', '5', '0'),
    mc('以下程式的輸出是？\n\n```python\ndef total(nums):\n    return sum(nums)\n\nprint(total([1, 2, 3]))\n```', '6', '[1, 2, 3]', '123', '3'),
    mc('以下程式的輸出是？\n\n```python\ndef greet(name):\n    message = f"Hi {name}"\n\nresult = greet("Bob")\nprint(result)\n```', 'None', 'Hi Bob', 'Bob', '發生錯誤',
       explanation='函式內只指定變數沒有 return。'),
    mc('以下程式的輸出是？\n\n```python\ndef triple(x):\n    return x * 3\n\nprint(triple("ab"))\n```', 'ababab', 'ab3', '發生錯誤', 'ab ab ab',
       explanation='字串乘整數是重複。'),
    mc('以下程式的輸出是？\n\n```python\ndef area(w, h):\n    return w * h\n\nprint(area(3, 4) > 10)\n```', 'True', 'False', '12', '10'),
    mc('以下程式的輸出是？\n\n```python\ndef half(n):\n    return n / 2\n\nprint(half(9))\n```', '4.5', '4', '4.0', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndef last_char(text):\n    return text[-1]\n\nprint(last_char("Python"))\n```', 'n', 'P', 'o', '-1'),
    mc('以下程式的輸出是？\n\n```python\ndef mystery(n):\n    return n\n\nprint(mystery(7) * mystery(2))\n```', '14', '72', '9', '77'),
    mc('以下程式的輸出是？\n\n```python\ndef cheer():\n    return "加油"\n\nword = cheer()\nprint(word * 2)\n```', '加油加油', '加油 加油', 'cheer cheer', '發生錯誤'),
    mc('以下程式呼叫了 shout 幾次？\n\n```python\ndef shout():\n    print("!")\n\nfor i in range(3):\n    shout()\n```', '3 次', '1 次', '0 次', '4 次'),
    mc('以下程式的輸出是？\n\n```python\ndef minus(a, b):\n    return a - b\n\nprint(minus(10, 3) - minus(5, 2))\n```', '4', '10', '7', '3',
       explanation='7 - 3。'),
    mc('以下程式的輸出是？\n\n```python\ndef first_word(sentence):\n    return sentence.split()[0]\n\nprint(first_word("hello world"))\n```', 'hello', 'world', 'h', 'hello world'),
    mc('以下程式的輸出是？\n\n```python\ndef make_list(n):\n    return [n, n * 2]\n\nprint(make_list(3))\n```', '[3, 6]', '[3, 3]', '36', '(3, 6)'),
    mc('以下程式的輸出是？\n\n```python\ndef check(n):\n    return "正" if n > 0 else "負或零"\n\nprint(check(-5))\n```', '負或零', '正', '-5', 'None'),
    mc('以下程式的輸出是？\n\n```python\ndef add_tax(price):\n    return int(price * 1.05)\n\nprint(add_tax(100))\n```', '105', '100', '105.0', '5'),
    mc('以下程式的輸出是？\n\n```python\ndef repeat(word, times):\n    return word * times\n\nprint(repeat("no", 3))\n```', 'nonono', 'no3', 'no no no', '發生錯誤'),

    # 觀念（13）
    mc('函式內部建立的變數（區域變數）在哪裡有效？', '只在該函式內', '整支程式',
       '所有函式', '只在迴圈內'),
    mc('「一個函式只做一件事」的好處是？', '容易理解、測試與重複使用', '執行更快',
       '減少參數', '不用 return'),
    mc('「優先回傳資料，不要在函式裡直接 print」的原因是？',
       '回傳值可以被後續程式再利用', 'print 會出錯', 'return 比較短', '兩者相同'),
    mc('把 BMI 程式拆成「計算」與「判斷」兩個函式，屬於？', '模組化設計', '遞迴',
       '排序', '除錯'),
    mc('呼叫函式時引數的順序？', '依參數順序對應', '可任意排列', '由大到小',
       '由函式自己決定'),
    mc('def f(a, b): 只傳入一個引數 f(1) 會發生什麼？', 'TypeError（缺少引數）',
       '自動補 0', 'b 是 None', '正常執行'),
    mc('哪個是合法的函式名稱？', 'calc_total', '2calc', 'calc-total', 'def'),
    mc('return 可以一次回傳多個值嗎？', '可以，用逗號分隔（回傳元組）', '不可以',
       '最多兩個', '只能回傳字串'),
    mc('函式呼叫自己以外的另一個函式，可以嗎？', '可以，函式能互相呼叫', '不可以',
       '只能呼叫內建函式', '要先 import'),
    mc('把重複三次的相同程式碼改成函式呼叫，主要改善了？', '重複性（DRY 原則）',
       '執行速度', '記憶體', '縮排'),
    mc('函式的「介面」指的是？', '參數與回傳值的約定', '函式長度',
       '變數名稱', '縮排格數'),
    mc('print(add(2, 3)) 與 add(2, 3) 單獨一行的差別是？',
       '前者顯示回傳值、後者計算後不顯示', '完全相同', '後者會報錯', '前者比較快'),
    mc('測試函式時「邊界輸入」的例子是？', 'grade(60) 剛好在及格線', 'grade(75)',
       'grade("abc")', '不需要測試'),

    # ── L1 填空（45）──
    fb('定義打招呼函式。\n\n```python\n__1__ greet(name):\n    return f"你好 {name}"\n\nprint(greet("Amy"))   # 你好 Amy\n```', 'def'),
    fb('把結果交回呼叫端。\n\n```python\ndef add(a, b):\n    __1__ a + b\n\nprint(add(2, 3))   # 5\n```', 'return'),
    fb('計算長方形面積。\n\n```python\ndef area(w, h):\n    return w __1__ h\n\nprint(area(8, 5))   # 40\n```', '*'),
    fb('判斷偶數回傳布林值。\n\n```python\ndef is_even(n):\n    return n % 2 __1__ 0\n\nprint(is_even(6))   # True\n```', '=='),
    fb('呼叫函式並印出結果。\n\n```python\ndef square(x):\n    return x * x\n\nprint(__1__(5))   # 25\n```', 'square'),
    fb('成績等第函式的及格線。\n\n```python\ndef grade(score):\n    if score >= __1__:\n        return "及格"\n    return "不及格"\n\nprint(grade(75))   # 及格\n```', '60'),
    fb('函式回傳兩數較大值。\n\n```python\ndef bigger(a, b):\n    if a > b:\n        return a\n    return __1__\n\nprint(bigger(3, 9))   # 9\n```', 'b'),
    fb('攝氏轉華氏函式。\n\n```python\ndef to_f(c):\n    return c * 9 / 5 + __1__\n\nprint(to_f(100))   # 212.0\n```', '32'),
    fb('打電話函式呼叫兩次。\n\n```python\ndef ring():\n    print("鈴鈴")\n\nring()\n__1__()\n```', 'ring'),
    fb('把參數改名成有意義的名稱。\n\n```python\ndef circle_area(__1__):\n    return 3.14 * r * r\n\nprint(circle_area(10))   # 314.0\n```', 'r'),
    fb('回傳字串長度。\n\n```python\ndef word_len(word):\n    return __1__(word)\n\nprint(word_len("python"))   # 6\n```', 'len'),
    fb('回傳平均。\n\n```python\ndef average(nums):\n    return sum(nums) / len(__1__)\n\nprint(average([80, 90]))   # 85.0\n```', 'nums'),
    fb('兩段式呼叫：先存回傳值再使用。\n\n```python\ndef double(n):\n    return n * 2\n\nresult = __1__(6)\nprint(result + 1)   # 13\n```', 'double'),
    fb('函式印出歡迎詞（不回傳）。\n\n```python\ndef welcome(name):\n    __1__(f"歡迎 {name}")\n\nwelcome("小明")   # 歡迎 小明\n```', 'print'),
    fb('回傳絕對值。\n\n```python\ndef my_abs(x):\n    if x < 0:\n        return __1__\n    return x\n\nprint(my_abs(-7))   # 7\n```', '-x'),
    fb('把兩個函式串起來用。\n\n```python\ndef double(n):\n    return n * 2\n\ndef add_one(n):\n    return n + 1\n\nprint(add_one(__1__(4)))   # 9\n```', 'double'),
    fb('回傳打折價。\n\n```python\ndef discount(price):\n    return price * __1__\n\nprint(discount(200))   # 160.0\n```', '0.8'),
    fb('函式判斷正負。\n\n```python\ndef sign(n):\n    if n > 0:\n        return "正"\n    elif n < 0:\n        return "負"\n    __1__:\n        return "零"\n\nprint(sign(0))   # 零\n```', 'else'),
    fb('回傳名字第一個字。\n\n```python\ndef first_char(text):\n    return text[__1__]\n\nprint(first_char("Amy"))   # A\n```', '0'),
    fb('用參數控制重複次數。\n\n```python\ndef stars(n):\n    return "*" * __1__\n\nprint(stars(4))   # ****\n```', 'n'),
    fb('BMI 計算函式。\n\n```python\ndef bmi(weight, height):\n    return weight / height __1__ 2\n\nprint(round(bmi(50, 1.6), 1))   # 19.5\n```', '**'),
    fb('把總分函式用在三科成績。\n\n```python\ndef total(a, b, c):\n    return a + b + c\n\nprint(total(70, 80, __1__))   # 240\n```', '90'),
    fb('回傳倒數第二個元素。\n\n```python\ndef second_last(items):\n    return items[__1__]\n\nprint(second_last([1, 2, 3, 4]))   # 3\n```', '-2'),
    fb('沒有 return 的函式，呼叫後得到的值是？\n\n```python\ndef calc(n):\n    result = n + 1\n\nprint(calc(5))   # __1__\n```', 'None'),
    fb('回傳及格科目數。\n\n```python\ndef pass_count(scores):\n    count = 0\n    for s in scores:\n        if s >= 60:\n            count += 1\n    return __1__\n\nprint(pass_count([50, 70, 90]))   # 2\n```', 'count'),
    fb('計算週薪。\n\n```python\ndef weekly_pay(hourly, hours):\n    return hourly * __1__\n\nprint(weekly_pay(190, 40))   # 7600\n```', 'hours'),
    fb('先定義才能呼叫：把呼叫移到定義之後。\n\n```python\ndef hi():\n    return "HI"\n\nprint(__1__())   # HI\n```', 'hi'),
    fb('把秒轉分的函式。\n\n```python\ndef to_minutes(seconds):\n    return seconds __1__ 60\n\nprint(to_minutes(180))   # 3\n```', '//'),
    fb('回傳字串重複版本。\n\n```python\ndef echo(word, times):\n    return word * times\n\nprint(echo("嘿", __1__))   # 嘿嘿嘿\n```', '3'),
    fb('函式包住 f-string 排版。\n\n```python\ndef label(name, score):\n    return f"{name}：{__1__} 分"\n\nprint(label("Amy", 95))   # Amy：95 分\n```', 'score'),
    fb('判斷回文的函式。\n\n```python\ndef is_palindrome(text):\n    return text == text[::__1__]\n\nprint(is_palindrome("noon"))   # True\n```', '-1'),
    fb('回傳最大值（用內建）。\n\n```python\ndef top(nums):\n    return __1__(nums)\n\nprint(top([3, 9, 5]))   # 9\n```', 'max'),
    fb('圓周長函式。\n\n```python\ndef perimeter(r):\n    return 2 * 3.14 * __1__\n\nprint(perimeter(5))   # 31.400000000000002\n```\n\n（此輸出為浮點數原樣）', 'r'),
    fb('用函式檢查字串開頭。\n\n```python\ndef is_mobile(phone):\n    return phone.startswith(__1__)\n\nprint(is_mobile("0912345678"))   # True\n```', ['"09"', "'09'"]),
    fb('回傳購物總價（含運費 60）。\n\n```python\ndef checkout(subtotal):\n    return subtotal + __1__\n\nprint(checkout(500))   # 560\n```', '60'),
    fb('把成績四捨五入的函式。\n\n```python\ndef final_score(s):\n    return __1__(s)\n\nprint(final_score(89.6))   # 90\n```', 'round'),
    fb('提前結束：負數直接回傳 0。\n\n```python\ndef safe_sqrt(n):\n    if n < 0:\n        __1__ 0\n    return n ** 0.5\n\nprint(safe_sqrt(-4))   # 0\n```', 'return'),
    fb('函式計算差幾分及格。\n\n```python\ndef need(score):\n    return 60 - __1__\n\nprint(need(52))   # 8\n```', 'score'),
    fb('回傳兩數的和與差其中的和。\n\n```python\ndef add_sub(a, b):\n    return a + b, a - b\n\ns, d = add_sub(7, 3)\nprint(__1__)   # 10\n```', 's'),
    fb('用函式算折扣後最便宜的價格。\n\n```python\ndef best_price(a, b):\n    if a < b:\n        return a\n    return b\n\nprint(best_price(180, __1__))   # 150\n```', '150'),
    fb('把訊息加上驚嘆號。\n\n```python\ndef excited(msg):\n    return msg + __1__\n\nprint(excited("好耶"))   # 好耶!\n```', ['"!"', "'!'"]),
    fb('計算三角形面積的函式。\n\n```python\ndef triangle(base, height):\n    return base * height / __1__\n\nprint(triangle(6, 4))   # 12.0\n```', '2'),
    fb('回傳清單第一個與最後一個。\n\n```python\ndef ends(items):\n    return items[0], items[-1]\n\na, b = ends([5, 6, 7])\nprint(a + __1__)   # 12\n```', 'b'),
    fb('判斷成年。\n\n```python\ndef is_adult(age):\n    return age __1__ 18\n\nprint(is_adult(20))   # True\n```', '>='),
    fb('函式接串列回傳翻倍串列。\n\n```python\ndef double_all(nums):\n    return [n * 2 for n in __1__]\n\nprint(double_all([1, 2]))   # [2, 4]\n```', 'nums'),
]


# ── U7 Level 2：60 選擇 + 40 填空（TQC+ 觀念題：參數機制＋區域變數）──
U7_L2 = [
    # 追蹤（32）
    mc('以下程式的輸出是？\n\n```python\ndef greet(name="同學"):\n    return f"哈囉 {name}"\n\nprint(greet())\n```', '哈囉 同學', '哈囉', '哈囉 name', '發生錯誤',
       explanation='未傳引數時使用預設參數。'),
    mc('以下程式的輸出是？\n\n```python\ndef greet(name="同學"):\n    return f"哈囉 {name}"\n\nprint(greet("Amy"))\n```', '哈囉 Amy', '哈囉 同學', 'Amy', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndef power(base, exp=2):\n    return base ** exp\n\nprint(power(3), power(2, 3))\n```', '9 8', '9 9', '6 8', '8 9'),
    mc('以下程式的輸出是？\n\n```python\ndef info(name, age):\n    return f"{name}:{age}"\n\nprint(info(age=16, name="Amy"))\n```', 'Amy:16', '16:Amy', '發生錯誤', 'name:age',
       explanation='關鍵字參數可不依順序。'),
    mc('以下程式的輸出是？\n\n```python\nx = 10\n\ndef change():\n    x = 5\n\nchange()\nprint(x)\n```', '10', '5', 'None', '發生錯誤',
       explanation='函式內的 x 是區域變數，不影響外部。'),
    mc('以下程式的輸出是？\n\n```python\ndef calc(n):\n    result = n * 2\n    return result\n\ncalc(5)\nprint(result)\n```', 'NameError（result 是區域變數）', '10', 'None', '5'),
    mc('以下程式的輸出是？\n\n```python\ndef stats(nums):\n    return min(nums), max(nums)\n\nlow, high = stats([3, 9, 5])\nprint(high - low)\n```', '6', '9', '3', '(3, 9)',
       explanation='多值回傳＋unpacking。'),
    mc('以下程式的輸出是？\n\n```python\ndef bmi(w, h_cm):\n    h = h_cm / 100\n    return w / h ** 2\n\ndef level(b):\n    return "正常" if b < 24 else "過重"\n\nprint(level(bmi(70, 175)))\n```', '正常', '過重', '22.9', '發生錯誤',
       explanation='70/1.75² ≈ 22.86 < 24。'),
    mc('以下程式的輸出是？\n\n```python\ndef f(n):\n    if n > 10:\n        return "大"\n    return "小"\n\nprint(f(10))\n```', '小', '大', '10', 'None'),
    mc('以下程式的輸出是？\n\n```python\ndef process(items):\n    items.append(99)\n\ndata = [1, 2]\nprocess(data)\nprint(data)\n```', '[1, 2, 99]', '[1, 2]', '[99]', '發生錯誤',
       explanation='串列是可變物件，函式內的修改會反映到外部。'),
    mc('以下程式的輸出是？\n\n```python\ndef tax(price, rate=0.05):\n    return round(price * (1 + rate))\n\nprint(tax(100), tax(100, 0.1))\n```', '105 110', '105 105', '100 110', '110 105'),
    mc('以下程式的輸出是？\n\n```python\ndef outer(n):\n    return inner(n) + 1\n\ndef inner(n):\n    return n * 10\n\nprint(outer(3))\n```', '31', '30', '13', '發生錯誤',
       explanation='outer 呼叫 inner：30+1。'),
    mc('以下程式的輸出是？\n\n```python\ncount = 0\n\ndef visit():\n    return count + 1\n\nprint(visit(), count)\n```', '1 0', '1 1', '0 0', '發生錯誤',
       explanation='函式內讀取全域變數可以，但沒有修改它。'),
    mc('以下程式的輸出是？\n\n```python\ndef fee(age):\n    if age < 12:\n        return 150\n    if age >= 65:\n        return 150\n    return 300\n\nprint(fee(70) + fee(30))\n```', '450', '600', '300', '150'),
    mc('以下程式的輸出是？\n\n```python\ndef shout(text):\n    return text.upper() + "!"\n\nprint(shout("go") * 2)\n```', 'GO!GO!', 'GO!', 'gogo!', 'GO! GO!'),
    mc('以下程式的輸出是？\n\n```python\ndef middle(a, b, c):\n    return sorted([a, b, c])[1]\n\nprint(middle(9, 2, 5))\n```', '5', '2', '9', '[2, 5, 9]'),
    mc('以下程式的輸出是？\n\n```python\ndef apply_twice(f, x):\n    return f(f(x))\n\ndef inc(n):\n    return n + 3\n\nprint(apply_twice(inc, 4))\n```', '10', '7', '14', '發生錯誤',
       explanation='函式可以當引數傳遞：4→7→10。'),
    mc('以下程式的輸出是？\n\n```python\ndef parse(text):\n    parts = text.split(",")\n    return parts[0], int(parts[1])\n\nname, score = parse("Amy,88")\nprint(score + 2)\n```', '90', '88', 'Amy', '882'),
    mc('以下程式的輸出是？\n\n```python\ndef discount(price, is_vip):\n    if is_vip:\n        return price * 0.8\n    return price\n\nprint(int(discount(500, True)))\n```', '400', '500', '480', '100'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 0\n\ndef add(n):\n    global total\n    total += n\n\nadd(5)\nadd(3)\nprint(total)\n```', '8', '0', '5', '發生錯誤',
       explanation='global 宣告後才能修改全域變數。'),
    mc('以下程式的輸出是？\n\n```python\ndef safe_div(a, b):\n    if b == 0:\n        return None\n    return a / b\n\nresult = safe_div(10, 0)\nprint(result is None)\n```', 'True', 'False', '0', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndef make_email(user, domain="school.edu"):\n    return f"{user}@{domain}"\n\nprint(make_email("amy"))\n```', 'amy@school.edu', 'amy@', 'user@domain', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndef longest(words):\n    best = words[0]\n    for w in words:\n        if len(w) > len(best):\n            best = w\n    return best\n\nprint(longest(["hi", "hello", "hey"]))\n```', 'hello', 'hi', 'hey', '5'),
    mc('以下程式的輸出是？\n\n```python\ndef swap(a, b):\n    return b, a\n\nx, y = swap(1, 2)\nprint(x, y)\n```', '2 1', '1 2', '(2, 1)', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndef count_down(n):\n    while n > 0:\n        n -= 1\n    return "完成"\n\nprint(count_down(3))\n```', '完成', '3 2 1', '0', 'None'),
    mc('以下程式的輸出是？\n\n```python\ndef classify(n):\n    return "偶" if n % 2 == 0 else "奇"\n\nresult = [classify(x) for x in [1, 2, 3]]\nprint(result)\n```', "['奇', '偶', '奇']", "['偶', '奇', '偶']", "['奇', '奇', '偶']", '奇偶奇'),
    mc('以下程式的輸出是？\n\n```python\ndef add_prefix(name, prefix="王"):\n    return prefix + name\n\nprint(add_prefix("小明", prefix="陳"))\n```', '陳小明', '王小明', '小明陳', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndef area(w, h):\n    return w * h\n\nsizes = [(2, 3), (4, 5)]\ntotal = 0\nfor w, h in sizes:\n    total += area(w, h)\nprint(total)\n```', '26', '20', '6', '14',
       explanation='6 + 20。'),
    mc('以下程式的輸出是？\n\n```python\ndef check_pwd(pwd):\n    if len(pwd) < 8:\n        return "太短"\n    if pwd.isdigit():\n        return "太簡單"\n    return "可用"\n\nprint(check_pwd("12345678"))\n```', '太簡單', '太短', '可用', 'None',
       explanation='長度夠但全是數字。'),
    mc('以下程式的輸出是？\n\n```python\ndef scale(nums, factor=10):\n    return [n * factor for n in nums]\n\nprint(scale([1, 2], 3))\n```', '[3, 6]', '[10, 20]', '[1, 2, 3]', '[30, 60]'),
    mc('以下程式的輸出是？\n\n```python\ndef total_price(prices):\n    t = sum(prices)\n    if t >= 1000:\n        t *= 0.9\n    return int(t)\n\nprint(total_price([600, 500]))\n```', '990', '1100', '1000', '900',
       explanation='1100 滿千打九折。'),
    mc('以下程式的輸出是？\n\n```python\ndef f(a, b=2, c=3):\n    return a + b + c\n\nprint(f(1, c=10))\n```', '13', '6', '15', '發生錯誤',
       explanation='a=1、b 用預設 2、c=10。'),

    # 觀念（28）
    mc('預設參數應該寫在參數列的哪裡？', '沒有預設值的參數之後（右側）', '最前面',
       '任意位置', '單獨一行'),
    mc('關鍵字參數 f(name="Amy") 的好處是？', '不必記引數順序、可讀性高', '執行更快',
       '可以少寫參數名', '自動轉型'),
    mc('區域變數與全域變數同名時，函式內部使用的是？', '區域變數', '全域變數',
       '兩者相加', '發生錯誤'),
    mc('在函式內修改「全域變數」需要哪個關鍵字？', 'global', 'public', 'outer', 'static'),
    mc('「避免依賴全域變數」的原因是？', '函式行為難以預測、不易測試',
       '全域變數比較慢', '語法不允許', '佔記憶體'),
    mc('把「純計算」與「輸入輸出」分開的好處是？', '計算函式容易被自動測試',
       '不需要 input', '程式變短', 'print 變快'),
    mc('函式回傳多個值時，實際回傳的型態是？', '元組（tuple）', '串列', '字典', '多個變數'),
    mc('def f(nums): nums.append(1) 會影響呼叫端的串列嗎？',
       '會，串列是可變物件、傳遞的是同一個物件', '不會', '只影響一半', '會複製一份'),
    mc('「一個函式只做一件事」，下列哪個函式違反此原則？',
       '讀輸入、計算 BMI、印出結果全包的函式', '只計算 BMI 的函式',
       '只把 BMI 分級的函式', '只格式化輸出的函式'),
    mc('docstring 應該寫什麼？', '函式的用途、輸入與輸出說明', '作者姓名',
       '程式碼行數', '版本號'),
    mc('None 通常用來表示？', '沒有值／查無結果', '零', '空字串', 'False 的別名'),
    mc('判斷函式回傳是否為 None，建議寫法是？', 'if result is None:', 'if result == 0:',
       'if not result 永遠等價', 'if result = None:'),
    mc('函式當作引數傳遞（如 sorted 的 key）代表函式是？', '一種可以傳遞的物件',
       '字串', '只能呼叫', '全域變數'),
    mc('grade(score) 函式重複用在 3 個地方，需求改成 70 分及格時要改幾處？',
       '1 處（函式內）', '3 處', '0 處', '每次呼叫都要改'),
    mc('參數命名 h 與 height_cm，何者較好？為什麼？', 'height_cm：帶單位的名稱避免誤用',
       'h：比較短', '都一樣', '單位不重要'),
    mc('函式測試的三類輸入是？', '正常、邊界、錯誤輸入', '大、中、小',
       '快、中、慢', '新、舊、未來'),
    mc('回傳 print 的結果 return print("hi") 會回傳什麼？', 'None（print 沒有回傳值）',
       '"hi"', 'True', '發生錯誤'),
    mc('函式間共享資料的建議方式是？', '用參數傳入、用 return 傳出', '全部用全域變數',
       '寫進檔案', '用 input'),
    mc('validate_score(score) 應該回傳什麼型態最合適？', '布林值（合法與否）', '字串',
       '分數本身', 'print 輸出'),
    mc('哪種函式「沒有副作用」（純函式）？', '只根據參數計算並回傳，不改外部狀態',
       '會 print 的', '會修改全域變數的', '會 append 傳入串列的'),
    mc('def f(x=[]) 使用「可變預設參數」是？', '危險寫法：預設串列會被所有呼叫共享',
       '推薦寫法', '語法錯誤', '效能最佳'),
    mc('函式呼叫太深（a 呼叫 b 呼叫 c…）要看懂流程，最實用的做法是？',
       '逐層追蹤每個函式的輸入輸出', '刪掉函式', '全部改全域', '改用 while'),
    mc('把程式拆成 parse→validate→summarize→format 四個函式，這種設計稱為？',
       '資料處理管線（模組化）', '遞迴', '物件導向', '排序'),
    mc('傳入參數與回傳值的「型態約定」寫在哪裡最合適？', 'docstring（或型態註記）',
       '變數名稱後面隨意', '不用寫', '寫在報告'),
    mc('內建函式（len、sum）與自訂函式的呼叫方式？', '完全相同：名稱加括號與引數',
       '內建的不用括號', '自訂的要加 def', '內建的要 import'),
    mc('一支程式的主流程通常放在？', '主程式區（或 main 函式）統一呼叫各函式',
       '每個函式裡', '註解裡', 'import 前'),
    mc('回傳值沒被接住（沒指定給變數也沒用 print）會怎樣？', '值被丟棄，程式繼續',
       '發生錯誤', '自動印出', '存進全域'),
    mc('哪個情境「最適合」寫成函式？', '同樣的稅額計算在五個地方用到',
       '只執行一次的一行程式', 'import 語句', '變數宣告'),

    # ── L2 填空（40）──
    fb('預設參數。\n\n```python\ndef greet(name=__1__):\n    return f"哈囉 {name}"\n\nprint(greet())   # 哈囉 同學\n```', ['"同學"', "'同學'"]),
    fb('次方函式的預設指數。\n\n```python\ndef power(base, exp=__1__):\n    return base ** exp\n\nprint(power(5))   # 25\n```', '2'),
    fb('關鍵字參數呼叫。\n\n```python\ndef info(name, age):\n    return f"{name}:{age}"\n\nprint(info(__1__="Amy", age=16))   # Amy:16\n```', 'name'),
    fb('多值回傳與 unpacking。\n\n```python\ndef stats(nums):\n    return min(nums), __1__(nums)\n\nlow, high = stats([3, 9, 5])\nprint(low, high)   # 3 9\n```', 'max'),
    fb('BMI 兩函式組合。\n\n```python\ndef calc_bmi(w, h_cm):\n    h = h_cm / __1__\n    return w / h ** 2\n\nprint(round(calc_bmi(70, 175), 1))   # 22.9\n```', '100'),
    fb('修改全域變數。\n\n```python\ntotal = 0\n\ndef add(n):\n    __1__ total\n    total += n\n\nadd(7)\nprint(total)   # 7\n```', 'global'),
    fb('安全除法：除數為 0 回傳 None。\n\n```python\ndef safe_div(a, b):\n    if b == 0:\n        return __1__\n    return a / b\n\nprint(safe_div(6, 0))   # None\n```', 'None'),
    fb('函式互相呼叫。\n\n```python\ndef net(price):\n    return price * 0.95\n\ndef checkout(price):\n    return round(__1__(price) + 60)\n\nprint(checkout(1000))   # 1010\n```', 'net'),
    fb('統計函式回傳三個值。\n\n```python\ndef summary(nums):\n    return sum(nums), max(nums), min(nums)\n\ntotal, big, small = summary([4, 8, 2])\nprint(total, big, __1__)   # 14 8 2\n```', 'small'),
    fb('用函式包住輸入驗證。\n\n```python\ndef valid(score):\n    return 0 <= score <= __1__\n\nprint(valid(105))   # False\n```', '100'),
    fb('提早 return 的守門條件。\n\n```python\ndef divide(a, b):\n    if b == 0:\n        __1__ "除數不可為 0"\n    return a / b\n\nprint(divide(8, 0))   # 除數不可為 0\n```', 'return'),
    fb('函式當引數。\n\n```python\ndef inc(n):\n    return n + 1\n\ndef apply(f, x):\n    return __1__(x)\n\nprint(apply(inc, 5))   # 6\n```', 'f'),
    fb('把解析函式接到主流程。\n\n```python\ndef parse(record):\n    name, score = record.split(",")\n    return name, int(__1__)\n\nn, s = parse("Amy,88")\nprint(s + 12)   # 100\n```', 'score'),
    fb('會員價函式（布林參數）。\n\n```python\ndef price(base, vip):\n    if __1__:\n        return base * 0.8\n    return base\n\nprint(price(100, True))   # 80.0\n```', 'vip'),
    fb('把攝氏轉華氏包成函式後批次使用。\n\n```python\ndef to_f(c):\n    return c * 9 / 5 + 32\n\nresult = [to_f(c) for c in [0, 100]]\nprint(__1__)   # [32.0, 212.0]\n```', 'result'),
    fb('預設運費參數。\n\n```python\ndef total(subtotal, shipping=60):\n    return subtotal + shipping\n\nprint(total(500), total(500, __1__))   # 560 500\n```', '0'),
    fb('用函式找中間值。\n\n```python\ndef middle(a, b, c):\n    return sorted([a, b, c])[__1__]\n\nprint(middle(7, 1, 4))   # 4\n```', '1'),
    fb('函式內部變數不外漏：把結果 return 出來。\n\n```python\ndef calc(n):\n    result = n * 3\n    return __1__\n\nprint(calc(4))   # 12\n```', 'result'),
    fb('等第函式（提前回傳串接）。\n\n```python\ndef level(bmi):\n    if bmi < 18.5:\n        return "過輕"\n    if bmi < __1__:\n        return "正常"\n    return "過重"\n\nprint(level(22))   # 正常\n```', '24'),
    fb('傳入串列會被就地修改。\n\n```python\ndef add_tax_all(prices):\n    for i in range(len(prices)):\n        prices[i] = int(prices[i] * 1.05)\n\ndata = [100, 200]\nadd_tax_all(__1__)\nprint(data)   # [105, 210]\n```', 'data'),
    fb('把函式回傳值累加。\n\n```python\ndef fee(age):\n    return 150 if age < 12 else 300\n\ntotal = 0\nfor a in [8, 35, 10]:\n    total += __1__(a)\nprint(total)   # 600\n```', 'fee'),
    fb('用 return 提前跳出迴圈所在的函式。\n\n```python\ndef find_first_even(nums):\n    for n in nums:\n        if n % 2 == 0:\n            return __1__\n    return None\n\nprint(find_first_even([3, 7, 8, 10]))   # 8\n```', 'n'),
    fb('鍵盤輸入包裝函式（轉整數）。\n\n```python\ndef read_int():\n    return __1__(input())\n\nn = read_int()\nprint(n * 2)\n```', 'int'),
    fb('把運算結果格式化的輸出函式。\n\n```python\ndef report(name, avg):\n    return f"{name} 平均 {avg:.1f}"\n\nprint(report("Amy", 85.25))   # Amy 平均 __1__\n```\n\n（填輸出中的數值）', '85.2',
       explanation='85.25 以 .1f 顯示為 85.2（浮點儲存 85.249…）。'),
    fb('多參數含預設值的順序。\n\n```python\ndef make_tea(size, sugar=__1__):\n    return f"{size}杯{sugar}糖"\n\nprint(make_tea("大"))   # 大杯半糖\n```', ['"半"', "'半'"]),
    fb('把兩點距離包成函式。\n\n```python\ndef dist(x1, y1, x2, y2):\n    return ((x2 - x1) ** 2 + (y2 - y1) ** 2) ** __1__\n\nprint(dist(0, 0, 3, 4))   # 5.0\n```', '0.5'),
    fb('回傳布林的命名慣例。\n\n```python\ndef __1__(n):\n    return n % 2 == 0\n\nprint(is_even(10))   # True\n```', 'is_even'),
    fb('把清單統計包成函式回傳筆數與總和。\n\n```python\ndef stats(nums):\n    return len(nums), sum(nums)\n\ncount, total = stats([5, 5, 5])\nprint(count * 100 + __1__)   # 315\n```', 'total'),
    fb('巢狀呼叫：先取絕對值再開根號。\n\n```python\ndef my_abs(x):\n    return -x if x < 0 else x\n\nprint(my_abs(-16) ** 0.5)   # 4.0\n```\n\n空格：my_abs 內的三元運算式條件是 x __1__ 0。', '<'),
    fb('累進計費函式。\n\n```python\ndef parking(hours):\n    if hours <= 1:\n        return 40\n    return 40 + (hours - 1) * __1__\n\nprint(parking(4))   # 130\n```', '30'),
    fb('把已排序清單的中位數函式化。\n\n```python\ndef median(sorted_nums):\n    return sorted_nums[len(sorted_nums) // __1__]\n\nprint(median([1, 5, 9]))   # 5\n```', '2'),
    fb('回傳歡迎名單（逐一加稱謂）。\n\n```python\ndef add_title(names):\n    return [n + "同學" for n in __1__]\n\nprint(add_title(["小明"]))   # [\'小明同學\']\n```', 'names'),
    fb('依模式回傳不同分隔符。\n\n```python\ndef joiner(items, sep="-"):\n    return sep.__1__(items)\n\nprint(joiner(["a", "b"]))   # a-b\n```', 'join'),
    fb('函式回傳值再當條件。\n\n```python\ndef is_pass(s):\n    return s >= 60\n\nif is_pass(72):\n    print(__1__)   # 過關\n```', ['"過關"', "'過關'"]),
    fb('把重複三次的訊息輸出改成函式。\n\n```python\ndef notify(name):\n    print(f"{name} 請繳交作業")\n\nfor n in ["A", "B", "C"]:\n    __1__(n)\n```', 'notify'),
    fb('用函式計算列表平均並四捨五入。\n\n```python\ndef avg(nums):\n    return __1__(sum(nums) / len(nums))\n\nprint(avg([70, 75]))   # 72\n```', 'round'),
    fb('讓函式支援可調稅率。\n\n```python\ndef with_tax(price, rate=0.05):\n    return int(price * (1 + __1__))\n\nprint(with_tax(200, 0.1))   # 220\n```', 'rate'),
    fb('主流程統一呼叫。\n\n```python\ndef parse(t):\n    return [int(x) for x in t.split()]\n\ndef total(nums):\n    return sum(nums)\n\nprint(total(__1__("10 20 30")))   # 60\n```', 'parse'),
    fb('回傳多值後只取需要的。\n\n```python\ndef min_max(nums):\n    return min(nums), max(nums)\n\n_, biggest = min_max([4, 9, 1])\nprint(__1__)   # 9\n```', 'biggest'),
    fb('函式預設參數在無資料時回空清單長度。\n\n```python\ndef count_items(items=None):\n    if items is None:\n        return 0\n    return __1__(items)\n\nprint(count_items())   # 0\n```', 'len'),
]


# ── U7 Level 3：35 選擇 + 65 填空（競賽／TQC 實作：函式組合與介面）──
U7_L3 = [
    # 進階追蹤（35，含競賽原題）
    mc('執行下列 Python 程式片段，輸出結果為何？\n\n```python\ndef triangle_number(n):\n    return n * (n + 1) // 2\nprint(triangle_number(10) % 4)\n```', '3', '0', '1', '2',
       explanation='55 % 4 = 3。（113 商業類技藝競賽學科第 14 題）'),
    mc('以下程式的輸出是？\n\n```python\ndef f(x, lst=[]):\n    lst.append(x)\n    return lst\n\nprint(f(1))\nprint(f(2))\n```\n\n第二行輸出是？', '[1, 2]', '[2]', '[1]', '發生錯誤',
       explanation='可變預設參數被所有呼叫共享 — 經典陷阱。'),
    mc('以下程式的輸出是？\n\n```python\ndef compose(x):\n    return step2(step1(x))\n\ndef step1(x):\n    return x + 10\n\ndef step2(x):\n    return x * 2\n\nprint(compose(5))\n```', '30', '20', '25', '40',
       explanation='(5+10)×2。'),
    mc('以下程式的輸出是？\n\n```python\ndef counter():\n    count = 0\n    count += 1\n    return count\n\nprint(counter(), counter())\n```', '1 1', '1 2', '2 2', '0 1',
       explanation='區域變數每次呼叫重新建立，不會累計。'),
    mc('以下程式的輸出是？\n\n```python\ndef process(text):\n    text = text.strip()\n    return text.upper()\n\nraw = " hi "\nprint(process(raw), len(raw))\n```', 'HI 4', 'HI 2', 'hi 4', 'HI 3',
       explanation='字串不可變：函式內的處理不影響原字串。'),
    mc('以下程式的輸出是？\n\n```python\ndef make_adder(n):\n    def adder(x):\n        return x + n\n    return adder\n\nadd5 = make_adder(5)\nprint(add5(10))\n```', '15', '10', '5', '發生錯誤',
       explanation='函式可以回傳函式（閉包）。'),
    mc('以下程式的輸出是？\n\n```python\ndef fib(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\nprint(fib(6))\n```', '8', '5', '13', '6'),
    mc('以下程式的輸出是？\n\n```python\ndef tag(name, *, required):\n    return f"{name}:{required}"\n\nprint(tag("欄位", required=True))\n```', '欄位:True', 'name:required', '發生錯誤', '欄位',
       explanation='星號後的參數只能用關鍵字傳遞。'),
    mc('以下程式的輸出是？\n\n```python\nscores = [55, 80]\n\ndef curve(scores):\n    return [min(100, s + 20) for s in scores]\n\nnew = curve(scores)\nprint(scores, new)\n```', '[55, 80] [75, 100]', '[75, 100] [75, 100]', '[55, 80] [55, 80]', '[75, 100] [55, 80]',
       explanation='生成式建立新串列，原串列不變。'),
    mc('以下程式的輸出是？\n\n```python\ndef validate(s):\n    return 0 <= s <= 100\n\ndef average(raw):\n    nums = [int(x) for x in raw.split(",")]\n    valid = [n for n in nums if validate(n)]\n    return sum(valid) / len(valid)\n\nprint(average("80,120,60"))\n```', '70.0', '86.7', '120', '發生錯誤',
       explanation='120 被驗證函式過濾，(80+60)/2。'),
    mc('以下程式的輸出是？\n\n```python\ndef apply_all(funcs, x):\n    for f in funcs:\n        x = f(x)\n    return x\n\ndef double(n):\n    return n * 2\n\ndef dec(n):\n    return n - 1\n\nprint(apply_all([double, dec, double], 3))\n```', '10', '11', '12', '9',
       explanation='3→6→5→10。'),
    mc('以下程式的輸出是？\n\n```python\ndef risky(n):\n    if n < 0:\n        return\n    return n * 2\n\nprint(risky(-3))\n```', 'None', '0', '-6', '發生錯誤',
       explanation='return 不帶值等同回傳 None。'),
    mc('以下程式的輸出是？\n\n```python\ndef outer():\n    x = "外"\n    def inner():\n        return x + "內"\n    return inner()\n\nprint(outer())\n```', '外內', '內外', '外', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndef sort_by_len(words):\n    return sorted(words, key=len)\n\nprint(sort_by_len(["ccc", "a", "bb"]))\n```', "['a', 'bb', 'ccc']", "['ccc', 'bb', 'a']", "['a', 'ccc', 'bb']", '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndef total_seconds(h, m=0, s=0):\n    return h * 3600 + m * 60 + s\n\nprint(total_seconds(1, s=30))\n```', '3630', '3690', '5430', '90',
       explanation='3600 + 0 + 30。'),
    mc('以下程式的輸出是？\n\n```python\ndef find(nums, target):\n    for i, v in enumerate(nums):\n        if v == target:\n            return i\n    return -1\n\nprint(find([5, 8, 2], 2) + find([5, 8, 2], 9))\n```', '1', '2', '-1', '3',
       explanation='2 + (-1) = 1。'),
    mc('以下程式的輸出是？\n\n```python\ndef memo_less(n):\n    total = 0\n    for i in range(1, n + 1):\n        total += i\n    return total\n\nprint(memo_less(4) == 4 * 5 // 2)\n```', 'True', 'False', '10', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\ndef greet(name):\n    return "Hi " + name\n\nf = greet\nprint(f("Bob"))\n```', 'Hi Bob', 'greet', 'f Bob', '發生錯誤',
       explanation='函式名稱可以指定給別的變數。'),
    mc('以下程式的輸出是？\n\n```python\ndef grade(s):\n    for limit, g in [(90, "A"), (80, "B"), (70, "C")]:\n        if s >= limit:\n            return g\n    return "D"\n\nprint(grade(85))\n```', 'B', 'A', 'C', 'D',
       explanation='查表式分級：85 >= 80。'),
    mc('以下程式的輸出是？\n\n```python\ndef mask(text, keep=3):\n    return text[:keep] + "*" * (len(text) - keep)\n\nprint(mask("0912345678"))\n```', '091*******', '0912345678', '***2345678', '091',
       explanation='保留前三碼其餘打星。'),
    mc('以下程式的輸出是？\n\n```python\nresult = []\n\ndef collect(n):\n    result.append(n)\n\ncollect(1)\ncollect(2)\nprint(result)\n```', '[1, 2]', '[]', '[2]', '發生錯誤',
       explanation='沒有重新指定，只呼叫方法，可直接操作全域串列。'),
    mc('以下程式的輸出是？\n\n```python\ndef pipeline(text):\n    return format_out(int(text) * 2)\n\ndef format_out(n):\n    return f"值={n}"\n\nprint(pipeline("21"))\n```', '值=42', '值=21', '42', '值=2121'),
    mc('以下程式的輸出是？\n\n```python\ndef choose(f, g, use_f, x):\n    return f(x) if use_f else g(x)\n\nprint(choose(len, str.upper, False, "abc"))\n```', 'ABC', '3', 'abc', '發生錯誤',
       explanation='use_f 為 False，套用 str.upper。'),
    mc('以下程式的輸出是？\n\n```python\ndef stats(nums):\n    return {"n": len(nums), "sum": sum(nums)}\n\nr = stats([2, 4])\nprint(r["sum"] / r["n"])\n```', '3.0', '6', '2', '發生錯誤',
       explanation='回傳字典包多個統計值（教材 summarize 形式）。'),
    mc('以下程式的輸出是？\n\n```python\ndef retry(f, x, times):\n    for _ in range(times):\n        x = f(x)\n    return x\n\nprint(retry(lambda n: n // 2, 40, 3))\n```', '5', '10', '20', '0',
       explanation='40→20→10→5。'),
    mc('以下程式的輸出是？\n\n```python\ndef a(n):\n    return b(n) + 1\n\ndef b(n):\n    return c(n) * 2\n\ndef c(n):\n    return n + 3\n\nprint(a(2))\n```', '11', '10', '9', '12',
       explanation='c(2)=5、b=10、a=11。'),
    mc('以下程式的輸出是？\n\n```python\ndef safe_index(lst, i, default=None):\n    if 0 <= i < len(lst):\n        return lst[i]\n    return default\n\nprint(safe_index([1, 2], 5, "無"))\n```', '無', 'None', 'IndexError', '2'),
    mc('以下程式的輸出是？\n\n```python\ncounterA = 0\n\ndef hit():\n    global counterA\n    counterA += 1\n    return counterA\n\nhit()\nhit()\nprint(hit())\n```', '3', '1', '2', '0'),
    mc('以下程式的輸出是？\n\n```python\ndef normalize(text):\n    return "".join(ch.lower() for ch in text if ch.isalnum())\n\ndef is_pal(text):\n    t = normalize(text)\n    return t == t[::-1]\n\nprint(is_pal("A1, 1a!"))\n```', 'True', 'False', 'a11a', '發生錯誤',
       explanation='normalize 後 a11a 是回文（教材 U6/U7 綜合）。'),
    mc('以下程式的輸出是？\n\n```python\ndef score_gap(scores):\n    s = sorted(scores)\n    return s[-1] - s[0]\n\nprint(score_gap([72, 95, 60]))\n```', '35', '23', '95', '12'),
    mc('以下程式的輸出是？\n\n```python\ndef greet(name, greeting="Hi"):\n    return f"{greeting}, {name}"\n\nprint(greet(greeting="Yo", name="Al"))\n```', 'Yo, Al', 'Hi, Al', 'Al, Yo', '發生錯誤'),
    mc('以下兩個函式的差別是？\n\n```python\ndef f1(nums):\n    nums = nums + [99]\n    return nums\n\ndef f2(nums):\n    nums.append(99)\n    return nums\n```', 'f1 建立新串列不影響原串列、f2 就地修改會影響',
       '完全相同', 'f2 不影響原串列', '兩者都會報錯',
       explanation='+ 產生新物件、append 是就地操作。'),
    mc('以下程式的輸出是？\n\n```python\ndef run_checks(pwd):\n    checks = [len(pwd) >= 8, any(ch.isdigit() for ch in pwd)]\n    return all(checks)\n\nprint(run_checks("abcdefg1"))\n```', 'True', 'False', '2', '發生錯誤',
       explanation='長度 8 且含數字。'),
    mc('以下程式的輸出是？\n\n```python\ndef transform(nums, f):\n    return [f(n) for n in nums]\n\nprint(transform([1, -2, 3], abs))\n```', '[1, 2, 3]', '[-1, -2, -3]', '[1, -2, 3]', '6'),
    mc('以下程式的輸出是？\n\n```python\ndef make_id(prefix, no):\n    return f"{prefix}{no:03d}"\n\nprint(make_id("S", 7))\n```', 'S007', 'S7', 'S700', 'S 7',
       explanation='03d 補零到三位。'),

    # ── L3 填空（65）──
    fb('競賽風格：三角形數函式。\n\n```python\ndef triangle_number(n):\n    return n * (n + 1) __1__ 2\n\nprint(triangle_number(10) % 4)   # 3\n```', '//'),
    fb('函式管線：解析→驗證→統計。\n\n```python\ndef parse(text):\n    return [int(x) for x in text.split(",")]\n\ndef valid(n):\n    return 0 <= n <= 100\n\nnums = [n for n in parse("80,120,60") if __1__(n)]\nprint(sum(nums))   # 140\n```', 'valid'),
    fb('回傳函式（閉包）。\n\n```python\ndef make_multiplier(k):\n    def mul(x):\n        return x * k\n    return __1__\n\ntriple = make_multiplier(3)\nprint(triple(7))   # 21\n```', 'mul'),
    fb('函式當參數的批次轉換。\n\n```python\ndef transform(nums, f):\n    return [f(n) for n in nums]\n\nprint(transform([-1, 2, -3], __1__))   # [1, 2, 3]\n```', 'abs'),
    fb('查表式分級函式。\n\n```python\ndef grade(s):\n    for limit, g in [(90, "A"), (80, "B")]:\n        if s >= limit:\n            return __1__\n    return "C"\n\nprint(grade(92))   # A\n```', 'g'),
    fb('迭代版費氏數列函式。\n\n```python\ndef fib(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a __1__ b\n    return a\n\nprint(fib(7))   # 13\n```', '+'),
    fb('遮罩函式：保留前 keep 碼。\n\n```python\ndef mask(text, keep=3):\n    return text[:keep] + "*" * (len(text) - __1__)\n\nprint(mask("ABCDEFG"))   # ABC****\n```', 'keep'),
    fb('安全取值：索引越界回傳預設。\n\n```python\ndef safe_get(lst, i, default=0):\n    if 0 <= i < len(lst):\n        return lst[i]\n    return __1__\n\nprint(safe_get([5, 6], 9))   # 0\n```', 'default'),
    fb('用 all 做多重檢查。\n\n```python\ndef strong(pwd):\n    return __1__([len(pwd) >= 8, not pwd.isdigit()])\n\nprint(strong("abc12345"))   # True\n```', 'all'),
    fb('把統計結果包成字典回傳。\n\n```python\ndef summarize(nums):\n    return {"count": len(nums), "total": __1__(nums)}\n\nr = summarize([3, 4, 5])\nprint(r["total"])   # 12\n```', 'sum'),
    fb('組合函式：先清理再判斷回文。\n\n```python\ndef normalize(t):\n    return "".join(ch.lower() for ch in t if ch.isalnum())\n\ndef is_pal(t):\n    c = __1__(t)\n    return c == c[::-1]\n\nprint(is_pal("No on"))   # True\n```', 'normalize'),
    fb('用函式算複利年數。\n\n```python\ndef years_to_double(rate):\n    money = 1.0\n    years = 0\n    while money < 2:\n        money *= (1 + rate)\n        years += 1\n    return __1__\n\nprint(years_to_double(0.1))   # 8\n```', 'years'),
    fb('把攤販找零流程函式化。\n\n```python\ndef change(pay, price):\n    c = pay - price\n    return c // 100, c % 100\n\nbills, coins = change(1000, 640)\nprint(bills, __1__)   # 3 60\n```', 'coins'),
    fb('遞增計數器（global）。\n\n```python\nclicks = 0\n\ndef click():\n    global clicks\n    clicks __1__ 1\n\nclick()\nclick()\nprint(clicks)   # 2\n```', '+='),
    fb('函式回傳生成式過濾結果。\n\n```python\ndef adults(ages):\n    return [a for a in ages if a >= __1__]\n\nprint(adults([15, 22, 18]))   # [22, 18]\n```', '18'),
    fb('把秒數格式化成 mm:ss 的函式。\n\n```python\ndef fmt(sec):\n    return f"{sec // 60}:{sec % 60:02__1__}"\n\nprint(fmt(65))   # 1:05\n```', 'd'),
    fb('可調門檻的過濾函式。\n\n```python\ndef over(nums, threshold=60):\n    return [n for n in nums if n > __1__]\n\nprint(over([50, 70, 90], 80))   # [90]\n```', 'threshold'),
    fb('把清單正規化成百分比。\n\n```python\ndef to_percent(nums):\n    total = sum(nums)\n    return [round(n / total * 100) for n in __1__]\n\nprint(to_percent([1, 3]))   # [25, 75]\n```', 'nums'),
    fb('鏈式呼叫：先過濾再統計。\n\n```python\ndef only_pass(scores):\n    return [s for s in scores if s >= 60]\n\ndef average(nums):\n    return sum(nums) / len(nums)\n\nprint(average(__1__([50, 70, 90])))   # 80.0\n```', 'only_pass'),
    fb('用預設參數控制四捨五入位數。\n\n```python\ndef fmt_num(x, digits=__1__):\n    return round(x, digits)\n\nprint(fmt_num(3.14159))   # 3.14\n```', '2'),
    fb('遞迴前身：函式反覆套用。\n\n```python\ndef apply_n(f, x, n):\n    for _ in range(n):\n        x = f(x)\n    return x\n\nprint(apply_n(lambda v: v * 2, 1, 5))   # __1__\n```\n\n（填輸出）', '32'),
    fb('把姓名清單轉學號格式。\n\n```python\ndef make_ids(names):\n    return [f"S{i:02d}" for i in range(1, len(names) + __1__)]\n\nprint(make_ids(["a", "b"]))   # [\'S01\', \'S02\']\n```', '1'),
    fb('驗證函式回傳原因字串。\n\n```python\ndef check(score):\n    if score < 0:\n        return "太低"\n    if score > 100:\n        return "太高"\n    return __1__\n\nprint(check(50))   # OK\n```', ['"OK"', "'OK'"]),
    fb('計算 BMI 並分級（兩函式串接）。\n\n```python\ndef bmi(w, h):\n    return w / h ** 2\n\ndef level(b):\n    return "過重" if b >= 24 else "正常"\n\nprint(level(bmi(80, 1.7)))   # __1__\n```\n\n（填輸出）', '過重',
       explanation='80/2.89 ≈ 27.7 ≥ 24。'),
    fb('函式化的最大公因數。\n\n```python\ndef gcd(a, b):\n    while b:\n        a, b = b, a __1__ b\n    return a\n\nprint(gcd(36, 60))   # 12\n```', '%'),
    fb('把消費紀錄轉月報表（函式回傳格式化字串）。\n\n```python\ndef report(month, total):\n    return f"{month}月支出 {total:,} 元"\n\nprint(report(7, 12500))   # 7月支出 __1__ 元\n```\n\n（填輸出中的金額字串）', '12,500'),
    fb('依 key 函式排序。\n\n```python\ndef by_score(item):\n    return item[1]\n\ndata = [("Amy", 88), ("Bob", 95)]\ndata.sort(key=__1__, reverse=True)\nprint(data[0][0])   # Bob\n```', 'by_score'),
    fb('把百分制轉五分制的函式。\n\n```python\ndef to_gpa(score):\n    return min(5, score // __1__ + 1)\n\nprint(to_gpa(88))   # 5\n```', '20',
       explanation='88//20+1=5。'),
    fb('避免副作用：回傳新串列而非修改。\n\n```python\ndef add_bonus(scores):\n    return [s + 5 for s in scores]\n\nold = [70, 80]\nnew = add_bonus(old)\nprint(old, __1__)   # [70, 80] [75, 85]\n```', 'new'),
    fb('限制次數的重試流程。\n\n```python\ndef guess_game(answers, target):\n    for i, a in enumerate(answers, start=1):\n        if a == target:\n            return i\n    return -1\n\nprint(guess_game([3, 7, 5], 5))   # __1__\n```\n\n（填輸出）', '3'),
    fb('把長度驗證獨立成函式。\n\n```python\ndef valid_len(text, low=2, high=10):\n    return low <= __1__(text) <= high\n\nprint(valid_len("ab"))   # True\n```', 'len'),
    fb('多層預設參數呼叫。\n\n```python\ndef order(item, qty=1, note=""):\n    return f"{item}x{qty}{note}"\n\nprint(order("紅茶", note="去冰"))   # 紅茶x__1__去冰\n```\n\n（填輸出中的數量）', '1'),
    fb('把清單分成前後兩半的函式。\n\n```python\ndef split_half(items):\n    mid = len(items) // 2\n    return items[:mid], items[mid:]\n\nfront, back = split_half([1, 2, 3, 4])\nprint(__1__)   # [3, 4]\n```', 'back'),
    fb('溫度警報函式（回傳布林）。\n\n```python\ndef alert(t, low=10, high=35):\n    return t <= low __1__ t >= high\n\nprint(alert(36))   # True\n```', 'or'),
    fb('把重複的輸入驗證包成 while 函式。\n\n```python\ndef read_valid():\n    n = int(input())\n    while n < 0:\n        n = int(input())\n    return __1__\n\nprint(read_valid())\n```', 'n'),
    fb('計算平方和的函式。\n\n```python\ndef square_sum(nums):\n    return sum(n ** __1__ for n in nums)\n\nprint(square_sum([1, 2, 3]))   # 14\n```', '2'),
    fb('把函式存進清單輪流呼叫。\n\n```python\ndef a(x):\n    return x + 1\n\ndef b(x):\n    return x * 2\n\nresult = 3\nfor f in [a, b, a]:\n    result = __1__(result)\nprint(result)   # 9\n```', 'f',
       explanation='3→4→8→9。'),
    fb('回傳最接近目標的值。\n\n```python\ndef closest(nums, target):\n    best = nums[0]\n    for n in nums:\n        if abs(n - target) < abs(best - __1__):\n            best = n\n    return best\n\nprint(closest([10, 22, 35], 25))   # 22\n```', 'target'),
    fb('把運費規則封裝並回傳總額。\n\n```python\ndef shipping(amount, member):\n    if amount >= 1000 or (member and amount >= 500):\n        return 0\n    return __1__\n\nprint(shipping(600, True))   # 0\n```', '80'),
    fb('用函式包住重複的邊界修正。\n\n```python\ndef clamp(n, low=0, high=100):\n    if n < low:\n        return low\n    if n > high:\n        return __1__\n    return n\n\nprint(clamp(120))   # 100\n```', 'high'),
    fb('批次呼叫驗證函式統計合格數。\n\n```python\ndef ok(n):\n    return n % 2 == 0\n\nnums = [1, 2, 3, 4]\nprint(sum(1 for n in nums if __1__(n)))   # 2\n```', 'ok'),
    fb('讓函式輸出排行榜名次。\n\n```python\ndef rank_of(scores, mine):\n    ordered = sorted(scores, reverse=True)\n    return ordered.index(__1__) + 1\n\nprint(rank_of([70, 95, 88], 88))   # 2\n```', 'mine'),
    fb('把逗號金額字串轉數值的函式。\n\n```python\ndef to_int(money):\n    return int(money.replace(",", __1__))\n\nprint(to_int("1,200") * 2)   # 2400\n```', ['""', "''"]),
    fb('產生乘法表單列的函式。\n\n```python\ndef row(n):\n    return [n * j for j in range(1, 10)]\n\nprint(row(9)[__1__])   # 81\n```', '-1'),
    fb('把清單標準化（減最小值）。\n\n```python\ndef normalize(nums):\n    low = min(nums)\n    return [n - __1__ for n in nums]\n\nprint(normalize([5, 8, 6]))   # [0, 3, 1]\n```', 'low'),
    fb('用函式判斷閏年。\n\n```python\ndef is_leap(y):\n    return y % 400 == 0 or (y % 4 == 0 __1__ y % 100 != 0)\n\nprint(is_leap(2024))   # True\n```', 'and'),
    fb('把兩函式的結果相比取大。\n\n```python\ndef plan_a(x):\n    return x * 0.9\n\ndef plan_b(x):\n    return x - 100\n\nx = 800\nprint(min(plan_a(x), plan_b(__1__)))   # 700\n```', 'x',
       explanation='720 vs 700，取較省的 700。'),
    fb('函式內建立累計並回傳（無副作用）。\n\n```python\ndef running_total(nums):\n    out = []\n    total = 0\n    for n in nums:\n        total += n\n        out.append(total)\n    return __1__\n\nprint(running_total([1, 2, 3]))   # [1, 3, 6]\n```', 'out'),
    fb('把驗證錯誤提前擋掉（guard）。\n\n```python\ndef divide(a, b):\n    if b == 0:\n        return "錯誤"\n    return a __1__ b\n\nprint(divide(9, 3))   # 3.0\n```', '/'),
    fb('用參數切換排序方向。\n\n```python\ndef order(nums, desc=False):\n    return sorted(nums, reverse=__1__)\n\nprint(order([3, 1, 2], True))   # [3, 2, 1]\n```', 'desc'),
    fb('把使用時間轉費用（每 30 分 20 元，無條件進位）。\n\n```python\ndef fee(mins):\n    units = (mins + 29) // __1__\n    return units * 20\n\nprint(fee(61))   # 60\n```', '30'),
    fb('回傳週幾名稱（查表）。\n\n```python\ndef day_name(n):\n    names = ["一", "二", "三", "四", "五", "六", "日"]\n    return names[n - __1__]\n\nprint(day_name(3))   # 三\n```', '1'),
    fb('用函式移除清單中所有指定值（生成新串列）。\n\n```python\ndef remove_all(items, bad):\n    return [x for x in items if x __1__ bad]\n\nprint(remove_all([1, 0, 2, 0], 0))   # [1, 2]\n```', '!='),
    fb('用函式檢查兩清單是否互為排列。\n\n```python\ndef same_items(a, b):\n    return __1__(a) == sorted(b)\n\nprint(same_items([3, 1], [1, 3]))   # True\n```', 'sorted'),
    fb('依權重加總的評分函式。\n\n```python\ndef final(mid, end, w=0.4):\n    return mid * w + end * (1 - __1__)\n\nprint(final(80, 90))   # 86.0\n```', 'w'),
    fb('回傳清單中第 k 大的值。\n\n```python\ndef kth_largest(nums, k):\n    return sorted(nums, reverse=True)[k - __1__]\n\nprint(kth_largest([5, 9, 1, 7], 2))   # 7\n```', '1'),
    fb('把整數轉為位數清單的函式。\n\n```python\ndef digits(n):\n    return [int(ch) for ch in __1__(n)]\n\nprint(digits(504))   # [5, 0, 4]\n```', 'str'),
    fb('把清單旋轉 k 位的函式。\n\n```python\ndef rotate(items, k):\n    k = k % len(items)\n    return items[k:] + items[:__1__]\n\nprint(rotate([1, 2, 3, 4], 1))   # [2, 3, 4, 1]\n```', 'k'),
    fb('把驗證與轉換合成一個安全轉換函式。\n\n```python\ndef to_score(text):\n    if not text.isdigit():\n        return None\n    n = int(text)\n    return n if 0 <= n <= 100 else __1__\n\nprint(to_score("120"))   # None\n```', 'None'),
    fb('模擬簡單狀態機：函式回傳下一狀態。\n\n```python\ndef next_state(s):\n    return {"紅": "綠", "綠": "黃", "黃": "紅"}[s]\n\nstate = "紅"\nfor _ in range(2):\n    state = next_state(__1__)\nprint(state)   # 黃\n```', 'state'),
    fb('把攝氏批次轉華氏並找最大。\n\n```python\ndef to_f(c):\n    return c * 9 / 5 + 32\n\ntemps = [20, 35, 28]\nprint(max(to_f(c) for c in __1__))   # 95.0\n```', 'temps'),
    fb('回傳「是否全部及格」。\n\n```python\ndef all_pass(scores):\n    return __1__(s >= 60 for s in scores)\n\nprint(all_pass([70, 80, 61]))   # True\n```', 'all'),
    fb('回傳「是否有人不及格」。\n\n```python\ndef any_fail(scores):\n    return __1__(s < 60 for s in scores)\n\nprint(any_fail([70, 50, 80]))   # True\n```', 'any'),
    fb('把函式串成資料清理管線。\n\n```python\ndef clean(t):\n    return t.strip()\n\ndef to_num(t):\n    return int(t)\n\nraw = " 42 "\nprint(to_num(__1__(raw)) + 8)   # 50\n```', 'clean'),
    fb('把重複的稅額計算包成函式並套用。\n\n```python\ndef with_tax(price):\n    return round(price * 1.05)\n\nprint(with_tax(200) + with_tax(100))   # 315\n```\n\n空格：稅率 5% 對應的乘數是 1.__1__。', '05'),
]
