"""Unit 2（條件判斷 If／Elif／Else）混合題庫 — 全選擇制。

fb() 題會由 curriculum_questions_v2 的 _all_mc() 於載入時自動轉成選擇題。
L1 對標 ITS（概念＋單步追蹤）、L2 對標 TQC+ 觀念題（多分支追蹤＋邊界值）、
L3 對標競賽／TQC 實作（規則建模、chained comparison、三元運算式）。
收錄競賽原題：113 商業類學科第 25 題（→L2）。
"""
from .question_helpers import mc, fb

# ── U2 Level 1：55 選擇 + 45 填空（概念辨識、單步追蹤）──
U2_L1 = [
    # 關係運算子（12）
    mc('哪個運算子用來判斷兩個值「相等」？', '==', '=', '!=', '≈'),
    mc('哪個運算子表示「不相等」？', '!=', '==', '<>', '=/='),
    mc('x = 5 與 x == 5 的差別是？', 'x = 5 是指定值，x == 5 是比較是否相等',
       '兩者完全相同', 'x = 5 是比較，x == 5 是指定', '兩者都會發生錯誤'),
    mc('print(5 > 3) 的輸出是？', 'True', 'False', '5', '3'),
    mc('print(7 == 7) 的輸出是？', 'True', 'False', '7', '發生錯誤'),
    mc('print(3 != 3) 的輸出是？', 'False', 'True', '3', '發生錯誤'),
    mc('print(10 >= 10) 的輸出是？', 'True', 'False', '10', '發生錯誤',
       explanation='>= 包含「等於」的情況。'),
    mc('print(2 < 1) 的輸出是？', 'False', 'True', '2', '1'),
    mc('關係運算（如 a > b）的結果是哪一種型態？', 'bool', 'int', 'str', 'float'),
    mc('「小於或等於」的運算子是？', '<=', '=<', '<', '≦'),
    mc('print("cat" == "cat") 的輸出是？', 'True', 'False', 'cat', '發生錯誤'),
    mc('score = 59 時，score >= 60 的結果是？', 'False', 'True', '59', '60'),

    # 語法規則（12）
    mc('if 條件式的行尾必須加上什麼符號？', '冒號 :', '分號 ;', '句點 .', '逗號 ,'),
    mc('if 底下要執行的程式區塊靠什麼標示？', '縮排', '大括號 { }', '小括號 ( )', '引號'),
    mc('elif 的意思是？', '前面條件不成立時，再檢查另一個條件', '重複執行前面的條件',
       '結束整個判斷', '無條件執行'),
    mc('else 後面需要寫條件嗎？', '不需要，else 承接所有剩餘情況', '需要寫一個條件',
       '只能寫 True', '只能寫數字'),
    mc('一組 if/elif/else 中，最多會執行幾個分支？', '1 個', '2 個', '全部', '0 個',
       explanation='互斥分支：由上往下找到第一個成立的條件就執行該分支，其餘跳過。'),
    mc('下列哪個 if 寫法正確？', 'if x > 5:', 'if x > 5', 'If x > 5:', 'if x > 5 then:'),
    mc('一組判斷中可以寫幾個 elif？', '需要幾個就寫幾個', '最多 1 個', '最多 2 個', '不能使用'),
    mc('一組 if 判斷中 else 最多能有幾個？', '1 個', '2 個', '3 個', '不限'),
    mc('if 成立時要執行的那一行忘記縮排，會發生什麼？', '引發 IndentationError',
       '正常執行', 'Python 自動補縮排', '引發 ValueError'),
    mc('條件不成立且沒有寫 else 時，程式會？', '跳過整組判斷，繼續執行後面的程式',
       '發生錯誤', '停止程式', '自動執行 if 區塊'),
    mc('Python 的 if 關鍵字正確寫法是？', '全小寫 if', 'If', 'IF', 'iF'),
    mc('elif 可以不接在 if 之後單獨使用嗎？', '不可以，elif 必須接在 if 之後',
       '可以單獨使用', '只要有 else 就可以', '一支程式只能用一次'),

    # 邏輯運算子（12）
    mc('and 的意思是？', '兩個條件都成立才為 True', '至少一個條件成立就為 True',
       '反轉條件真假', '兩個條件都不成立才為 True'),
    mc('or 的意思是？', '至少一個條件成立就為 True', '兩個條件都要成立',
       '反轉條件真假', '永遠為 True'),
    mc('not 的作用是？', '把 True 變 False、False 變 True', '連接兩個條件',
       '結束判斷', '比較兩值大小'),
    mc('print(True and False) 的輸出是？', 'False', 'True', 'None', '發生錯誤'),
    mc('print(True or False) 的輸出是？', 'True', 'False', 'None', '發生錯誤'),
    mc('print(not True) 的輸出是？', 'False', 'True', 'not', '發生錯誤'),
    mc('「成績及格『而且』出席率達標」應該用哪個運算子連接兩條件？', 'and', 'or', 'not', '=='),
    mc('「今天是星期六『或』星期日」應該用哪個運算子？', 'or', 'and', 'not', '!='),
    mc('print(not (5 > 3)) 的輸出是？', 'False', 'True', '5', '發生錯誤',
       explanation='5 > 3 是 True，not True 是 False。'),
    mc('x = 8 時，x > 5 and x < 10 的結果是？', 'True', 'False', '8', '發生錯誤'),
    mc('x = 12 時，x < 5 or x > 10 的結果是？', 'True', 'False', '12', '發生錯誤'),
    mc('print(False or False) 的輸出是？', 'False', 'True', 'None', '0'),

    # 單一 if／if-else 追蹤（10）
    mc('以下程式的輸出是？\n\n```python\nx = 10\nif x > 5:\n    print("大")\n```', '大', '沒有任何輸出', 'x > 5', 'True'),
    mc('以下程式的輸出是？\n\n```python\nx = 3\nif x > 5:\n    print("大")\n```', '沒有任何輸出', '大', 'False', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nif True:\n    print("A")\n```', 'A', '沒有任何輸出', 'True', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nn = 7\nif n % 2 == 1:\n    print("奇數")\n```', '奇數', '偶數', '沒有任何輸出', '1'),
    mc('以下程式的輸出是？\n\n```python\nn = 6\nif n % 2 == 0:\n    print("偶數")\nelse:\n    print("奇數")\n```', '偶數', '奇數', '6', '0'),
    mc('以下程式的輸出是？\n\n```python\nscore = 75\nif score >= 60:\n    print("及格")\nelse:\n    print("不及格")\n```', '及格', '不及格', '75', '60'),
    mc('以下程式的輸出是？\n\n```python\nn = -3\nif n >= 0:\n    print("非負數")\nelse:\n    print("負數")\n```', '負數', '非負數', '-3', '0'),
    mc('以下程式的輸出是？\n\n```python\na = 5\nb = 9\nif a > b:\n    print(a)\nelse:\n    print(b)\n```', '9', '5', 'a', 'b'),
    mc('以下程式的輸出是？\n\n```python\npwd = "1234"\nif pwd == "1234":\n    print("登入成功")\nelse:\n    print("登入失敗")\n```', '登入成功', '登入失敗', '1234', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nx = 5\nif x > 3:\n    print("A")\nprint("B")\n```', 'A 與 B（兩行都輸出）', '只輸出 A', '只輸出 B', '沒有任何輸出',
       explanation='print("B") 沒有縮排，不屬於 if 區塊，一定會執行。'),

    # elif 多分支追蹤（9）
    mc('以下程式的輸出是？\n\n```python\nt = 36.5\nif t > 37.5:\n    print("發燒")\nelif t < 36:\n    print("偏低")\nelse:\n    print("正常")\n```', '正常', '發燒', '偏低', '36.5'),
    mc('以下程式的輸出是？\n\n```python\nt = 38.2\nif t > 37.5:\n    print("發燒")\nelif t < 36:\n    print("偏低")\nelse:\n    print("正常")\n```', '發燒', '正常', '偏低', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nscore = 85\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelse:\n    print("C")\n```', 'B', 'A', 'C', 'AB'),
    mc('以下程式 score = 90 時的輸出是？\n\n```python\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelse:\n    print("C")\n```', 'A', 'B', 'C', 'A 與 B',
       explanation='90 >= 90 成立，執行第一個分支後整組判斷結束。'),
    mc('以下程式的輸出是？\n\n```python\nscore = 59\nif score >= 60:\n    print("及格")\nelif score >= 50:\n    print("補考")\nelse:\n    print("重修")\n```', '補考', '及格', '重修', '59'),
    mc('以下程式的輸出是？\n\n```python\nn = 0\nif n > 0:\n    print("正數")\nelif n < 0:\n    print("負數")\nelse:\n    print("零")\n```', '零', '正數', '負數', '0'),
    mc('以下程式的輸出是？\n\n```python\nx = 10\nif x > 5:\n    print("A")\nif x > 8:\n    print("B")\n```', 'A 與 B（兩行都輸出）', '只輸出 A', '只輸出 B', '沒有任何輸出',
       explanation='兩個獨立的 if 會分別判斷；elif 才會互斥。'),
    mc('以下程式的輸出是？\n\n```python\nx = 10\nif x > 5:\n    print("A")\nelif x > 8:\n    print("B")\n```', '只輸出 A', 'A 與 B', '只輸出 B', '沒有任何輸出',
       explanation='if 成立後，後面的 elif 不再檢查。'),
    mc('以下程式的輸出是？\n\n```python\ns = 95\nif s >= 60:\n    print("及格")\nelif s >= 90:\n    print("優秀")\n```', '及格', '優秀', '及格與優秀', '沒有任何輸出',
       explanation='95 先滿足 s >= 60，「優秀」分支永遠不會被檢查 — 條件順序很重要。'),

    # ── L1 填空（45）──
    fb('讀入成績，60 分以上（含）輸出「及格」。\n\n```python\nscore = int(input())\nif score __1__ 60:\n    print("及格")\n```', '>='),
    fb('密碼正確才輸出歡迎訊息。\n\n```python\npwd = input()\nif pwd __1__ "abc123":\n    print("歡迎")\n```', '=='),
    fb('輸入的答案「不等於」標準答案時輸出提示。\n\n```python\nans = input()\nif ans __1__ "B":\n    print("答錯了")\n```', '!='),
    fb('n 是偶數時輸出「偶數」，否則輸出「奇數」。\n\n```python\nn = int(input())\nif n % 2 == 0:\n    print("偶數")\n__1__:\n    print("奇數")\n```', 'else'),
    fb('三段判斷：正數、負數、零。\n\n```python\nn = int(input())\nif n > 0:\n    print("正數")\n__1__ n < 0:\n    print("負數")\nelse:\n    print("零")\n```', 'elif'),
    fb('年齡在 13 到 17 歲（含）之間輸出「青少年」（用 and）。\n\n```python\nage = int(input())\nif age >= 13 __1__ age <= 17:\n    print("青少年")\n```', 'and'),
    fb('星期六或星期日輸出「假日」。\n\n```python\nday = int(input())\nif day == 6 __1__ day == 7:\n    print("假日")\n```', 'or'),
    fb('不是會員才顯示註冊提示。\n\n```python\nis_member = False\nif __1__ is_member:\n    print("請先註冊")\n```', 'not'),
    fb('n 可以被 2 整除時輸出「偶數」。\n\n```python\nn = int(input())\nif n % 2 __1__ 0:\n    print("偶數")\n```', '=='),
    fb('補上 if 行尾缺少的符號。\n\n```python\nx = int(input())\nif x > 100__1__\n    print("超過上限")\n```', ':'),
    fb('體溫超過 37.5 輸出警告。\n\n```python\nt = float(input())\nif t __1__ 37.5:\n    print("體溫過高")\n```', '>'),
    fb('餘額低於 100 時提醒儲值。\n\n```python\nbalance = int(input())\nif balance __1__ 100:\n    print("請儲值")\n```', '<'),
    fb('輸入 "yes" 就繼續遊戲。\n\n```python\nagain = input()\nif again == __1__:\n    print("再玩一局")\n```', ['"yes"', "'yes'"]),
    fb('滿 18 歲（含）輸出「成年」，否則輸出「未成年」。\n\n```python\nage = int(input())\nif age >= 18:\n    print("成年")\nelse:\n    print(__1__)\n```', ['"未成年"', "'未成年'"]),
    fb('速度超過速限 60 輸出「超速」，否則輸出「正常」。\n\n```python\nspeed = int(input())\nif speed > __1__:\n    print("超速")\nelse:\n    print("正常")\n```', '60'),
    fb('判斷 n 是否為 5 的倍數。\n\n```python\nn = int(input())\nif n __1__ 5 == 0:\n    print("是 5 的倍數")\n```', '%'),
    fb('兩人成績相同輸出「平手」。\n\n```python\na = int(input())\nb = int(input())\nif a __1__ b:\n    print("平手")\n```', '=='),
    fb('a 比 b 大時輸出 a，否則輸出 b（求較大值）。\n\n```python\na = int(input())\nb = int(input())\nif a __1__ b:\n    print(a)\nelse:\n    print(b)\n```', '>'),
    fb('電量少於等於 20 時輸出「低電量」。\n\n```python\nbattery = int(input())\nif battery __1__ 20:\n    print("低電量")\n```', '<='),
    fb('輸入非零就輸出「有數值」。\n\n```python\nn = int(input())\nif n __1__ 0:\n    print("有數值")\n```', '!='),
    fb('成績同時大於等於 0 且小於等於 100 才算有效。\n\n```python\ns = int(input())\nif s >= 0 __1__ s <= 100:\n    print("有效成績")\n```', 'and'),
    fb('會員或持優惠券擇一即可折扣。\n\n```python\nis_member = True\nhas_coupon = False\nif is_member __1__ has_coupon:\n    print("享有折扣")\n```', 'or'),
    fb('不是假日就要上學。\n\n```python\nis_holiday = False\nif __1__ is_holiday:\n    print("上學日")\n```', 'not'),
    fb('三段成績等級：90 以上 A、80 以上 B、其餘 C。\n\n```python\ns = int(input())\nif s >= 90:\n    print("A")\nelif s >= __1__:\n    print("B")\nelse:\n    print("C")\n```', '80'),
    fb('身高滿 120 公分才能搭乘。\n\n```python\nheight = int(input())\nif height >= __1__:\n    print("可以搭乘")\nelse:\n    print("身高不足")\n```', '120'),
    fb('庫存為 0 時顯示補貨中。\n\n```python\nstock = int(input())\nif stock __1__ 0:\n    print("補貨中")\nelse:\n    print("有現貨")\n```', '=='),
    fb('遲到超過 10 分鐘記缺席，否則記遲到。\n\n```python\nlate = int(input())\nif late > 10:\n    print("缺席")\n__1__:\n    print("遲到")\n```', 'else'),
    fb('溫度低於 0 度輸出「結冰」。\n\n```python\nt = float(input())\nif t < __1__:\n    print("結冰")\n```', '0'),
    fb('按讚數達 1000（含）輸出「熱門貼文」。\n\n```python\nlikes = int(input())\nif likes __1__ 1000:\n    print("熱門貼文")\n```', '>='),
    fb('輸入 1 輸出「開燈」、輸入其他輸出「關燈」。\n\n```python\ncmd = int(input())\nif cmd == __1__:\n    print("開燈")\nelse:\n    print("關燈")\n```', '1'),
    fb('n 是正偶數（大於 0 且能被 2 整除）時輸出訊息。\n\n```python\nn = int(input())\nif n > 0 __1__ n % 2 == 0:\n    print("正偶數")\n```', 'and'),
    fb('四段等級判斷的最後一段：其餘情況輸出 F。\n\n```python\ns = int(input())\nif s >= 90:\n    print("A")\nelif s >= 80:\n    print("B")\nelif s >= 70:\n    print("C")\n__1__:\n    print("F")\n```', 'else'),
    fb('密碼長度至少 8 個字元才安全。\n\n```python\npwd = input()\nif __1__(pwd) >= 8:\n    print("長度足夠")\nelse:\n    print("太短")\n```', 'len'),
    fb('點數不足 50 無法兌換。\n\n```python\npoints = int(input())\nif points < 50:\n    print("點數不足")\nelse:\n    print(__1__)\n```', ['"兌換成功"', "'兌換成功'"]),
    fb('輸入的月份是 12、1 或 2 輸出「冬季」。\n\n```python\nm = int(input())\nif m == 12 or m == 1 __1__ m == 2:\n    print("冬季")\n```', 'or'),
    fb('把「大於等於 60」的比較結果直接輸出（True/False）。\n\n```python\ns = int(input())\nprint(s __1__ 60)\n```', '>='),
    fb('三人成績找最高（先比前兩人）。\n\n```python\na, b, c = 70, 85, 60\nbig = a\nif b > big:\n    big = b\nif c __1__ big:\n    big = c\nprint(big)   # 85\n```', '>'),
    fb('判斷輸入是否介於 1 到 6（骰子點數合法性，用 and）。\n\n```python\nd = int(input())\nif d >= 1 __1__ d <= 6:\n    print("合法點數")\n```', 'and'),
    fb('會員費：成人 300、兒童（未滿 12）150。\n\n```python\nage = int(input())\nif age < 12:\n    print(150)\nelse:\n    print(__1__)\n```', '300'),
    fb('答對輸出「正確」，否則輸出「再想想」。\n\n```python\nans = int(input())\nif ans == 42:\n    print("正確")\nelse:\n    print("再想想")\n```\n\n若輸入 41，輸出是？（把輸出文字填入）', ['再想想', '"再想想"', "'再想想'"]),
    fb('用 not 讓條件反轉：不在營業時間輸出休息中。\n\n```python\nis_open = False\nif not is_open:\n    print(__1__)\n```', ['"休息中"', "'休息中'"]),
    fb('滿千免運：金額達 1000（含）運費為 0，否則 80。\n\n```python\namount = int(input())\nif amount >= 1000:\n    fee = __1__\nelse:\n    fee = 80\nprint(fee)\n```', '0'),
    fb('判斷字串是否為空（長度等於 0）。\n\n```python\ntext = input()\nif len(text) == __1__:\n    print("沒有輸入內容")\n```', '0'),
    fb('成績 60 以上且未滿 90 輸出「中等」。\n\n```python\ns = int(input())\nif s >= 60 and s __1__ 90:\n    print("中等")\n```', '<'),
    fb('兩科都及格（>= 60）才輸出「過關」。\n\n```python\nch = int(input())\nen = int(input())\nif ch >= 60 __1__ en >= 60:\n    print("過關")\n```', 'and'),
]


# ── U2 Level 2：60 選擇 + 40 填空（TQC+ 觀念題風格：多分支追蹤＋邊界值）──
U2_L2 = [
    # 多段分級與邊界值（14）
    mc('以下程式 score = 90 時的輸出是？\n\n```python\nif score < 0 or score > 100:\n    print("輸入範圍錯誤")\nelif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelse:\n    print("C")\n```', 'A', 'B', 'C', '輸入範圍錯誤'),
    mc('同上題結構，score = 101 時的輸出是？\n\n```python\nif score < 0 or score > 100:\n    print("輸入範圍錯誤")\nelif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelse:\n    print("C")\n```', '輸入範圍錯誤', 'A', 'B', 'C',
       explanation='guard 條件先擋掉無效輸入，101 > 100 成立。'),
    mc('同上題結構，score = -5 時的輸出是？\n\n```python\nif score < 0 or score > 100:\n    print("輸入範圍錯誤")\nelif score >= 80:\n    print("B")\nelse:\n    print("C")\n```', '輸入範圍錯誤', 'C', 'B', '發生錯誤'),
    mc('以下程式 score = 60 時的輸出是？\n\n```python\nif score >= 90:\n    print("優")\nelif score >= 60:\n    print("及格")\nelse:\n    print("不及格")\n```', '及格', '優', '不及格', '沒有任何輸出',
       explanation='60 >= 60 成立 — 邊界值剛好及格。'),
    mc('以下程式 score = 59 時的輸出是？\n\n```python\nif score >= 90:\n    print("優")\nelif score >= 60:\n    print("及格")\nelse:\n    print("不及格")\n```', '不及格', '及格', '優', '發生錯誤'),
    mc('以下程式 score = 89 時的輸出是？\n\n```python\nif score >= 90:\n    print("優")\nelif score >= 60:\n    print("及格")\nelse:\n    print("不及格")\n```', '及格', '優', '不及格', '89',
       explanation='89 < 90，落到第二個條件。'),
    mc('以下程式的輸出是？\n\n```python\nm = 2\nif m == 2:\n    days = 28\nelif m in [4, 6, 9, 11]:\n    days = 30\nelse:\n    days = 31\nprint(days)\n```', '28', '30', '31', '29'),
    mc('以下程式的輸出是？\n\n```python\nt = 37.5\nif t > 37.5:\n    print("發燒")\nelse:\n    print("正常")\n```', '正常', '發燒', '37.5', '發生錯誤',
       explanation='37.5 > 37.5 不成立（> 不含等於）。'),
    mc('以下程式 age = 65 時的輸出是？\n\n```python\nif age < 12:\n    print("兒童票")\nelif age >= 65:\n    print("敬老票")\nelse:\n    print("全票")\n```', '敬老票', '全票', '兒童票', '發生錯誤'),
    mc('以下程式 age = 12 時的輸出是？\n\n```python\nif age < 12:\n    print("兒童票")\nelse:\n    print("全票")\n```', '全票', '兒童票', '12', '發生錯誤',
       explanation='12 < 12 不成立，剛滿 12 歲買全票。'),
    mc('以下程式的輸出是？\n\n```python\nbmi = 22.5\nif bmi < 18.5:\n    print("過輕")\nelif bmi < 24:\n    print("正常")\nelif bmi < 27:\n    print("過重")\nelse:\n    print("肥胖")\n```', '正常', '過輕', '過重', '肥胖'),
    mc('以下程式 bmi = 24 時的輸出是？\n\n```python\nif bmi < 18.5:\n    print("過輕")\nelif bmi < 24:\n    print("正常")\nelif bmi < 27:\n    print("過重")\nelse:\n    print("肥胖")\n```', '過重', '正常', '過輕', '肥胖',
       explanation='24 < 24 不成立，落入下一段。'),
    mc('以下程式的輸出是？\n\n```python\nn = 100\nif n % 10 == 0:\n    print("十的倍數")\nelif n % 5 == 0:\n    print("五的倍數")\n```', '十的倍數', '五的倍數', '兩行都輸出', '沒有任何輸出',
       explanation='elif 互斥：第一個條件成立後，後面不再檢查。'),
    mc('哪一組測試資料最能檢查「score >= 60 及格」的邊界？', '59 和 60', '0 和 100', '30 和 90', '61 和 70',
       explanation='邊界值測試要挑條件兩側最接近的值。'),

    # 邏輯運算求值（12，含競賽原題）
    mc('執行以下 Python 程式片段，其結果為何？\n\n```python\na = 5; b = 10\nA1 = a < b and b > 15\nA2 = a < b or b < 15\nprint(f"{A1} {A2}")\n```', 'False True', 'True True', 'False False', 'True False',
       explanation='A1：True and False = False；A2：True or True = True。（113 商業類技藝競賽學科第 25 題）'),
    mc('x = 7 時，x > 5 and x % 2 == 0 的結果是？', 'False', 'True', '7', '發生錯誤',
       explanation='7 是奇數，第二個條件不成立。'),
    mc('x = 7 時，x > 5 or x % 2 == 0 的結果是？', 'True', 'False', '7', '發生錯誤'),
    mc('print(not (3 > 1 and 2 > 1)) 的輸出是？', 'False', 'True', 'None', '發生錯誤',
       explanation='括號內是 True，not True = False。'),
    mc('print(5 > 3, 2 > 4) 的輸出是？', 'True False', 'False True', 'True True', 'False False'),
    mc('print(not False or False) 的輸出是？', 'True', 'False', 'None', '發生錯誤',
       explanation='not False = True，True or False = True。'),
    mc('a = 3、b = 8 時，not (a > b) 的結果是？', 'True', 'False', '3', '8'),
    mc('以下程式的輸出是？\n\n```python\nx = 10\nprint(x > 0 and x < 5 or x > 8)\n```', 'True', 'False', '10', '發生錯誤',
       explanation='x>0 and x<5 為 False；False or True = True。'),
    mc('三個條件都要成立才輸出，哪個寫法正確？', 'if a > 0 and b > 0 and c > 0:',
       'if a > 0 or b > 0 or c > 0:', 'if a and b and c > 0:', 'if a, b, c > 0:'),
    mc('print(type(5 > 3)) 的輸出是？', "<class 'bool'>", "<class 'int'>", 'True', "<class 'str'>"),
    mc('day = 3 時，day == 6 or day == 7 的結果是？', 'False', 'True', '3', '發生錯誤'),
    mc('哪個條件式可以判斷 n「不是」3 的倍數？', 'n % 3 != 0', 'n % 3 == 0', 'n // 3 != 0', 'n != 3'),

    # 閏年與倍數（TQC 情境改寫）（8）
    mc('以下程式 year = 2024 時的輸出是？\n\n```python\nif year % 400 == 0 or (year % 4 == 0 and year % 100 != 0):\n    print("閏年")\nelse:\n    print("平年")\n```', '閏年', '平年', '2024', '發生錯誤',
       explanation='2024 % 4 == 0 且 2024 % 100 != 0。'),
    mc('以下程式 year = 1900 時的輸出是？\n\n```python\nif year % 400 == 0 or (year % 4 == 0 and year % 100 != 0):\n    print("閏年")\nelse:\n    print("平年")\n```', '平年', '閏年', '1900', '發生錯誤',
       explanation='1900 能被 100 整除但不能被 400 整除，是平年。'),
    mc('以下程式 year = 2000 時的輸出是？\n\n```python\nif year % 400 == 0 or (year % 4 == 0 and year % 100 != 0):\n    print("閏年")\nelse:\n    print("平年")\n```', '閏年', '平年', '2000', '發生錯誤',
       explanation='2000 % 400 == 0，直接判定閏年。'),
    mc('以下程式 x = 15 時的輸出是？\n\n```python\nif x % 3 == 0 and x % 5 == 0:\n    print("3 和 5 的倍數")\nelif x % 3 == 0:\n    print("3 的倍數")\nelif x % 5 == 0:\n    print("5 的倍數")\nelse:\n    print("都不是")\n```', '3 和 5 的倍數', '3 的倍數', '5 的倍數', '都不是',
       explanation='複合條件要放最前面，否則永遠輪不到（TQC 倍數判斷情境）。'),
    mc('以下程式 x = 55 時的輸出是？\n\n```python\nif x % 3 == 0 and x % 5 == 0:\n    print("3 和 5 的倍數")\nelif x % 3 == 0:\n    print("3 的倍數")\nelif x % 5 == 0:\n    print("5 的倍數")\nelse:\n    print("都不是")\n```', '5 的倍數', '3 的倍數', '3 和 5 的倍數', '都不是'),
    mc('以下程式 x = 92 時的輸出是？\n\n```python\nif x % 3 == 0 and x % 5 == 0:\n    print("3 和 5 的倍數")\nelif x % 3 == 0:\n    print("3 的倍數")\nelif x % 5 == 0:\n    print("5 的倍數")\nelse:\n    print("都不是")\n```', '都不是', '3 的倍數', '5 的倍數', '3 和 5 的倍數'),
    mc('若把「x % 3 == 0」放在第一個條件、複合條件「x%3==0 and x%5==0」放第二個，x = 15 會輸出？', '3 的倍數',
       '3 和 5 的倍數', '5 的倍數', '都不是',
       explanation='15 先滿足 x%3==0，複合條件分支永遠不會被執行 — 條件順序錯誤的典型 bug。'),
    mc('判斷「同時是 4 的倍數與 6 的倍數」，最合適的條件是？',
       'n % 4 == 0 and n % 6 == 0', 'n % 4 == 0 or n % 6 == 0',
       'n % 24 == 0', 'n % 4 and n % 6',
       explanation='and 表示兩者皆須成立；%24 會漏掉 12 這類數。'),

    # 程式追蹤與常見錯誤（14）
    mc('以下程式會發生什麼？\n\n```python\nx = 5\nif x = 5:\n    print("五")\n```', 'SyntaxError（= 應為 ==）', '輸出 五', '沒有任何輸出', 'ValueError'),
    mc('以下程式的輸出是？\n\n```python\nx = 8\nif x > 5:\n    if x > 10:\n        print("大")\n    else:\n        print("中")\n```', '中', '大', '沒有任何輸出', '發生錯誤',
       explanation='巢狀判斷：外層成立進入後，內層 8 > 10 不成立走 else。'),
    mc('以下程式的輸出是？\n\n```python\nx = 5\ny = 10\nif x > 3:\n    x += y\nprint(x)\n```', '15', '5', '10', '53'),
    mc('以下程式的輸出是？\n\n```python\nmoney = 100\nif money >= 50:\n    money -= 50\nif money >= 50:\n    money -= 50\nprint(money)\n```', '0', '50', '100', '-50',
       explanation='兩個獨立 if 都會判斷：100→50→0。'),
    mc('以下程式的輸出是？\n\n```python\nmoney = 100\nif money >= 50:\n    money -= 50\nelif money >= 50:\n    money -= 50\nprint(money)\n```', '50', '0', '100', '發生錯誤',
       explanation='elif 在第一個 if 成立後不再執行，只扣一次。'),
    mc('以下程式的輸出是？\n\n```python\na, b, c = 3, 7, 5\nif a >= b and a >= c:\n    print(a)\nelif b >= c:\n    print(b)\nelse:\n    print(c)\n```', '7', '3', '5', '發生錯誤',
       explanation='三數取最大：a 不是最大，b >= c 成立輸出 7。'),
    mc('以下程式的輸出是？\n\n```python\nx = -7\nif x < 0:\n    x = -x\nprint(x)\n```', '7', '-7', '0', '發生錯誤',
       explanation='絕對值的典型寫法。'),
    mc('以下程式的輸出是？\n\n```python\ntotal = 1200\nif total >= 1000:\n    total = total * 0.9\nprint(total)\n```', '1080.0', '1200', '1080', '900.0',
       explanation='滿千打九折，浮點乘法結果帶小數點。'),
    mc('以下程式輸入 60 時的輸出是？\n\n```python\ns = int(input())\nif s >= 60:\n    print("PASS")\nelse:\n    print("FAIL")\n```', 'PASS', 'FAIL', '60', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nx = 10\nif not x > 10:\n    print("未超過")\nelse:\n    print("超過")\n```', '未超過', '超過', '10', '發生錯誤',
       explanation='10 > 10 為 False，not False = True。'),
    mc('以下程式的輸出是？\n\n```python\na = "5"\nif a == 5:\n    print("相等")\nelse:\n    print("不相等")\n```', '不相等', '相等', '5', 'TypeError',
       explanation='字串 "5" 與整數 5 型態不同，== 比較結果為 False（不會報錯）。'),
    mc('以下程式的輸出是？\n\n```python\nwin = 0\nlose = 0\na, b = 3, 3\nif a > b:\n    win += 1\nelif a < b:\n    lose += 1\nprint(win, lose)\n```', '0 0', '1 0', '0 1', '1 1',
       explanation='平手時兩個條件都不成立，兩變數維持 0。'),
    mc('以下程式的輸出是？\n\n```python\nlevel = "gold"\nif level == "gold":\n    rate = 0.8\nelif level == "silver":\n    rate = 0.9\nelse:\n    rate = 1.0\nprint(int(100 * rate))\n```', '80', '90', '100', '0.8'),
    mc('下列哪一種寫法「一定」會輸出東西（不論變數值為何）？',
       '有 else 的 if/else 判斷', '單獨一個 if', '兩個連續的 if', '巢狀 if 裡再放 if',
       explanation='else 承接所有剩餘情況，保證有一個分支被執行。'),

    # 綜合觀念（12）
    mc('「先處理無效輸入」的判斷應該放在哪裡？', '整組 if/elif 的最前面', '最後面',
       'else 裡面', '不需要處理'),
    mc('成績分級條件「範圍由嚴格到寬鬆排列」的意思是？', '先判斷 >= 90 再依序判斷 >= 80、>= 70',
       '先判斷 >= 60 再判斷 >= 90', '順序沒有影響', '從 else 開始寫'),
    mc('以下程式有什麼問題？\n\n```python\ns = int(input())\nif s >= 60:\n    print("及格")\nelif s >= 90:\n    print("優秀")\n```', '「優秀」永遠不會輸出（順序錯誤）', '語法錯誤',
       '90 分會輸出兩行', '沒有問題'),
    mc('判斷 x 介於 1 到 100（含）之間，哪個寫法「錯誤」？',
       'if x >= 1 or x <= 100:', 'if x >= 1 and x <= 100:',
       'if 1 <= x <= 100:', 'if not (x < 1 or x > 100):',
       explanation='or 寫法對任何數字都成立，是常見錯誤。'),
    mc('input() 讀入 "7" 後要和數字比大小，需要先做什麼？', '用 int() 轉成整數',
       '用 str() 轉成字串', '加上引號', '什麼都不用'),
    mc('哪一個條件可以正確判斷 year 是閏年？（含世紀年規則）',
       'year % 400 == 0 or (year % 4 == 0 and year % 100 != 0)',
       'year % 4 == 0', 'year % 100 == 0', 'year % 4 == 0 or year % 400 == 0',
       explanation='只看 %4 會把 1900 誤判為閏年。'),
    mc('以下程式的輸出是？\n\n```python\nn = 24\nresult = ""\nif n % 2 == 0:\n    result += "偶"\nif n % 3 == 0:\n    result += "三"\nprint(result)\n```', '偶三', '偶', '三', '沒有任何輸出',
       explanation='兩個獨立 if：24 同時符合兩個條件，字串累加。'),
    mc('與 not (a and b) 意義相同的是？', '(not a) or (not b)', '(not a) and (not b)',
       'a or b', 'not a', explanation='笛摩根定律：not(A and B) = notA or notB。'),
    mc('溫度 t 在「10 度以下或 35 度以上」要發布警報，條件怎麼寫？',
       't <= 10 or t >= 35', 't <= 10 and t >= 35', '10 <= t <= 35', 'not t > 10',
       explanation='一個數不可能同時 ≤10 又 ≥35，用 and 永遠不成立。'),
    mc('以下程式 raining = True、has_umbrella = False 時的輸出是？\n\n```python\nif raining and not has_umbrella:\n    print("會淋濕")\nelse:\n    print("安全")\n```', '會淋濕', '安全', 'True', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\nvip = False\namount = 800\nif vip or amount >= 1000:\n    print("免運")\nelse:\n    print("運費 60")\n```', '運費 60', '免運', '800', '發生錯誤'),
    mc('成績分五級（A≥90、B≥80、C≥70、D≥60、其餘 F），用 if/elif/else 寫最少需要幾個 elif？',
       '3 個', '4 個', '5 個', '2 個',
       explanation='if 處理 A、三個 elif 處理 B/C/D、else 處理 F。'),

    # ── L2 填空（40）──
    fb('完成成績分級：90 以上 A、80 以上 B、70 以上 C、60 以上 D、其餘 F。\n\n```python\ns = int(input())\nif s >= 90:\n    print("A")\nelif s >= 80:\n    print("B")\nelif s >= 70:\n    print("C")\nelif s >= __1__:\n    print("D")\nelse:\n    print("F")\n```', '60'),
    fb('先擋無效輸入：成績小於 0「或」大於 100 都算錯誤。\n\n```python\ns = int(input())\nif s < 0 __1__ s > 100:\n    print("輸入錯誤")\nelif s >= 60:\n    print("及格")\nelse:\n    print("不及格")\n```', 'or'),
    fb('完成閏年判斷（能被 400 整除，或能被 4 整除「且」不能被 100 整除）。\n\n```python\ny = int(input())\nif y % 400 == 0 or (y % 4 == 0 __1__ y % 100 != 0):\n    print("閏年")\nelse:\n    print("平年")\n```', 'and'),
    fb('閏年判斷：不能被 100 整除的比較運算子。\n\n```python\ny = int(input())\nif y % 400 == 0 or (y % 4 == 0 and y % 100 __1__ 0):\n    print("閏年")\nelse:\n    print("平年")\n```', '!='),
    fb('票價：未滿 12 歲兒童票、65 歲（含）以上敬老票、其餘全票。\n\n```python\nage = int(input())\nif age < 12:\n    print("兒童票")\nelif age __1__ 65:\n    print("敬老票")\nelse:\n    print("全票")\n```', '>='),
    fb('BMI 分級的第二段：小於 24 為正常。\n\n```python\nbmi = float(input())\nif bmi < 18.5:\n    print("過輕")\nelif bmi __1__ 24:\n    print("正常")\nelif bmi < 27:\n    print("過重")\nelse:\n    print("肥胖")\n```', '<'),
    fb('學生「且」假日才有優惠。\n\n```python\nis_student = True\nis_holiday = True\nif is_student __1__ is_holiday:\n    print("優惠價")\nelse:\n    print("原價")\n```', 'and'),
    fb('滿 1000 元或持 VIP 卡即免運。\n\n```python\namount = int(input())\nvip = False\nif amount >= 1000 __1__ vip:\n    print("免運")\nelse:\n    print("運費 60")\n```', 'or'),
    fb('三數取最大值（逐一挑戰擂台）。\n\n```python\na, b, c = 12, 7, 20\nbig = a\nif b > big:\n    big = b\nif c > big:\n    big = __1__\nprint(big)   # 20\n```', 'c'),
    fb('用 if 實作絕對值：負數取相反數。\n\n```python\nx = -9\nif x < 0:\n    x = __1__\nprint(x)   # 9\n```', '-x'),
    fb('奇偶與正負複合判斷：正的偶數。\n\n```python\nn = int(input())\nif n > 0 and n % 2 __1__ 0:\n    print("正偶數")\nelse:\n    print("其他")\n```', '=='),
    fb('滿千打九折，輸出折扣後金額。\n\n```python\ntotal = int(input())\nif total >= 1000:\n    total = total * __1__\nprint(total)\n```', '0.9'),
    fb('極端氣溫警報：10 度以下「或」35 度以上。\n\n```python\nt = float(input())\nif t <= 10 __1__ t >= 35:\n    print("極端氣溫警報")\n```', 'or'),
    fb('月份判斷季節：3、4、5 月是春季。\n\n```python\nm = int(input())\nif m == 3 or m == 4 __1__ m == 5:\n    print("春季")\n```', 'or'),
    fb('停車費：前 2 小時 60 元，之後每小時 40 元。\n\n```python\nhours = int(input())\nif hours <= 2:\n    fee = 60\nelse:\n    fee = 60 + (hours - __1__) * 40\nprint(fee)\n```', '2'),
    fb('判斷輸入是否為三位數（100 到 999）。\n\n```python\nn = int(input())\nif n >= 100 __1__ n <= 999:\n    print("三位數")\nelse:\n    print("不是三位數")\n```', 'and'),
    fb('剪刀石頭布：出拳相同即平手。\n\n```python\na = input()\nb = input()\nif a __1__ b:\n    print("平手")\nelse:\n    print("分勝負")\n```', '=='),
    fb('會員等級折扣：gold 八折、silver 九折、其餘原價。\n\n```python\nlevel = input()\nif level == "gold":\n    rate = 0.8\n__1__ level == "silver":\n    rate = 0.9\nelse:\n    rate = 1.0\nprint(rate)\n```', 'elif'),
    fb('雙重驗證：帳號與密碼都正確才登入。\n\n```python\nuser = input()\npwd = input()\nif user == "admin" __1__ pwd == "0000":\n    print("登入成功")\nelse:\n    print("登入失敗")\n```', 'and'),
    fb('把負分數視為 0 分再輸出（下限保護）。\n\n```python\ns = int(input())\nif s < 0:\n    s = __1__\nprint(s)\n```', '0'),
    fb('把超過 100 的分數壓回 100（上限保護）。\n\n```python\ns = int(input())\nif s > 100:\n    s = __1__\nprint(s)\n```', '100'),
    fb('超速罰款：超過速限 50 在 10 以內罰 1600、超過 10 罰 3600。\n\n```python\nspeed = int(input())\nover = speed - 50\nif over <= 0:\n    print("未超速")\nelif over <= __1__:\n    print(1600)\nelse:\n    print(3600)\n```', '10'),
    fb('三角形判斷：任兩邊之和必須「大於」第三邊。\n\n```python\na, b, c = 3, 4, 5\nif a + b __1__ c and b + c > a and a + c > b:\n    print("可以構成三角形")\n```', '>'),
    fb('滿額禮：消費滿 5000 送 500 禮券，滿 3000 送 200。\n\n```python\namount = int(input())\nif amount >= 5000:\n    print("送 500 禮券")\nelif amount >= __1__:\n    print("送 200 禮券")\nelse:\n    print("感謝惠顧")\n```', '3000'),
    fb('遊戲扣血：防禦成功只扣 1，否則扣 10。\n\n```python\nhp = 100\ndefended = False\nif defended:\n    hp -= 1\nelse:\n    hp -= __1__\nprint(hp)   # 90\n```', '10'),
    fb('輸入兩數，輸出較小值。\n\n```python\na = int(input())\nb = int(input())\nif a < b:\n    print(a)\n__1__:\n    print(b)\n```', 'else'),
    fb('判斷字元是否為大寫英文字母（"A" 到 "Z" 之間）。\n\n```python\nch = input()\nif "A" <= ch __1__ ch <= "Z":\n    print("大寫字母")\n```', 'and'),
    fb('水質酸鹼：pH 小於 7 酸性、等於 7 中性、大於 7 鹼性。\n\n```python\nph = float(input())\nif ph < 7:\n    print("酸性")\nelif ph __1__ 7:\n    print("中性")\nelse:\n    print("鹼性")\n```', '=='),
    fb('簡訊計費：70 字以內 1 元，超過依每 70 字 1 元無條件進位。\n\n```python\nn = int(input())\nif n <= 70:\n    print(1)\nelse:\n    print((n + 69) __1__ 70)\n```', '//'),
    fb('紅綠燈：red 停、green 行、其他情況（黃燈）減速。\n\n```python\nlight = input()\nif light == "red":\n    print("停止")\nelif light == "green":\n    print("通行")\n__1__:\n    print("減速")\n```', 'else'),
    fb('消費累點：每 100 元 1 點，滿 10 點（含）升級 VIP。\n\n```python\nspend = int(input())\npoints = spend // 100\nif points __1__ 10:\n    print("升級 VIP")\nelse:\n    print(f"目前 {points} 點")\n```', '>='),
    fb('清單長度為 0 表示沒有資料。\n\n```python\nitems = []\nif __1__(items) == 0:\n    print("沒有資料")\n```', 'len'),
    fb('骰子遊戲：點數 1 或 6 重骰。\n\n```python\nd = int(input())\nif d == 1 or d __1__ 6:\n    print("重骰")\nelse:\n    print(f"點數 {d}")\n```', '=='),
    fb('外送運費：3 公里內 30 元，之後每公里加 10 元。\n\n```python\nkm = int(input())\nif km <= 3:\n    fee = 30\nelse:\n    fee = 30 + (km - 3) * __1__\nprint(fee)\n```', '10'),
    fb('密碼規則：至少 8 碼「且」不能與帳號相同。\n\n```python\nuser = input()\npwd = input()\nif len(pwd) >= 8 __1__ pwd != user:\n    print("密碼可用")\nelse:\n    print("密碼不安全")\n```', 'and'),
    fb('把成績四捨五入後再判斷及格。\n\n```python\ns = float(input())\nif __1__(s) >= 60:\n    print("及格")\nelse:\n    print("不及格")\n```', 'round'),
    fb('雙十一：11 月「且」11 日才輸出特賣。\n\n```python\nmonth = int(input())\nday = int(input())\nif month == 11 __1__ day == 11:\n    print("雙十一特賣")\n```', 'and'),
    fb('年齡層：未滿 18 未成年、18 到 64 成人、65 以上長者。\n\n```python\nage = int(input())\nif age < 18:\n    print("未成年")\nelif age < __1__:\n    print("成人")\nelse:\n    print("長者")\n```', '65'),
    fb('統計負數個數。\n\n```python\nneg = 0\nfor n in [3, -1, -7, 8, -2]:\n    if n __1__ 0:\n        neg += 1\nprint(neg)   # 3\n```', '<'),
    fb('線上會議提醒：開始前 10 分鐘（含）以內提醒。\n\n```python\nminutes_left = int(input())\nif minutes_left <= 10 and minutes_left __1__ 0:\n    print("即將開始")\n```', '>='),
]



# ── U2 Level 3：35 選擇 + 65 填空（競賽／TQC 實作風格：規則建模）──
U2_L3 = [
    # 進階追蹤（35）
    mc('x = 7 時，print(3 < x < 10) 的輸出是？', 'True', 'False', '7', '發生錯誤',
       explanation='chained comparison：等同 3 < x and x < 10。'),
    mc('x = 10 時，print(3 < x < 10) 的輸出是？', 'False', 'True', '10', '發生錯誤',
       explanation='10 < 10 不成立。'),
    mc('以下程式的輸出是？\n\n```python\ns = 75\nprint("PASS" if s >= 60 else "FAIL")\n```', 'PASS', 'FAIL', '75', '發生錯誤',
       explanation='三元運算式：條件成立取前值，否則取 else 後的值。'),
    mc('以下程式的輸出是？\n\n```python\nn = -5\nprint("非負數" if n >= 0 else "負數")\n```', '負數', '非負數', '-5', '發生錯誤'),
    mc('以下程式 amount = 1000 時的輸出是？\n\n```python\nfee = 0 if amount >= 1000 else 80\nprint(fee)\n```', '0', '80', '1000', '發生錯誤'),
    mc('執行以下程式片段，其結果為何？\n\n```python\nx = 5; y = 3\nif x > y:\n    x -= y\nprint((x + y) % 4)\n```', '1', '0', '2', '3',
       explanation='x=2、y=3，(2+3)%4=1。（競賽風格）'),
    mc('以下程式 s = 95 時的輸出是？\n\n```python\nif s >= 80:\n    print("甲")\nelif s >= 90:\n    print("乙")\n```', '甲', '乙', '甲與乙', '沒有任何輸出',
       explanation='95 先滿足 >= 80 — 條件範圍重疊時只有第一個會執行。'),
    mc('以下程式 n = -4 時會輸出幾行？\n\n```python\nif n < 0:\n    print("負數")\nif n % 2 == 0:\n    print("偶數")\n```', '2 行（負數、偶數）', '1 行（負數）', '1 行（偶數）', '0 行',
       explanation='兩個獨立 if；-4 % 2 == 0 成立（Python 的 % 結果非負）。'),
    mc('print(not not True) 的輸出是？', 'True', 'False', 'None', '發生錯誤'),
    mc('print(True and False or True) 的輸出是？', 'True', 'False', 'None', '發生錯誤',
       explanation='and 優先於 or：(True and False) or True = True。'),
    mc('print(5 > 3 > 1) 的輸出是？', 'True', 'False', '5', '發生錯誤',
       explanation='連鎖比較：5 > 3 且 3 > 1。'),
    mc('print(5 > 3 > 3) 的輸出是？', 'False', 'True', '3', '發生錯誤'),
    mc('以下程式的輸出是？\n\n```python\na, b = 4, 4\nif a > b:\n    print("a 大")\nelif a == b:\n    print("平手")\nelse:\n    print("b 大")\n```', '平手', 'a 大', 'b 大', '沒有任何輸出'),
    mc('以下程式的輸出是？\n\n```python\nx = 12\nif x > 5:\n    if x > 15:\n        print("A")\n    else:\n        print("B")\n```', 'B', 'A', '沒有任何輸出', '發生錯誤',
       explanation='else 與最近的 if 配對：內層 12 > 15 不成立。'),
    mc('以下程式的輸出是？\n\n```python\na, b = 3, 8\nm = a if a < b else b\nprint(m)\n```', '3', '8', 'a', '發生錯誤',
       explanation='三元運算式取較小值。'),
    mc('以下程式 kwh = 250 時的輸出是？\n\n```python\nif kwh <= 120:\n    print("第一級")\nelif kwh <= 200:\n    print("第二級")\nelse:\n    print("第三級")\n```', '第三級', '第二級', '第一級', '發生錯誤'),
    mc('以下程式 income = 500000 時的輸出是？\n\n```python\nif income <= 560000:\n    rate = 0.05\nelif income <= 1260000:\n    rate = 0.12\nelse:\n    rate = 0.2\nprint(rate)\n```', '0.05', '0.12', '0.2', '發生錯誤'),
    mc('以下程式哪些輸入「不會有任何輸出」？\n\n```python\ns = int(input())\nif s > 90:\n    print("優")\nelif s < 60:\n    print("待加強")\n```', '60 到 90 之間的分數', '95', '50', '0',
       explanation='條件涵蓋不完整：60 <= s <= 90 沒有任何分支處理。'),
    mc('與 not (a or b) 等價的是？', '(not a) and (not b)', '(not a) or (not b)',
       'a and b', 'not a', explanation='笛摩根定律：not(A or B) = notA and notB。'),
    mc('year = 2100 時，閏年判斷（%400==0 or (%4==0 and %100!=0)）的結果是？', '平年', '閏年',
       '發生錯誤', '無法判斷', explanation='2100 能被 100 整除但不能被 400 整除。'),
    mc('以下程式 s = 85 時的輸出是？\n\n```python\ngrade = "A" if s >= 90 else ("B" if s >= 80 else "C")\nprint(grade)\n```', 'B', 'A', 'C', '發生錯誤',
       explanation='巢狀三元運算式：85 不滿足 >= 90，進入第二層判斷。'),
    mc('以下程式的輸出是？\n\n```python\namount = 500\nis_member = True\nfree = amount >= 1000 or (is_member and amount >= 500)\nprint(free)\n```', 'True', 'False', '500', '發生錯誤',
       explanation='會員且滿 500 即免運（教材 shipping_fee 規則）。'),
    mc('以下程式 mins = 61 時的輸出是？\n\n```python\nunits = (mins + 29) // 30\nif units <= 2:\n    fee = units * 20\nelse:\n    fee = 40 + (units - 2) * 15\nprint(fee)\n```', '55', '60', '40', '20',
       explanation='units=(61+29)//30=3，fee=40+1×15=55。'),
    mc('「1 < x < 5」與下列哪個寫法等價？', 'x > 1 and x < 5', 'x > 1 or x < 5',
       '1 < x or x < 5', 'x == 2 or x == 3 or x == 4',
       explanation='chained comparison 是 and 關係的簡寫（最後一項只對整數成立，但 x 可能是浮點數）。'),
    mc('以下程式 s = 85 時的輸出是？\n\n```python\nif s >= 60:\n    print("D")\nelif s >= 70:\n    print("C")\nelif s >= 80:\n    print("B")\nelse:\n    print("F")\n```', 'D', 'B', 'C', 'F',
       explanation='條件由寬鬆到嚴格是錯誤排法：85 先滿足 >= 60。'),
    mc('密碼檢查「長度不足 8 或與帳號相同都不安全」，等價的「安全」條件是？',
       'len(pwd) >= 8 and pwd != user', 'len(pwd) >= 8 or pwd != user',
       'not (len(pwd) >= 8 and pwd != user)', 'len(pwd) < 8 and pwd == user',
       explanation='不安全 = A or B，安全 = not(A or B) = notA and notB。'),
    mc('以下程式的輸出是？\n\n```python\nf = 100\nc = (f - 32) * 5 / 9\nif c > 37.5:\n    print("發燒")\nelse:\n    print("正常")\n```', '發燒', '正常', '100', '發生錯誤',
       explanation='(100-32)×5/9 ≈ 37.78 > 37.5。'),
    mc('以下程式的輸出是？\n\n```python\nx = -3\nprint(x if x >= 0 else -x)\n```', '3', '-3', '0', '發生錯誤',
       explanation='三元運算式實作絕對值。'),
    mc('y = 2024 時，以下程式的輸出是？\n\n```python\nleap = y % 400 == 0 or (y % 4 == 0 and y % 100 != 0)\nprint(366 if leap else 365)\n```', '366', '365', 'True', '發生錯誤'),
    mc('a = b = c = 2 時，print(a == b == c) 的輸出是？', 'True', 'False', '2', '發生錯誤',
       explanation='連鎖比較可以串三個以上。'),
    mc('以下程式 hour = 23 時的輸出是？\n\n```python\nif 6 <= hour < 18:\n    print("日間")\nelif 18 <= hour < 23:\n    print("夜間")\nelse:\n    print("深夜")\n```', '深夜', '夜間', '日間', '發生錯誤',
       explanation='23 不滿足 hour < 23，落入 else。'),
    mc('以下程式 n = 0 時的輸出是？\n\n```python\nresult = "正" if n > 0 else "負" if n < 0 else "零"\nprint(result)\n```', '零', '正', '負', '發生錯誤'),
    mc('哪個條件可以判斷「x 與 y 恰好一個為正數」？',
       '(x > 0) != (y > 0)', 'x > 0 and y > 0', 'x > 0 or y > 0', 'x * y > 0',
       explanation='兩布林值不相等表示恰有一個成立（互斥或）。x*y>0 是同號、and 是同正。'),
    mc('以下程式 total = 2500 時的輸出是？\n\n```python\nif total >= 3000:\n    total *= 0.8\nelif total >= 2000:\n    total *= 0.9\nprint(int(total))\n```', '2250', '2000', '2500', '1800',
       explanation='2500×0.9=2250.0，int 後 2250。'),
    mc('以下判斷式在 score 為哪個值時，兩種寫法結果「不同」？\n\n寫法一：if score > 60\n寫法二：if score >= 60', '60', '59', '61', '100',
       explanation='只有邊界值 60 會讓 > 與 >= 產生差異。'),

    # ── L3 填空（65）──
    fb('電價級距：120 度內每度 1.63，121–330 度每度 2.38，超過每度 3.52。用量 200 度。\n\n```python\nkwh = 200\nif kwh <= 120:\n    bill = kwh * 1.63\nelif kwh <= __1__:\n    bill = 120 * 1.63 + (kwh - 120) * 2.38\nelse:\n    bill = 120 * 1.63 + 210 * 2.38 + (kwh - 330) * 3.52\nprint(round(bill))   # 386\n```', '330'),
    fb('計程車夜間加成：夜間（23 時後或 6 時前）車資乘 1.2。\n\n```python\nfare = 250\nhour = 23\nif hour >= 23 __1__ hour < 6:\n    fare = fare * 1.2\nprint(int(fare))   # 300\n```', 'or'),
    fb('用 chained comparison 判斷及格區間：60 到 100（含）。\n\n```python\ns = 88\nif 60 __1__ s <= 100:\n    print("及格")   # 及格\n```', '<='),
    fb('三元運算式：成年與否一行判斷。\n\n```python\nage = 20\nstatus = "成年" __1__ age >= 18 else "未成年"\nprint(status)   # 成年\n```', 'if'),
    fb('三元運算式的另一半：否則的值。\n\n```python\nn = 7\nparity = "偶數" if n % 2 == 0 __1__ "奇數"\nprint(parity)   # 奇數\n```', 'else'),
    fb('高鐵早鳥票：提前 28 天（含）65 折、提前 14 天（含）8 折，否則原價。票價 1490、提前 20 天。\n\n```python\ndays = 20\nprice = 1490\nif days >= 28:\n    price *= 0.65\nelif days >= __1__:\n    price *= 0.8\nprint(int(price))   # 1192\n```', '14'),
    fb('BMI 完整分級（過輕/正常/過重/肥胖），先算 BMI 再判斷。體重 80、身高 1.7。\n\n```python\nw, h = 80, 1.7\nbmi = w / h __1__ 2\nif bmi < 18.5:\n    print("過輕")\nelif bmi < 24:\n    print("正常")\nelif bmi < 27:\n    print("過重")\nelse:\n    print("肥胖")   # 肥胖\n```', '**',
       explanation='80/2.89 ≈ 27.68，屬肥胖級。'),
    fb('所得稅級距：56 萬內 5%、56–126 萬 12%。所得 80 萬（單位：元）。\n\n```python\nincome = 800000\nif income <= 560000:\n    tax = income * 0.05\nelse:\n    tax = 560000 * 0.05 + (income - __1__) * 0.12\nprint(int(tax))   # 56800\n```', '560000'),
    fb('水費級距：10 度內每度 7 元，超過部分每度 10 元。用量 18 度。\n\n```python\ndegree = 18\nif degree <= 10:\n    bill = degree * 7\nelse:\n    bill = 10 * 7 + (degree - 10) * __1__\nprint(bill)   # 150\n```', '10'),
    fb('闖關資格：三關全部達標（用 and 串接）。\n\n```python\ns1, s2, s3 = 70, 82, 65\nif s1 >= 60 and s2 >= 60 __1__ s3 >= 60:\n    print("全數過關")   # 全數過關\n```', 'and'),
    fb('獎學金資格：平均 90 以上「且」操行 A，或者競賽獲獎。\n\n```python\navg = 88\nconduct = "A"\nprize = True\nif (avg >= 90 and conduct == "A") __1__ prize:\n    print("符合資格")   # 符合資格\n```', 'or'),
    fb('guard clause：先擋無效值再處理。\n\n```python\nn = -5\nif n __1__ 0:\n    print("輸入需為正數")   # 輸入需為正數\nelse:\n    print(n ** 0.5)\n```', '<='),
    fb('電影分級：未滿 6 歲禁看輔導級以上；6 到 11 需家長陪同。\n\n```python\nage = 8\nif age < 6:\n    print("不可觀賞")\nelif age <= __1__:\n    print("家長陪同")\nelse:\n    print("可自行觀賞")   # 家長陪同\n```', '11'),
    fb('顏色燈號：分數 80 以上綠燈、60 以上黃燈、其餘紅燈（巢狀三元）。\n\n```python\ns = 72\nlight = "綠" if s >= 80 else ("黃" if s >= __1__ else "紅")\nprint(light)   # 黃\n```', '60'),
    fb('會員升等：年消費 10 萬升白金，5 萬升金卡。年消費 68000。\n\n```python\nspend = 68000\nif spend >= 100000:\n    print("白金")\nelif spend >= __1__:\n    print("金卡")\nelse:\n    print("一般")   # 金卡\n```', '50000'),
    fb('血壓判讀：收縮壓 140 以上「或」舒張壓 90 以上即偏高。\n\n```python\nsys_bp, dia_bp = 135, 95\nif sys_bp >= 140 __1__ dia_bp >= 90:\n    print("血壓偏高")   # 血壓偏高\n```', 'or'),
    fb('簡化 FizzBuzz：15 的倍數輸出 FizzBuzz、3 的倍數 Fizz、5 的倍數 Buzz。\n\n```python\nn = 45\nif n % __1__ == 0:\n    print("FizzBuzz")\nelif n % 3 == 0:\n    print("Fizz")\nelif n % 5 == 0:\n    print("Buzz")   # FizzBuzz\n```', '15',
       explanation='最嚴格的複合條件（15 的倍數）必須放第一個。'),
    fb('顛倒的分級要修正：把條件由「嚴格到寬鬆」排列 — 第一個條件應該判斷哪個等級？\n\n```python\ns = 85\nif s >= __1__:\n    print("A")\nelif s >= 80:\n    print("B")\nelif s >= 70:\n    print("C")   # B\n```', '90'),
    fb('季節判斷（3–5 春、6–8 夏、9–11 秋、其餘冬）用 chained comparison。\n\n```python\nm = 7\nif 3 <= m <= 5:\n    print("春")\nelif 6 <= m __1__ 8:\n    print("夏")\nelif 9 <= m <= 11:\n    print("秋")\nelse:\n    print("冬")   # 夏\n```', '<='),
    fb('停車費：30 分鐘 20 元、不足 30 分以 30 分計，前 1 小時 40 元封頂後改每單位 15 元。停 100 分鐘。\n\n```python\nmins = 100\nunits = (mins + 29) // 30\nif units <= 2:\n    fee = units * 20\nelse:\n    fee = 40 + (units - 2) * __1__\nprint(fee)   # 70\n```', '15',
       explanation='units=5?（100+29)//30=4，fee=40+2×15=70。'),
    fb('匯款手續費：同行免費，跨行 500 萬（含）以下 30 元、超過 100 元。\n\n```python\nsame_bank = False\namount = 800\nif same_bank:\n    fee = 0\nelif amount <= 5000000:\n    fee = __1__\nelse:\n    fee = 100\nprint(fee)   # 30\n```', '30'),
    fb('顛倒判斷改用 not：非會員且未滿額才收運費。\n\n```python\nis_member = False\namount = 300\nif __1__ is_member and amount < 490:\n    print("運費 65")   # 運費 65\nelse:\n    print("免運")\n```', 'not'),
    fb('外送優惠疊加：滿 300 折 30，再判斷雨天加收 20。\n\n```python\namount = 350\nraining = True\nif amount >= 300:\n    amount -= 30\nif raining:\n    amount += __1__\nprint(amount)   # 340\n```', '20'),
    fb('棒球計數：好球數滿 3 三振，壞球數滿 4 保送（else if 關係）。\n\n```python\nstrikes, balls = 3, 2\nif strikes >= 3:\n    print("三振")\n__1__ balls >= 4:\n    print("保送")\nelse:\n    print("繼續打擊")   # 三振\n```', 'elif'),
    fb('疫苗接種年齡：65 歲以上或未滿 6 個月嬰兒優先。\n\n```python\nage_year = 70\nage_month = 840\nif age_year >= 65 or age_month __1__ 6:\n    print("優先接種")   # 優先接種\n```', '<'),
    fb('選課人數上限：已滿且無候補名額才關閉。\n\n```python\nenrolled = 60\nwaitlist = 5\nif enrolled >= 60 __1__ waitlist >= 10:\n    print("關閉選課")\nelse:\n    print("尚可候補")   # 尚可候補\n```', 'and'),
    fb('圖書逾期費：7 天內每天 5 元、超過 7 天部分每天 10 元。逾期 12 天。\n\n```python\ndays = 12\nif days <= 7:\n    fine = days * 5\nelse:\n    fine = 7 * 5 + (days - 7) * __1__\nprint(fine)   # 85\n```', '10'),
    fb('三數排大小：輸出中間值（不是最大也不是最小）。\n\n```python\na, b, c = 7, 2, 5\nif (b <= a <= c) or (c <= a <= b):\n    print(a)\nelif (a <= b <= c) or (c <= b __1__ a):\n    print(b)\nelse:\n    print(c)   # 5\n```', '<='),
    fb('UV 指數警示：8 以上過量級、11 以上危險級（先判斷危險）。\n\n```python\nuv = 9\nif uv >= __1__:\n    print("危險級")\nelif uv >= 8:\n    print("過量級")\nelse:\n    print("普通")   # 過量級\n```', '11'),
    fb('用一個布林運算式判斷「恰好一個為真」。\n\n```python\na = True\nb = False\nprint(a __1__ b)   # True\n```', '!=',
       explanation='兩布林值不相等 = 恰好一個成立（互斥或）。'),
    fb('工讀時薪：平日 190，假日 1.34 倍（四捨五入到整數）。\n\n```python\nis_holiday = True\nwage = 190\nif is_holiday:\n    wage = wage * __1__\nprint(round(wage))   # 255\n```', '1.34'),
    fb('溫室風扇控制：溫度超過 30「且」濕度超過 80 才開強風。\n\n```python\ntemp = 32\nhumidity = 85\nif temp > 30 __1__ humidity > 80:\n    print("強風")\nelse:\n    print("弱風")   # 強風\n```', 'and'),
    fb('會員日折扣順序：先打 9 折再折 50（順序影響結果）。原價 1000。\n\n```python\nprice = 1000\nprice = price * 0.9\nprice = price - __1__\nprint(int(price))   # 850\n```', '50'),
    fb('線上考試防弊：切換視窗 3 次（含）以上或離開超過 60 秒即標記。\n\n```python\nswitches = 2\naway_seconds = 75\nif switches >= 3 or away_seconds __1__ 60:\n    print("標記異常")   # 標記異常\n```', '>'),
    fb('遊戲等級：經驗值 1000 升 Lv2、3000 升 Lv3、6000 升 Lv4。經驗 4500。\n\n```python\nexp = 4500\nif exp >= 6000:\n    print("Lv4")\nelif exp >= __1__:\n    print("Lv3")\nelif exp >= 1000:\n    print("Lv2")\nelse:\n    print("Lv1")   # Lv3\n```', '3000'),
    fb('汽車保養提醒：里程超過 10000 公里「或」距上次保養超過 180 天。\n\n```python\nkm = 8500\ndays = 200\nif km > 10000 __1__ days > 180:\n    print("該保養了")   # 該保養了\n```', 'or'),
    fb('把巢狀 if 改寫成 and：兩層條件合併成一行。\n\n```python\nage = 20\nhas_id = True\nif age >= 18 __1__ has_id:\n    print("可入場")   # 可入場\n```', 'and'),
    fb('快遞材積：長寬高任一邊超過 150 公分即為大型件。\n\n```python\nl, w, h = 100, 160, 80\nif l > 150 or w > 150 __1__ h > 150:\n    print("大型件")   # 大型件\n```', 'or'),
    fb('三元運算式計算門票：假日 350、平日 280。\n\n```python\nis_holiday = False\nprice = 350 if is_holiday __1__ 280\nprint(price)   # 280\n```', 'else'),
    fb('手搖飲甜度：全糖 10、半糖 5、無糖 0，其他輸入顯示錯誤。\n\n```python\nsweet = "半糖"\nif sweet == "全糖":\n    print(10)\nelif sweet == "半糖":\n    print(5)\nelif sweet == "無糖":\n    print(0)\n__1__:\n    print("無此選項")   # 5\n```', 'else'),
    fb('數字範圍夾擠（clamp）：把 n 限制在 0 到 100 之間。\n\n```python\nn = 130\nif n > 100:\n    n = 100\nelif n < 0:\n    n = __1__\nprint(n)   # 100\n```', '0'),
    fb('颱風假判斷：風力 7 級以上「或」雨量 350 毫米以上。\n\n```python\nwind = 6\nrain = 400\nif wind >= 7 or rain >= __1__:\n    print("停班停課")   # 停班停課\n```', '350'),
    fb('連鎖比較判斷等差：三數是否等差（b-a == c-b）。\n\n```python\na, b, c = 3, 7, 11\nif b - a __1__ c - b:\n    print("等差")   # 等差\n```', '=='),
    fb('付款方式手續費：信用卡 2%、行動支付 1%、現金免手續費。金額 2000 刷卡。\n\n```python\nmethod = "card"\namount = 2000\nif method == "card":\n    fee = amount * __1__\nelif method == "mobile":\n    fee = amount * 0.01\nelse:\n    fee = 0\nprint(int(fee))   # 40\n```', '0.02'),
    fb('轉學門檻：兩科皆 80 以上，「或」平均 85 以上。\n\n```python\nch, en = 78, 92\navg = (ch + en) / 2\nif (ch >= 80 and en >= 80) or avg >= __1__:\n    print("符合門檻")   # 符合門檻\n```', '85'),
    fb('reversed 判斷：分數「不在」及格範圍才補考。\n\n```python\ns = 45\nif __1__ (60 <= s <= 100):\n    print("補考")   # 補考\n```', 'not'),
    fb('滿意度轉星等：90 以上 5 星、70 以上 4 星、50 以上 3 星，其餘 2 星。分數 68。\n\n```python\nscore = 68\nif score >= 90:\n    star = 5\nelif score >= 70:\n    star = 4\nelif score >= __1__:\n    star = 3\nelse:\n    star = 2\nprint(star)   # 3\n```', '50'),
    fb('防呆：除數為 0 就不做除法。\n\n```python\na, b = 10, 0\nif b __1__ 0:\n    print(a / b)\nelse:\n    print("除數不可為 0")   # 除數不可為 0\n```', '!='),
    fb('午餐加購：主餐滿 120 加 30 升級套餐，滿 90 加 45。主餐 100。\n\n```python\nmain = 100\nif main >= 120:\n    combo = main + 30\nelif main >= 90:\n    combo = main + __1__\nelse:\n    combo = main + 60\nprint(combo)   # 145\n```', '45'),
    fb('三段運費一行寫：用巢狀三元運算式。\n\n```python\nw = 8\nfee = 60 if w <= 5 else (90 if w __1__ 10 else 150)\nprint(fee)   # 90\n```', '<='),
    fb('身分證末碼判單雙號口罩日（單號週一三五）。\n\n```python\nlast_digit = 7\nday = 3\nif last_digit % 2 == 1 and day in [1, 3, 5]:\n    print("可購買")\nelif last_digit % 2 == 0 and day __1__ [2, 4, 6]:\n    print("可購買")\nelse:\n    print("今日不可購買")   # 可購買\n```', 'in'),
    fb('闖紅燈罰鍰：機車 1800、汽車 2700，其他車種 300。\n\n```python\nvehicle = "car"\nif vehicle == "moto":\n    print(1800)\nelif vehicle == __1__:\n    print(2700)\nelse:\n    print(300)   # 2700\n```', ['"car"', "'car'"]),
    fb('連續判斷收斂：輸入介於 1~5 顯示低、6~10 顯示高（chained）。\n\n```python\nn = 8\nif 1 <= n <= 5:\n    print("低")\nelif 6 __1__ n <= 10:\n    print("高")   # 高\n```', '<='),
    fb('哪一天的溫差最大：兩天溫差比較。\n\n```python\ndiff1 = abs(31.2 - 24.5)\ndiff2 = abs(29.8 - 21.1)\nif diff1 __1__ diff2:\n    print("第一天")\nelse:\n    print("第二天")   # 第二天\n```', '>',
       explanation='diff1=6.7、diff2=8.7，第一天沒有比較大，走 else。'),
    fb('及格門檻可調：模考採 55 分及格，正式採 60。\n\n```python\nis_mock = True\nthreshold = 55 if is_mock else __1__\ns = 57\nprint("及格" if s >= threshold else "不及格")   # 及格\n```', '60'),
    fb('雙重身份優惠只能擇優：學生 8 折、敬老 65 折，同時符合取 65 折。\n\n```python\nis_student = True\nis_senior = True\nprice = 1000\nif is_senior:\n    price *= 0.65\nelif is_student:\n    price *= __1__\nprint(int(price))   # 650\n```', '0.8'),
    fb('資安鎖定：連續錯誤達 5 次「且」距上次成功登入超過 30 天。\n\n```python\nfails = 6\ndays = 45\nif fails >= 5 __1__ days > 30:\n    print("帳號鎖定")   # 帳號鎖定\n```', 'and'),
    fb('模擬骰子比大小：點數大者勝，同點比第二顆。\n\n```python\na1, a2 = 4, 6\nb1, b2 = 4, 3\nif a1 > b1:\n    print("A 勝")\nelif a1 < b1:\n    print("B 勝")\nelif a2 __1__ b2:\n    print("A 勝")\nelse:\n    print("B 勝或平手")   # A 勝\n```', '>'),
    fb('高鐵座位：靠窗偏好且 A/E 座有空位才安排。\n\n```python\nwants_window = True\nseat_a_free = False\nseat_e_free = True\nif wants_window and (seat_a_free __1__ seat_e_free):\n    print("安排靠窗")   # 安排靠窗\n```', 'or'),
    fb('分期零利率門檻：金額滿 3000 可分 3 期，滿 10000 可分 6 期。金額 12000。\n\n```python\namount = 12000\nif amount >= 10000:\n    print("可分 6 期")\nelif amount >= __1__:\n    print("可分 3 期")\nelse:\n    print("不可分期")   # 可分 6 期\n```', '3000'),
    fb('氣象警報等級：雨量 500 以上紅色、350 橙色、200 黃色。雨量 420。\n\n```python\nrain = 420\nif rain >= 500:\n    print("紅色警報")\nelif rain >= __1__:\n    print("橙色警報")\nelif rain >= 200:\n    print("黃色警報")   # 橙色警報\n```', '350'),
    fb('檢查西洋棋座標合法性：欄 a–h「且」列 1–8。\n\n```python\ncol = "e"\nrow = 4\nif "a" <= col <= "h" __1__ 1 <= row <= 8:\n    print("合法座標")   # 合法座標\n```', 'and'),
    fb('自動補考名單：40（含）到 59 分之間可補考。\n\n```python\ns = 52\nif 40 <= s __1__ 60:\n    print("可補考")   # 可補考\nelif s < 40:\n    print("重修")\n```', '<'),
    fb('用整除找世紀：西元年除以 100 無條件進位。1999 年是第幾世紀？\n\n```python\nyear = 1999\ncentury = (year + 99) __1__ 100\nprint(century)   # 20\n```', '//'),
    fb('結匯申報門檻：單筆達 50 萬（含）以上需申報。\n\n```python\namount = 620000\nif amount __1__ 500000:\n    print("需申報")   # 需申報\nelse:\n    print("無需申報")\n```', '>='),
]
